### ISSUE TITLE
Stop people sending us book chapters

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1044]
@markmacgillivray, I believe that the DOI gives information on if something is a book chapter, or journal article etc. Can we start checking for that when the request is made and rejecting it if that’s the case?

**Comment by markmacgillivray** [comment]
I have a list of all the types, @JosephMcArthur which ones do we want to allow?

https://dev.api.cottagelabs.com/use/crossref/types

**Comment by markmacgillivray** [comment]
Accept journal-article, proceedings-article, dissertation, report

For those we don't accept, and say why - e.g. crossref says this item is not a journal article, and that is all we will accept.

**Comment by markmacgillivray** [comment]
But also provide a link to allow the user to force creation of a request anyway.

**Comment by markmacgillivray** [comment]
Added text as below, similar to close on too old:

We can't request this because it doesn't seem to be a journal article, we're sorry. If you think this is a mistake, let us know. Thanks for using the Open Access Button, try again soon.

This does not have the force to allow a creation, because it turns out we did not have for the too-old articles either. But the "let us know" has the link through to /feedback#general

Also this only happens if it appears to be a UI request creation, as you also stated for the <5 years or missing DOI ones.

If this copy is OK and you are happy to not have the force, beyond just having them contact us through feedback, then close this. Otherwise reassign to me, with new copy / instructions.
