### ISSUE TITLE
EmbedOA missing icon in some installs

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1087]
Forwarded full info to Mark

**Comment by markmacgillivray** [comment]
Hmm didn't we used to have a bit on those pages explaining that the bootstrap css would also be needed if their site does not already include it? That is likely the case here - the magnifying glass icon will get served as part of the bootstrap css that our site serves, so that needs to be included too if they don't already have it. The notes in the widget code itself do explain this, and I thought we had that explained on the page too, but it is not there any more. The notes did refer to a CL link so I have updated that to be an OAB link. But we probably still have to put it into the text of the page somewhere.

It also requires jquery to work as well, although perhaps that is more common than bootstrap. So the instructions need to say "if you don't have bootstrap and/or jquery already on your site, also include the following code":

<script src="https://openaccessbutton.org/static/jquery-1.10.2.min.js"></script>
<link rel="stylesheet" href="https://openaccessbutton.org/static/bootstrap.min.css">

**Comment by markmacgillivray** [comment]
Ah I just found it - the eResource version does explain that jquery and bootstrap could be needed. So the other two have to mention that as well.

**Comment by markmacgillivray** [comment]
However if bootstrap is not already used on those Libguide / ILL pages that people are installing this to, then including it could have many unexpected effects.

**Comment by markmacgillivray** [comment]
The jquery is definitely required, without it their search boxes just would not work if they did not already happen to have jquery. The bootstrap is not required, but of course without it the box does not style the same as ours, and that includes the search icon. We could try serving a separate icon just for use on those widgets and alter the widget code to refer to it instead of the bootstrap search icon. But still, without knowing the styling framework they are using, we could not be sure it would look right.

**Comment by markmacgillivray** [comment]
I think this was an issue we discussed at the time, come to think of it - the more like our style we want it to be, the harder it is for it to be generic to fit in to any other site. The simplest solution would be to use the word "search" instead of an icon.

**Comment by markmacgillivray** [comment]
@JosephMcArthur do you want to change that embedoa page or shall I? Note I have just updated the links that are used on the page just in case, but not actually changed the content

**Comment by markmacgillivray** [comment]
I am working now on changing the icon to be a png instead of a glyphicon so at least that part will work even without bootstrap.

**Comment by JosephMcArthur** [comment]
> I am working now on changing the icon to be a png instead of a glyphicon so at least that part will work even without bootstrap.

That would be great!

**Comment by markmacgillivray** [comment]
OK have changed it to use a png instead of the glyphicon. It is still true that style will not exactly match ours unless bootstrap is included, but that may be better to ignore because it could have more unintended consequences. However we do need to say that jquery could be required if not already on their site if they find the widget does not work for them.

**Comment by JosephMcArthur** [comment]
> However we do need to say that jquery could be required if not already on their site if they find the widget does not work for them 

Can you make a suggested change for this?

**Comment by markmacgillivray** [comment]
OK, I have to do some other things just now but will assign this to me to come back to.

**Comment by JosephMcArthur** [comment]
Will the png update go out automatically, or will people need to make code changes?

**Comment by markmacgillivray** [comment]
It is automatic, once we push this to live people will start getting the new version. But anyone having problems due to lack of jquery would have to manually add that.
