### ISSUE TITLE
Search La Referencia for papers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#109]
Add a /use endpoint

**Comment by markmacgillivray** [comment]
@JosephMcArthur what actually is La Referencia? Googling it throws up various possibilities. Can you clarify what it is you want me to connect to here?

**Comment by JosephMcArthur** [comment]
This is the site I'm thinking about: http://lareferencia.redclara.net/rfr/. If we need help from a native speaker, just let me know.

**Comment by markmacgillivray** [comment]
Ooh, yeah I know virtually no Spanish. I google translated it, but did not see anything about "API". Can you get someone to find out where the API is, and where the docs are, and if they are in English? Do you have someone who can speak Spanish? If not, my cousin does.

I will assign this to you for now, because I can't progress it myself.

**Comment by natalianorori** [comment]
Hey Mark, 


You've got a Spanish speaker here. What exactly do you need? Just got back from OpenCon but I can help you with anything starting later today. 

La Referencia is a mexican repository for papers, it is widely used in Latin America

**Comment by markmacgillivray** [comment]
Hi @natalianorori great!

Somewhere on that site I need to find their API documentation, and if it is in English then I just need a link to it so I can read it.

Otherwise, I need the URL of wherever they serve their API itself, and I can perhaps guess from there how it works.

Or, if their API docs can be read by you, then the specific things I need to know are:

* the URL of their API to send queries to
* do we need to authenticate to use it? If so how do we sign up to get an API token?
* what is the API URL to send search queries, so we can find out if something is in their repo?
* what sorts of search can we do? Can we search for a DOI, and/or an article title?
* if we can do those sorts of search, what is the syntax for doing so (assuming you can find such a section, then I probably just need to be told where it is so I can look at their examples, if they provide any - the language won't matter by that point)

Thanks!

**Comment by markmacgillivray** [comment]
@natalianorori it is not a huge rush by the way, I don't need to know right now. This is in our current milestone which still has the rest of this week and next week to go, so if you can find out these things by say Wednesday 23rd November, then I should still have time to get us connected to La Referencia during this sprint.

**Comment by natalianorori** [comment]
Perfect! Thanks for the instructions and I'll get back to you before the weekend ends!

**Comment by natalianorori** [comment]
Mark, 

La Referencia operates as an Open Source platform, and they develop most of their code on GitHub, the problem might be that their code is both in English and Spanish, but here is a link to their repo: https://github.com/lareferencia?tab=repositories

I found out they work with LRHarvester and LRProvider to validate and transform OAI Metadata, and their platform is developed using Java 1.7

I sent an email to get in touch with their developer so that I could answer this questions more accurately. In the meantime, this is their backbend: https://github.com/lareferencia/main/tree/master/backend

**Comment by markmacgillivray** [comment]
Hi Natalia, thanks for looking into it. However it's not their code I really need to know about, but their API if they have one. That is, a web URL where I can send queries to.

I don't know what LRHarvester and LRProvider are, but you say they use them to transform DOI metadata - does this mean that they just have the same content as that which can be retrieved from the crossref DOI API directly?

Thanks for contacting them, let me know what you hear back from them! For now I'll move this issue out to the next milestone.

**Comment by JosephMcArthur** [comment]
Okay, so CORE list this as a provider but list 0 articles from the source: https://core.ac.uk/search/repositories.id:(1730)

I'll follow up.

**Comment by JosephMcArthur** [comment]
Okay, they've just added a bunch of sources in bulk & think it might be taking time for them to harvest & appear in CORE. This makes sense, as others I looked at had the same issue. 

Am awaiting their confirmation of this, but for now let's not implement this ourselves.

**Comment by JosephMcArthur** [comment]
@meganwaps can you find some article / paywall pairs that would serve as suitable test cases here please?

**Comment by JosephMcArthur** [comment]
More on this from CORE: "their OAI base URL http://www.lareferencia.info:8080/oai/provider which resolves into a 404 page"

**Comment by JosephMcArthur** [comment]
Am still trying to make progress on this bts

**Comment by JosephMcArthur** [comment]
this no progress here

**Comment by JosephMcArthur** [comment]
Discussions with COAR suggest this won't be needed soon.
