### ISSUE TITLE
Create workflow for set up / management of InstantILL

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1103]
Some things I'm sure we'll need:
- [ ] email domains used (comma separated)
- [ ] who to email submission to
- [ ] T&C conditions link (or full text)
- [ ] turn around times (average processing times (in hours), if weekends are included)
- [ ] price (free, varied, fixed). If this, how to take payment. 
- [ ] Where should we submit ILLs
- [ ] Institution name
- [ ] Ill contact email (for user issues)

But, we'll need to discuss this with others after feedback.

**Comment by JosephMcArthur** [comment]
So, in this issue we need to:
- [ ] fork the EmbedOA files / set up the process (including webpage)

Far aside from all the fields above, at first we'll just want: 
* to know who to email submissions to (can be just the users account email)
* to be able to tie stats to that setup
* for people to be able to come back and adjust some settings in a UI if needed

**Comment by markmacgillivray** [comment]
Have created a new instantill page where a signed in user (or user is prompted to sign in) can see the code they need to copy to embed an instantill widget. That page sets the ID of the currently logged in user, and tells the user that they will be the only person who can manage the instantill plugin, but for now it does not actually offer any config options, as we can get the email address from the already logged in user account.

I have copied the embedoa/openaccessbutton widget js and made a new instantill widget based on it, which has its own identifier so that we can pick it up in stats. We will also get the ID of the user so will be able to differentiate different instantill uses by their creator user ID. Nothing has been added to the stats page for this yet though, so there are no actual visible changes anywhere yet.

When users eventually do come back to give us configurable values, would that be best added to the instantill page on the site, or to their user account page?

Also, todo, I will have the instantill/user account page tell the user if they already appear to have an instantill button running on their ID - will we then be letting them see the stats? If so these stats will have to go somewhere other than the current stats page, as that has been made admin-only.

**Comment by JosephMcArthur** [comment]
> When users eventually do come back to give us configurable values, would that be best added to the instantill page on the site, or to their user account page?

I'd say on the instantill page would be best for a user, but if it means a lot more coding / complexity for us I'd say lets put it on the user account page. 

> Also, todo, I will have the instantill/user account page tell the user if they already appear to have an instantill button running on their ID - will we then be letting them see the stats? If so these stats will have to go somewhere other than the current stats page, as that has been made admin-only.

Keep the stats as admin only for now. Technically, they'd be offered as part of our investment program.

**Comment by JosephMcArthur** [comment]
Little bug:

> InstantILL can be installed on your website for general use, but only you ([object Object])will be able to configure it.

- [ ] fix
