### ISSUE TITLE
Allow InstantILL to submit ILL's through to (pre-set) templated emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1104]
We'll want a generic template, and maybe ones designed for things to be used for Worldcat (share?) that can be chosen. Should go to the address(s) specified on set up (I'd suggest we allow this to be flexible).

**Comment by JosephMcArthur** [comment]
In this sprint, let's have a button (like in the mockups) that's a generic as possible show up any time after a search. Later on, we'll choose when to show that button according to the workflow logic but for now lets just get this bit doing what we want. 

In the email, we'll want something like:

# ILL Submitted: <<random ID>>

Title:
<<title>>

Journal:
<<journal>>

and so on.

**Comment by markmacgillivray** [comment]
There is an issue here, and related to the issue about getting pubmed IDs for ILLs too - our system is not designed to collect metadata and return it to the user. It is designed to find an open access version of an article, and to do that as fast as possible. Also, as has come up in other issues, we have added bits here and there to meet various new and changing use cases, which have led to a system that sometimes returns some pieces of metadata, and other times does not.

For the ILL request, it seems that what is really desired is as much metadata as possible - NOT a link to an open access copy. This means that our current find/resolve processes are not suitable for ILLs. Instead, we need a process that searches as many possible places for as much metadata as possible, if what you want to do is provide a lot of metadata to the ILL request. This WILL be slower than what we currently do, and will require more significant API development.

So far, there is an instantill widget that can be used and could be trialled by an institution, to send an template ILL email as this issue requires. So we could feasibly close this now. BUT the amount of metadata it would pass about the required article could be very small - in some cases, nothing more than the title that the user tried to search for.

Recent developments to our system have begun to shift away from the idea of searching for any kind of content and instead only searching for DOIs - but we have also discovered that it is possible for a valid DOI to exist and yet for the crossref API to return no data about it.

So a decision needs to be made here about whether you want slower processing and more coverage, by hitting as many potential metadata source APIs as possible, or whether you want what the system currently does, which is to respond as fast as possible with whatever metadata has been found (if any) whilst trying to find an open access version.

To "export as much metadata as we can", I will need to spend an additional day to two days writing a different process for ILL metadata lookups rather than using our current find/resolve processes (but you could still go ahead with testing what I've done so far for the instantill plugin while I do write more API code).

Will assign this to @JosephMcArthur as well as myself, to await an answer.

**Comment by JosephMcArthur** [comment]
- [ ] Move to InstantILL@openaccessbutton.org
