### ISSUE TITLE
Search Figshare for papers

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#111]
I've seen people put pre-prints and author versions here, would be interesting to see how would be good to search for these.

**Comment by markmacgillivray** [comment]
Figshare is also now ready as a /use endpoint, but similarly to openaire, only for searching articles. We can search by DOI for a specific article, so all I need to know is if you think this is a source that we would find additional things from beyond where we would already search. If so, I can add it in. Assigning to @meganwaps for now to await decision on which sources to use, and informing @JosephMcArthur too.

**Comment by JosephMcArthur** [comment]
please turn this on, it's not in base.

**Comment by markmacgillivray** [comment]
OK it is on. @JosephMcArthur are you wanting all these issues left open so they can be tested once we have a comprehensive list of ones to test against and where we know they should come from the various sources? For now I will leave open but assign to @meganwaps but if this is incorrect, just close this issue.

**Comment by markmacgillivray** [comment]
For the first one, it has no DOI, and I have yet to find a reliable way to search figshare without DOI. For example, searching for the entire title of that article without quotes returns many results, and none of the first ten are the right one. It is not clear how deep we would have to scroll to find it, if it comes up at all. Searching the full title in quotes returns no results. Searching the title up to but not including the : in quotes returns the correct article, but there is no indication as to why. Searching the whole title in quotes without the : does not find it, and removing the comma also does not help, so just yanking non-ascii does not work. Therefore, I think we can only find things in figshare that have DOIs, so we can search for them by DOI.

The second one you tested does have a DOI, it is 10.1021/acs.inorgchem.6b01826. But in figshare there are actually two records for this article which I can find by searching a subset of the title content, however neither of them have this as the DOI - they both have extra parts. See:

https://dev.api.cottagelabs.com/use/figshare/search?search_for=%22A%20potential%20wasteform%20for%20Cs%20immobilization%22

It could be possible to match these by title searches and subset matching the DOIs, BUT as noted above title matches cannot be done reliably either. So, still stuck.

The situation is similar for the third, but ADDS a complication. Let's say we did decide to search by title and make a guess at it. Well, this third one actually also has two records in figshare, neither of which share the same DOI as the article you link to:

https://dev.api.cottagelabs.com/use/figshare/search?search_for=%22Design%20of%20graft%20block%20polymer%20thermoplastics%22

One of those has a DOI that is an extension of the one you linked to, but the other is a totally different DOI with a slightly different title too - there is no way to know which is the correct one.

The fourth one you tried says it is no longer available.

At best, we could do a partial title match if DOI match fails, and IF there are any results, pick the first one. But there is from this test at least a 25% chance of us being wrong if we do that.

**Comment by meganwaps** [comment]
@markmacgillivray So after some further research (since I was personally kind of stumped) I understand now that on FigShare, those who choose to publish are immediately given a DOI, but can option to Reserve the DOI if the author does not want the material to be readily made available. 

So I guess the question I'm proposing is; is this a problem with the button/figshare or is it the issue of articles not being fully made public by the authors on figshare?

**Comment by markmacgillivray** [comment]
I'd say it looks like what happens is people put something on figshare and get a doi, but then later they publish that thing with some journal, which gets a different doi. Or it may even happen the other way round, it goes on the journal then later on figshare. The problem is that the figshare version - and sometimes there is more than one, because they probably made changes then decided to publish another - does not share the same DOI as the published version in the journal, which is where the person who does not have access and tries to use the button will be looking.

It could be said that this IS one advantage of the more old fashioned publishing paradigm - it is not so ready to give out DOIs until a thing is DONE, although even then people do make changes and retractions, so in some sense the seeming finality of a DOI is also problematic. In this case though, fighsare appears to give them too readily, or at least in such a way that a user may indeed have multiple copies of the same article but with different DOIs. We can't really fault figshare for this though, it is just the way they do it.

Because the author then (or previously) publishes their article somewhere else, and with a different DOI, we can't then find the open version on figshare by searching for that DOI. Again we can't really fault the publisher here, they just do what they do. We could maybe say the author should ensure their articles refer each other somehow, but they don't, and there may not be a way in the systems to do that. This is just the classic problem of disambiguation - it is not solvable, and it is better just to accept that there is more than one version of a thing, and in different places.

Where we are stuck is that even if we don't need to disambiguate, we can't even reliably find that another version exists. This comes down to the fact that we do not seem to be able to reliably search figshare for titles. I think I've tried the possibilities for achieving that, but it does not return a result set we can be sure of.

We could try following up with figshare asking if there is some better way to search by title, or if they can improve how they return results by title search.

Regarding whether or not it is an issue of articles not being made public, not as far as I know. The ones Joe linked to were available, just not findable by DOI - apart from the last one, that sad it was no longer available. Perhaps it is, but the author did not make it public, or changed it to not being public any more. Even if this is the case, I doubt we can do much about that - the author chose to make it private for a reason - beyond the usual advocacy of telling people they should make their stuff public.

**Comment by meganwaps** [comment]
@markmacgillivray thanks so much, seriously I've been so lost on this! I think we probably need to discuss this at a Dev or leadership meeting and see what others think. It would be fabulous to be able to  effectively search Figshare, but that 25% error rate could be a PR disaster, as well as a mess during user testing. That being said, if we wanted to, I could easily add searching Figshare papers to the improved User testing I'm planning for 2017, but I think we might need more voices to chime in on this.

**Comment by JosephMcArthur** [comment]
I've reached out to figshare to see if they can shed any light on the title searching issue, or generally advise here.

**Comment by JosephMcArthur** [comment]
They've now made some changes to their title searching from our feedback that should help with the above. They've asked if we can do a test to check, I'm moving this out monitoring to the backlog.

**Comment by JosephMcArthur** [comment]
@markmacgillivray a little nudge here, since we're looking at all things find system atm!

**Comment by markmacgillivray** [comment]
This is done too

**Comment by JosephMcArthur** [comment]
Can we see a test case of it working?

**Comment by markmacgillivray** [comment]
http://dev.openaccessbutton.org/find?url=Attitudes%20of%20secondary%20school%20students%20towards%20english%20as%20foreign%20language

**Comment by JosephMcArthur** [comment]
That goes to the wrong place :'(

**Comment by markmacgillivray** [comment]
Is it? There's no other paper findable with that name. Title search to figshare is the last thing to run. I can make it not return unless the title is an exact match, but I thought something was better than nothing

**Comment by markmacgillivray** [comment]
The other titles figshare returns for that search are totally inaccurate, but that one seemed pretty good - it is the same, but without the suffix.

https://dev.api.cottagelabs.com/use/figshare/search?search_for=%22Attitudes%20of%20secondary%20school%20students%20towards%20english%20as%20foreign%20language%22

**Comment by JosephMcArthur** [comment]
When I follow

> http://dev.openaccessbutton.org/find?url=Attitudes%20of%20secondary%20school%20students%20towards%20english%20as%20foreign%20language

I get:

https://figshare.com/articles/Life_and_its_transfiguration_in_Nietzsche_s_thought/4688905

I can see what's coming out the api... which is right. So... now I'm confused :)

**Comment by markmacgillivray** [comment]
Ha, oops. Fixed. Obscure use of quotation marks on the figshare API.

**Comment by JosephMcArthur** [comment]
Tried some of the above

>  http://pubs.acs.org/doi/abs/10.1021/acs.macromol.6b02033 (https://figshare.com/articles/Design_of_Graft_Block_Polymer_Thermoplastics/4275422)

worked like a dream. 

> http://dev.openaccessbutton.org/find?url=Attitudes%20of%20secondary%20school%20students%20towards%20english%20as%20foreign%20language

that link now works, but I'm still having trouble getting to it from a URL / title on the site.

**Comment by markmacgillivray** [comment]
Just typing in the title to the box works fine for me. Not sure what you mean about getting to it from a URL though. You mean a different URL for the same article?

**Comment by JosephMcArthur** [comment]
I mean this URL:

> https://edupediapublications.org/journals/IJR/article/view/1835

and this happens with I do the title:

:'( http://recordit.co/md2fQlK7nb

still no luck.

**Comment by markmacgillivray** [comment]
Yeah searching for the full title on figshare just doesn't find it - that remains a problem with their search. But, now that we don't get actually bad results from them, it seems, we can still keep figshare in and we will sometimes find stuff there.

**Comment by markmacgillivray** [comment]
The last word of this example is pakistan.pdf in their system, hence the fail. If we strip the last word of any title, we could still submatch it.

**Comment by markmacgillivray** [comment]
Actually will leave as is - really it is wrong metadata in figshare, so let's leave as is rather than tweak

**Comment by JosephMcArthur** [comment]
Okay, so to close this we need to: 

- [ ] test a few more articles @svmelton 
- [ ] feedback to figshare about their title search api - @me 
- [ ] do a mini-blog @chealsye

**Comment by JosephMcArthur** [comment]
My understanding here is that we are not going to be sending folks to the wrong article so, it's better than nothing. However, there are improvements that could be made to their title search so we could find more. With that understanding I think it can ship.

**Comment by chealsye** [comment]
@JosephMcArthur Is it all right to slate this for the week of 6 March?

**Comment by svmelton** [comment]
# Testing Notes
Tested on Chrome Version 54.0.2840.98 (64-bit)

## Testing Articles
Tested 3 articles: 
https://figshare.com/articles/Discover_DH_Introduction_to_Digital_Humanities_Theories_and_Methods/4287263
-No issues, pulls up article in Figshare

https://figshare.com/articles/Timeline_of_Manuscript_Exchanges_between_Malmesbury_and_Cirencester/3990543
-No issues, pulls up article in Figshare

https://figshare.com/articles/Evolution_at_the_Surface_of_Euclid_Elements_of_a_Long_Infinity_in_Motion_Along_Space/1247503
-Pulls up article in university repository (http://dlc.dlib.indiana.edu/dlc/handle/10535/7395)

https://figshare.com/collections/How_the_Leopard_Hides_Its_Spots_em_ASIP_em_Mutations_and_Melanism_in_Wild_Cats/1637504
-Received message "Sorry, something went wrong." This article is also available in PLOS One--perhaps this is causing an issue?

https://figshare.com/collections/Are_online_symptoms_checkers_useful_for_patients_with_inflammatory_arthritis_/3627998
-Received message "Sorry, something went wrong" when searching by title. When searching by Figshare-assigned DOI (https://doi.org/10.6084/m9.figshare.c.3627998), the article was found in Figshare. When searching by publisher-assigned DOI (10.1186/s12891-016-1189-2), article appeared in original journal.

**Comment by svmelton** [comment]
@svmelton will test a few more articles with paywalls

**Comment by markmacgillivray** [comment]
I will look at the title errors - sarah to continue testing with more DOIs

**Comment by svmelton** [comment]
# Testing Notes
Tested on Firefox 51.0.1 (64-bit)

## Testing With DOIs
Tested https://figshare.com/articles/Diverse_Synaptic_Plasticity_Induced_by_the_Interplay_of_Ionic_Polarization_and_Doping_at_Salt-Doped_Electrolyte_Semiconducting_Polymer_Interface/4702660 (DOI https://doi.org/10.1021/acsomega.6b00392.s001)
-No issues

Tested https://figshare.com/articles/Synthesis_and_anti-inflammatory_study_of_novel_fluoro-benzothiazole_derivatives/3381331 (DOI https://doi.org/10.6084/m9.figshare.3381331.v1)
-No issues

Tested https://figshare.com/articles/The_Dewar_Benzene_Radical_Cation_and_Its_Ring_Opening_Reaction/3075037 (DOI https://doi.org/10.1021/ja060176m.s002)
-Button indicated that the article was available:
![screen shot 2017-02-28 at 10 54 45 am](https://cloud.githubusercontent.com/assets/7232545/23412686/6411c896-fda4-11e6-83cc-5d3f04b6b484.png)
-But when following the link (http://dx.doi.org/10.1021/JA060176M.S002), I got a "DOI not found" message


## Other Notes

-Formatting seems to be off on test site
![screen shot 2017-02-28 at 10 41 49 am](https://cloud.githubusercontent.com/assets/7232545/23412151/b373e98e-fda2-11e6-91e5-21eac0903415.png)
-I'm wondering about the "start a data request" messaging. For figshare in particular, it seems as though what people are getting *is* the data & supplementary materials, not necessarily the article itself.

**Comment by markmacgillivray** [comment]
Yep, dev site formatting could be off, it is still in progress.

Regarding the one where the DOI cannot be found - there is not much we can do about that. When a publisher is given a DOI they are contractually obligated to ensure it resolves to the content it is supposed to resolve to, but if it does not, there is nothing we can do about it. In this case, it looks like the DOI itself is wrong - crossref can't even resolve it to a source. But this is the DOI that is on the page in figshare, so somebody could have just put the wrong DOI in. Again, not much we can do about this - some are just not going to work. This is not down to our system, and anyone trying to use that DOI to access the content would have the same problem.

As to the materials in figshare actually being data and not an article - this is a problem. I will look to see if there is any way to tell that a particular figshare resource is data rather than article (or both). But if there is no way to tell, we have to decide what to do about such a case @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Got a linkage via figshare here which is off:
* https://figshare.com/articles/Replication_induced_DNA_damage_after_PARP_inhibition_causes_G_sub_2_sub_delay_and_cell_line_dependent_apoptosis_necrosis_and_multinucleation/1569277
* http://science.sciencemag.org/content/355/6330/1152

**Comment by JosephMcArthur** [comment]
Suggesting we don't ship this yet, still not looking good when I use it

**Comment by markmacgillivray** [comment]
I removed figshare from title search, but still left it in for doi search which seems ok. So we can still say we use figshare as a source.

**Comment by JosephMcArthur** [comment]
Okay, lets leave it at that.
