### ISSUE TITLE
Allow .docx files & .tex files to pass version checking

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1114]
So, this should be quite straightforward, and so serves to start the version checking part of the file checking. 

If we're given a .docx or .tex file type, we should consider it always the right version and deposit it.

**Comment by markmacgillivray** [comment]
Any reason why just these two? If the assumption is that a publisher one would be a pdf, why not anything that does not end with .pdf? For example could be .doc, .txt, .odf, .html, etc - there are many that are not pdf that could be a users own copy.

**Comment by JosephMcArthur** [comment]
.doc and .odf make sense. I don't think people really author in .txt or .html, or at least I don't hear about it, but I suppose it's fine. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Certainly the various document editor types would be the main ones, however even of those there are many - authors on Apple software might have a .pages file for example. I wrote my phd in html, but that is hardly the norm :) (and isn't a published document anyway).

That's why I was thinking it would be easier to say "if not .pdf" rather than "if .doc, .docx, .odf,..." - there could be many, and many we don't know about.

Or we could make a short list.

**Comment by JosephMcArthur** [comment]
Let's say it's not a .pdf for now, and we can adjust if that stops making sense.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
ok

**Comment by markmacgillivray** [comment]
Done, to be discussed at next meeting
