### ISSUE TITLE
Intergrate with Share

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#112]
Could we use this to close #110 and #69 and others Share feeds from?

**Comment by JosephMcArthur** [comment]
Api is here: https://osf.io/api/v1/share/data/help/#!/SHARE/get_share_search

Closing this closes #110, #69, #70, #111, (maybe #111 and #173 ) and #171 I think.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @meganwaps for this and the other integrations, the key thing seems to be knowing which sources are covered by which other sources - I believe the two of you have been working on this? I can start with this SHARE integration one, and if you are happy that it then means we cover the other sources mentioned above, then I will not implement the other ones that this one already covers.

We do already have some of the other integrations anyway, and some are partially there for other functionality but not for search - e.g we deposit to zenodo already but do not yet search it. So even if this one does not cover all the things we thought it did, or if we ever have to stop using it, it will not be too hard to finish the other ones. However, knowing that SHARE reliably covers the others means that we don't have to actually run those multiple searches, which will keep things faster.

So I will start on this one anyway, and if you both can do your research and confirm what you think covers what, then as soon as the new integrations are ready you will be able to test that they return what you expect.

**Comment by markmacgillivray** [comment]
@JosephMcArthur just notifying you that the API you referenced no longer works, it just 404s. It does say it was a demonstration. I have since found the v2 API which just exposes elasticsearch for search, which is useful, so I will see what I can do with that instead. Just thought I'd tell you in case it is relevant to what you / Megan are doing to decide whether or not the content of SHARE covers other things we want.

**Comment by markmacgillivray** [comment]
It turns out also that the new API does not work properly.

Docs describing their v2 API ES endpoint:

http://share-research.readthedocs.io/en/latest/elasticsearch.html

state that the "links" field is available, but it appears not to be.

Their tutorials only show examples using the "sources" field, overlooking the problem searching on "links", and they only appear to store IDs such as DOIs as part of the links that are in the "lists" object:

https://github.com/erinspace/share_tutorials

So I looked directly at their ES mapping instead, which specifies that indexing (and thus searching) is not enabled on the "lists" object at all, meaning the claimed functionality is not possible:

https://share.osf.io/api/v2/search/abstractcreativework/_mapping

So we cannot currently use this service to look up anything by DOI, and using title as first attempt is likely to be too flaky.

I have contacted them via the contact page on the share-research.org site, asking for an alternative or asking if they can fix this. But given that I'd guess it requires re-indexing all their data, and depending how they manage that process, they may not be up for doing that any time soon.

For the time being, we cannot progress with using SHARE until this is sorted though.

I will leave this issue in the current milestone for now, but if we cannot progress it, it will have to fall back to the backlog.

**Comment by JosephMcArthur** [comment]
@markmacgillivray from our chat I hear they're planning this for the next sprint. Keeping you assigned but bumping to the next sprint. The only action for that sprint is 

- [ ] check on if Share are working on fixing this.

**Comment by JosephMcArthur** [comment]
@markmacgillivray have we heard back on Share on this?

**Comment by JosephMcArthur** [comment]
@markmacgillivray any progress from share on this? Can you ping them another note?

**Comment by JosephMcArthur** [comment]
Need to:

- [ ] output a list of sources in share - @markmacgillivray 
- [ ] align above list with #181 sheet
- [ ] test
- [ ] turn on

**Comment by markmacgillivray** [comment]
Share search is now possible. We need to match the sources names in share with our own list of preprint servers. Attached is the list as a txt but it is actually a csv so can be used in google sheets etc - github just does not upload csv for some reasn
[share_sources.txt](https://github.com/OAButton/discussion/files/737696/share_sources.txt)

**Comment by JosephMcArthur** [comment]
Sources we want here: https://docs.google.com/spreadsheets/d/1TOq3nGF-L-OKwkgiojm-gp4W8WVvuUulmMP6kEOhik4/edit?usp=sharing

**Comment by markmacgillivray** [comment]
Completed

**Comment by JosephMcArthur** [comment]
re-opening for some testing & documentation from @svmelton

**Comment by svmelton** [comment]
# Testing Notes
Tested with 51.0.1 (64-bit)

## Testing Open Articles by URL 

- Tested https://share.osf.io/creativework/4608C-F67-2B4
Was taken to item in MLA Repo (https://hcommons.org/deposits/item/hc:11297/), a source that is found in SHARE but not in other repos as far as I can tell, so request seems to be functioning as expected

- Tested https://share.osf.io/preprint/4617D-58D-FEE
Received a "Sorry, something went wrong" message.  I also tried searching https://osf.io/preprints/socarxiv/98nyf/, the URL from SocArXiv (one of the repos SHARE pulls from), and received the same message. This is a book chapter, in case that makes any difference.

## Testing Open Articles by DOI

- Tested http://dx.doi.org/10.17613/M6TH0R
Was taken to item in MLA Repo (https://hcommons.org/deposits/item/hc:11297/), a source that is found in SHARE but not in other repos as far as I can tell, so request seems to be functioning as expected

## Testing Closed Articles by URL

- Tested http://journals.sagepub.com/doi/abs/10.1177/1367877913513690
Was taken to paper in KU's repo (https://kuscholarworks.ku.edu/bitstream/handle/1808/18943/halegoua%20-%20calling%20all%20fiberhoods.pdf;jsessionid=E66A0006F2DB723595D06CAA93829E35?sequence=1), which is one of SHARE's sources 

## Testing Closed Articles by DOI

- Tested http://dx.doi.org/10.1111/nous.12180, which is available as a preprint in SocArXiv through SHARE (https://osf.io/preprints/socarxiv/8hjf3/)
The Button indicated that it had found the article but took me to a Figshare page for a different article (https://figshare.com/articles/Biocompatibility_and_characterization_of_polyglycerol-based_thermoresponsive_nanogels_designed_as_novel_drug-delivery_systems_and_their_intracellular_localization_in_keratinocytes/4711252)
However, the DOI appears correct—if you drop it into a search box, it pulls up the right article, so it's not a case of the publisher having the wrong DOI.

**Comment by JosephMcArthur** [comment]
done & up
