### ISSUE TITLE
EmbedOA bug in libguides

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1132]
see "Trouble setting up EmbedOA in my Libguide"

**Comment by markmacgillivray** [comment]
Being fixed as part of instantill dev, so that new instantill embed and old oab widget can use the newly developed css

**Comment by JosephMcArthur** [comment]
Hurray!

**Comment by markmacgillivray** [comment]
THis has been fixed as part of instantill work and the css changes have been ported back to the openaccessbutton widget which is used for embedoa on libguides. I have checked the page linked by the user that brought up the issue, and our search box looks correct there now. I have also added some config options to the widget/instantill so that advanced users who in future have any problems with the css I have added can overwrite it themselves.

Will assign this to Joe now to follow up with the user.

**Comment by JosephMcArthur** [comment]
Done, thanks Mark!
