### ISSUE TITLE
Layout technical plan to associate a paper with key institutions 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#117]
- [ ] Funders
- [ ] Publisher
- [ ] Journal
- [ ] University

**Comment by JosephMcArthur** [comment]
@markmacgillivray does Crossref / fundref give us any easy wins here once we have the DOI?

**Comment by JosephMcArthur** [comment]
I think if we can get what info we can just from the DOI, it's okay to "call it a day" on this issue.

**Comment by markmacgillivray** [comment]
I think this would need more clarification. What is the purpose of the association? What do each mean?

* funders - understandably, the person / people who funded the research the article is about. There are various sources we could retrieve this from, but all are patchy. I am not sure if crossref has enough to be useful, and not sure of the state of fundref. For lantern we use grist where possible.

* publisher, journal - these may seem understandable, and if on a page where a user is blocked access and it is a journal page owned by a publisher, then obviously straightforward to extract (barring the usual caveats of bad publisher metadata making it not completely reliable). BUT if we FIND an article for someone, say in an institutional repo, we are not necessarily sharing the version that belongs to / was published in that given journal by that given publisher. So here for example is where it is useful to know what is the purpose of having such data, and whether it means being correct about the data referring to the copy we actually share, or the copy the user was looking at when they pressed the button, and how much it is worth putting effort into ensuring we can extract it from all the various messy publisher site metadata (this always seems simple and people wonder why we don't extract more metadata, but the problem is if it becomes an expectation that we have it, then the times we don't have it really stand out, and without vast amounts of effort could easily by 10% or 20% of all articles users click on - never mind the fact that we also allow users to click on URLs that are not necessarily even "official" published articles in journals, so such data may not ever exists for a reasonable number of the URLs we collect.

university - this one is not clear. University where the research took place? Where the lead author is an employee? where the lead author WAS an employee? Where other authors are employed? where the institutional repo we find the article in is physically located? Or a big list of all universities that may have in some way been involved (note for things such as physics review papers of CERN work, this can be hundreds).

**Comment by markmacgillivray** [comment]
Moving to current(ish) milestone to track easily

**Comment by markmacgillivray** [comment]
I don't think I can progress this without wider decision. Maybe there is no more progress to make here, at least at this time?

**Comment by JosephMcArthur** [comment]
superseded by #1096
