### ISSUE TITLE
What to do when we do match the article, but don't get all the meta-data

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1170]
There are some cases where we'll do a title match, but not get the year, journal title, or some other essential bit of information *for ILL* that eventually we might make essential. 

What should we do then? Subs & OA matches may not need them, so we still want to show them, but the ILL will not go through.

I feel like somehow displaying a box for missing meta-data on the results page might make sense, which has to be filled before submitting. Or, having the submit request click through to a form, which then submits. 

Mark, I'm wondering what the ideal solution for you might look like. What is easiest for you?

**Comment by markmacgillivray** [comment]
if we find an OA or a sub then the user is able to click on them to continue. But if they choose to do the ILL, at the moment it just allows them to do so regardless of what metadata we have. However, in the case where nothing was found we do push the user to the form where they have to provide mandatory metadata before being able to progress to submitting an ILL. So it seems to me that we should push users to that metadata form in every case where there is not mandatory metadata, and if they do not provide it all then we do not allow them to submit an ILL. In this case, we will need some reason to give to them which says why we are refusing to do it.

**Comment by JosephMcArthur** [comment]
I suppose the best UX here is defined by how often the sub / oa is what they want. From the tests, it seems like most of the time this is it, which means putting a form in front of them would be a waste, but in the real world that might not be the case or I suppose maybe the results could be wrong.

Let's do this. 

* if we get no metadata or matches, put direct to the form (as discussed)
* if we get no metadata but a match, show matches and option for ill as now. However, when they try to complete the request show the wrong article form with whatever info we have included. When they submit that, skip the availability checks etc and go right to ILL.

**Comment by markmacgillivray** [comment]
I've made some extensive changes to try to handle this and the wrong article workflow effectively.

Now, the user searches for something. If we get back no metadata or just a title we push the user straight to the metadata form.

The the user can try adding some metadata. Then we check again. Then the user sees whatever we did manage to find - OR, if in the first case we did find more than just title, the user will already be at this point.

if it is still not the right thing, the user can click to provide more metadata and try again.

If at any point we found an OA  or a sub, or we have an openurl or email option, these will be shown as it used to do if we have more metadata than just title.

If the user does click an OA or a sub, they are redirected and we are done.

If the user clicks an openurl or an email option, then if there is still not enough of the necessary metadata (at least title, journal, and year) then they will see the metadata form and will be asked for more.

Once the user has provided sufficient metadata we do one more check to see if we can get any more (if we did not already now have enough) and we either update the openurl and send the user on to it, or trigger an email request. 

If the user gets to the metadata form 3 times via any methods, we give up and show them an error recommending they contact their library. They also get this error if we fail to create an ILL on their request for any reason.

The system now also records an ILL creation on our API, whether the user creates an ILL via email or even if just an openurl forward is occurring, so that we have record of all of the times we got to the point of creating an ILL.

As already covered in the stats, we now show the count of how often we created an ILL with all the core metadata as well.

I am going to add a column to the stats to show how many are openurl forwards vs email ILLs, as that may be useful too.

I have tested this and I think it covers everything and works, but as it is quite convoluted it would be good for someone else to look over first before pushing it to live.

**Comment by JosephMcArthur** [comment]
> Now, the user searches for something. If we get back no metadata or just a title we push the user straight to the metadata form.

Tried this with 'llkj kj kj lkj lkj lkj lkj lkj lkj lkj lkj ' and got back what I'd expected from our designs / discussions and the above. Thanks!

> The the user can try adding some metadata. Then we check again. Then the user sees whatever we did manage to find - OR, if in the first case we did find more than just title, the user will already be at this point.

I then tried with 'Some Specific Taxonomic Characters of common Lucilia Larvae-Calliphorinae-Diptera.' and when to the wrong article form. I put in the right info by hand: Knipling, EF, 1936, Iowa State College journal of science. Then, on submit, I was told we couldn't find a match and given an error. In this case, the user provided all the info to make an ILL, so they should have been allowed to do that. I think there is a bug there. 


> if it is still not the right thing, the user can click to provide more metadata and try again.

This seems reasonable. Haven't been able to test yet due to the above. 

> If at any point we found an OA or a sub, or we have an openurl or email option, these will be shown as it used to do if we have more metadata than just title.
If the user does click an OA or a sub, they are redirected and we are done.

Seems good. Tried this on the demo one. I like that we filled the wrong article form with what we had at this stage. However, two odd things happened:
* if I say that what's searched here is wrong, then change nothing, and continue the request when I arrive back at the results page the journal title changes. 
* if I do change something, say changing 2016 to 2017, it changes that back. When the user gives us information on that page, we have to trust it and only enrich, not change it. E.g if they give us a journal title, sure lets try and find the ISSN, but I don't think we should adjust their input since that's the human backup for all the automation. 

> If the user clicks an openurl or an email option, then if there is still not enough of the necessary metadata (at least title, journal, and year) then they will see the metadata form and will be asked for more.

I've not been able to find an article where this case actually comes up, which is suprising but in good way! Do you have a test article for this? 

> Once the user has provided sufficient metadata we do one more check to see if we can get any more (if we did not already now have enough) and we either update the openurl and send the user on to it, or trigger an email request.

I think I've spoken to this above

> If the user gets to the metadata form 3 times via any methods, we give up and show them an error recommending they contact their library. They also get this error if we fail to create an ILL on their request for any reason.

Do we need to set an address for them to email at set up perhaps? This seems reasonable though. Could we get a notification if the happens maybe, would that be possible? 

> The system now also records an ILL creation on our API, whether the user creates an ILL via email or even if just an openurl forward is occurring, so that we have record of all of the times we got to the point of creating an ILL.

Thanks!

> As already covered in the stats, we now show the count of how often we created an ILL with all the core metadata as well.

By core, you're included the ISSN in here too, yes? 

> I am going to add a column to the stats to show how many are openurl forwards vs email ILLs, as that may be useful too.

Is this per embed, or in total? Agree it's helpful in total, but not per embed (as you can only use one at a time)

**Comment by markmacgillivray** [comment]
Confirmed in chat, keep what the user gives us.
