### ISSUE TITLE
Add caching to InstantILL to speed up responses

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1177]
Seems like we should add caching back onto InstantILL to speed it up when possible. We have caching on some sub-systems already, but not all, and not on all the response. 

From a quick chat with Mark. 

> There are a bunch of things to take into account that are not the same for instantill as they were for availability checks. Such as the criteria we use to decide if a result is good enough to be worth caching, and then whether or not to re-use or replace a result at a later time, and also whether or not we would use user-provided values as cached results, given that we are going to be accepting user values over our API values.

A few thoughts:
* I'd not cache user input (until we see some indictation it's good)
* Let's cache results for the same amount of time as we cache availabilities. 

I'm unclear what criteria are included in:

> the criteria we use to decide if a result is good enough to be worth caching

**Comment by markmacgillivray** [comment]
When a user gives us metadata to override with, cache that as well. Then the next time we serve that overwrite with new user content if necessary

**Comment by markmacgillivray** [comment]
Done, but we actually cache the metadata as we find it rather than as the user gives it, except where the user gives us something we do not find at all. This does not affect what any user sees, because any cached result we return will still be overwritten by any specific metadata they have given if it is different, so caching what we actually found was easier and did not impact intended functionality.
