### ISSUE TITLE
If critical InstantILL APIs go down, display an error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1182]

**Comment by markmacgillivray** [comment]
Rather interestingly, serialssolutions seems to be down for the last hour.

**Comment by markmacgillivray** [comment]
An error message has been added, saying:

"Please note, we encountered errors querying the following subscription services"

Then lists the name of whatever subscription endpoints failed to return. Note though that because it is possible other subs do return, this would show up as extra info below whatever results we end up also displaying. I can change it to only show up if no subscription result was found at all, but it is not clear from the title of this issue if that is what is meant - it sounds more like you mean telling the user about things that were not run, regardless of answer found or not.

**Comment by markmacgillivray** [comment]
If our API does not work at all, change to the new msg. And move the "full article title" etc error to only show if we cannot run because title given is too short

**Comment by JosephMcArthur** [comment]
you can use this copy

> Oh dear, the service is down! We're aware, and working to fix the problem. Please try again soon, or contact the library.

**Comment by markmacgillivray** [comment]
Done
