### ISSUE TITLE
Stats from Subscriptions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1184]
Display stats from subscriptions (how many times the results show per embed, and in total)

**Comment by markmacgillivray** [comment]
To check, what do you mean by in total here? SO far on the instantill usage we have values per user ID, but no totals. The subs provided column will now show a count of when we have been able to find any subscription URL (although only for future ones where we find a subscription, due to recent changes in how we have decided to cache stuff). Is that OK? Or do you mean some other total somewhere else?

**Comment by JosephMcArthur** [comment]
keep as per user id, ignore total
