### ISSUE TITLE
Ensure you can only see your own data through the API

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1204]
Currently, the API is private to protect user data. We want to make it available to the universities whose data / embed it is. This will mean you'll need to be authorized to get data from the APIs.

**Comment by markmacgillivray** [comment]
This is the ILL API

**Comment by markmacgillivray** [comment]
This requires clarification. Originally it was only the /ills endpoint that we secured, which allows searching of all ILLs created via our system. The other endpoints are not secured, and the embed does not provide security credentials, it only provides user ID (which is the user ID of the user that configured and installed the widget, not necessarily the person using it) - all secured actions such as altering config are handled on the instantill web page, where the user is logged in. So we can't make all the endpoints actually secure, otherwise the embed would stop working.

Assuming this is OK, and is what you meant by this issue, I have done the following on each endpoint, on dev:

/ill 
GET: just confirms the service is here, no auth
POST: starts an ILL, auth is optional, if present we record which user created it

/ill/subscription
GET: tells whether or not a subscription is available for a given user account, giving a link if so, no auth required, but if auth is provided rather than uid param, then the auth'd user is the one we check the subscription for

/ill/metadata
GET: provides full metadata if possible for provided search parameters, no auth necessary

/ill/openurl
GET: will eventually be a redirect after reading openurl params, but not operational yet
POST: returns the configured openurl for the identified account, no auth required

/ill/validate
POST: validates an email address so the widget can confirm the provided email address is valid, no auth required

/ill/config
GET: returns the config for the account identified in uid param, or for the optionally authorised user
POST: alters the widget config for the authorised user, auth IS required (and this is not currently handled by the widget at all, only on the instantill web page where the user signs in)

/ill/:library
POST: for a given library, start an ILL (this was originally how we started ILLs for libraries when testing with Imperial). It does not require auth, but do need to know the right name/ID for the library to start for.

/ills
GET / POST: search all ILLs. Auth had been restricted only to OAB admin users and it showed all results - now it requires any OAB user, and only shows the ILLs created by the user account that is currently authorised. Admin accounts can still get queries of all results by adding an all=true param to their searches.

**Comment by markmacgillivray** [comment]
Assigning @JosephMcArthur to review the above

**Comment by JosephMcArthur** [comment]
On first read, this sounds right. But, it's complex and you understand it best. Let's discuss on the call to be 100% sure. 

My aim is that it's easy for a campus to get it's own data on ILL submitted through the API, but not see another campuses data. That is because they may have a local system for managing ILLs, and developer capacity to link that to InstantILL as a frontend (they could, for instance, run InstantILL in 'email submit' mode, but query the api in the background and pull things into their system). However, ILL data is often considered sensitive, people don't like the idea that data on what their people want is broadly available. So, only *they* should be able to get that data, not others (except us). 

The rest of the settings make sense to me, e.g  posts to /ill/config requiring auth.

> /ills
GET / POST: search all ILLs. Auth had been restricted only to OAB admin users and it showed all results - now it requires any OAB user, and only shows the ILLs created by the user account that is currently authorised. Admin accounts can still get queries of all results by adding an all=true param to their searches.

I'm presuming this is the part that matters from this case, and that we consider this done because it's restricted by user and only a user knows their ID (which is random, hard to guess, etc)?

**Comment by markmacgillivray** [comment]
As long as by "data" you mean the ILLs they have created, then yes, this is what we have secured. But it would be possible for someone to find out if a certain library has a subscription to something, or to find out the ILL base url, or URL configs, for any given user, if they know that user account details. None of that data should be stuff that actually needs to be secure, and would not relate to any actual user anyway, because that is the config data of the user account that created and installed the widget rather than the data of the users using it on campus.

Yes, /ills is the part that matters, but no it's not just secure on the user ID - it is actually secure, requiring the user ID and api key of the user that configured the widget. So this part is properly secure, and as you say, could be used by a library that does have dev capability to query the endpoint, and they would only get the ILLs created by their own users.

So I think we are agreed on this, and I am about to push to live but we don't actually tell anyone this yet anyway, but we can review when we talk then close this.

**Comment by JosephMcArthur** [comment]
By data I do mean ills created. Thanks for clarifying how secure it is, that sounds good. 

We are in agreement and can close this.
