### ISSUE TITLE
Debug IUPUI subscriptions

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1210]
I'm doing a systematic review of our effectiveness at gathering subs. The results are here: https://docs.google.com/spreadsheets/d/1LYla2xW0YkThmQiBEiXlzyfx6EZG69a0COTjR4fbtzM/edit#gid=294124953. 

Where we get it wrong, we need to debug as to why.

**Comment by JosephMcArthur** [comment]
From Chat

> https://journal.code4lib.org/articles/108
> that might be helpful, a xml interface for serial solutions
> it seems that for some of these, googling 'name of link resolver' + xml or json can help find bits and bobs
> and it seems to work
> e.g
> http://yv4zn7rr3m.openurl.xml.serialssolutions.com/openurlxml?version=1.0&genre=article&issn=00907324&title=Reference%20Services%20Review&volume=34&issue=1&date=20060201&atitle=The%20one-minute%20paper%20and%20the%20one-hour%20class.&spage=148&pages=148-155&sid=EBSCO:Library%2C%20Information%20Science%20%26%20Technology%20Abstracts&aulast=Choinski,%20Elizabeth
> works vs 
> http://yv4zn7rr3m.search.serialssolutions.com/?genre=article&issn=00907324&title=Reference%20Services%20Review&volume=34&issue=1&date=20060201&atitle=The%20one-minute%20paper%20and%20the%20one-hour%20class.&spage=148&pages=148-155&sid=EBSCO:Library%2C%20Information%20Science%20%26%20Technology%20Abstracts&aulast=Choinski,%20Elizabeth

**Comment by markmacgillivray** [comment]
I have changed the serialssolutions lookup to use the xml API instead of the html one.

From the xml, whenever there is an element that has the "article" type, I take the first one as being a link to an article that the institution should have access to, and that is what gets passed back. It does have an empty accountid param in it, but there is no way for us to know what that is, so we will have to try it as is and see if it works.

However there is also a new separate error somewhere that is causing titles to get passed into the search wrongly. The metadata is being incorrectly parsed, so I am looking for that error now.

I am also disabling caching on the ILL subscription checks until we get this sorted, we can turn it back on later, but may see some slightly slower results for now.

Also I do not understand what the spreadsheet of systematic tests is supposed to be doing - it does an availability lookup with the instantill plugin param, and returns ILL findings if we did find one, based on your account ID, I think. So, is your account currently set up to actually have access to the serials solutions endpoint that you are trying to test, and do you already know that the institution you are emulating has access to all those titles? It seems that the cells called "Does the LR have access" and "LR link" are all empty, so how would we know if it is something we should expect to be able to find or not?

**Comment by markmacgillivray** [comment]
As mentioned in msg just now, to clarify, work on this is ongoing and will probably not be completed this week (thus also holding up issues to come after it).

**Comment by markmacgillivray** [comment]
For the particular examples given above, just to note, it is not clear why the html one does not work, but that would be an issue we would face from our API. It is also not clear if that is an error that is happening for any other ones we have run, as we would have to look specifically for that error in our attempts. It appears to be a totally different page from the ones we were testing on previously, and is for a different institution(RIT). As this does however indicate that we can have no reliable idea of what sort of html page we could get back from these queries, it does unfortunately show that our previous approach of extracting the data from any returned html would be unreliable unless customised (or at least tested) for every institution that attempts to use it.

**Comment by JosephMcArthur** [comment]
> I have changed the serialssolutions lookup to use the xml API instead of the html one.

To what extent did you consider / test this?

> It does have an empty accountid param in it, but there is no way for us to know what that is, so we will have to try it as is and see if it works.

Have you been using the login for their subs I gave you? That would be a way to confirm this. 

> However there is also a new separate error somewhere that is causing titles to get passed into the search wrongly. The metadata is being incorrectly parsed, so I am looking for that error now.

Perfect, makes sense something like this would happen.

> Also I do not understand what the spreadsheet of systematic tests is supposed to be doing - it does an availability lookup with the instantill plugin param, and returns ILL findings if we did find one, based on your account ID, I think. So, is your account currently set up to actually have access to the serials solutions endpoint that you are trying to test, and do you already know that the institution you are emulating has access to all those titles? It seems that the cells called "Does the LR have access" and "LR link" are all empty, so how would we know if it is something we should expect to be able to find or not?

Yes, as of now my account is set up to hit IUPUI's endpoint. It was originally too, but I changed it at some point. All those articles, as discussed, are presumed to be available. The columns you mention are where i've gone back and double confirmed this by hand.

**Comment by markmacgillivray** [comment]
More note: it appears for that RIT one that their serialssolutions URL first tries to go through their own Shib endpoint, which refuses our connection. Probably because we are not on their campus. Any other institution that routes the links in this way would probably have the same problem. However, it does mean that it could be possible that the final page we would get to in the end could be the same html, thus negating my previous statement. Either way though, going straight to the xml URL solves the problem as they do not appear to route that through their shib (which begs the question, why is it routed that way at all?)

**Comment by markmacgillivray** [comment]
I'm not sure what you mean by the extent I considered / tested it. I previously wrote the parser based on the html because that is what I thought we were told from the institution. Then you mentioned there is an xml endpoint, and linked to the code4lib article about it. So I changed our parser to use the xml endpoint instead. I mentioned above what it does to extract an article from the xml it retrieves, which as far as I understand is what represents an article being available to the institution doing the search (or the institution we appear to be, when we do the search). The resulting xml does appear to have such a link in it, and the xml itself is accessible from my home IP address, so does appear to work. Given what I have also mentioned above about the RIT shibboleth rerouting issues, it seems that the xml endpoint is a better choice than the html endpoint.

I haven't used a login to check the subs, because at the moment it was not clear to me which institution I was testing. The issue is about IUPUI but the examples are for RIT. Now that I have written the xml parser, what I will be doing next is seeing what results I get back for the titles given in the spreadsheet - but I can't do that until after I fix the title metadata parsing problem.

Thanks for clarifying what the fields in the sheet mean, and which institution your account is configured to check. I can continue the testing with that sheet once I fix the metadata error.

**Comment by JosephMcArthur** [comment]
> I haven't used a login to check the subs, because at the moment it was not clear to me which institution I was testing. The issue is about IUPUI but the examples are for RIT. Now that I have written the xml parser, what I will be doing next is seeing what results I get back for the titles given in the spreadsheet - but I can't do that until after I fix the title metadata parsing problem.

Sorry, we're testing IUPUI. I sent an RTI link as an example, and the paper as backup, but the same transformation works for IUPUI and other serial links (which I tested, but didn't send here at least (i may have in chat??). )

> I'm not sure what you mean by the extent I considered / tested it. 

You've answered it, I just wanted to understand if you'd tested each throughly before change to help me as I consider / test on my end. 

I feel up to speed here, thank you!

**Comment by markmacgillivray** [comment]
Yes, by "which one we are testing" I meant has the sheet been changed to try RIT now, since the examples above had been for RIT rather than IUPUI, but you've already clarified your account is setup for IUPUI and the titles in the sheet are expected to be available for IUPUI, so that makes sense now too, thanks.

**Comment by markmacgillivray** [comment]
The metadata problem is solved. Moving on to testing the new subscription check method.

**Comment by markmacgillivray** [comment]
Notes:

It appears that Joes account only has some hull URL set as a subscription endpoint, so that does not match any of the 3 subscription checkers we have written so far. So the lookups from the sheet will not work, as they try to use Joes account. Using my own account, which has the 3 examples that do work, I can get it to query the xml endpoint and get a response.

However, so far it appears that it will never respond positively when given a title. Although the instructions it provides say that it will work with at least one of a title, doi, pmid, or ISSN, it seems that this is not true. Testing with the examples above, it ONLY works if article title AND journal title are provided, or one of the identifiers.

So at the moment our approach will certainly not work for just titles - we are going to need to at least find the journal title first as well. I am looking into how possible that is.

**Comment by markmacgillivray** [comment]
OK, I believe it works now. However the results we get back can contain items that are open access, and they seem to come before the subscription links, although I don't know if there is a reliable order to how they appear. There is no element tag to indicate which are subscriptions and which are open, but there are element tags that give the source of where the link came from, and the "database" it is in. But without knowing which source URLs or database IDs they use for all the possible open access locations, we can't reliably filter the article URLs based on those values.

So all I have done for now is, if there is an article URL, take the first one. So we may well be returning open access article URLs to people as subscription URLs (and likely would have already given the user the open URL anyway).

Take this one for example, that lists DOAJ and NLM first as sources, and then Ebsco, Proquest, etc:

http://rx8kl6yf4x.openurl.xml.serialssolutions.com/openurlxml?version=1.0&atitle=Chronotopic%20maps%20in%20human%20supplementary%20motor%20area&title=PLoS%20biology

This means we cannot reliably give them a URL that they CAN submit an ILL for, even if they don't need to, which is something that our instantILL workflow does currently try to offer the user.

Does this matter? If it does, do you (or any of the library people you are in contact with) know of a way of filtering out the open access ones?

**Comment by JosephMcArthur** [comment]
> It appears that Joes account only has some hull URL set as a subscription endpoint, so that does not match any of the 3 subscription checkers we have written so far. So the lookups from the sheet will not work, as they try to use Joes account. Using my own account, which has the 3 examples that do work, I can get it to query the xml endpoint and get a response.

I was on terrible wifi earlier, my account must not have saved, sorry. 

> So at the moment our approach will certainly not work for just titles - we are going to need to at least find the journal title first as well. I am looking into how possible that is.

Helpful update, thank you! Unhelpful docs from their side... I presume we can just use the meta-data look up to find some of this

**Comment by markmacgillivray** [comment]
A script has been written to run though titles in the test sheet and create a results sheet where we can review the output. The script still has to be run, should be able to do it later today.

**Comment by markmacgillivray** [comment]
Testing a few times with the first two titles in the test sheet, I cannot get it to work using the ID of the "Joe" user. However, using my own ID, I can get it to find one of them (from serialssolutions).

Sticking with my own ID, I tried running the top 10. Five can be found. Of the five that cannot, three were ones we could not find metadata for, so it was not possible for the subscription lookup to succeed. But two where we did have the metadata including journal title still could not be found. I have been unable to find out why this is.

Providing article title AND journal title, taking away any failings in our metadata lookup, we find five as well. I do not yet know why there is not an improvement here either.

**Comment by markmacgillivray** [comment]
Continuing testing

**Comment by markmacgillivray** [comment]
Manually check the link resolver html endpoint as well, in case there are false positives in the sheet

**Comment by markmacgillivray** [comment]
Assuming that a result showing journal info in the xml means that there is a subscription to that journal, then we are able to find 64 out of 100 by just title (e.g. we find the journal ourselves and then are able to lookup).

If title and journal are provided, we find 89.

So, if the first 100 in the sheet really are ones that IUPUI subscribe to, then as long as we find or are given a title and a journal, and assuming that seeing the journal info in the XML means they do have a subscription, then we are able to find 89% of them.

But there are still issues. Firstly - we need IUPUI to look at the first 100 in that sheet and let us know if they really do have access to those journals. I have not found a way in the XML to be certain that we are not just seeing the journal metadata given back to us even if there is a subscription or not - so I am just assuming that if it IS there, then it IS a subscription. Looking up visually may help with this, but only if the person looking knows whether or not what they are looking at definitely does mean they have access.

Secondly - we still have the issue that these journal results are ONLY telling us the journal metadata. We do not get back a URL for these results. At least 31 of the 100 tested are in this category. So, we need to decide how to change the UI of the widget, because up to now we have assumed we will have a link to serve if we do find there is a valid subscription. That will have to be changed.

@JosephMcArthur this is probably all I can do on this for now, can you get some feedback from IUPUI? The only other thing I could do is run more through it, but I think it would be more useful to first get confirmation of what IUPUI think they have access to, of that first 100.

**Comment by JosephMcArthur** [comment]
On me, unassigning Mark
