### ISSUE TITLE
When admins upload a file on receiver pages, auto-publish file on Zenodo, and fire 'successful_upload'

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1230]

**Comment by markmacgillivray** [comment]
Done on dev, should be tested

**Comment by markmacgillivray** [comment]
Still a problem with this saving, rec is undefined. Need to check all the different declared vars across the two pages

**Comment by markmacgillivray** [comment]
I have fixed this and checked that altered fields can save successfully. I have not yet checked that every item of the admin controls are functional - I could do that, but what would be the result? e.g. can I safely try the status change quick actions, or will they trigger actual emails to users on dev? I do not know because I did not recently do this sort of testing. What were you doing before to test these?

There is also still the matter of testing the change that this issue was actually about - automatically publishing on zenodo. It is not clear how we could really test this, as it will create a real published item on zenodo.

Assigning @JosephMcArthur to consider the above

**Comment by markmacgillivray** [comment]
Note I can do full testing, and check whether or not emails send, and disable them if so, and test every item of functionality on the page, but I estimate that will take about another day to go through all possibilities. This could be done before proceeding to other items in the next sprint.

**Comment by JosephMcArthur** [comment]
Looks good Mark. As ever, we'll test this in production due to having no sandbox for zenodo atm. Just glad to hear you've tested basic saving via the UI :)
