### ISSUE TITLE
Mike's Wrong Paper Issue

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1264]
> One of our patrons report a false match for a title search in the InstantILL search box, and I’ve confirmed it. Passing it along as a bug report J
> 
> When we search for “The Church of Greece in critical times: reflections through philanthropy” it returns the correct citation, but then links to an article on breastfeeding from a different journal
> 
> http://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC4410446&blobtype=pdf
> ![image](https://user-images.githubusercontent.com/4953703/64463637-9f08c980-d0fc-11e9-8fb8-49e4a0ae5f26.png)

**Comment by markmacgillivray** [comment]
As the issue describes, we do find the right data for this paper. But at some point in the past, we must have had an error that caused us to pick up the wrong article from EPMC. I have cleared this from the cache and retested, and now we don't show up the wrong OA link - we don't show any link at all, unfortunately, because although we do still get the correct metadata, we do not find a suitable OA paper now. But, that is better than returning the wrong one!
