### ISSUE TITLE
Complete TODOs in new demo & alpha page

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1266]
See code comments. It's a variety of small bugs, tweaks, and general bits and bobs I've seen while testing.

**Comment by JosephMcArthur** [comment]
mark, gone in and cleaned up a bunch of stuff on my end. Code pushed. TODOs still left for you still need done as part of this.

**Comment by markmacgillivray** [comment]
One TODO still left, to make the save and preview pick up changes to settings

**Comment by markmacgillivray** [comment]
Note a new todo, change the code so that the height of the demo is not controlled to the height of the window or content - the demo will sit below the other content of the page, and must have some height that is suitable, but not related to the rest of the page height.

**Comment by JosephMcArthur** [comment]
below & above other content. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, the TODOs have been finished and the code has been altered so that it does not create a large area around the instantill box when included on the demo page. However, we are now back to it not centring on that area either.

Let me know if you want me to spend more time making it centre on that area, regardless of where that area might appear on that page, and what other content may be above or below it. Also, let me know if you want me to spend more time keeping it centred when it changes size after it does a search. Also, if the size of the result is larger than the green box to the right of it, should it also change the height of the green box to the right to keep centred in comparison to that extended green right hand side, or should it just overflow it and leave a white gap below the green right hand side?

**Comment by JosephMcArthur** [comment]
Do you have idea how long this might take to get it to a similar standard as before, given the below?

> Let me know if you want me to spend more time making it centre on that area, regardless of where that area might appear on that page, and what other content may be above or below it.

Ideally yes

> Also, let me know if you want me to spend more time keeping it centred when it changes size after it does a search.

Ideally yes

> Also, if the size of the result is larger than the green box to the right of it, should it also change the height of the green box to the right to keep centred in comparison to that extended green right hand side, or should it just overflow it and leave a white gap below the green right hand side?

Ideally former.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK I have added some spacing controls on that, hopefully should be good enough. If not, let me know and reassign this to me.

**Comment by JosephMcArthur** [comment]
Could we do a bit more spacing on top and bottom? It seems to work pretty darn well expect at #part6 where the button on instantill merges with the next section. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
OK, done more spacing. How is it now.

**Comment by JosephMcArthur** [comment]
it's looking good. I think same has changed some button space, etc, as you said which is throwing stuff off a bit so I'll as him to fix. For now, let's close this! 

Thanks again! Great progress.
