### ISSUE TITLE
more issues with sfx

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1273]
See the following:

> We can't seem to make our SFX link work. See screenshot below for our setup:
> 
> Screen Shot 2019-09-16 at 1.02.26 PM.png
> 
> Comments from IT staff:
> 
> I've tried all three:
> http://resolver.library.ualberta.ca/resolver/ 
> http://resolver.library.ualberta.ca/resolver?
> And
> http://resolver.library.ualberta.ca/resolver?_service_type=getFullTxt
> None of them worked for me. 
> I just tried it with
> http://resolver.library.ualberta.ca/resolver (no trailing slash).
> And still no luck. Can you find out from them how much information is *supposed* to be in that box? Their example URL contains a lot more information, but at the moment it doesn't look like it's even trying to search SFX.
> 
> Here is an example title from an EBSCO database for an article we have holdings for with our SFX link:
> 
> Understanding students’ satisfaction with OERs as course materials
> 
> http://resolver.library.ualberta.ca/resolver?ID=doi:10.1108%2FPMM-12-2017-0059&genre=article&atitle=Understanding%20students%E2%80%99%20satisfaction%20with%20OERs%20as%20course%20materials&title=Performance%20Measurement%20and%20Metrics&issn=14678047&isbn=&volume=19&issue=1&date=20180205&aulast=Shanna%20Smith%20Jaggars,%20author&spage=66&pages=66-74&sid=EBSCO:Emerald%20Insight:edsemr.10.1108.PMM.12.2017.0059  
>

**Comment by JosephMcArthur** [comment]
Pending finding user id, which I have requested

**Comment by JosephMcArthur** [comment]
email sent

**Comment by markmacgillivray** [comment]
That account has the old style of subscription config. We would need to ask them to login to their config page and set the subscription type to sfx. Their subscription URL does not have anything in it that allows our system to guess, so the old config is not working for them.]

@JosephMcArthur  If you could contact them and ask them to make that change then try again, that would be best - then we can confirm that the config change works for them too, and then see if they get results.

**Comment by JosephMcArthur** [comment]
okay, I thought I'd covered bases on this but they were still doing this around the time of change so maybe there was weirdness.

**Comment by JosephMcArthur** [comment]
They say it's still not working, having done that. Can we check their config again, and if it isn't working we'll need to 1) update it on our end and 2) look into why it's not being updated (likely just testing it on our systems again)

**Comment by markmacgillivray** [comment]
Their config is updated now to show the correct type, so that part is working.

The page content that it returns, though, is not the same as the page content we had previously analysed for finding sfx links. So it was not able to find a fulltext link from that html page.

We had recently tested sfx xml lookup though, and had found that it worked better. But it seems we were not yet able to identify that this was an sfx url that we could append the xml param onto.

I tested the lookup of their sfx page, and it was not successfully triggering the switch to xml that we previously added on dev, so I have made some changes to that so it should get picked up that this is an sfx url that we can add an xml param to, so now it is capable of returning the xml.

Once we get the xml, for the link they give above, we are able to find the link to the full text. 

However, their config has not been set up to tell us that their endpoint expects the doi to be in a field called ID - so we are not actually successfully passing the DOI into that endpoint. Despite this, though, it is still found as we have sufficient other metadata in this case. But it could be possible on future ones that we would not have enough other metadata, so without properly passing the DOI these lookups could fail where they should succeed.

I imagine this is something to do with the config system not being obvious about how they should be renaming their params so that we can know to use ID instead of our default for doi (which is rft_id).

Additionally though, even if we did know the correct URL param from their config to put the DOI into, it still would not work, because the endpoint expects the DOI to be prefixed with "doi:". There is no way in our current system to get the user to tell us that a value must also have a prefix, and there is no way that we could tell whether or not this is the case. At best we could just guess that if it is an sfx endpoint then the doi has to be prefixed. But if we are just going to guess, I think we would have been as well not bothering with all the complex config stuff and we should just test whether or not certain endpoints actually need specific user-configured params or not, or if we can just assume that certain endpoints will accept certain params (I would think this is the case, but we have not tested that, as we did not design the system this way). It is also still possible that these endpoints have a more programmatic alternative that we have not yet put time into investigating, either, but these are certainly points beyond the scope of this issue.

Note, it will not be possible to ask this user to re-test our changes until we update live, as they are using a live account rather than a dev one, so they will still be seeing errors if they try it.

I'd suggest we do the following:

* update live with these latest changes, and ask the user to re-test
* create and schedule new issues to investigate each of these endpoints we have built into the system and find out if user-defined configuration is actually necessary, or if there are well-defined alternatives we could reliably use instead
* create and schedule a new issue to simplify (or remove, depending on the result of the above point) the user configuration portion of the instantill UI
* if we cannot remove the user configuration and do have to rely on what the user tells us in order to configure the URLs, we also have to create and schedule an issue to work out how to get the user to tell us not only the name they use for each param, but also whether or not that param value requires some sort of prefix, such as "doi:" before a DOI, and also whether or not that prefix is always the same or has to depend somehow on the value being sent. Given that "ID" is pretty generic and it seems to specify the TYPE of ID using the prefix "doi:", it is possible that this is the case. This could be very difficult, or impossible, depending on how much flexibility we want to try to support.

**Comment by JosephMcArthur** [comment]
Thanks, Mark. Lots of comments so let me confirm understanding.

> Their config is updated now to show the correct type, so that part is working.

Get, so looks like there was an issue originally with caching that is unlikely to happen again. Good.

> The page content that it returns, though, is not the same as the page content we had previously analysed for finding sfx links. So it was not able to find a fulltext link from that html page.
> 
> We had recently tested sfx xml lookup though, and had found that it worked better. But it seems we were not yet able to identify that this was an sfx url that we could append the xml param onto.
> 
> I tested the lookup of their sfx page, and it was not successfully triggering the switch to xml that we previously added on dev, so I have made some changes to that so it should get picked up that this is an sfx url that we can add an xml param to, so now it is capable of returning the xml.

Gotcha, so sounds like we had a few kinks to work out here and have now done that. Good news. 

> Once we get the xml, for the link they give above, we are able to find the link to the full text.

Great. In my book, that's this issue closed (pending release / confirmation etc).

> However, their config has not been set up to tell us that their endpoint expects the doi to be in a field called ID - so we are not actually successfully passing the DOI into that endpoint. Despite this, though, it is still found as we have sufficient other metadata in this case. But it could be possible on future ones that we would not have enough other metadata, so without properly passing the DOI these lookups could fail where they should succeed.

Okay, my brain hurts thinking about all the configs. What you're saying is... How *we* give data to SFX means they don't understand it. I.e when we're pinging sfx to ask for data, we're giving them the wrong values so may not always get a correct response.

> I imagine this is something to do with the config system not being obvious about how they should be renaming their params so that we can know to use ID instead of our default for doi (which is rft_id).

How would they currently change these values? Can they? 

I seem to remember originally we had the values that we sent to ILL systems and the values we sent to Link Resolvers (like SFX) tied, but I said we shouldn't do that as they're *different* systems. We discussed making independent values and giving a UI for that, but it wasn't clear it was actually needed, so we backed off. 

> Additionally though, even if we did know the correct URL param from their config to put the DOI into, it still would not work, because the endpoint expects the DOI to be prefixed with "doi:". There is no way in our current system to get the user to tell us that a value must also have a prefix, and there is no way that we could tell whether or not this is the case. At best we could just guess that if it is an sfx endpoint then the doi has to be prefixed. But if we are just going to guess, I think we would have been as well not bothering with all the complex config stuff and we should just test whether or not certain endpoints actually need specific user-configured params or not, or if we can just assume that certain endpoints will accept certain params (I would think this is the case, but we have not tested that, as we did not design the system this way). It is also still possible that these endpoints have a more programmatic alternative that we have not yet put time into investigating, either, but these are certainly points beyond the scope of this issue.

This makes sense, it's a complex problem. 

> Note, it will not be possible to ask this user to re-test our changes until we update live, as they are using a live account rather than a dev one, so they will still be seeing errors if they try it.

Roger

> I'd suggest we do the following:
> 
> update live with these latest changes, and ask the user to re-test
> create and schedule new issues to investigate each of these endpoints we have built into the system and find out if user-defined configuration is actually necessary, or if there are well-defined alternatives we could reliably use instead
> create and schedule a new issue to simplify (or remove, depending on the result of the above point) the user configuration portion of the instantill UI
> if we cannot remove the user configuration and do have to rely on what the user tells us in order to configure the URLs, we also have to create and schedule an issue to work out how to get the user to tell us not only the name they use for each param, but also whether or not that param value requires some sort of prefix, such as "doi:" before a DOI, and also whether or not that prefix is always the same or has to depend somehow on the value being sent. Given that "ID" is pretty generic and it seems to specify the TYPE of ID using the prefix "doi:", it is possible that this is the case. This could be very difficult, or impossible, depending on how much flexibility we want to try to support.

Understood, and I broadly agree. 

Thank you for digging into all this, extremely helpful to understand this situation better.

**Comment by markmacgillivray** [comment]
Yes, so far we never gave them a specific way to tell us URL params for the two parts, but as we did not make any changes there in the end, it still uses the config for both parts. So, whatever config they create for the names of the params they accept is also the config we will use for the params we send to the subscription endpoints. In the case of the user this issue is about, none of those params are configured, so I was saying that they do not appear to have tried changing them for either case (which is not obvious to them anyway, hence is something we should do something about).

But it is still also true that even if they changed them, we would not know to prefix the DOI with "doi:", so even if they do configure them, it will make no difference.

For the case of finding out if user configuration is even necessary, we should explore if we can automatically discern usable URL param names for both their ILL endpoints and their subscription endpoints. If so we can get rid of all that URL config stuff. If not, we can at least make it clear which one it is necessary for. If it turns out to be necessary for the subscription ones, then we still have the additional problem of having to know possible value prefixes such as "doi:", which we have not tried to solve yet, and which may be intractable, depending how much of a generalised solution we hope to achieve.

So shall we keep this open until we push to live and you can confirm with the user then close or update?

And for the suggested new issues, do you want to create those now and schedule them, or after this issue is closed, or should I create them?

**Comment by JosephMcArthur** [comment]
Leave it all with me for now. When we deploy I'll get in touch, and we can close this once I've turned this all into issues. That's on me, I think I get it, and I just want to look at all our info in this context.

**Comment by JosephMcArthur** [comment]
A brief note to self, in all other sfx links we've seen they have doi infront of doi's. https://github.com/OAButton/discussion/issues/1244

**Comment by JosephMcArthur** [comment]
To close I need to:

- [ ] Get dev in shape to push
- [ ] email CJ
- [ ] make issues

**Comment by JosephMcArthur** [comment]
New issues here are covered under #1202. All other stuff for this is pushed, so closing.
