### ISSUE TITLE
zenodo upload issue, part 1213

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1274]
> I got a notification for a zenodo upload that required publishing for these requests https://openaccessbutton.org/request/Qbmx3H2siq4QRAHWZ,  https://openaccessbutton.org/request/DMz5Jy79mgegrPR6t. But when I go to Zenodo there is no record created for the articles, and their response pages are not showing a url for the supposedly uploaded files

**Comment by JosephMcArthur** [comment]
cc @natalianorori

**Comment by natalianorori** [comment]
Zenodo is not taking uploads at all since yesterday evening. I've tried logging out, uploading as an admin and uploading as a username and the site does nothing, not even an error message. I've checked Zenodo and uploads are not being recorded there either. Not sure if this is related, or if I should move this to another issue

**Comment by natalianorori** [comment]
What I mentioned above seems to be working now.

**Comment by JosephMcArthur** [comment]
But the original comment still stands. Something is clearly up.

**Comment by JosephMcArthur** [comment]
Let's only look at the files raised in the initial post.

**Comment by JosephMcArthur** [comment]
Won't fix: instead focus on shareyourpaper and retire this system.
