### ISSUE TITLE
Push refactored code live

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1322]
Making an issue since this a big job

**Comment by markmacgillivray** [comment]
One thing about pushing live - it will break your stats page, as the way we run finds is quite different now. So, as long as you don't mind not having up to date stats for a while, it is OK. But if you want up to date stats, we will need to do some work on the stats before we can push to live.

**Comment by JosephMcArthur** [comment]
That's fine, how long will it take to fix stats?

**Comment by markmacgillivray** [comment]
It depends how fixed you want it. There will be some work to change the stats page itself to query the new catalogue/find endpoints instead of the old ones, which will no longer get updated. That will probably take a couple of hours, as there may be some other small changes that affect how the queries for the tables/graphs operate so they will need to be checked.

Then, if you want to continue to be able to see old and new data all on that page, we will need to write and run some scripts to convert all the old availability checks into new finds. That will probably be two or three hours to write, test, run on dev, then run on live and check results.

**Comment by markmacgillivray** [comment]
All issues prior to this one have been done, so pushing to live is what I will be doing tomorrow, unless you want to delay it. In which case let me know what you would like to prioritise ahead of it.

**Comment by JosephMcArthur** [comment]
Nope let's push this out

**Comment by markmacgillivray** [comment]
This has been progressed but not completed yet - should finish it tomorrow.

**Comment by markmacgillivray** [comment]
This was done at end of last week but have kept it open while I have been checking logs for any issues
