### ISSUE TITLE
Create 'Re-deposit' route for then articles are OA

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1324]
Currently, the deposit route for OA seems to be using the dark deposit route (in terms of API / UI). This isn't quite right, although it's a similar route in terms of how it works for us.

To properly do the OA deposit we should create a route in that API that is the same as the dark deposit route except:

* it dumps any url's to open content in the emails / records created
* It's called 'redeposit'

On the UI, it should go like we have, except once they submit their email they should see:

![Published _ Live (1)](https://user-images.githubusercontent.com/4953703/70265877-3d0b3f00-1793-11ea-857d-45df8ca6c4a9.png)

**Comment by markmacgillivray** [comment]
I don't understand how this will functionally be any different from dark deposit. The paper is already open, but any additional copy we get given will just go to the institution, right? So, as with any other dark deposit, we will not know when it actually gets deposited in the institutional repo - and also in the case of one that is already open, we will probably never know when it becomes discoverable in an institutional repo, because we will already have recorded a discovery of it somewhere else.

So the only place they can "redeposit" it is with their own institutional repo, the outcome is the same as (or actually slightly more opaque) than any other dark deposit - so, why would we make it a different action to a dark deposit? Is there something else you think we would get from it that I am missing?

**Comment by markmacgillivray** [comment]
What I have so far is:

* if an email address is provided it is a dark deposit
* if a file is provided it is a "forward" deposit where we send the file to the institutional user
* if a file had been provided in a case where it was not from an institutional embed, this would be a "review" deposit and would go to our admin
* later once we have file and permissions checking that lets us auto deposit, we will have another type called "auto" where we put it straight in zenodo. Some of the "forward" and "review" ones would then be able to become "auto" ones in future.

**Comment by JosephMcArthur** [comment]
> I don't understand how this will functionally be any different from dark deposit. The paper is already open, but any additional copy we get given will just go to the institution, right? 

It's functionally similar to deposit in what we do, the initial and final conditions are different. The file starts open, and will be put in the new repo as an open record (i.e. not dark with means 'request only')

> So, as with any other dark deposit, we will not know when it actually gets deposited in the institutional repo - and also in the case of one that is already open, we will probably never know when it becomes discoverable in an institutional repo, because we will already have recorded a discovery of it somewhere else.

Indeed, this a tricky thing. Eventually, we may want to discuss how to close the feedback loop here. E.g would we want to run a version of find here that returns all answers, and then can check if we see one in a montana repo (for instance). 

> So the only place they can "redeposit" it is with their own institutional repo, the outcome is the same as (or actually slightly more opaque) than any other dark deposit - so, why would we make it a different action to a dark deposit? Is there something else you think we would get from it that I am missing?

I suppose, it's different mainly in that we'll want to count it differently, provide a different UI, and provide some different information on-route. I don't especially mind if that's a part of the 'dark' route, but I expect over the long term that will get confusing. 

I think thinks are seeming more similar now than they really will be in the fullness of time because we're early and the more sophisticated systems are still coming online.

**Comment by markmacgillivray** [comment]
So the only difference is that when I record the deposit information against the record, if the article is already publicly available, I should call it "redeposit" instead of "dark".

About closing the feedback loop, it's still not clear how that would be of any benefit to us or anyone else - we will already have a link to a publicly available record anyway, and we will already know we initiated a "redeposit" with the institution. Whether they follow through with it or not, and what URL it ends up at, will have no effect on the service we can offer to anyone.

**Comment by markmacgillivray** [comment]
Also it is still unclear why in some cases we take an email address and in other cases we take a file - especially now that in another issue you asked me to change it so that after we take a file we also take an email address.

What is the advantage of not taking a file from the user every time? Even if they give us the wrong file, eventually we will be able to check for that and do some work for the institution. And even if we still give a wrong file to the institution, they will have to email the user for the file - which is what they are already going to have to do every time anyway.

So it still seems that it would make more sense to just always take a file and an email if we are doing any kind of deposit, whether it is a dark one, a redeposit, or one that can be open but isn't yet available and needs reviewed by the institution or us.

**Comment by JosephMcArthur** [comment]
I just tried this and didn't get an email on submit

**Comment by markmacgillivray** [comment]
Can you describe what you did and what identifier you used? I have tried again just now using the example DOI from our site front page and i select "i still want it in scholarworks" then I put in my email address, and I receive the email that goes to you and me with all the info in it. Are you not getting that email or are you expecting another email?

**Comment by JosephMcArthur** [comment]
I'm using this: 10.1126/science.196.4287.293. I don't get an email. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Are you getting the emails when I do one? I just did one with that DOI on the montana page and I got the email, and it was copied to you and to Leila.

**Comment by JosephMcArthur** [comment]
At 7:37 I got one from dark deposit with you. I'm not getting an redeposits or emails when I do it. 

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I did a redeposit one again from montana page with the DOI you listed above, and I get the redeposit email. Also in my email history I can see that a redeposit email was also sent for someone putting in "joe@montana.edu", which I would guess was you, and that email went to me, you and Leila as well. Do you have that in your email history?

Or are you expecting the system to send some other email apart from the informational one to us?

**Comment by JosephMcArthur** [comment]
Just that email was going to spam for me!!! I see it now.
