### ISSUE TITLE
when file is deposited, show this

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1326]
![Published _ Can Share Post (3)](https://user-images.githubusercontent.com/4953703/70265233-e05b5480-1791-11ea-8ac2-1c71b42678f5.png)

Then...

![Published _ Live](https://user-images.githubusercontent.com/4953703/70265257-e81af900-1791-11ea-8c5e-747902b5d1b7.png)

The email should be saved, and passed along with the email and saved in the record.

**Comment by markmacgillivray** [comment]
Currently in the case where an item is already available we allow someone to go through to provide their email. Also when an item cannot be deposited we allow them to provide their email to "dark" deposit. If we also require them to provide their email in the case where they can provide a file, it seems a bit odd to make that different to the other ways. By adding this we are making it impossible to do anything without providing an email address. So why not just make that the next action regardless of what the case is?

e.g. the user puts in their identifier, then the next page shows them any of the possible variations. But in any of those variations we can offer the user to provide their email address and then to upload a file. There doesn't appear to be any functional difference in any of these steps in terms of what a user can actually do, so why make them different? We'd be as well getting the email address and any suitable file in all cases.

**Comment by markmacgillivray** [comment]
To clarify, as I understand it now, there is never any situation where a user CANNOT provide something. 

The user can put in their ID and find that the article i already available, and may choose to stop at that point.

However if the article is available they can still choose to dark deposit anyway. Or if the article can be publicly shared but is not yet available they can choose to deposit via us/their institution. Or if the article cannot be publicly shared it can still be dark deposited via their institution.

So in all cases if the user proceeds beyond "your file is publicly available" - the outcome can be the same: collect an email address and a file. We just show different words preceding the file upload box depending on which kind of deposit is possible.

It also seems like it would be easier to collect the email address and file in one screen rather than getting the file then showing another screen to ask for an email address...

**Comment by markmacgillivray** [comment]
Also, this final page example above says "check back soon to see your paper live". But there is now way we would be able to show that to a user, except in the case where the paper can be shared publicly but is not yet publicly findable - but those are the cases where we know we could instantly deposit. Any case where the file has to be deposited to the institutional repo can not be found by us  except in the case where we later pick it up as having been published there if it is possible to publish it in a "non-dark" way. But that will not necessarily be soon, and is beyond our control.

**Comment by markmacgillivray** [comment]
However I have made the changes as described in the opening of this issue, so if that still makes sense for you then you can just check and close.

**Comment by JosephMcArthur** [comment]
The changes here look good, and let's talk on the phone about the above more general thoughts
