### ISSUE TITLE
Webpages constantly flashing after InstantILL sign in

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1329]
Making an issue for this since it’s been reported more than once. In both cases, seemingly it went away by itself in a later session. 

For now, Mark, can you do a quick review of how I’ve made login on the page to make sure it’s okay and check anything that could be causing this.

Otherwise, we’ll keep this issue open to track.

**Comment by markmacgillivray** [comment]
I have tested and works fine for me on the dev instantill setup page. Would need more info on which bit is flashing, is it flashing or whole page reloading, does it happen before or after seeing the login page, before or after seeing the account page, etc.

Will assign back to you for followup with users if possible

**Comment by JosephMcArthur** [comment]
I FINALLY saw this. I can't replicate it, but here is roughly how it happened and what it looks like. 

I went to instantill.org/setup
Got to: https://openaccessbutton.org/instantill/setup
Wanted dev, so put .dev in front
put in email
hit login
when to login page
Then... I navigated away to get email
got email
before I put code in, I got sent back to instantill login page somehow
flashing as shown http://g.recordit.co/4NX8r1I0Tb.gif

**Comment by JosephMcArthur** [comment]
Must be my lucky day. 

Just saw it again. 

This time, I started at https://openaccessbutton.org/instantill/setup#login
This time, I went to dev.https://dev.openaccessbutton.org/instantill/setup again
I got to dev.https://dev.openaccessbutton.org/instantill/setup#login
I saw the embed on the left, which made me pause as generally that shouldn't show.
Put in my email again and went to login
Same thing as before, it seemed to log me in and redirect me
Same flashing as before

After this, I went to the account page, the same flashing was present. 
Seems it was a more general account issue maybe. 
Eventually, it stopped. 

In the end, I could replicate it by going to https://dev.openaccessbutton.org/instantill/setup#login while logged in on dev but not on live, and putting in my email. When that was flashing, https://dev.openaccessbutton.org/account was flashing too, as were other parts of the site. The flashing seems to be refreshing. Me refreshing or attempting hard refresh didn't work.

**Comment by JosephMcArthur** [comment]
In the end, I could replicate it by going to https://dev.openaccessbutton.org/instantill/setup#login while logged in on dev but not on live, and putting in my email. When that was flashing, https://dev.openaccessbutton.org/account was flashing too, as were other parts of the site. The flashing seems to be refreshing. Me refreshing or attempting hard refresh didn't work.

**Comment by JosephMcArthur** [comment]
I think, at least, we should make it so that if you go to https://dev.openaccessbutton.org/instantill/setup#login it checks if you're logged in before showing you the page.

**Comment by markmacgillivray** [comment]
I have been able to recreate the problem. It happens if you go to instantill not logged in, enter your email address, wait for the token email to arrive, click the link in the token email, and then while the link is opening, click back onto the page you already had open in your browser. It seems then that when the one you clicked in the email opens and logs you in, and then the one you are now already viewing (the old page where you started) tries to reload itself to the correct point, it gets stuck in a loop after trying to redirect you back to where you started (the instantill page). It causes a fresh login to start, and a progress check to take place, which ends up endlessly looping the page.

I have not yet found what is causing the new login to begin and kicking off the endless loop, but now that I know how to cause the error (by clicking back onto the first page whilst the other one is opening) I have an idea of where the problem is being caused, and am now working to find out which cookies are being set in the wrong order by the two different pages.

So this is close to solved, but will take a couple of hours more to do, which will have to be tomorrow.

**Comment by JosephMcArthur** [comment]
Perfect! This is great, let's do what's needed to close this before sending out the next round.

**Comment by markmacgillivray** [comment]
Fixed!
