### ISSUE TITLE
Repeat title usage results in inconsistent results

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1339]
There are a few bugs at play here I think, including #1334 & #1332. This is a bit separate in that the first time I searched the article we found all the info nice and fast, and then the second time we found none with the same input. I was shown this by another user who had the same experience.

To reproduce:

* Go to: https://library.scripps.edu/c.php?g=988098
* Search: 
> Reporting: Recommendations/Guidelines
* You should see us match it, and pull back data from https://link.springer.com/chapter/10.1007/174_2017_87. 
* Click submit request.
* Refresh and search the above title again. 
* Now you'll see use pull back no info.

**Comment by markmacgillivray** [comment]
I can see on that page (which connects to our live API) that the submitted title does not get kept and re-used, however I don't really notice a difference in what it returns each time. This is probably because the code has changed between now and when this bug was recorded.

I have tested this on dev and can confirm there that the latest code with fixes from this weeks sprint behave as we expect now. Please take a look on dev and if this seems suitable resolved you can close this issue, otherwise please provide more detail on what else I should change.
