### ISSUE TITLE
api documentation for deposit route

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1345]
- [x] Mark can you draft some text that I can edit for /api

**Comment by JosephMcArthur** [comment]
- [ ] Not to self. I think a part of this is about making sure the names of things we return are super clear. We're still iterating, which is totally fine, but I've noticed both Natalia & I mix up fields at a quick glance.

**Comment by JosephMcArthur** [comment]
Another note to self:

- [ ] review file api statements when they stabilize
- [ ] switch use of 'ricks' for 'permissions'

**Comment by JosephMcArthur** [comment]
Right, in #1377 I feel like we figure out a lot of the major things needed to make this thing work. I think this issue is going to become about making it easy to use.

So, as part of documentation I'd like to make sure that the API response itself is as human-readable, machine-readable and maintainable as possible. People are going to have a bias against trusting us here, which I think is important context.

In throwing it together I've seen Natalia, myself and external folks struggle with naming and what we do / don't pass back, so I'm going to basically up-end what I've previously said here. 

Generally, what I say here will apply to what we pass back in the API response and also the emails.

A few principles:

* lets name fields so that if you read them, you know what it means
* if we pass back 'true' it should be good news for depositing the file
* let's provide all our evidence and list core assumptions explicitly 
* let's match the rick's api when we can

Here are a few suggestions for changes:

## general

- [ ] even without verbose, we should pass back what is currently called `expected`, `lantern`, and `versioning` too.
- [ ] The URL field is a bit confusing. It seems to be both found OA URLs, but also the upload URL. This is quite confusing, we should probably split these out. `oa_url` and `given_url` may work.
- [ ] We should rename `ricks` --> `permissions_oab`
- [ ] We should rename `sherpa` --> `permissions_sherpa_romeo`
- [ ] `email` should be renamed --> `author_email`

## files

- [ ] rename `permitted` --> `file_archivable`
- [ ] rename `permits` --> `permissions_permits`
- [ ] rename `acceptable` --> `archivable`
- [ ] `acceptance` should get an overhaul. Right now, the statements we give are going to be tricky for machines to use, are hard for us to refer to, and currently need better copy. I think we can use them for the case of laying this out to humans elsewhere, and I'll make copy for that later. However, we should breakout the general assertions more specifically. I'm thinking a json response like this:

```
archiveable_reason:
        version_allowed_by_permissions: true / false
        licence_allows: true / false
        correct_paper: true / false
        depositor_confirms: true / false
        administrator_confirms: true / false
        readable_summary: "We believe this is a publisher pdf and Rick says such versions can be shared",
```

Now... if my plan works, then you should be able to pretty easily figure out what those true / false statements refer to having looked through your code :). So, I won't expand here. If I've missed one... let me know. 

- [ ] we should **add** `version_standard` as a response. This will translate `version` as follows:
* publisher pdf --> publishedVersion
* postprint --> acceptedVersion
* preprint --> submittedVersion

- [ ] `match` --> `correct_paper`
- [ ] `type ` --> `format`

- [ ] we should **add** a response for if we are / aren't able to perform a proper file analysis as follows:

```
analysis_possible: true / false
analysis_possible_reason:
        file_content_readable: true / false
        got_title_or_doi: true / false
```

again, there may be more reasons I'm forgetting. Those are the ones I know of. 

- [ ] `expected` --> `correct_paper_evidence`
- [ ] `words` --> `word_count`
- [ ] `doi` --> `doi_match`
- [ ] `title` --> `title_match`
- [ ] `author` --> `author_match`
- [ ] `type` --> `traditional_format`
- [ ] in `correct_paper_evidence` **add** a new line for `words_more_than_500: true/false` just to make our assumption clear

- [ ] in `versions/matches` can we have the system return the items in this order: `by`, `in`, `indicates`.
- [ ] rename `versioning` --> `version_evidence`
- [ ] rename `checked ` --> `strings_checked`
- [ ] in `version_evidence` **add** a new line for `format_not_pdf_so_postprint: true/false` just to make our assumption clear. This is especially important as we will use this a lot, and otherwise we provide little evidence for it here.
- [ ] I'm not 100% sure what `ve` does. I thought it showed what we've called +ve matches before, but actually it seems to add them up. I think we should break this out into:
```
publisher_pdf_text_indicator_matches: X
postprint_text_indicator_matches: Y
aggregate_text_indicator_matches: Z
```

- [ ] rename `matches` --> `matches_details`
- [ ] rename `by` --> `found`

- [ ] rename `lantern` --> `licence_evidence`
- [ ] **remove** `licence` from `licence_evidence` to keep symmetry with other `evidence`
- [ ] in `licence_evidence` rename `match` --> `found`
- [ ] in `licence_evidence` **remove** `matched` unless you know a good reason to keep it (seems always to be a less readable version of the `match`.

# Some Q's:

- [ ] Generally, it seems to me that currently `permitted` and `acceptable` are the same, is that true? If so, I may want to suggest we name them the same thing, or return only one.  I have assumed they are the same above.
- [ ] is `file/expected/type` the check we have to see if it's a sensible extension, like .docx, .pdf or .tex? I have assumed it is above.
- [ ] I'm unclear on why `statement` is sometimes at the top of the response. Can you explain?

All of this would mean our the file response would look like this: https://docs.google.com/document/d/1glV4naLWxztFHnKOnVSrGet5-YerMM6LaW9nrYK9xnI/edit

**Comment by markmacgillivray** [comment]
This entails changes to essentially everything we have done in the last few weeks. There is no way we can do all this and put out a live version on Monday. And if we make changes this big after Monday, we will instantly break any live version we have put out. So, we need to schedule this over the course of another couple of weeks, I'd guess.

**Comment by JosephMcArthur** [comment]
That makes sense, and I somewhat expected it, I should've stated that. Let's kick this out of the sprint, and discuss a plan and the changes generally on Monday.

**Comment by markmacgillivray** [comment]
Some responses to your questions and other things to consider:

* there is a difference in how we are thinking of permissions. To me permitted and acceptable are not the same because permissions are about an article, whereas acceptability is about a file. This difference seems to permeate a lot of what you have said above, so I do not understand how the structure you want would accurately represent the state of things in the world. To me, the permissions info we get is relevant to an article regardless of what file we are given, whereas the acceptability of a file can change depending on what file we are given. We could simplify down the way I have constructed it, so that we only ever give responses in the context of the file we are shown, but in that case we are not really accurately reflecting the reality of the difference between article permissions and file acceptability. This would also have some impact on how we could record this information in the catalogue - it would seem strange to record permissions against every instance of a file being deposited, when permissions are uniquely about a given article in the catalogue, whereas multiple files could be deposited in relation to one article. And we do have to have the ability to record multiple "files" against a given article, because we already have a requirement to have multiple "deposits" against a given article, so that a user may to a dark deposit then later a different kind, or so that an administrator may make a deposit of a different kind to the original, and so that we can simply record the fact that we might be given different files over time that are all the same article.

* statement is sometimes at the top because it is only sometimes provided by ricks, and only sometimes necessary.

* yes, file.expected.type indicates that the file is of an expected type.

* I am not sure what you mean about the url field being confusing. In the permissions endpoint there is no url field returned. In the deposit endpoint (which includes the permissions info) there is only a zenodo URL returned sometimes, as far as I can tell. What other url do you mean? Or are you talking about within the metadata response? If so, that would be a bigger change outside of the permissions/deposit work, and would impact things we have already put on live, and also is fairly irrelevant to deposit because we could just not show the metadata section at all on the deposit responses.

* same goes for email - what email do you mean? From the deposit endpoint, the email field is not necessarily the author email, so it is not clear that would make sense. If you mean somewhere else beyond the deposit endpoint, that would have impact on other parts of the system we have already put live.

* the acceptance field is not intended to be machine usable at all, and none of our code in the API or in the embeds relies on it. It only exists because you already said you did want a human-readable statement to be present in the API response, about why we had made an acceptance decision. I'm not sure how breaking that back out into a JSON object with various true/false values would be useful, given that the statement that is present is itself already generated out of true/false values that exist elsewhere within the response, and those are the values that the "machines" rely on anyway. Certainly the content of the acceptance field could be changed to say whatever you prefer it to say though.

* making the names of variables longer and "human-readable" is a popular practice in many "good software development" guides, but to me it is provably false. Certainly there is value in not naming variables so obscurely that you can't even comprehend a difference between them in a given output, but the practice of making them contain information for a human does not actually lead to the claimed benefit. The claimed benefit is usually "a human could look at this code / API response and know what these variables mean. But that is not true. The variable names will always be open to interpretation. This is provably by the fact that there are many variable names already within the development of this permissions endpoint that we have all had different interpretations of, including in our own and in external responses; also of the variable names you have given above, I can think of many different meanings for them, and do not find them more understandable than the ones we already have. Making variable names that supposedly communicate sufficient information about their context is as hard as expecting someone to interpret a language with no additional environmental cues. So, shorter memorable variable names are far more usable in practice, and easier for a human to type and to look up, to remember and read about in documentation if necessary, and to eventually memorise without having to worry about what punctuation, underscores, whitespaces, and so on they may or may not have used.

However, many of the above points are stylistic and in the end we can make the API respond however you would like it to, as long as we put sufficient scheduling into the milestones to get all the changes made.

**Comment by markmacgillivray** [comment]
Expected file types:
'doc','tex','pdf','htm','xml','wpd','wks','wps','txt','rtf','odf','odt','page'

**Comment by markmacgillivray** [comment]
I've not done more on this until structure is confirmed by joe

**Comment by JosephMcArthur** [comment]
Let's have file types be:

'doc','tex','pdf','html','xml',''txt','rtf','odf','odt','page'

presuming that list includes docx by including doc.

**Comment by JosephMcArthur** [comment]
Okay, what I have in the [doc](https://docs.google.com/document/d/1glV4naLWxztFHnKOnVSrGet5-YerMM6LaW9nrYK9xnI/edit) is great.

Presuming all my changes in that are clear, you can entirely ignore my previous change list.

**Comment by markmacgillivray** [comment]
OK, what you had in the doc as v3 has been implemented on the permissions endpoint, and the deposit endpoint has been updated to take account of the changes, and so has the shareyourpaper embed code. You can see the output at the usual permissions route to check it against your doc, and you can test the embed as usual and should get the same answers as you got in previous tests. I tried a couple via the embed and they appeared to work as expected, but I didn't try all possibilities. I have pushed my code, and probably won't get any more done tonight or tomorrow, but as mentioned earlier I can probably be around tomorrow night (your Thursday morning). Also if you add any comments to any issues I will try to get in any replies that I have time for during the next 24 hours or so.

**Comment by JosephMcArthur** [comment]
I haven't dug into the API response, but currently, I can't see any deposit action working on the UI. E.g file upload or submission of a redeposit.

We get an error (which is good) saying that you should contact the library.

**Comment by markmacgillivray** [comment]
Note - when testing just now I find that Ricks is up BUT it returns an internal server error for certain DOIs. There must be a bug in it somewhere.

For example this one errors out:
https://rickscafe-api.herokuapp.com/permissions/doi/10.1126/scitranslmed.3008973

Even though at the same time the system is up and successfully responds to this one:
https://rickscafe-api.herokuapp.com/permissions/doi/10.1073/pnas.1905762116

**Comment by markmacgillivray** [comment]
Testing with 10.1063/1.4937158 seems to get me through to where I can deposit a file. Depositing that file, however, results in the response that it is in zenodo already, which we have not yet decided a solution for. So, the UI just shows "something looks wrong" even though it is nothing the user can do anything about.

If something is already in zenodo, what do you want us to do? Put it into manual review? in which case, still ask the user to confirm the file is right? Or just show them success? Or put it into zenodo with the DOI moved to the  related_identifier field?

I assume at this point that deposit itself would work if the thing I was trying to deposit was not in zenodo, but I have not got that far to find out, and with Ricks not responding reliably it is hard to tell which ones work and which do not at the moment. This is all I have time for just now, but will push my code and hopefully you can make progress while I am offline.

**Comment by JosephMcArthur** [comment]
> Note - when testing just now I find that Ricks is up BUT it returns an internal server error for certain DOIs. There must be a bug in it somewhere.

I have flagged this. It's possibly my fault, I gave them a bunch of buggy data yesterday as a pipe in my house broke dramatically and I didn't check all the things. I have an automated solution for this now. 

> Testing with 10.1063/1.4937158 seems to get me through to where I can deposit a file. Depositing that file, however, results in the response that it is in zenodo already, which we have not yet decided a solution for. So, the UI just shows "something looks wrong" even though it is nothing the user can do anything about.

I will start an issue for this later! 

> If something is already in zenodo, what do you want us to do? Put it into manual review? in which case, still ask the user to confirm the file is right? Or just show them success? Or put it into zenodo with the DOI moved to the related_identifier field?

Starting a new issue to discuss #1413 

> I assume at this point that deposit itself would work if the thing I was trying to deposit was not in zenodo

Me too. I tested redeposit and that looks fine.

**Comment by JosephMcArthur** [comment]
The only left for this is what to do about docs for this on /api. But, we don't need to tackle now, so moving this out the milestone.

**Comment by JosephMcArthur** [comment]
Just updated the archivable reason statements! 

Since we've been on a journey with this issue, I'll just restate what we need to do to close.

Mark, can you provide me a draft of some copy I can put on the api page about the deposit endpoint. This would also be helpful for me to review where we're at with this, and direct future work.

**Comment by JosephMcArthur** [comment]
/deposit

* post it some metadata.
* post it a file.
* get with url param

you'll get back a deposit object. you'll get some metadata about the deposit, depending on how it went.

can tell you about errors, otherwise you'll be told what type of deposit, confirm info back you passed, file names, zenodo info (links, ids, doi, file), you'll get permissions and metadata you get back.

/deposit:id

TODO: decide id.
takes 30 minutes to do.
But likely we don't really need it. Need to consider.

**Comment by JosephMcArthur** [comment]
I've just written up the docs for this after our discussion. 

Can you check my work? Doc here: https://docs.google.com/document/d/11sKq_QXe5YauTq3OaEvNfaSbOrcLpP1C4dhSEFSWriU/edit# 

I can take a pass at sticking it in the code, I think we've got everything we need for it on the page.

**Comment by JosephMcArthur** [comment]
Got the api docs updated. 

One remaining issue. On the deposited & deposit route, we need the users uid in the example URLs (when logged in) and right now I can't do it. Only the apikey is coming out in it.

**Comment by JosephMcArthur** [comment]
1 hour todo
