### ISSUE TITLE
Set up UI architecture for file checking

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1346]
I'm using this as a general issue to outline / discuss general file checking stuff. 

So, this depends on two other things:

* #1344 
* ability to put files in the zenodo sandbox on dev

In other issues, I'll describe signals we'll use to decide signals we should use for file checking. But, when we think the version given isn't allowed to deposit we should show:

![Published _ Uploaded with DOI _ 1 2 (2)](https://user-images.githubusercontent.com/4953703/71074209-c9493900-2179-11ea-837c-8f5b6632f719.png)

e.g we'd see this when a publishers pdf is given instead of an authors accepted manuscript.

Now this route gets a bit complex, as a few things can happen.

1. The author should be able to tell us it's correct. If this happens, we should revert to the page and process we have now. I.e we send the uni the file, ask them to moderate, etc.
2. If the author does nothing else, we should revert to a dark deposit. We want to do this so that if an author tries to upload, they never walk away empty-handed. So, we need some logic that says if they try to upload, we say they can't, and they don't try again (aka we don't see another upload attempt for that doi) for 5 hours (or some arbitrary fairly long amount of time) we'll submit through the dark deposit route. That time should be long so that if they do try again (but it takes them 20 mins to find the file in the same session) we don't issue two notifications. Of course, if they come back even later, and do it again, it's fine to issue a notification again, we just want to limit double notifications. 

In cases we're we're happy the right version has been deposited, we can display:

![Published _ Uploaded with DOI _ 2 2 (1)](https://user-images.githubusercontent.com/4953703/71074370-0ca3a780-217a-11ea-9749-2ab8b1e5890f.png)

Obviously, here we'd do the deposit in Zenodo too, and show the resulting DOI. On dev, we should do the closest equivalent. Note, there is obviously a dependancy on the permissions system here, as we'll need the values from it for the zenodo deposit. If we don't have those, we'll need to fallback to the response we have now (eventually we may be able to unpick this, but we've nearly got complete coverage with permissions so I don't expect it to be a major issue).

For the uni, we need to send them a notification with the file URL, metadata and permissions. We should make sure that in stats / emails it's clear this is an approved deposit.

In cases where the system isn't sure, we should return the same response we do now.

**Comment by markmacgillivray** [comment]
I haven't done anything with this one yet, I have still been working on the API side of file checking, so have not moved back to the UI side to do this.

**Comment by markmacgillivray** [comment]
Sandbox zenodo access and API connectivity has been done - we discussed that in the past but had never done it since they introduced the sandbox, so I have just done it now as part of this issue. I looked to see if we have another open issue to do that, but we don't. Also of interest, we had been waiting for zenodo to introduce a search endpoint to the API, and noted it should have been done in "autumn" (probably autumn 2018)... there is now a "records" endpoint that returns enhanced elasticsearch results with hits and aggregations in it, but there is no documentation yet on how to send it queries. It does not accept the usual ES queries, so they have clearly augmented what can be queried and how. Their API docs say it is still in beta and documentation is not yet available, so it is not much use yet. Once they finish it though, we would be able to search zenodo for things during our find checks, and also could search to see if something is already in there either from us or anyone else when we get to the point of depositing something, which will save some duplication of effort later.

Proceeding with other parts now.
