### ISSUE TITLE
On InstantILL demo, hitting 'complete request' as directed leads to error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1349]
When we tell people to hit 'complete request' as part of https://instantill.org/#part3 we're meant to show them just the table. Instead, it appears we show a table and then also direct to a link, which fails. We shouldn't send them to the link the demo.

**Comment by JosephMcArthur** [comment]
Also at this point, it appears the demo may just be responding with the wrong view. 

What is inputted doesn't match the title outputted (which is the same as the previous demo).

**Comment by markmacgillivray** [comment]
It seems that the demo was changed to have the title of an article that our system can't actually find, and that isn't the DOI we had previously set up to receive an automated demo response. Also the title was different on the responding view because the title sent by the demo page for that part of the demo had not been changed to match that new title.

I have changed the demo page to use that new title and changed the API to respond to the demo DOI or the demo title, and also changed the demo UI to autofill some of the metadata in this case, so that there is something to actually show in the demo table. Because we could not find the new demo title we could not actually return any metadata for the table to display, hence the demo table effect was not being triggered and the usual attempt to load a URL was then occurring.

Please check this on dev.instantill.org and let me know if it is how you expect now - I have tested, and I think it is, but just to make sure we have the same understanding.

**Comment by JosephMcArthur** [comment]
Hmm, no this isn't quite right.

The title for the section demo was:

> Exposing errors related to weak memory in GPU applications

Which, if you put it into:

https://ulib.iupui.edu/services/ILL

Does return a correct response (bar, originally, returning a journal title). 

The demo title used for '2/6. Let’s try an article title!' at this point should be the above, and should return essentially a normal response (although then when you hit complete request it should show the meta-data we get).

One good change I can see you made though is adding metadata to the return for the fake DOI we were using. This is great, and showing this under 'This is not the article I searched.' would be good thing. So, can we make sure the API responses as follows with metadata info for 10.1234/567890:

Article title (required)
> Engineering a Powerfully Simple Interlibrary Loan Experience with InstantILL
Journal title (required)
> Proceedings of the 16th IFLA ILDS conference: Beyond the paywall - Resource sharing in a disruptive ecosystem
Year of publication (required)
> 2019
Article DOI or URL
> https://scholarworks.iupui.edu/bitstream/handle/1805/20422/07-PAXTON.pdf?sequence=1&isAllowed=y

**Comment by markmacgillivray** [comment]
Getting these demo ones cleared up before a push to live so you have all your demos working correctly - I have changed it now, I think it matches what you describe above, the 10.1234/567890 DOI returns the metadata of your "Engineering..." article, but the "try a title" one is back to using the "Exposing errors" one, and clicking the "complete request" button as directed shows a table with the "Exposing errors" metadata in it. If this is correct now, please close.

**Comment by JosephMcArthur** [comment]
Looks good! 

With 10.1234/567890, we're still missing the journal title.

**Comment by markmacgillivray** [comment]
Yes, sorry, I thought that was how you intended it to be. What journal title would you like it to display?

**Comment by JosephMcArthur** [comment]
Proceedings of the 16th IFLA ILDS conference: Beyond the paywall - Resource sharing in a disruptive ecosystem

**Comment by JosephMcArthur** [comment]
URL is good. Any way we can make the URL prettier and conform to the page width? 

![image](https://user-images.githubusercontent.com/4953703/71854481-38111680-30d6-11ea-9820-f3ff219cabdb.png)

**Comment by markmacgillivray** [comment]
OK, journal title added and word wrap added to the URL displays - have a look, see if it is better.
