### ISSUE TITLE
Performant embed initial load

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1383]
Allow embed script to have everything it needs to initially load without a call to config so that embeds can load with the initial page load. 

This is primarily for us right now, however, if it can be done so that others can use it too in a similar amount of time that's an extra bonus. When that happens, I think when 'rollout mode' is turned on, we'll show new embed code for folks.

**Comment by JosephMcArthur** [comment]
Not much to add to the above, however, we shouldn't tie this to rollout. Instead, we should have a separate setting that updates the embed code. I have given example copy and IDs at link 738 of the shareyourpaper.org set up.

**Comment by markmacgillivray** [comment]
This has been done for the embed itself, when we talk this week we can discuss where you want the setting for this that will then cause it to actually show different embed code for users.

**Comment by markmacgillivray** [comment]
From line 763 joe has already added a config option for that. And then above that, where stickidin adds the config to the page, we should also add the config into the copy/paste option if the user has selected high performance mode

**Comment by JosephMcArthur** [comment]
Joe, add:

- [ ] add issue to propagate this to instantill
- [ ] copy for the button

**Comment by JosephMcArthur** [comment]
Documenting and adding a bit of info from call. 

On dev.shareyourpaper.org/sneakpeak adding the high performance version caused the styling to be removed and the embed to disappear.

Here it works: https://josephmcarthur.github.io/playground/high_performance
Here it doesn't: https://josephmcarthur.github.io/playground/high_performance_experiment

**Comment by markmacgillivray** [comment]
I have found out why this is failing. In the case where we provide the config in the script, the embed loads faster than jquery does. So on your demo page where you have already included jquery, the embed fails to succeed because it runs before the jquery loads. However on the other demo where you do not have jquery included, the embed calls jquery itself and then runs afterwards.

Any time someone wants to use the embed when they already have jquery included on their own site, they also have to put the js code inside a jquery document ready statement. 

We can't easily show that in the code we give them to copy/paste, because we would have to know from them first if they do have jquery on the site or not - but the whole point of the embed being able to do it itself is that people don't need to know that. However we also can't just show the jquery document ready every time, because then on sites where it is not already present, that code would fail.

I think at best we should just add copy to the page that explains that if they are putting it on a site where they already have their own jquery present, they need to put it inside a jquery document ready statement. If the person doing this is also a person who knows about using jquery and knows that they have it included, then they should know this anyway, because otherwise they would have already broken many other things on their own website. But if the person doing this does not know about that stuff, I don't know how we would make it easy for them to find out.

**Comment by JosephMcArthur** [comment]
The solution of giving copy sounds great.

**Comment by markmacgillivray** [comment]
OK. Shall you write it or shall I? The code needed is 

jQuery(document).ready(function() {

STUFF GOES HERE

})

as can be seen on the bottom of the sneakpeak page.

**Comment by JosephMcArthur** [comment]
Once I see the code for sneak peak I'll try it myself, write docs as I can, and come back to you with something for feedback

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Embed is appearing again, however the system we have for showing example dois and learn more is no longer appearing.

**Comment by markmacgillivray** [comment]
OK fixed. Since with high performance there is no longer an ajax request occurring once the embed loads, it could not trigger the change to the embed. So instead I added a wait loop which adds the changed buttons once the embed loads. You can close this if happy, and will push to dev soon.
