### ISSUE TITLE
emails are not required when file can go into zenodo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1396]
As discussed.

**Comment by markmacgillivray** [comment]
I think this is now the case

**Comment by JosephMcArthur** [comment]
I don't think so. 

Testing with: 10.1073/pnas.1905762116 & https://dev.openaccessbutton.org/static/test-manuscripts/Hou_et_al-manuscript.pdf which looks depositable to me seems (when looking directly at API) to have gone right to the email getting workflow still (just judging by the speed of response). 

I did at times see it go to wrong article, but that was somewhat inconsistent and only seemed to happen on set up. 

I'm guessing that there may be some mismatch with permissions atm.

**Comment by markmacgillivray** [comment]
Ah, there is a problem with the logic of this, from the UI perspective.

The user gives us a DOI, we look it up. We show UI changes to the user based on the metadata we received and the permissions we were able to discern. But at this point the user has NOT given us a file, so we do not actually know if the file itself is acceptable (because we have not yet tested it to see if it is the right file, etc). So it is impossible to know whether or not we need the users email before we actually try to deposit it, hence why we had it always ask for the user email.

In order to make it so that we don't collect the user email if the file can be deposited, we would have to first send the file to our backend to have it checked, then get the response back from that, then decide whether or not to ask for the user email. This will add a delay to the user interface, and also we would have to pass the file to the /permissions endpoint rather than the /deposit endpoint, given that if we sent it to /deposit it would actually try to deposit it anyway. But the /permissions endpoint is supposed to be only for testing, and you don't want it listed in the API or available for other people to use. If we put it in the embed it will be pretty obvious that it exists, if anyone cares to look. So depends how you feel about that.

I guess that is why you were saying it seemed to go straight to asking for email judging by speed of response; that confused me initially, because yes, it definitely is doing that, because we have never actually sent the file to the backend at this point. We only send the file once, at the end, once we have done everything else on the UI that we need to do. That is how it stays quick - there is only the one lookup at the start, after the user gives us the DOI.

However, it is possible to make the change you want, if you don't mind it being slower in the UI and adding load to the backend (receiving each file twice). It would take a bit more work to make this possible - another couple of hours probably.

**Comment by JosephMcArthur** [comment]
I've put an email box on the aam upload page so that we'll always have an email for deposits. I hope that simplifies deposit for us. It obviously has implications for other pages, e.g not needing to collect email later, and I've taken a pass at rejigging copy and boxes / buttons to account for this, but I haven't been able to test as I can't evoke that page at the moment (maybe we should add this to the demo).

Later on, we may want to do the work to remove the need to take an email here, but for now it seems to make a lot of problems go away so lets go for it. 

After I did that, I saw my first REAL SUCCESSFUL DEPOSIT 🥇 🍾 🎊 and the first deposit we successfully stopped as it was the wrong version. Isn't that damn amazing.

**Comment by markmacgillivray** [comment]
OK, what should I test/do here to close this?

**Comment by JosephMcArthur** [comment]
Are there any backend changes needed now so that email won't come up after we give a file?

**Comment by markmacgillivray** [comment]
All the backend does is copy the email into the email sent to the institution/admin, it hasn't been changed to do anything else with the email yet. So it has no effect on what the UI does about the email, so far.

**Comment by JosephMcArthur** [comment]
Can we get one of your examples on the demo (on the landing page) that show the page folks would see if the file checking system wasn't sure what the version was? 

The one starting

> We\'ll double check your paper

at line 409.

**Comment by markmacgillivray** [comment]
That line can now only be shown if a user tries to deposit something and has not already provided an email address.

**Comment by markmacgillivray** [comment]
Which, as far as I can tell, is now impossible.

**Comment by JosephMcArthur** [comment]
That screen is meant to show in a couple of cases. 

1. When the file checking system is not sure what version the file we've been given is. It seems like for this very moment, we've basically defined that possibility out of existence.

If not a PDF, it's a postprint. 
If it's a PDF, and we find any sign it's an pubpdf or AAM, it's whatever sign we get most of.
If it's a PDF, and we find nothing, it's a postprint.

2. When we thought the file was pub pdf, but the author tells us it's an AAM. 

This can still happen. Haven't yet seen if it will yet, need to test the other issue.

**Comment by JosephMcArthur** [comment]
and sorry, one more thing. 

It *used* to collect emails, as both of those then needed some manual step. 

Now, we have the email already, so I turned it into a confirmation page.

**Comment by markmacgillivray** [comment]
Ok. I think you'll need to write a description of the logic of the UI from the start of putting in a doi through all the different possible screens and contents it should show, then I'll need to rewrite the embed code again.

**Comment by markmacgillivray** [comment]
Note, you can do this tomorrow, assuming you're going to sleep soon. Even if you did it tonight I doubt I will be able to get a rewrite done by end of my Wednesday, and once I have done it we will need to re-test anyway, and probably also change the demo triggers, as they were based on previous models of what they should trigger on the UI, which may now be incorrect. So I think this is going to have to continue into next week work.

**Comment by JosephMcArthur** [comment]
Okay, hashed out over chat and we think this can close now.
