### ISSUE TITLE
When depositor confirms the version, kick them into the manual review workflow

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1404]
i.e take their email, and submit.

**Comment by markmacgillivray** [comment]
I think this is now the case

**Comment by JosephMcArthur** [comment]
Hmmm, I just tried to test this and I don't think it worked. Me clicking the button several times (there was no UI response) seems to have fired a bunch of submission emails.

**Comment by markmacgillivray** [comment]
The changes to some of the buttons on the UI required some alterations to the page update process, and I also tidied up how data gets resubmitted on a second deposit to the backend. That appears to be working now.

**Comment by markmacgillivray** [comment]
@JosephMcArthur is this one now working as you expect? If not, can you let me know what else needs changed?

**Comment by JosephMcArthur** [comment]
have you made changes, or are you referring to how is was like this morning? This morning it didn't work, when I clicked it just tried to deposit again.

**Comment by markmacgillivray** [comment]
I've made the changes described in my comment above, which were about changing the UI button elements to trigger the right effects again. There were no backend changes directly related to that I think, it was already doing it, which is why you were getting notifications - we just didn't have working logic on the embed UI to see a change on the page. So, it would depend what things you have since changed about where certain email boxes are on the page, and if any of those changes have done anything to stop that button working again. If you have not made changes that impact that, then the UI changes I made earlier and described above should still be working. If that is the case, then I think it is doing what you intended, but I may not have understood that properly.

**Comment by JosephMcArthur** [comment]
Got it, so when I hit the button it's done a forward deposit and sent an email.

What I see on the UI is:
![4SPmZMfwhq](https://user-images.githubusercontent.com/4953703/73699916-01321e80-46dd-11ea-99b3-1fa294ef38a0.gif)

and what I expect is for stuff from line 409 to come up.

**Comment by markmacgillivray** [comment]
OK, could you show that in a description of the UI logic as part of that requested in #1396 then I will do a rewrite of the embed.

**Comment by JosephMcArthur** [comment]
Okay, hashed out over chat and we think this can close now.
