### ISSUE TITLE
oasheet not reading from live api correctly

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1407]
Looks like OAsheet may not be working after the refactor.

Take this example file for instance: https://docs.google.com/spreadsheets/d/10aSNG80crJH7wtd_9SyZSmxfQZG4sK8vVWIBf6Lt4Xs/edit#gid=0

you get zero positive results when using oa sheet. 

When you do it manually (from the front page):

https://docs.google.com/spreadsheets/d/1LkFQm_mxU467FeT-5kz45XNv_IvqMNLlTuZi1-1Dkw4/edit#gid=0

you get a much rosier picture.

**Comment by markmacgillivray** [comment]
This is fixed but the fix needs pushed to the cluster machine that run the background jobs. That is in progress.

**Comment by markmacgillivray** [comment]
This has been sorted, and tested on live. A sheet submitted by a user to oasheet should get accurate results now. However note that there appeared to be some admin features that I don't think we need to resurrect, but let me know if that is not the case - for example there was a way to get it to check library availabilities and also to specify which fields it would return. This would require further work, and is not necessary for supporting it for any user, as far as I know. If you do need full functionality let me know and I will do a few hours more on this issue, otherwise close it.
