### ISSUE TITLE
When crossref provides abstract, we should use it

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1414]
Crossref occasionally provides abstracts, and when they do we should use them. We should do that in the following ways:

- [x] saving with the deposit record
- [x] exposing in emails (I have a tag commented out for this)
- [x] putting in deposit statements. It should be the first thing, with what we have now put below (separated by a line)

**Comment by JosephMcArthur** [comment]
- [ ] Same with message.subject in crossref. Can pass it as subject.

**Comment by JosephMcArthur** [comment]
- [ ] Same with message.subject in crossref. Can pass it as subject.

**Comment by JosephMcArthur** [comment]
note to self: Speaking with Andre about doing abstract extraction

**Comment by JosephMcArthur** [comment]
- [ ] same with keywords!

**Comment by JosephMcArthur** [comment]
Saw that these fields got magically added to our metadata pull, I presume as part of covid project.

To close this, that just means we need to:

- [ ] put abstracts into deposit statements. Abstracts should be the first thing in the description, and separated by a line from what we have now. If we don't have it, not problem, we don't need to add anything.
- [ ] save 'message.subject' to our deposit object
- [ ] provide keywords to the zenodo `keywords` field on deposit

**Comment by JosephMcArthur** [comment]
Re: subjects here. Plan to use crossref style. That said, later we may adjust, Zenodo requires both a subject name and a linkout / definition for each subject.

**Comment by markmacgillivray** [comment]
Abstracts now go into deposit statements when we have them, however they are not separated by a line. Just a whitespace. Because we don't know how or where these may get displayed, we cannot know if we should use a \n linebreak or an html BR linebreak, so it is safer to just use a whitespace, I think.

message.subject from crossref is already what we save in metadata.keyword, because crossref subjects are not objects with namespaces, they are just lists of strings, which correlates better to keywords. This also fits into the zenodo keywords field, and we have that added now. Zenodo would accept a subjects key as well, with objects in it, but we don't have any suitable info to put in there and the few examples I looked at from crossref didn't have any either.

**Comment by JosephMcArthur** [comment]
Any reason you didn't do the ORCID bit here?

**Comment by markmacgillivray** [comment]
Oh, missed that. Will do just now

**Comment by markmacgillivray** [comment]
orcids have been added, affiliations too if we have them. I have not tried a test deposit yet though. Do you want to try one before pushing live? Should be ok to do on dev, would go into zenodo sandbox.

Here is a doi that has some orcids:

10.1111/hsc.12818

**Comment by JosephMcArthur** [comment]
Hmm, it's saying the service is down

**Comment by markmacgillivray** [comment]
Which service? That may have just coincided with me doing updates on dev

**Comment by JosephMcArthur** [comment]
this: https://dev.shareyourpaper.org/10.1111/hsc.12818

I'm doing it now, still down. So, if you think it's down then coolio

**Comment by markmacgillivray** [comment]
oops sorry yeah coincided again. Try now. Definitely up now

**Comment by JosephMcArthur** [comment]
looks great https://sandbox.zenodo.org/record/526844#.Xp2D-VP0lQI
