### ISSUE TITLE
Missing results from unpaywall

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1443]
We don't find these DOIs, even though unpaywall gives them

Paywall: 10.1111/jfb.13668
Free: https://digital.csic.es/handle/10261/193393
https://api.unpaywall.org/10.1111/jfb.13668?email=joe@openaccessbutton.org

Paywall: 10.1021/acs.jafc.8b00635
Free: https://digital.csic.es/handle/10261/193269
https://api.unpaywall.org/10.1021/acs.jafc.8b00635?email=joe@openaccessbutton.org

**Comment by markmacgillivray** [comment]
This was because the CA for their https was not included in the ones our system checks for validity. So when we try to resolve the URL to make sure it works, we were failing. This has been augmented now to ignore certificate validity, as it won't really matter to us, and an end user will likely never see the warning anyway. This is fixed and tested on dev, so closing this, and it will go live with the next push.
