### ISSUE TITLE
have licence consented to be responsive to ricks

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1444]
When we ask people if they're okay to 'license your work CC-BY.' on the SYP UI, we need the license shown to be responsive to what Rick's says.

This means:

* If authoritative_permission.application.can_archive_conditions.licenses_required is not null, we should show what it says
* if authoritative_permission.application.can_archive_conditions.licenses_required is null we should have CC-BY as now.

**Comment by JosephMcArthur** [comment]
Note: This will need to happen with post prints and pub pdfs are being deposited

**Comment by markmacgillivray** [comment]
As with #1447, but here it makes more sense but just to check - you want us to show the user the licence that ricks tells us is required, regardless of what licence we think the submitted file is? If so I understand this one, in that we will be wanting them to confirm the item can be submitted under the required licence. Still not quite sure the implications of submitting a file that DOES somehow otherwise say it is of a different licence to what we say it is when we submit it, but at least it does make more sense in this context to be asking the user about the REQUIRED licence.

Once you confirm the above I can finish this issue.

**Comment by JosephMcArthur** [comment]
> you want us to show the user the licence that ricks tells us is required, regardless of what licence we think the submitted file is?

Yes

**Comment by markmacgillivray** [comment]
Done see details in #1448

**Comment by markmacgillivray** [comment]
Can close this too if as required
