### ISSUE TITLE
zenodo not using license from ricks

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1448]
Similar to the last issue. I feel like we had this working before, but maybe I'm mis-remembering. Regardless... 

Tried to deposit 10.1016/j.phrs.2019.104618 and got the following sandbox record: 
https://sandbox.zenodo.org/record/503473#.XlfjDxOeTOQ. If that doesn't work, you can replicate with 
[Test Paper for SYP upload (1).pdf](https://github.com/OAButton/discussion/files/4262432/Test.Paper.for.SYP.upload.1.pdf)

The license rick's gives wasn't used (see here: https://rickscafe-api.herokuapp.com/permissions/doi/10.1016/j.phrs.2019.104618).

For the license on zenodo, the rule is:

If the length of `authoritative_permission.application.can_archive_conditions.licenses_required` is >1, use that. 

Otherwise use 

> CC-BY

**Comment by markmacgillivray** [comment]
We had it working so that if we figured out a licence for the file we used that. However in this case we can't figure out a licence for the file so we default to cc-by. There is nothing at all in our permissions or deposit code about referring to a licenses_required field from ricks, so we have not used that value before.

Do you want that value to be used as the licence of the file we are given? Or only used as the licence passed to zenodo?

This does not make much sense to me because licenses_required does not sound like the same thing as licence. We calculate what licence we think the file is. licenses_required sounds like it is telling us what licence is required to be allowed to deposit. It would seem to me that if we are going to use that value at all we should be using it to check if we have the right licence - not just using it to set the licence to the value that it says is required. How will we know it is correct? That is why we currently use the licence we are able to calculate for the file, or default to cc-by because we think that is safe enough.

Do you want it to default to licenses_required if that is present? Or default to the licence we can discover if any, then licenses_required, and finally just cc-by? Also, given that the name is plural and the value is a list, do you just want to always use the first licence given in that list, regardless of what it is?

**Comment by JosephMcArthur** [comment]
Okay, good point re: file license, I missed that in the thinking.

## updated rule for zenodo

If the length of `authoritative_permission.application.can_archive_conditions.licenses_required` is >1, use that. 

Otherwise:

If we get a file license, use that. 

Otherwise:

> CC-BY

Let's also use the same rule for the file license set in .file.

Re your comment:

> This does not make much sense to me because licenses_required does not sound like the same thing as licence.

Indeed, it isn't _quite_. We need #1444 for that.

We calculate what licence we think the file is. licenses_required sounds like it is telling us what licence is required to be allowed to deposit. 

It is

> It would seem to me that if we are going to use that value at all we should be using it to check if we have the right licence - not just using it to set the licence to the value that it says is required. How will we know it is correct? 

This is what #1444 is for. It doesn't check the file (as the paper rarely contains a license, especially if it's an author accepted manuscript, but instead confirms the user is happy to share under that license.

That is why we currently use the licence we are able to calculate for the file, or default to cc-by because we think that is safe enough.

In most cases, I think the file license will be most useful for OA stuff where we take publisher PDFs (which do then to have license info in them) and where Rick's provides no info (as, usually, no licence is required for deposit). When a licence isn't stipulated by the publisher or file, then we're good to go with CC-BY (in our opinion) as we presume the author then has the right to do that. 

Happy to talk through the above, it's kinda complex, and requires some context you get from staring at tonnes of deposits.

**Comment by markmacgillivray** [comment]
OK. If ricks has licenses_required we now set a new value in our permissions object called licence_required which will be the first value in the ricks licenses_required field. 

If by the end of the permissions check we have found a file licence but did not get a value from ricks, then we set our permissions.licence_required to be the file licence that we found. 

When it comes to deposit we use the permissions.licence_required value we have set, or cc-by if there isn't one.

Same goes for the shareyourpaper embed UI - by default we say to them "licence your work CC-BY" unless we have set a permissions.licence_required in which case it will say that instead of CC-BY (so by this point, it will be asking them to confirm the first ricks licenses_required or the file licence we discovered).

I think this issue can be closed now, but please test and let me know if not as you imagined.
