### ISSUE TITLE
remove use of /convert on dev

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1452]
Intended as a temporary / internal use, but got released into the wild. 

Need to remove use on dev:
- [ ] remove internal use when possible
- [ ] remove external use nicely when possible
- [ ] kill support for it (after release of new permissions sheet)

This is the call in question:

> /api/convert?from=list&to=string&json=true&order=affiliation&subset=z_authors&newline=;%20&url=https://api.unpaywall.org/v2/10.1016/j.microrel.2015.06.084?email="

and can be used to find chat records about this.

**Comment by JosephMcArthur** [comment]
Awaiting:

* list of unique email addresses
* list of all calls that use an internal address (mine / natalias)

**Comment by JosephMcArthur** [comment]
@markmacgillivray did the logging work help address this?

Support for this can now be removed, and errors hidden, if that helps!

**Comment by markmacgillivray** [comment]
Whatever was calling it so regularly stopped. It's not that it's a problem for us to offer this, but that we never considered doing so, so it was running off our dev server. The convert API is still actually available and can be used by us or anyone else you'd like to make it available to, but we should keep in mind that the more API services we make available to others, the more cost there will be to run them.  Some of this will be reduced by moving to CF, but some won't because conversions can be long-running processes that won't be possible on CF, so they'll still create a load on our backend server. However this issue can be closed.
