### ISSUE TITLE
Preview buttons in set up not saving?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1461]
Pushed for time, so not able to do reproducibility steps.

However, during an instantil set up session yesterday I saw the preview button not work well. For example, a user put a doi into the test doi box for subscriptions, and it didn't seem to use that.

At other points, the preview button didn't seem to apply the settings changed. The meant users had to save it through save and continue and then go back.

The preview and test, I think, used to save the config and then refresh the preview so you'd see what it would look like.

**Comment by markmacgillivray** [comment]
The preview buttons were designed to run previews, not to save. There is a save class for saving things. The preview buttons do not run the embed as if it is configured in a different way, and they never did. So, if this is what you are expecting them to do, then we need to change them quite significantly.

I can see though that all of the preview buttons also have the save class. This makes the preview function somewhat obsolete, because all previews are going to try to run saves first. It would be better to just have save buttons that trigger previews, and then some that don't. If a preview button does have a save class then it should save the changes then run the preview, but as it does not necessarily restart the already embedded shareyourpaper embed, some of those config changes may not be available to the embed already on the page - this is because, as mentioned above, this was not the original intention of preview buttons.

There is also already a restart class, so perhaps what you are actually wanting is to restart the embed after every stage where a user has entered new config values and saved them. This could be possible, but we will need to look at how the restart class functions and how that would affect the save/preview order, as this functionality was also not in mind when the restart class was written.

So this probably also needs to be talked about to work out what the expected functionality is, and how we can change what we have to fit that without spending too much time rewriting things.

**Comment by markmacgillivray** [comment]
Make preview do a restart in every case.

Later come back and fix up the overlapping uses of classes in these pages.

**Comment by markmacgillivray** [comment]
OK I have tried making some changes to this, please retest and close if acceptable.

**Comment by JosephMcArthur** [comment]
This is looking much better now I think. 

Two things still needed to fix:

- [ ] For: "What is the DOI of an article you definitely have access to, which can be used for testing?" we're still not using the value they give in the preview (when they give it)
- [ ] confirm that the changes made here will be propagated to  the shareyourpaper.org set up page

**Comment by JosephMcArthur** [comment]
https://dev.openaccessbutton.org/instantill/setup#subscription

**Comment by markmacgillivray** [comment]
Note this is on instantill setup, we have a val box that is used in the preview, but need to check how previews get called after saves and if that still gets accessed or not

**Comment by markmacgillivray** [comment]
I had done changes to preview/save only on shareyourpaper, so need to make changes to instantill.

**Comment by markmacgillivray** [comment]
The changes have been made to instantill and shareyourpaper. The val box for instantill works now. Please confirm and close.

**Comment by JosephMcArthur** [comment]
On InstantILL setup it seems that the preview starts to run, but then disappears.

Also it seems that, although it's hard to 100% tell, that the val box changes the val on all preview buttons, not just the one for the subscription check.

**Comment by markmacgillivray** [comment]
I tried on setup clicking some preview and test buttons, and they seem to run to me. The val goes in the box, the embed runs, it displays the result.

Also yes, if there is a val set, then it gets used for every preview button unless the preview button explicitly sets some other val. Do you have certain preview buttons in there that should provide another val and that are failing to do so? If so could you tell me which one so I can try it?

**Comment by JosephMcArthur** [comment]
Every preview button I've tried seems to take the new val over it's set val.

I can't replicate the disappearing embed on preview now, so that's good!

**Comment by markmacgillivray** [comment]
OK I just checked that and yes, the provided config val takes precedence, intentionally, it seems. The intent of that must also have changed since we created it. Try again now and see if it does what you want.

**Comment by JosephMcArthur** [comment]
Now the other previews are fine, but the doi isn't used for subscriptions when given now.

**Comment by markmacgillivray** [comment]
ok try again now

**Comment by JosephMcArthur** [comment]
Still having the same issue

**Comment by markmacgillivray** [comment]
Can you describe what button you are pressing, what you are expecting to see, and what you are actually seeing?

**Comment by JosephMcArthur** [comment]
Shall we do this face to face on Monday?

**Comment by JosephMcArthur** [comment]
Thought of a way to show...

![](http://g.recordit.co/B0gHeMoevG.gif "")

I'd expect to see the new preview in the below.

But, not on any other preview button.

**Comment by markmacgillivray** [comment]
OK please test this again on dev, it looks to me like it is doing what you want now, and I tried another button and it did not use the value set in the field.

**Comment by JosephMcArthur** [comment]
That seems to work! I'm just going to do a full test of the pages and make sure everything we wanted here has landed.

**Comment by JosephMcArthur** [comment]
I think while making this the restart function has regressed. For example, if you go to: https://dev.openaccessbutton.org/instantill/setup, hit ' Interlibrary loans', note the article is 'Exposing errors related to weak memory in GPU applications'. Then, hit save and continue. That save & continue has a restart class, but the embed doesn't restart.

In potentially related news, the demo on https://dev.instantill.org/ seems to have disappeared. If you click 'try it now' it re-appears but doesn't work (not clicks in the demo work). I'm going to take a guess that this is related.

**Comment by JosephMcArthur** [comment]
Can likely jump on late tonight or our usual time this morning if it helps work through this.

**Comment by markmacgillivray** [comment]
The restart problem has been solved. As far as I can tell there was never any functionality attached to saves to cause them to also do a restart. That code only attaches to previews. Either this was never intended to be the case and is another misinterpretation of the requirements, or the code that did do this has been deleted at some point as well.

The dev.instantill.org problem is completely separate and I have no idea what is causing that. But there are multiple changes to the page that are wrong - uses of the same ID names again, that sort of thing. These make any html/js unreliable. I will continue to have a look and see if I can find out what has been changed to break it.

**Comment by markmacgillivray** [comment]
OK the dev.instantill.org page now shows the embed whether you click that button or not. It does not show it immediately, it takes a couple of seconds. This is because I have added a timeout to wait two seconds and then show it. Because I don't know what is causing it to disappear in the first place, and whatever it is happens later in page creation so I can just show it immediately. Also the page transition effect of sliding down when you hit "try it now" rather than just jumping, I don't think that is a default browser behaviour unless chrome has added it, and also I don't know how that is making the embed show up anyway.

But however, it works now.

**Comment by JosephMcArthur** [comment]
these are working it seems now!
