### ISSUE TITLE
don’t have new instantill metadata turn up in openurls

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1511]
InstantILL is currently generated openurls with metadata that isn't needed like reference lists, journal short names, abstracts and keywords.

E.g

`https://silliad.lib.montana.edu/illiad/illiad.dll?Action=10&Form=22&sid=InstantILL&rft_id=10.1126%2Fscitranslmed.3008973&atitle=Ultrahigh%20dose-rate%20FLASH%20irradiation%20increases%20the%20differential%20response%20between%20normal%20and%20tumor%20tissue%20in%20mice&aulast=Favaudon%2C%20Vincent%2C%20Caplier%2C%20Laura%2C%20Monceau%2C%20Virginie%2C%20Pouzoulet%2C%20Fr%C3%A9d%C3%A9ric%2C%20Sayarath%2C%20Mano%2C%20Fouillade%2C%20Charles%2C%20Poupon%2C%20Marie-France%2C%20Brito%2C%20Isabel%2C%20Hup%C3%A9%2C%20Philippe%2C%20Bourhis%2C%20Jean%2C%20Hall%2C%20Janet%2C%20Fontaine%2C%20Jean-Jacques%2C%20Vozenin%2C%20Marie-Catherine&title=Science%20Translational%20Medicine&issn=1946-6234&volume=6&issue=245&pages=245ra93-245ra93&date=2014-7-16&rft.year=2014&crossref_type=journal-article&journal_short=Sci.%20Transl.%20Med.&keyword=General%20Medicine&publisher=American%20Association%20for%20the%20Advancement%20of%20Science%20(AAAS)&abstract=In%20vitro%20studies%20suggested%20that%20sub-millisecond%20pulses%20of%20radiation%20elicit%20less%20genomic%20instability%20than%20continuous%2C%20protracted%20irradiation%20at%20the%20same%20total%20dose.%20To%20determine%20the%20potential%20of%20ultrahigh%20dose-rate%20irradiation%20in%20radiotherapy%2C%20we%20investigated%20lung%20fibrogenesis%20in%20C57BL%2F6J%20mice%20exposed%20either%20to%20short%20pulses%20(%E2%89%A4500%20ms)%20of%20radiation%20delivered%20at%20ultrahigh%20dose%20rate%20(%E2%89%A540%20Gy%2Fs%2C%20FLASH)%20or%20to%20conventional%20dose-rate%20irradiation%20(%E2%89%A40.03%20Gy%2Fs%2C%20CONV)%20in%20single%20doses.%20The%20growth%20of%20human%20HBCx-12A%20and%20HEp-2%20tumor%20xenografts%20in%20nude%20mice%20and%20syngeneic%20TC-1%20Luc%2B%20orthotopic%20lung%20tumors%20in%20C57BL%2F6J%20mice%20was%20monitored%20under%20similar%20radiation%20conditions.%20CONV%20(15%20Gy)%20triggered%20lung%20fibrosis%20associated%20with%20activation%20of%20the%20TGF-%CE%B2%20(transforming%20growth%20factor%E2%80%93%CE%B2)%20cascade%2C%20whereas%20no%20complications%20developed%20after%20doses%20of%20FLASH%20below%2020%20Gy%20for%20more%20than%2036%20weeks%20after%20irradiation.%20FLASH%20irradiation%20also%20spared%20normal%20smooth%20muscle%20and%20epithelial%20cells%20from%20acute%20radiation-induced%20apoptosis%2C%20which%20could%20be%20reinduced%20by%20administration%20of%20systemic%20TNF-%CE%B1%20(tumor%20necrosis%20factor%E2%80%93%CE%B1)%20before%20irradiation.%20In%20contrast%2C%20FLASH%20was%20as%20efficient%20as%20CONV%20in%20the%20repression%20of%20tumor%20growth.%20Together%2C%20these%20results%20suggest%20that%20FLASH%20radiotherapy%20might%20allow%20complete%20eradication%20of%20lung%20tumors%20and%20reduce%20the%20occurrence%20and%20severity%20of%20early%20and%20late%20complications%20affecting%20normal%20tissue.&reference=%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D&&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing.`

I think this is noted in: #1510 .

We should exclude these items from open urls.

**Comment by markmacgillivray** [comment]
This is actually because we have no fixed list of what should be provided in open URLs. We appear to have a list of what NOT to provide. So it was designed to default to sending all the metadata we can find. If you don't want that, I need a list of the metadata terms you DO want to send.

Also, regarding how the extra metadata came to be there in the first place - it is not specifically to do with my work on covidpapers, but I see what you mean. I have been adding improved extraction to some of the use endpoints, so that we get more metadata from them. But in addition, you've been posting issues such as "using" the abstract when crossref provides it, so it seemed to me that you were also wanting that extra metadata in OAB. If you only want to "use" it in certain places and not others, I need to know where you want it used. Because the openurl was made to send all the metadata apart from a certain designated list of internally relevant stuff, it IS sending all the metadata we can find, and would continue to send more and more, if we continued to find more and more.

So just let me know what it SHOULD send, not what it should NOT send.

**Comment by JosephMcArthur** [comment]
We should have:

* DOI & other ids (pmid etc)
* URL
* journal title (full, not short)
* article title
* Issn
* vol
* issue
* page
* article type
* publisher
* published date
* author list

we should also have notes and the sid of InstantILL, which I'm not sure is strictly metadata... but it does turn up in openurls!

**Comment by JosephMcArthur** [comment]
Before we close this, I need to confirm if:

- [ ] This is the same thing as flagged in: #1510

> the instantill API originally had a controlled list of expected variables and it cleaned them up when they came in. This has not been maintained and we now have dirty data in that system. It must be updated, and the data has to be cleaned. 2 days.

**Comment by markmacgillivray** [comment]
No these are different things. The API control over what variables come in is about what we accept in the config. The metadata that we send in openurls comes from whatever metadata we were able to find, and has never had control on it, it just sends whatever metadata we had. The only controls we had on the openurl bit were to stop it sending our own internal fields in the openurl, but it does still dump any metadata we find.

**Comment by JosephMcArthur** [comment]
Got you. Does it help to do the InstantILL controls at the same time as
shareyourpaper controls?

**Comment by JosephMcArthur** [comment]
Made issue for controls: #1523

**Comment by JosephMcArthur** [comment]
Est 1 hour.

**Comment by markmacgillivray** [comment]
I am removing the bug tag from this. It may seem trivial but I think given how we are currently reviewing our processes, it is important to keep in mind that things like this are not bugs - they are not unintended failing in the written code. They are intentional because this is how we wrote the code based on what we specified, they are a result of the process we used. If things like this should be more clearly defined (and they should) then this is an example of where we should be spending more time on how the code and backend operates rather than trying to drive that development by UI design.

**Comment by JosephMcArthur** [comment]
Gotcha, let's chat about the bug tag!

**Comment by JosephMcArthur** [comment]
Mark's done. 

Joe to test.

**Comment by JosephMcArthur** [comment]
looks good
