### ISSUE TITLE
catalogue cleaning

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1517]
>the catalogue of records we have previously seen already has duplicates and bad data in it, because we pushed it to live before it was ready. This now has to be fixed, the bad data has to be cleaned, and duplicates removed. 2 days.

the deposit API dumps a load of permissions junk from sherpa that we no longer need. It is dirtying up the data and we should get rid of it, and clean up the records we have. 1.5 days.

Est 1 day now.

**Comment by markmacgillivray** [comment]
Agreed to just dump all old catalogue and find data from dev, and catalogue from live. Check to see if finds on live continue to work after we push to live - have already checked that they appear to have the correct mapping so they are probably refusing the currently wrongly mapped events, and should go back to working as normal once we push the change.

**Comment by markmacgillivray** [comment]
Just a note to say that the loop error we saw when we were reviewing these things earlier today is solved now, due to timing of removing the old catalogue and formatting URLs that were passed in to permissions checks. So all ready to go now, but too late, going to bed. Will do the launch stuff in the morning, will msg you as soon as I am up.
