### ISSUE TITLE
admin deposit links on shareyourpaper.org don't work due to lack of ?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1532]
Link given is structured as follows:

https://shareyourpaper.org/10.1016/j.jep.2010.05.062&confirmed=PFF08gkKUqobfKxwibzZmA==&email=lachenmeier@web.de

As the syp domain works differently there is a lack of '?' and the embed flags this isn't a working doi

Can we make a special case for the syp domain in that handlebar for emails?

**Comment by markmacgillivray** [comment]
I investigated this one but could not see how I could fix it. As far as I can tell it is being created by the email template you created, where the info is being appended to the embedded value. Is that actually what we want? Will other people apart from us be expecting to do an admin deposit on their own websites, or is this something that only functions from our website? If only from our website why don't we just hard code the shareyourpaper domain in there instead of using a variable?

Or are you meaning something else I am not understanding?

**Comment by JosephMcArthur** [comment]
From Mark (this got put on the wrong issue):

> Discussed and will change to passing an "adminlink" variable which will also avoid any problem with URL param

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
adminlink is available for email templates now and can be tested on dev

**Comment by JosephMcArthur** [comment]
`adminlink` is the name, yes?

**Comment by markmacgillivray** [comment]
yep

**Comment by JosephMcArthur** [comment]
tested and all good
