### ISSUE TITLE
embargo not used in deposit when publisher pdf deposit is allowed?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1533]
I was moderating a deposit of 10.1086/704224. You can see the record / get the file in email. 

I noticed that the UI and deposit record didn't automatically use the embargo date (I put it in by hand). 

This happened even though seemingly the API picked it up. 

I've seen this for all other deposits, the only difference I could see here was that this was a publisher pdf deposit. Curious if there is a hole in the logic possibly.

**Comment by markmacgillivray** [comment]
Update on this one to discuss at meeting: it does not appear to be a bug. We specifically look for a field in ricks can_archive_conditions that gives us an embargo date for the specific TYPE of file in question. In this case the file is a publisher pdf, but ricks only gives us info about an embargo on a postprint. So, the code is accurately not using that embargo, because it applies to postprints, not to publisher PDFs.

If this should be changed it is easy enough, just let me know. This may be one of those cases where the "fix" label is accurate, because we have specifically coded it to look only for embargo dates that match the right file type, and there is code in there too that makes sure we do match it to the file type we are trying to receive, so we definitely did this on purpose at some point.

**Comment by markmacgillivray** [comment]
Changed to just match any field with embargo_end in it. Later can simplify to just get the field directly once it is decided what it will be called. It now will be just one field for any embargo on any allowed type

**Comment by JosephMcArthur** [comment]
tested and all good
