### ISSUE TITLE
Review use to crossref deposit dates & maybe adjust

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1535]
Would appreciate you walking me through how we get date data out of Crossref. We can do it on a call, and some changes might be needed. 

I've seen at least two occasion where results seem off:

10.1016/j.jep.2010.05.062
10.1111/j.1745-9125.2008.00102.x

and the deposits in our email now.

It seems we may be using the doi creation date at times, and that can throw us off, seeming when there may be better alternatives (judging by ricks).

**Comment by markmacgillivray** [comment]
Prefer published-print before published-online. Also if the date-parts do not have 3 parts but only have 2, guess a "1" for the last one (which is probably the day).

**Comment by markmacgillivray** [comment]
The reason we use date-parts rather than the timestamp or date-time is because they are not always there.

Also, prefer journal-issue.published-X over deposited.published-X

**Comment by markmacgillivray** [comment]
Also if we can get the date-parts and there is only one of them, e.g. the year, guess the month as 1 as well.

**Comment by markmacgillivray** [comment]
@JosephMcArthur I remembered after our call that one reason we take the published-online or other more recent values over published-print is because for requests we only process them if they are fairly new.

So the changes we discussed and described above would make our metadata more accurate, but things that were published-print a long time ago then subsequently published online and now possibly OA could be more likely to get automatically rejected by the requests system.

Is this an acceptable loss?

**Comment by JosephMcArthur** [comment]
Yup

**Comment by markmacgillivray** [comment]
As we'd already discussed this one and I had been working on it for other things, it has been done and pushed just now with updates to live. It has been tested and working where possible, although as seen yesterday it may not immediately result in visible changes on live due to caching, but future queries will get more accurate dates.
