### ISSUE TITLE
Configure functional api testing

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1543]
We're able to do functional API testing, but just haven't configured and put in some basic tests. 

Mark would like to get this set up and do some initial tests. Then, we'll touch base and I can request others. 

The plan is to have these run regularly, and can be linked to builds if desired.

**Comment by JosephMcArthur** [comment]
Part of this is:

* a change tracking spreadsheet
* enable a 'test' endpoint to run tests when we want

**Comment by JosephMcArthur** [comment]
I've started a change tracking sheet here: https://docs.google.com/spreadsheets/d/1uVg_oUsEOrQGnGJ3ZX9Dm5gzRLMzl0Yn_UUm6otPMsI/edit#gid=0 which also has some thoughts on functionality.

**Comment by JosephMcArthur** [comment]
Oh, by the way, I can imagine wanting to run every test above on live & on dev. Which means 2x. Then, of course, this is just two systems. There are quite a few others. I could see us getting to 1k tests quite quickly. The above was just what I had to hand to get started.

**Comment by markmacgillivray** [comment]
More to do on this, but lots of progress made. To be discussed.

**Comment by markmacgillivray** [comment]
Still to be configured, but ready to do so now. Will take a couple hours more this week.

**Comment by JosephMcArthur** [comment]
One thing that's likely to be helpful here is a function here that allows us to say 'ignore changes like this' which ignores divs that are exactly the same as ones noted.

**Comment by JosephMcArthur** [comment]
transferring comments here. 

### Name

Friendly name for use in discussions / subject lines / interfaces. when friendly name is not given, use url.

### Run everywhere?

Setting to toggle if this should be run on dev and live (i.e the opposite of whatever is in there)

### Contains

If this is not present, we should be alerted to it. This is intended to be a simple string. I'd suggest that if the change means the contains string is lost the subject line changes so that it's an 'alert'. This can then be configured in our inboxes as we desire. 

### Ignores

Something we've already seen with wachetes is that some changes happen again and again (e.g the addition or removal of a full stop from metadata).

It would be nice to be able to add things to stop notifications for these.

We'll also likely need to be able to put in some fields to ignore here, like query time in this: https://rickscafe-api.herokuapp.com/permissions/doi/10.1073/pnas.1905762116

Also, above, I've suggested:

> One thing that's likely to be helpful here is a function here that allows us to say 'ignore changes like this' which ignores divs that are exactly the same as ones noted.

### Rate

how often should it be monitored, in seconds

### Notify

Lists emails to notify, comma separated

### Note

a note to send with notification if more info is helpful

**Comment by markmacgillivray** [comment]
URL: curl in URL is prob not going to be useful. But a "headers" and "method" columns may be better, with risk caveats.

Run everywhere: not a very robust approach, as it does not fit a good general service model. May be better to have two sheets... to discuss.

Ignores: this will be tricky. It may be better to provide a range of options like case sensitivity, punctuation sensitivity, etc. For JSON keys though, that is easy to ignore, yeah.

Rate: should be in minutes, I think, and some of these rates seem far too low, as mentioned previously. To discuss.

Notify: not sure the sheet needs this, if we attach the sheet to a user account. Or do we allow different notification addresses? maybe, but how many... to consider.

Other things to consider:

I was testing this earlier and thought it is not very useful to get lots of separate emails. Would it be better to send one batch email with all changes in it? Otherwise at many times nothing will happen then every now and again a few hundred emails could arrive.

Would we expect alerts from this when whatever it is monitoring just does not respond at all? This is not really a change but a failure, and there are other services for that. We could combine it though, but needs a bit of a different approach.

Grouping - Some tests should have a group name as well as an individual name, perhaps.

Triggers - have a way to specify a trigger name, which then creates an endpoint under the user account which can be hit to trigger anything with that trigger name attached to it (which can then be used manually or programmatically).

More to discuss in call.

**Comment by JosephMcArthur** [comment]
filtering out load

**Comment by markmacgillivray** [comment]
An option to care about structure of html and/or content of html may be useful but not necessary right now - we just check the whole page and identify changes, wherever they are.

**Comment by markmacgillivray** [comment]
It would be useful for ignores to be able to specify sections to ignore. This would be easiest to do with a UI tool like a plugin, but for now just a naming of the div.

**Comment by markmacgillivray** [comment]
Or even saying a particular diff is not worth warning us about. Like if the diff is "this" changed to "that", and it keeps happening, have a way to say "ignore this diff in future". Ideally a link in the email too.

**Comment by JosephMcArthur** [comment]
- [ ] Joe to review monitor sheet and clean stuff up

**Comment by JosephMcArthur** [comment]
I've started the live sheet: https://docs.google.com/spreadsheets/d/12TuDSqjJ5FE5dijJHWjjEcmbxg0ExqugKlC3MnZuTrc/edit#gid=0.

**Comment by JosephMcArthur** [comment]
things to do:

- [ ] github needs to be configured to run groups of tests
- [ ] joe needs to define what tests should run on commit
- [ ] enable batch email notifications for diff test
- [ ] copy everything to live sheet

**Comment by JosephMcArthur** [comment]
Note, difftest now only gets used for json responses. Everything else is in ghostinspector.

**Comment by JosephMcArthur** [comment]
To close:

- [ ] move system ones (e.g eupmc) into the sheet
- [ ] turn on notifications

**Comment by markmacgillivray** [comment]
Still got to do some of these, just a note for reference.

**Comment by JosephMcArthur** [comment]
This is affected by CF workers. Planning to ignore file check parts for now.

Looking to spend one more hour (ish) to turn on notifications. Then we can close this.

After that, we'll casually keep an eye on it.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you provide an update here?

**Comment by JosephMcArthur** [comment]
@markmacgillivray any chance we can close this before we talk so we don't need to review it again 😉
