### ISSUE TITLE
some redeposits becoming request only deposits & weird oa links

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1553]
Not clear on if the two issues here are connected, but found them both at the same time and that tends to indicate it is! 

Two things:

1. We're seeing some expected redeposits become dark deposits. This is on dev & live.
2. We're seeing some expected closed articles show up as open. This is both in syp and on the homepage, but I think only on dev.

### Issue 1

Our test article for redeposits: https://josephmcarthur.github.io/playground/syp-dev?doi=10.1186/1758-2946-3-47

Is, once you submit, turning up in the emails as a request-only / dark deposit. Unclear as to why.

### Issue 2

Our test article for 'dark deposits' has the UI response of an already open article.

https://josephmcarthur.github.io/playground/syp-dev?doi=10.15650/hebruniocollannu.89.2018.0221

It's saying, even via the homepage, that it's open. It doesn't seem like unpaywall now finds it open though. 

Interestingly, our test oa article on the homepage, on dev, gives a different URL to live:

https://dev.openaccessbutton.org/?doi=10.1126/science.196.4287.293
https://openaccessbutton.org/?doi=10.1126/science.196.4287.293

**Comment by markmacgillivray** [comment]
Looking at issue 1, I don't understand the problem. If I go to that link it says the article is already available, which is true. Then it says I can give my email to "deposit". This does not make much sense because it is already deposited. But anyway, it seems to be the intended functionality. So I put in my email, and it says Hooray I am done, seems fine.

Then the email gets sent, and it says "I" would like to make a request-only deposit, and says the publisher PDF can be found at the link. This all seems to be true. What else should it be doing? What other kind of deposit could the person make, when the article is already freely available and they are, I guess, depositing to their local repo? What is a request-only deposit? Should it be called something else? Sorry i can't help until that is made clearer.

I'll look at issue 2 now.

**Comment by markmacgillivray** [comment]
OK issue 1 is fixed on dev.

**Comment by markmacgillivray** [comment]
It was a frontend fix to the js and I have merged it into develop so if you are happy with it then it can be merged into live any time.

**Comment by markmacgillivray** [comment]
I think this is doing what you want on dev now. Please confirm and if so I will run the script on live and then this can be closed

**Comment by markmacgillivray** [comment]
I have already checked, but just to make sure

**Comment by JosephMcArthur** [comment]
looks good!

**Comment by markmacgillivray** [comment]
Script run, will close now.
