### ISSUE TITLE
review title search / reverse lookup & citation search

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1557]
A librarian asked me why we don't find:

Crossley, Beate, et al. "pandemic." Emerging Infectious Diseases, vol. 18, no. 2, 2012, pp. 315.

In InstantILL, and I was confused as it seems like something we should manage. 

e.g a search of crossref brings it back:

* https://api.crossref.org/works?rows=5&query.bibliographic=Crossley,%20Beate,%20et%20al.%20%22pandemic.%22%20Emerging%20Infectious%20Diseases,%20vol.%2018,%20no.%202,%202012,%20pp.%20315.
* https://search.crossref.org/?q=Crossley%2C+Beate%2C+et+al.+%22pandemic.%22+Emerging+Infectious+Diseases%2C+vol.+18%2C+no.+2%2C+2012%2C+pp.+315.

**Comment by JosephMcArthur** [comment]
Okay, it looks like we just don't work with citations that don't have dois in any reasonable way at the moment. 

Baker, T. S., Eisenberg, D., & Eiserling, F. (1977). Ribulose Bisphosphate Carboxylase: A Two-Layered, Square-Shaped Molecule of Symmetry 422. Science, 196(4287), 293-295.

doesn't work.

Baker, T. S., Eisenberg, D., & Eiserling, F. (1977). Ribulose Bisphosphate Carboxylase: A Two-Layered, Square-Shaped Molecule of Symmetry 422. Science, 196(4287), 293-295. doi:10.1126/science.196.4287.293

**Comment by JosephMcArthur** [comment]
Seems like we should even be able to do some regex magic with these: https://www.researchgate.net/publication/238518285_Regular_expression-based_reference_metadata_extraction_from_the_web.

But crossref reverse look up should be doing more i expect.

**Comment by JosephMcArthur** [comment]
Some random thoughts to put here:

- [ ] do we check matches against other metadata given by search
- [ ] do we check matches against the length of what was given?
- [ ] how can we handle searches that are <<title>>, <<author>> better? E.g, ignore things after the commas?

**Comment by JosephMcArthur** [comment]
We don't match:

'Reverberation mapping measurements of black hole masses in six local seyfert galaxies'

even though it's identical to the doi: https://api.crossref.org/works/10.1088/0004-637X/721/1/715

**Comment by markmacgillivray** [comment]
Note see #1613

**Comment by markmacgillivray** [comment]
Copying from #1613 for reference

Adloff, F. (2009). "What encourages charitable giving and philanthropy?" Ageing & Society 29: 1185-1205
Khan, Sabith. "New styles of community building and philanthropy by Arab-American Muslims." Voluntas: International Journal of Voluntary and Nonprofit Organizations 27.2 (2016): 941-957.
(2018). “How do you incorporate charity into your holiday traditions?” America 219(13): 6-6

They respectively mapped to articles from

Zeitschrift für Geburtshilfe und Neonatologie (2016)
Schweizerische medizinische Wochenschrift (1963)
Pancreas (2015)

**Comment by markmacgillivray** [comment]
There are a number of factors involved here. Overall, title search and reverse lookup / citation search has been reviewed and improved, but quite a few articles listed above are still not found, and cannot be reliably found. Here is info on why not, first covering the changes I have made, then what we can now find, and then what we still can't, and why.

WHAT I CHANGED

Handling of special characters in citations has been improved, both as part of the recent user input cleaning, and also directly, in how we try to parse citations. Also the way we query them on crossref has been updated - we used to only issue a reverse lookup, as we could not do searches on works due to limitations in crossref API. Those limitations have since decreased, although still not ideal. We are now able to pass a citation string, or a title, to crossref works search, and sometimes get back a more accurate result than reverse lookup. BUT it is still not 100% accurate, even on title alone, because it turns out crossref does not actually do logical operations on the search parameters, it just ORs them all. So the longer the search term, the larger the result set. I have increased the size of results we ask for on a title search and have it loop through what is returned until it finds one with a close enough match, so we get more answers this way now. I have also increased the accuracy requirements for a reverse lookup, if we do continue to do one. Also, if there is a title and a fuller citation string, we try the title on works search, then on reverse, then full citation on reverse. And results from reverse search are also compared against year or journal values, if those are provided by the user. We now get more results overall by succeeding in title searches, but get less from reverse lookups as it is now stricter. This should increase overall accuracy.

WHAT WE CAN NOW FIND

Baker et al Ribulose... etc can now be found, without including the DOI in the citation string.

Reverberation mapping can now be found (NOTE searching this on crossref actually won't return it directly, it comes far down the results list, so we only find this by checking nearly 100 crossref results until we find the exact title match)

Adloff et al What encourages charitable giving... can now be found

Khan et al New styles of philanthropy... can now be found

WHAT WE STILL CAN'T FIND

The article that opened this issue, Beate et al "pandemic" still cannot be found - but this is unavoidable. Note that the crossref search actually doesn't exactly return this either - it returns a large result set of possible articles, and it does just so happen that this one is at the top, but the title is different. It is actually "Pandemic (H1N1) 2009 in Captive Cheetah" which is VERY different from the title provided, apart from just starting with the word "pandemic". Everything else about it is different, and we know from previous experience that if we tried to match ONLY on the word pandemic we would get a huge amount of false positives on other one-word matches. This is why we don't match on one-word matches. Also, even though with this one we are provided the year and some other metadata, we can't really match very easily on anything beyond year and journal title, and in this case, there are many other results that do also have the same year, and possibly the same journal, and actually have a closer title match than the expected article. So I don't think we should alter the system any more to make it possible to find this article - we should just accept that if a user gives us a citation with such a short and inaccurate title, there is no way we are going to get a reliable match without also risking greater false positives on other searches.

How do you incorporate charity... still cannot be found. In fact I can't find it anywhere. At least we don't match it to something wrongly now, with the improvements already outlined above. So, again, without a more accurate citation, we should not alter the system to be able to find this one (if we were even able to find out where it is ourselves in the first place to test it).

WHY WE STILL CAN'T FIND SOME THINGS

This is pretty much covered above, but the main point is that we cannot make the system more accurate in specific cases without also making it more likely to get false positives in other cases. It is possible that with a more searchable local copy of some article titles we could do better text searches on it where we could look for exact matches on short article titles such as "pandemic", or prefix article matches so that at least we would know that the title starts with the correct word, and then falling back to matching other metadata in the citation could be easier. As mentioned in separate discussions, a local searchable cache was not our original approach because OAB was originally intended as a plugin to run on web pages, not directly on article identifiers or citations/titles, and so the time of scraping the page, extracting suitable metadata, then sending that for search was already so great that a local cache had a tiny fraction of improvement on efficiency or accuracy. With our change in focus over recent years a local cache could indeed be better for the majority of our current use cases, but we will need to schedule some time into making and maintaining that, and altering the system to use it.

**Comment by JosephMcArthur** [comment]
We'd like to continue working on this to make sure that if a user gives us something that looks like a citation we can extract information from it in order to reduce how much they hit the 'wrong form'. This would run parallel to remote lookups, and be separate to current efforts to parse the title out. We'd use the info here if remote calls didn't return a good match.

**Comment by JosephMcArthur** [comment]
Do we need to wipe the cache on dev to get proper results for the above? I'm still seeing odd results for:

> Adloff, F. (2009). "What encourages charitable giving and philanthropy?" Ageing & Society 29: 1185-1205

for instance.

**Comment by JosephMcArthur** [comment]
We just got another issue from live on this:

> Citation searched – “Kaler, A. (2019). "Faith and Charity: Religion and Humanitarian Assistance in West Africa." Journal of Modern African Studies 57(2): 350-352
> 
> Journal of Modern African Studies”
> 
> InstantILL info:
> 
> Journal: Journal of Modern African Studies
> Volume: 22
> Issue: Part 1, No. 4
> Year: 2010
> Pages: 611-614
> Author: Ono, Teruaki, Norimoto, Misato,  ,
> Article Title: Kaler, A. (2019). "Faith and Charity: Religion and Humanitarian Assistance in West Africa." Journal of Modern African Studies 57(2): 350-352

**Comment by markmacgillivray** [comment]
This took longer than expected, but have got something useful out of it.

Firstly, no, none of the new citation matching stuff is on live yet, so it is not too bad that we are still getting reports of some bad matches on live.

Secondly, getting that citation to match the correct one as opposed to the very similar one was hard for a number of reasons that we have encountered recently:

* some of the relevant records returned were putting some of their title parts into that "subtitle" field we spotted before. This appears not to happen on journal-articles though, but maybe that is just cos I have not seen any yet, but it definitely occurs on some monographs, causing them to have smaller apparent titles that may then match. So I have updated the system to take account of subtitles when available and relevant.

* the citation above does not actually match the full title of the journal article in crossref, although in this case I would guess it is because crossref has it wrong. But because we tried to match just on title first to avoid the earlier problems of getting large result sets for queries with citations because they had more words in them, we were getting a bad match on the just the title. So I have changed this as well to try matching with the citation when we have it, then checking any additional metadata if we had it, then looping onto just doing the title search if we did not get a good enough match.

* I have also added one more allowance to let us match citations like this example correctly even if crossref seems to have extra stuff in the title field - we used to require titles to be within 20% length of the one we had and to match on the first 3 words; this is still the case, but I have also added an allowance for if the title we are given is at least six words long, and is fully included within the start of title we find. That allows cases like this one, where the title is correct but crossref has a bunch of extra metadata stuck at the end of the title. We can't allow this on titles that are only a few words long though, because that would start to allow for too many mismatches on short-titled articles.

So, this is still all ready to go onto live when we next do a push. We should consider that fairly soon as there isn't much holding us back on it, testing this week with the new embed calling the new find code (which runs the new citation matching) hasn't brought up any problems for me. So perhaps we review this and release at start of next week.

**Comment by JosephMcArthur** [comment]
Thanks Mark. If we can push this independent of other refactor work, I don't see why we shouldn't even do it today.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
