### ISSUE TITLE
file deposits not working on live & dev + everything is oa?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1568]
Currently file deposits through syp don't appear to be working. A file for testing in your email. When you upload, you should see a message telling you to contact your library. 

Not many other clues, I can't see any helpful errors or anything like that sadly.

https://api.openaccessbutton.org/deposit says false, but I'm not clear on if that's intended.

It also appears that we're back to showing all our test dois as oa, at least on dev: 10.1063/1.4937158. Only the redeposit one should be coming back as OA.

**Comment by markmacgillivray** [comment]
This file was being blocked because the word "test" appears in the abstract. We previously added a catch because users were putting the word "test" in some of the metadata they were providing to us when they were trying out some demos. This was giving us bad records in the catalogue. But of course now we are collecting and using much more metadata, and in more places across systems that it was not originally intended for, and so we have the check for "test" now not allowing saves of real records.

We also appear to still have some problems with deeper level caching, so I have dropped the dev catalogue again and this time disabled all caching that could be holding any data that affects these results. We will need to do a full review of all caching in the system and see where bad data may still have got stuck during the time we had unexpected code running in places. This also relates to the index TLC issue so that is convenient.

I have created two new issues for reviewing caching and reviewing the content users provide (which we also recently discussed in chat) - see #1569 and #1239 

Note also that, at the time, it was suggested that users should not be doing demos on the live system anyway, because that is what the dev system is for. We should revisit that at some point, and put the necessary time into making sure that demos are not using or dirtying live systems.

As we discussed yesterday implementing a new policy of not pushing anything to master until it has been reviewed, I have not pushed the changes that I have made to live yet. They are backend API code rather than frontend website repo code, but in the interests of trying out the process, I am letting you know here.

So, to release to live, the changes I have made need to be reviewed on dev and then let me know they are acceptable. Then I will push to live, and drop the live catalogue as well.

Note I have already tested these changes on dev, and I can successfully submit the file and get back accurate OA results - the above is about the process of review, not testing it from scratch.

**Comment by JosephMcArthur** [comment]
Sounds good Mark. I'd say push live when you can, things certainly look better.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Still seems to be a problem with this one: https://josephmcarthur.github.io/playground/syp-dev?doi=10.1063/1.4937158 from our test list. eupmc is still reporting on dev that it's oa, and it isn't.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
That should be sorted now. Let me know if so, and I will push to live once I get up tomorrow.

Also can you provide a list of DOIs with their expected responses, then I can use those to start testing the change tester.

**Comment by markmacgillivray** [comment]
I've pushed this live, dumped the catalogue, was up in the middle of the night. I have tested with the front page URLs and others I could find, looks good. Let me know if any issues, otherwise close whenever you are happy.
