### ISSUE TITLE
save what was searched initially in instantill

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1572]
I'm having libraries be quite interested in what the initial search in Instantill was, and for diagnostics it can be quite helpful.

This doesn't need to show up in the openurl or emails for now, but can we save it? If we could see it in our internal metadata dumps to emails that would probably be enough.

**Comment by JosephMcArthur** [comment]
I just did two searches, with ILLID of PjYzPyZB9A2cKNnh8 and EksivGu35d2pPiHqr. In neither did I see a field for what I searched in the internal "ILL CREATED" email. That said, I can't quite remember if we actually were expecting this right now. 

What I did see was that in PjYzPyZB9A2cKNnh8 it looked like we tracked down extra metadata, even for my non-sense search that should've been too short to fire a metadata / oa search.

**Comment by markmacgillivray** [comment]
This goes into a field called input. If the email templates have not been updated, which we did not do last time, then no this will not show up anywhere yet. I think you said you just wanted us to save it and later would do something useful with it.

The extra metadata one, it appears has previously been used as a test one, and so yes the test info that was provided by you means we now have what the system thinks is a legit record there (because we chose to believe user input over what we find). So although the title is not good enough to do an actual search, it will still match anything we have already accepted as being correct and have stored in our own collection.

I also did note that we issued some title searches unnecessarily though, this it to be discussed at our next meeting.

**Comment by JosephMcArthur** [comment]
- [ ] Can you put the field into the template we use for internal `ILL CREATED` emails then please?

> So although the title is not good enough to do an actual search, it will still match anything we have already accepted as being correct and have stored in our own collection

Seems like this is likely to cause false positives and should be avoided, or am I missing something? 

- [ ] We still need to discuss `I also did note that we issued some title searches unnecessarily though, this it to be discussed at our next meeting.`

**Comment by markmacgillivray** [comment]
Unnecessary title searches have been modified out, no need to discuss. Email template has been changed, will push code and reload templates to test.

About the title thing, yes it does mean we can get false positives, but that is exactly the side effect of prioritising data we get from users over data we get from sources we search. If we allow the system to override with what the users give us, which we do, then how else are we going to use that data unless we do actually use it? I'm pretty sure I brought this up at the time, and it was why I didn't think we should change the system to prioritise data that users give us.

**Comment by JosephMcArthur** [comment]
Let's chat in our meeting. Not urgent, and easier done not over text.
