### ISSUE TITLE
Null email for permissions request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1577]
To replicate: https://shareyourpaper.org/10.1021/acs.chemrestox.0c00089 and click 'review email'

- [ ] this shouldn't ever be possible to be null, should always fall back to the embed email.
- [ ] This is ACS, which is a slightly weird record. I should check to see if we're giving a permissions request record too

**Comment by markmacgillivray** [comment]
I don't see a "review email" button. I only see a "see free version" and a "do another" button, because the item is freely available.

However I have looked at the code, and I have changed it to not pass an undefined email. Here is what we have previously coded it to do:

* if ricks gives a permission_required_contact, use that
* in which case, cc the config deposit_help address
* if there is no deposit_help address to cc, then cc the fallback email
* the fallback email is whichever one of config problem_email, config email, or config adminemail is available, in that order of preference
* if we were not able to set a mailto from ricks, then use the deposit_help if available for that, or the fallback email
* and in this case, given there is only a mailto, then there will be no cc mail address


In this it was possible that the email could still be undefined, because none of the above were available. So now it defaults to an empty string, so then the user can just type an email into the email page when it opens.

Let me know if this needs more alteration.
