### ISSUE TITLE
Handle / stop certificates updates bringing down the site

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1610]
Currently every few months updating the certificates drops all our sites for a few minutes. (I think) we've look into why before, and seemingly had trouble resolving this.

#1253 

It's worth:

- [ ] re-reviewing why
- [ ] having some heads up given to the team so we know not to panic (or, it doesn't wake Mark up for instance).

There is a good chance that #618 would resolve this. Since it's irregular, and fairly minor, happy to address as a non-urgent issue.

**Comment by markmacgillivray** [comment]
Yeah we did technically resolve the previous issue, which was them failing to renew and the site going down. Now it works fine, it is just that there are quite a few of them, so if it takes over a minute then all the alerts start triggering (and some users will get unresponsive API requests). Cloudflare could solve, or altering configs to allow renewal without bringing nginx down, but due to some oldness of things on our infrastructure, that is not so easy. Anyway, not major, only happens every 90 days, and quite often does not take long enough to be noticeable anyway.

**Comment by JosephMcArthur** [comment]
Ah yes, you're quite right, I remember now!

**Comment by JosephMcArthur** [comment]
- [ ] add instantil.org & shareyourpaper.org to uptimerobot so we know when they go down. 

I know we have said this isn't really needed, but after today and adding them to the embed scripts I"d like to do it just in case.

**Comment by markmacgillivray** [comment]
Unfortunately this has taken a fair bit longer than was hoped, but it did need doing. The old configs of letsencrypt (which is now certbot) were from when it was first released, and we never had them automatically configured to work well with nginx on auto-renew. Some of that was mitigated by having important sites covered by cloudflare anyway, and getting alerts when certs needed renewing, so we mostly kept them up to date (I think twice we missed them over the years). However, I started the work of getting the configs updated, because as we know we've skipped some sysadmin earlier in the year, so things need reviewed and sorted out. Our recent issues were caused because we have many domain names now, so there is sometimes sufficient enough delay for people to notice the site not responding when the old style renewals turn nginx on and off in order to get the new certs. So I changed the configs to do that in a better way, that doesn't require nginx to go on and off. However I then had to do that for every domain on the system, because it couldn't autorenew some of them in one way and the others in a different way, whilst also keeping nginx up the whole time. That has now mostly been solved, but there are still 5 domains throwing as yet unknown errors when they try to autorenew, which would still cause renewal delay to other certs, but probably wouldn't cause people to notice any more. But at least one of those failing domains is an OAB one, so I have to continue until this is solved, so that I can do a final run through of an auto-renew that I keep an eye on, and once that succeeds on all of them, I can leave it automated to check each week, then we will be up to date and won't have problems any more.
