### ISSUE TITLE
Reviewing our bug management process

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1655]
Meta comment. I've made a `process` label where we can store some discussions like this. We've discuss adding more here... so this is my start. 

Recently we had a couple of production bugs after pushing our new code. These were on old systems, and affected important partners / products. We fixed them fast, and seemingly people are happy. This is not a bad start point. However, the fix didn't feel as smooth as it could be. Since we're in the habit of review atm, we're reviewing this.

Already, we have put in place:

- [X] Automated testing of production systems to 'sanity check' them. This was a hole in our test coverage and now doesn't exist, and removes a piece of work we frequently have to do on live pushes. This means the error would've be caught and fixed before users found out.
* https://github.com/OAButton/discussion/issues/1646. This would ensure that even if the error wasn't caught, it could've been handled better for the end user.
- [X] Templates for bugs / enhancements on github where process improvement points can be added.

In our meeting we discussed our communications challenges and other things going on:

* Due to how I described the issue, and as I couldn't fix it myself, Mark presumed it was a server side issue.
* Mark didn't check /deposit as he didn't know it existed / was in use. I had set the up myself previously, and not communicated it.
* For both Mark and I, production bugs are stressful events. We just want it to be fixed and done asap. They always come at 11pm and interrupt time with partners / relaxing. 
* Talking on hangouts creates a sense of urgency that doesn't help the above. However, it makes it *feel* like we're doing something fast. 
* When stressed, Mark and I revert to the places we feel most comfortable. I think frontend, he things backend. For each of us, in the complex system the intuitive fix is different.
* This was one of the first times it was clear to Mark that we really do have paying customers that also we don't work closely with.

These are not issues limited to this bug, or even just bugs, we see them in many places.

Our take aways, so far:

* Hangouts is an anti-pattern for us. It results in non-thoughtful chat. We need to get everything to Github ASAP, as this creates a very different context for discussion.
- [X] Set up email to github issues. We now have oab@fire.fundersclub.com for this.
* A good fix likely requires one of us explaining what we think the right fix is, and the other confirming understanding. e.g in this example when I described what I thought the fix was, Mark could have explained what he's going to do. When he mentioned servers I'd have realized we weren't aligned and could've caught that. This doesn't need to be laborious.
* Realizing the above is a requirement for a 'good' fix, but may create delay (and be harder 'in the moment' when we just want the thing fixed) we may want to expect that a 'fast' fix might not be a 'good' fix. The fast fix may be whatever each of us can do alone, quickly to mitigate the issue. However, it might not be the most optimal fix, and require some clear up after and a second fix. The advantage of this is that we can fix things really fast, but of course the downside is that overall we perhaps spend more time on the bug. This is likely an acceptable price to pay for big production bugs, and a reasonably strategy for a small remote team where sync communication is hard.
* I don't know even simple javascript. 
* I should maybe do an internal talk on the state of OAB.

After sleeping on this, I decided that alongside some of this we may also want to start:

- [ ] using 'announcements' on uptimerobot to flag on our status page when we know there is an issue. This serves to pro-actively let people know we understand there is an issue and we're working on a fix. This can mean that 'fast' fixes aren't quite so required. 
- [x] have a 'banner' that can be revealed without any code pushes on certain pages when we know there is an issue (e.g the page affect, plug /feedback#bug etc). This serves to pro-actively let people know we understand there is an issue and we're working on a fix. This can mean that 'fast' fixes aren't quite so required.
- [x] making sure that in the process of working with users we let them know how to mitigate the impact. For instance, I could have let alberta know they could upgrade their embed to the new one, and the other user that they could use shareyourpaper.org. This can mean that 'fast' fixes aren't quite so required.
- [x] de-stressing big production bugs feels important. Writing up some templates or something like that for responding would be helpful to make that more thoughtless (e.g what can I send in a few clicks at 11pm).

I'm also curious:

- [x] could our new logging caught these issues in any way? Since those are partly for error catching, and these are errors, how might they have helped?

**Comment by JosephMcArthur** [comment]
Oh, and this can be shut once we've reflect on the above, and made issues etc for things.

**Comment by markmacgillivray** [comment]
I don't think logging could have caught the issue, and even if it had, I don't think I would have been able to know that it was an issue. We already do fix issues pretty fast anyway, but sometimes it seems more like it's hard to tell what is going to be an issue and what isn't. I think this comes down to something that still happens during our development/refactor phase, which is that we often de-prioritise things that we probably should not.

For example in the case of changing the config names on the embeds, one of the things we specifically talked about was how that would affect users with old configs. It seems that we didn't manage to communicate effectively to each other what the outcome of our choices there would be. This probably relates to the fact that it wasn't clear to me that we were talking about a production system with paying users, and the difference in our frontend/backend way of thinking, and also to something else I notice a lot, which is what feels like too much reliance on the idea of "quick wins". Quick wins are good when they are simplifying what we need now rather than building unnecessary things, but they're not good when they predictably result in slower progress and higher cost later on.

Examining the config renames example further:

* if I'd been aware that at the time we were discussing changing the config names that there were paying users who could have a broken service as a result of our changes, I would not have agreed to the changes that we chose to make. We decided that if old users said they'd had problems with their configs no longer working, then we were just going to point them to the new config page and ask them to reconfigure and reinstall - but of course that is not what happened, as soon as a paying user had an issue, then we had a critical bug to fix. This is also why even if logging had picked up on this, I wouldn't have done anything about it before a user complained - it seemed to me to be an intended consequence of the decisions we made.

* I should have pushed harder to do more work on the backend, which would mean it would have taken longer, which would look like even less early progress at the frontend. However, that would have resulted in us having backend code capable of handling both the old and new configs more robustly. The apparently faster results achieved by the decisions we made were not in fact real, because in the end we had to do extra work to deal with the problem for the paying user, and we now have at least one other open issue where we should probably support translation of an old user config to a new one. This would have been easier to just do at the time we were making the changes to the system - OR, the extra time it would have taken should have been deemed not worth making the change, and we should have stuck with the old config names. I feel that, at the time, I did say we should not change them because in the end it really doesn't matter what names they are, as long as they work. It is true that I didn't like the confusing names we had, but the proper solution to that would have been to do a better analysis of the config when we first built the new embeds, but we already know we made lots of fast/bad decisions during that time as there were other operational constraints that severely limited how long we could spend on anything that did not have an immediate visible impact. This is probably my fault for not being clear enough about the impact of certain decisions, because I tend not to understand what is obvious and what is not obvious.

* Whilst I often agree that it is best to do something fast that works rather than over-engineer something for no real requirement, I do still feel that I often suggest things we need to do on the backend, but as soon as I say it takes half a day or more, it gets deprioritised or becomes a discussion about how to solve that problem with some external service. Sometimes, when we are clearer about the requirements, an external service IS the right answer. And sometimes deprioritising things that could take longer is also the right answer. But it often feels like we think about the immediate cost as "half a day of backend dev time is £X to the project and has no visible impact", so anything that takes longer than that is hard to argue for. But the reality in the end is that we often spend far longer than half a day fixing the resulting issues that arise from that early decision, and we spend MANY days in tiny details of how the UI works. In these cases, we're not really finding quick wins, we're just avoiding spending backend money early - but we end up spending MORE on both frontend and backend later. This was a necessary approach when there was no "early" money to spend, but it has bad consequences that we shouldn't replicate when we don't need to.

* In both the first versions and the latest refactor, we did specifically discuss that a demo/setup UI to construct a fairly simple JSON config object was possibly a great deal of additional work for something that already had an easy solution, and we were choosing to put functions into the config that should not have been there, and that the more detailed we made it the less general the solution would be. When we talked about whether we should change config names or not, the decision seemed to come down to how those configs would look to users copy/pasting them than to how it would affect the functionality of our system. And the decision to build such a complex demo/setup UI to make the problem of config seem simpler to some users may actually have been less simple than just explaining to them to write JSON. It may even have been cheaper, easier, and faster to just fly me directly to their offices to write their embed pages in person. When RSCVD had to be built slightly differently, it was exactly the case of the very particular config UI not being capable of handling it generally enough, so we ended up building custom work-arounds for it anyway. And when our own demo configs could have been altered by just writing the JSON configs into our own web pages, we both got confused over how to do that, because I thought you must mean you wanted it done in a way that seemed far harder than what to me looked like the far easier solution.


I agree that our overall goal of making things really simple to use is a great way to help improve the world and get people to share more. I think there are a few things that will help us in future, and most of these are things we're already bringing in, so that is good:

* separate out backend and frontend dev time a bit more, so that the need to keep frontend visual changes happening doesn't mean deprioritising backend work that has worse longer term impact on the services. Bringing in a new frontend person will help with this, which we're already doing. Then it won't be a case of my time having to be split across both.

* think more about the trade-offs between customisation of a UI to make it seem simpler to use vs keeping it functionally simple and more usable for more use cases (and more robust).

* take more consideration of the long term sustainability of the backend system - again, we've already started doing this, and by having more time to focus on it I will also take more responsibility to argue for the importance of this work even if it doesn't seem to be so immediately impactful. I will also spend more time communicating what I HAVE developed, because we have a lot of additional ability that could be spun out as useful services for our users (e.g. we already see lots of people using our system to convert data in spreadsheets, but we've never taken the time to properly support that).

* the backend/frontend API divide is also often a useful point at which requirements really become clear. When it's possible to focus more on good decisions from that perspective, it will also help to have a frontend person focus more on good decisions at the UI, and then there should be less trade-offs because there is more investment in each part, and any real trade-offs will be easier to understand. This should also give you (Joe) more information, more time, and more resources with which to focus on good decisions for the users (paying and non-paying ones) - and you'll be able to communicate more with the team about who we're delivering to, and why (which you've also already started doing).

**Comment by JosephMcArthur** [comment]
>  using 'announcements' on uptimerobot to flag on our status page when we know there is an issue. This serves to pro-actively let people know we understand there is an issue and we're working on a fix. This can mean that 'fast' fixes aren't quite so required.

@markmacgillivray can you give me access to our uptime account so I can post these?

**Comment by JosephMcArthur** [comment]
Noting some points from our chat today:

* We're moving in the right direction. However, there may be a lag feeling the benefits (or, some adjustments to habits to feel the benefits). E.g automated testing is a good store of requirements, however, we're not yet trusting it to make changes and await failures.

Things we'd like to improve:

* Small commits
* Linking commits to issues. This can be done by putting: `OAButton/discussion#ISSUE NUMBER` in the message. 
* Using issues as code comments. 
* Joe playing with writing up user stories and requirements for some part of our app
* Joe / Mark giving a 'demo' internally of the UI / backend code so we both get to know it better (as we both store requirements 'in' that code).

**Comment by JosephMcArthur** [comment]
Ticked some boxes above my making a major upgrade to https://github.com/OAButton/discussion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md. It now has tips we can both use as nudges to handle this better.
