### ISSUE TITLE
Embed agile processes in our workflow and have a contributor friendly set of repositories. 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#166]

**Comment by markmacgillivray** [comment]
Note, there is no such thing as "all key agile processes". The point of agile is to use what is most appropriate for the team and the task at hand. Quite often I see people doing "all teh agile things", having overlooked the fact that the initial purpose of agile was to strip down to what is necessary - not to follow what is common. SImilarly, whilst a contrbutor-friendly set of repos sounds good, it very much depends on what sort of code is being written, and the code for oabutton simply is not the sort that will attract a lot of contributions because it is highly unlikely to be the sort of thing that someone would download and use themselves. We are not making a library for use in other projects, we are making a project that uses many libraries, some of which are our custom "glue" that are really only useful to our project. Of course we should still keep things as open as possible, but in our case this is really a matter of transparency rather than collaboration.

**Comment by JosephMcArthur** [comment]
Haha, yes. all teh kei agile processes isn't a thing indeed. This was mainly me testing "epics" on Zenhub. In my head it just means make sure we have things like stand-ups, a half decent idea of a product backlog and those sorts of things. Certainly not looking to go nuts here though. 

With contributions, we've had a great handful of code contributions in the past and I want to make it as simple as possible to have that continue where it's helpful. But, moreso I'm also thinking about non-code contributions here and making those easy. This is also certainly an effort on my part to keep what we're doing transparent not just to the outside world but to our team in general.

Generally, I won't be asking you to push this type of stuff forwards as a priority (where it isn't super basic like simple readmes and docs), I'll just try and embed it into our process slowly.

**Comment by JosephMcArthur** [comment]
have done vast majority of what was planned for this not, so having an epic isn't that helpful. Closing.
