### ISSUE TITLE
Adding a DOI field in requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#169]
@dhimmel commented on [Sat Apr 09 2016](https://github.com/OAButton/odb/issues/58)

Having each request linked to a URL and not a DOI seems like it will be susceptible to linkrot. Additionally, it's much easier to get metadata for a DOI. Also searching for requests by DOI makes more sense than search by URL, since there are many URLs for a single article.

I get that it would be undesirable to only support pages with DOIs, so allowing an optional field may be the way to go.

---

@dhimmel commented on [Sat Apr 09 2016](https://github.com/OAButton/odb/issues/58#issuecomment-207852244)

As an example aesthetic benefit, [account pages](https://opendatabutton.org/account) would display:

```
Supporting data for DOI: 10.1007/s11192-015-1592-8
```

rather than

```
Supporting data for the article at http://link.springer.com/article/10.1007/s11192-015-1592-8/fulltext.html
```

---

@JosephMcArthur commented on [Mon Jul 04 2016](https://github.com/OAButton/odb/issues/58#issuecomment-230240085)

Thanks @dhimmel! 

@markmacgillivray any thoughts on this? I know many things don't have URL's, so this doesn't work in all places but seems like it would be good where possible.

**Comment by JosephMcArthur** [comment]
@markmacgillivray just seen this on #268

**Comment by markmacgillivray** [comment]
We can collect DOIs and could use them for display purposes where a title is not present (although now we can almost certainly get a title for every page anyway). But we cannot use DOIs instead of URLs, not even in the case of items that have DOIs - DOIs always resolve down to some URL, and when the user is on a web page and using the button, they are viewing a specific URL, not a specific DOI. What we offer is a service to find the content of a thing that is available at a specific URL, not a specific DOI. We could resolve URLs back to DOIs, but then we will be doing something different for things that have DOIs than we are doing for things that do not have DOIs. Whilst it may seem that DOIs are less susceptible to rot than URLs, this is not necessarily true in practice (it is just part of the illusion of validity that people tend to believe in, and that DOIs make them feel comfortable with). By this I mean that for example the DOI resolver relies on the underlying service, say Elsevier, to keep it up to date of any URL changes, but Elsevier use an internal resolver system anyway to resolve the URLs that the DOIs resolve to; so the DOI is only as robust as the efforts of the underlying company in keeping their URLs or their own resolvers active. So actually DOI provides no extra protection against rot unless all those involved wish to keep it up to date - but if they did, they could have done (and do) that with their own URL systems anyway.

**Comment by dhimmel** [comment]
> What we offer is a service to find the content of a thing that is available at a specific URL, not a specific DOI.

I disagree. Let's imagine an article has several URLs --- one for the abstract, one for the full text, one for author information, and one for the supplementary data. I think users will find it frustrating if requests to any of those four URLs are not treated as the same article.

> So actually DOI provides no extra protection against rot unless all those involved wish to keep it up to date

DOIs have agencies that are responsible for keeping links active. DOI registrants agree to abide by certain conventions, such as updating their DOIs, as a precondition for their membership. When I see a broken DOI, I report it and it generally gets fixed. Anecdotally I've had more issues with link rot of non-DOI than DOI links (but I couldn't find a comparative study on this point). Some issues such as changes in copyright / hosting location make it difficult to persist publisher links and thus require a resolution such as DOI. And a broken DOI link is much easier to track down than a broken non-DOI link, because the DOI link has accompanying metadata.

It sounds like you're not interested in making DOIs your primary identifier. You may still be able to retrieve DOIs for articles -- and thus get the metadata benefits -- by looking for a [`citation_doi` field](https://help.altmetric.com/support/solutions/articles/6000086842-getting-started-with-altmetric-on-your-journal-books-or-institutional-repository).

**Comment by markmacgillivray** [comment]
We can retrieve DOIs, and I am not against making them our primary identifier from a technical perspective. But, it is definitely the case that what we offer now is a service to find the content of a thing at a specific URL - we don't guarantee that different things at different URLs will be identified as the same thing.

We could do this, but as we do not limit to pages with a DOI, it would have to be a case of doing it only for the ones that do have a DOI, which would mean different functionality for different sorts of pages. This is not technically hard either, but changes the expectation a user might have about what sort of content they are asking for.

My point about DOIs is exactly that of your second sentence re. DOIs - registrants agree to abide by certain conventions. Those agreements are just a layer abstracted away from web links and onto DOIs (which are just web links too). Whilst it may be true that as a human it is easier to find an issue with a dead DOI and report it, using a DOI to actually access content programmatically can be significantly harder - those underlying redirect systems I mentioned quite often do not follow standard protocols, and sometimes attempt to purposefully fail for requests that are not made by humans (which can be faked, but still, additional complexity).

We could know that multiple URLs have the same DOI on them, and could then infer that they are the same article, and decide to merge requests on that basis. It is not straightforward though - the fields used by different publishers to represent DOIs on their web pages are not consistent. There are of course different conventions, but not all are followed by all publishers, and not all are followed accurately. So we cannot guarantee that we could say different URLs are actually for the same DOI. For example, we may accidentally think a page is about the same DOI when actually it is a reply piece about an item with a DOI (depending on how the DOI is embedded in that page, whether it is done correctly to some standard or not, whether we have considered that standard in our DOI extraction techniques, and so on).

If everyone used DOIs correctly (or everyone maintained URLs to supposedly permanent resources correctly) then these problems could be mitigated. But if everyone did things correctly, there would be no need for open access button.

So I'm not against the idea, just unfortunately highlighting the hidden complexities.

**Comment by JosephMcArthur** [comment]
@markmacgillivray we seem to have thought about this a bunch recently, any new thoughts here/

**Comment by JosephMcArthur** [comment]
@dhimmel we've done a lot of work on improving the aesthetics of our link display (so we don't display them & almost always have actual titles) and working across multiple identifiers (including, of course DOI's).

For what I understand as the original issue here, I think we've improved beyond the point where it's helpful having this sit in our backlog. Let me know if you disagree!
