### ISSUE TITLE
interesting ghost test / fail pattern

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1691]
I've notice that many of our tests involving Zenodo have been failing recently. Some examples:

https://app.ghostinspector.com/tests/5f23de22bfb7c24532047d14
https://app.ghostinspector.com/tests/5f23e0c2bfb7c2453204a754
https://app.ghostinspector.com/tests/5f36abaafb816a0cd2dd50dd
https://app.ghostinspector.com/tests/5f2ffbbb229b0352bfa3801b/edit#schedule

They would fail because the embed didn't show the successful screen (i.e complete the deposit) in less than 20 seconds. 

Having run them myself now, they're all working. However, when they were being run as a 'scheduled' job, they seemed to consistently fail. The pattern below is kinda typical.

![image](https://user-images.githubusercontent.com/4953703/96374675-e4a31d00-116b-11eb-879f-5670575810e5.png)

@markmacgillivray... curious if you have any ideas for why we might see a pattern like this.

I would say it's simply that randomly it's taking longer than that sometimes for the deposit to happen (the cut off is 20 seconds before test failure) but that wouldn't explain the several failures and then passing when I do it it.

- [x] At the least, I think it makes sense to increase how long it'll wait as 20 seconds is a bit short for a file upload / save / return.

Attempting to debug this as I want our tests to really only fail when they're actually failing and right now we get a fair few false positives… it seems (linked to #1641).

**Comment by markmacgillivray** [comment]
I've had a look but unfortunately the pattern isn't consistent in a way that can be identified. Some of them fail on schedule, but plenty on schedule also succeed. I don't think increasing the timeout would help, it's more likely a failure of the system in trying to do the upload. This could either be at our end for example if it coincides with the site or API going up or down for an unrelated reason like a code change, or could be because zenodo doesn't succeed. Our dev site uploads to zenodo sandbox, which itself is not guaranteed to be up all the time, and sometimes does get emptied, so it is possible for uploads to seem to not work.

I was able to cause the test to fail myself, by interfering with the API at the time the test was running, which did result in a similar failure. Hence why I think increasing the timeout won't help.

As a file upload and deposit test is likely to be the longest-running test, it is more likely to be the one where we would see failures. 

I don't think there is much more we could do about this one for now. When we do the code rewrite we could reconsider which scheduled tests we run and why, and see if there is a more informative way to run sets of tests.

**Comment by JosephMcArthur** [comment]
Gotcha, thanks! 

- [ ] I've just realized that one thing I didn't do, but should, is try to line up the test time with the confirmation emails we get for deposit. That way I can see if it actually did deposit.

**Comment by JosephMcArthur** [comment]
Have checked. The deposits happened even though the tests failed.
