### ISSUE TITLE
After error no input can be given

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1698]
**Describe the bug**

If (at least on instantill) you see an error message it's not possible to correct it.

**To Reproduce**

Go to:
* https://rscvd.org/?doi=10.1016/B978-0-12-800262-9.00002-0
* note it has errored
* attempt to enter `10.1126/scitranslmed.3001922`
* see "Please complete all required fields"

**Expected behavior**

It should allow you to enter a new search and proceed as normal

**Proposed Fix (if available)**
How might we fix this?

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
- [ ] Stay clear of hangouts

Process checklist:
- [ ] Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good` 

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)
- [ ] notify `Fwd: TU307`

**Comment by markmacgillivray** [comment]
@JosephMcArthur I've made a change for this on dev, have a look and see if that's good for you. Previously we showed the error message if someone tried a book but the error msg assumes they will want to continue to go and try to get that book, not to keep using the form, so it didn't reset the form for further use. I've changed it so that now it resets the form and also shows the error msg.

I've pushed this into develop branch too, so if you want to release to live without me being around, you can just merge that into master and now that codeship is working again it should deploy. Looks to me like cloudflare has picked up changes from yesterday too - did you hit the purge button? I didn't yet, so if it picked up on its own, that's good.

**Comment by JosephMcArthur** [comment]
Looks good. Can you push live now please?

Are there other examples like these where the form isn't reset?

I didn't hit purge.

**Comment by markmacgillivray** [comment]
Yes, errors don't generally reset the form. However errors are usually something we want the user to do something about and then continue, rather than reset. The only other one that looked the same was that shareyourpaper had the same sort of response so I set that to also reset.

Will push live now, and then close this.
