### ISSUE TITLE
joe@openaccessbutton.org incorrectly set as embed owner on shareyourpaper for random person

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1701]
**Describe the bug**

A new shareyourpaper.org user was setting up their embed. Yesterday they got setup without issue and put their embed code here: https://libraryguides.missouri.edu/shareyourpaper. They spend the day testing the tool and the API.

Today, when checking their embed code, they found it was

```
<div id="shareyourpaper"></div>
<script src="https://shareyourpaper.org/embed.js"></script>
<script>_oab=shareyourpaper({uid: "A4JJeBQbigHuWGiyc", config: {"repo_name":"MOspace","owner":"joe@openaccessbutton.org","terms":"https://mospace.umsystem.edu/xmlui/bitstream/handle/10355/60367/MOspaceCCLicense2016-05.doc?sequence=1&isAllowed=y","old_way":"http://library.missouri.edu/secure/mospace","ror":"02ymw8z06","pilot":1603291299787}});</script>
```

Note, I now own their embed but seemingly everything else is the same.

**To Reproduce**

*I think* I have reproduced this on dev but I don't have the exact steps yet. The account I reproduced it with was `joe+234567@arl.org` and my embed code became:

```
<div id="shareyourpaper"></div>
<script src="https://dev.shareyourpaper.org/embed.js"></script>
<script>_oab=shareyourpaper({api: 'https://dev.api.cottagelabs.com/service/oab', uid: "J8Rxfss5F9HQSkPpT", config: {"owner":"joe@openaccessbutton.org"}});</script>
```

I replicated it a second time with `joe+45678@righttoresearch.org`

```
<div id="shareyourpaper"></div>
<script src="https://dev.shareyourpaper.org/embed.js"></script>
<script>_oab=shareyourpaper({api: 'https://dev.api.cottagelabs.com/service/oab', uid: "pcAoSDLmr4nS2jEqS", config: {"owner":"joe@openaccessbutton.org","pilot":1603307299423}});</script>
```

Again, for whatever reason I couldn't figure out the exact steps.

I think logging into the same account incognito removes the issue.. but due to #1702 I'm having a bit of trouble really nailing this down.

At one point, I saw the issue replicated and when I went to the InstantILL set up page I no longer saw the issue. However, when I asked the other person to try the same they did.

My hunch was that using the frontpage, where I am the owner had some affect. I also wondered if there has been some change in how we handle logs which means their config is clashing with some usage by me on live.

**Expected behavior**

People don't randomly get me owning their embeds. 

**Additional context**

I have spoken with them, they're techy. Their noddy cookie is currently:

`noddy:"%7B%22email%22%3A%22pryors%40missouri.edu%22%2C%22createdAt%22%3A1586977019265%2C%22created_date%22%3A%222020-04-15%201956.59%22%2C%22updatedAt%22%3A1603304953592%2C%22updated_date%22%3A%222020-10-21%201929.13%22%2C%22retrievedAt%22%3A1603304953587%2C%22retrieved_date%22%3A%222020-10-21%201929.13%22%2C%22_id%22%3A%22A4JJeBQbigHuWGiyc%22%2C%22username%22%3A%22pryors%40missouri.edu%22%2C%22profile%22%3A%7B%22firstname%22%3A%22Steven%22%2C%22lastname%22%3A%22Pryor%22%7D%2C%22roles%22%3A%7B%22openaccessbutton%22%3A%5B%22user%22%5D%7D%2C%22service%22%3A%7B%22openaccessbutton%22%3A%7B%22profile%22%3A%7B%22confirm_public%22%3Atrue%2C%22confirm_terms%22%3Atrue%2C%22affiliation%22%3A%22University%20of%20Missouri%22%7D%2C%22deposit%22%3A%7B%22config%22%3A%7B%22repo_name%22%3A%22MOspace%22%2C%22owner%22%3A%22joe%40openaccessbutton.org%22%2C%22terms%22%3A%22https%3A%2F%2Fmospace.umsystem.edu%2Fxmlui%2Fbitstream%2Fhandle%2F10355%2F60367%2FMOspaceCCLicense2016-05.doc%3Fsequence%3D1%26isAllowed%3Dy%22%2C%22old_way%22%3A%22http%3A%2F%2Flibrary.missouri.edu%2Fsecure%2Fmospace%22%2C%22ror%22%3A%2202ymw8z06%22%2C%22pilot%22%3A1603291299787%7D%2C%22had_old%22%3Afalse%7D%7D%7D%2C%22timestamp%22%3A1603220069763%2C%22resume%22%3A%22eaa92b11b9ae434e7eca2b78e8c4b7%22%2C%22fingerprint%22%3A%22a1acef9eae40718358979395c3a97288%22%7D"`

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

**Comment by JosephMcArthur** [comment]
Whoops, hit save too soon!

**Comment by JosephMcArthur** [comment]
I seem to have been able to get `joe+45678@righttoresearch.org` to go back to normal but not `joe+234567@arl.org`. 

Since this was a bit tricky to replicate in the first place (I could do it... but not repeatably / rigorously) it's sort of hard to know. 

I'm going to spend some more time just playing around and seeing it I can get it happen again (especially with the other issue potentially closed).

**Comment by JosephMcArthur** [comment]
Assuming this is fixed... some questions it would be great to know before pushing this live:

* What is the thing we turned off again? Is it the system we use for remembering configs for logged out users? Is this the same as the config caching you discussed?
* If the config doesn't update itself, what can the user do to reset (ideally without losing the values they actually want)?

And, thanks for helping with this so fast. Much appreciated given the user took 40 mins out their day to chat with me and we wanted to release this today!

**Comment by markmacgillivray** [comment]
We have multiple layers to the config system now, having altered our initial intentions somewhat.

* we used to have login, and it was required, and that was the only way to do config

* then we thought it would be better to support people to use the embed without login, which they can do, but also for them to be able to create a config for it. So we made the setup page usable without login

* but then we wanted to have it so that someone who created a config without logging in, then came back to the setup page after having deployed it somewhere, would still be able to see the configs they had created when they were last on the page, even though they had not been logged in. So we started storing them in the localstorage (similar to cookie)

* but then we decided we did want to continue supporting login as well, so we made it possible to create a config on setup, have it usable directly in the embed, and also save to the user account if the user was logged in, so that logged in users wouldn't actually have to copy/paste when they changed their configs, if they already had an embed deployed somewhere with their account ID. So we allowed for both possibilities, and so now the config is also in the user account (which is what the person you were talking to was able to see in the cookie)

* and then we decided that actually we would make login required anyway for the setup, so people do still have to login there before doing a config now anyway. But we still have the various possible ways of storing config available.

* then we created our own demo of the embed, using a demo account that we already had from older versions (actually one from dev and one from live). So that had no config actually present in the embed, but was getting it from the backend.

* then we decided to embed the config of the demo directly into the page. It actually also still has the user ID of the backend account that already existed, but also now has a config written into the embed instantiation on the page. 

* that is what caused the problem - the demo on the front page of SYP is technically logged in and has a config, because we put them there. So then someone views that page and it stores that in their localstorage for them. Then they go to setup and they have to login, but then they strangely find that there is already an email address for their config, and it's not theirs. It's yours, because that is what we have written in the config of the front page demo.

* so we have two somewhat opposing paradigms going on - one for a world where we imagined no logins necessary for config, and one where we've decided to require logins anyway.

* so for now I've just changed the embed settings so by default it does not save the config locally, and if there is a config in localstorage it wipes it.

* this won't matter right now because we're making everyone login to do config anyway. So they can set their configs, copy/paste it to their embed location, then when they next come back to change their configs, they'll have to login again anyway which will load their config again for them from their user account.

* later, if we decide we do want to allow not logged in setup pages, and we also want to store the configs people create there while not logged in so they see it when they come back, we'll have to specify when and when not to use localstorage.

* for us, that will be anywhere on our own site where we provide a config with our own details, we should set local saving of config to false. But on the setup page we can set it to true. Since we don't actually need this now, it was easier to just default it to off everywhere, rather than searching through all the places we should explicitly set it.

**Comment by JosephMcArthur** [comment]
Okay, understood. I think we're good to push live. Let's keep this open for a little while as a holder for a discussion about this a bit later as I think it's worth unpacking a bit more.

**Comment by JosephMcArthur** [comment]
Closing unless we here otherwise that this is an issue.
