### ISSUE TITLE
Consider use of Internet Archive's Fatcat for metadata & OA urls

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1707]
**Is your feature request related to a problem? Please describe.**

We want more metadata. Also, we want to be able to direct people to versions of Open Access articles that aren't on websites that'll track them. Fatcat may help with both.

**Describe the solution you'd like**

We should evaluate if the service can help with these. For this we could take 1000 articles at random and compare in a sheet with our current vs fatcat. 

I think we should also speak to them, as at the moment it's apparently only used internally at the archive.

**Comment by markmacgillivray** [comment]
I did some more exploring of this. We would need to talk to them, yeah. Right now the search API is the ES endpoint exposed to GET requests, which is great in terms of usability. But the docs do say that is just a trial and may change later. Sometimes search capability gets annoyingly restricted later, so we would need to know how much search capability is going to stay, and how much layers of hassle may get added to it, if any. 

Fatcat records are editable by anyone, it is a wiki for managing metadata. I don't mind that, I think it's good, and it's how I would develop my own catalogue if I was doing so. But sometimes that open approach is not acceptable so certain projects or customers, so we would need to keep that in mind.

There are about 150m records in what looks like their current index. About 140m have DOIs. I haven't looked to see what they all are yet. All or almost all have what look like publication year (release_year), and about 54m have what look like publication dates (release_date). About 13m have wikidata QIDs. Our wikidata has about 67m records, and about 22m of them have DOIs, but they have not been carefully vetted.

They include an is_oa flag in records, as we do. About 24m come back as OA.

The search API responses are reasonably fast, about what I'd expect from a single-node cluster, which it appears to be. I haven't tried running any larger difficult facet queries on it, but we don't really need those anyway.

As you say, we could test a 1000 or so queries of things in our catalogue against theirs, and see how it compares.

In terms of comparison to what we do, it's similar to how I have done it as well - a large index, aggregate into it, and then make it all easily queryable. For the speeds we want to achieve, we may still have to run our own local copy or our own local cache of query results, even if we do use theirs as the authoritative source.

So whether or not we do use it would come down to questions we could ask them about intent rather than technicality:

* what sources are they using, how often do they update from them, and what is their commitment to continue doing so?

* what level of query capability is likely to continue to be available?

* what level of complexity would be acceptable in queries we send, if we can still send full ES queries?

* what rate limiting, if any, is or may be imposed? And could there be costs to high usage?

* what is their uptime aim for the index? Is it considered core or secondary? If it goes down, how soon could we expect it to come back up? Will robustness be added with additional nodes in the ES cluster? (I don't mind if not, just wondering)

* do they want contributions back from us if we have new records or additions to the metadata? e.g. particularly when we receive deposits it could be worth noting that in their metadata too. The API has auth and write ability to those who have a login, so this isn't about technical possibility, it's about how they want us to interact with them.

**Comment by markmacgillivray** [comment]
Oh also the docs say nothing can be depended on at the moment, so we'd also need to know if there is any mechanism to notify us of upcoming changes or do we just keep reading their web page. We can test for changes when they happen, but advance warning would be handy, especially if it's something major like not exposing the ES endpoint any more. 

If a future decision was as drastic as not exposing ES, we'd need to know we can get a dump of all the data before they make such a change, so that we could go back to just putting it in our own index. If we're running our own local copy anyway this isn't such a big deal, but if we can rely in forewarning from them then we could reduce the duplication of effort until it becomes necessary by future divergence of goals.

**Comment by markmacgillivray** [comment]
It doesn't look like we could expect fatcat to have a higher degree of metadata coverage than we do, so switching to it wouldn't be for an increase in coverage, it would just be to reduce duplication of effort if they're committing to it anyway, and possibly to contribute. For example, we know that not all records have all relevant ISSNs, and a quick look leads me to guess that's the case with fatcat records too. So we've already started adding all ISSNs to records where there is only one. If we start using fatcat, could we keep doing this kind of work and contribute it back to them? If we need to do it anyway (which we do), but we can only keep it ourselves locally, then using fatcat doesn't give us any benefit but adds a possible point of failure. In that case we could use fatcat as a source, but would definitely still want to keep having our own improved content locally.

Actually I'd say that's probably our answer, the following are our two options: 

* if we talk to fatcat and they do want external users of our type, who want high degree of query access and can contribute back some useful additions to the metadata, and if they're committing to that longer term, then we should commit to using fatcat too and contributing metadata improvements that we run on our own infrastructure, to make fatcat the better and authoritative source of catalogue data, instead of duplicating that effort by having our own. In this case we would only cache locally for performance gains but we would not consider our local copies to be the main resource.

* otherwise we continue with our own local one, and continue our own improvements to it, but we add fatcat as a source that we use to find article metadata as our starting points. A quick test of their coverage compared to what we already have, and some more info about the sources they use and how often they update from them, may enable us to simplify our own ingest stages to just be an ingest from fatcat. In this case we wouldn't be contributing/collaborating so much with their catalogue, just using it as one of our own (or our only) ingest starting points.

Either would be good for us.

**Comment by markmacgillivray** [comment]
Their coverage notes indicate similar sources to what we already use, so fatcat can be a handy way for us to get all of those instead of continuing to do them separately ourselves:

https://fatcat.wiki/about

And the following page says the "intent" is continuous ingest:

https://guide.fatcat.wiki/sources.html

Would need to know if that IS the case, and what granularity is "continuous".

Looks like the guide stuff is quite old, would be good to know if anyone is still actively working on fatcat.

ES isn't their core datasource (I didn't think it was, just confirming) - it goes into postgres first. Would need to know that they intend to continue providing an ES endpoint, or a regular data dump that we can just index ourselves. 

There is mention in their guide/roadmap of plans to have rdf/json-ld, OAI, etc, but in the end I am still of the opinion that none of these things are as useful as dumping everything into ES and querying it directly, then building queries to expose it in whatever form is needed. So we'd definitely still need an ES endpoint, and my recent searches for something better than ES still indicate that there isn't anything.

Also, as we know, paying anyone to run ES as a service is wildly expensive, so just as well we can do it ourselves! This does mean though that it would be hard to pay fatcat for an ES service if it is not something they intend to continue supporting, because it is highly unlikely to be cheaper or better than just continuing to have our own. So if ES is not going to remain on their roadmap then I'd say we want a regular data dump from them and run our own ES, and if they like, we could give them some sort of data dump back, like with more ISSNs per record, or info about the deposits we've received for articles.

**Comment by markmacgillivray** [comment]
And what is their definition of is_oa? Is it like DOAJ or unpaywall, or different from both?

**Comment by JosephMcArthur** [comment]
@markmacgillivray in the end did you activate this as a use route our API can call?

**Comment by markmacgillivray** [comment]
I did but it didn't gain us further solutions for what we need, so it's probably not worth integrating more fully with it.

**Comment by JosephMcArthur** [comment]
makes sense. We'll just consider the nice and private OA urls part of this then.

**Comment by markmacgillivray** [comment]
I don't know what that means.

**Comment by JosephMcArthur** [comment]
The archive has picked up a bunch of papers that are OA and started hosting them. This means the papers are: 1) certainly there 2) have a consistent & fast & nice UI 3) have no trackers. Those three things alone would be nice, but together they're great and I'd like to explore having our find system point at them instead of the ones hosted by publishers / repos.

**Comment by markmacgillivray** [comment]
Well we can certainly still add fatcat as a source that we try to query, we just need to consider that in the overall thoughts on what to query, what to cache, what to combine, etc. This is related to the OCLC thing, and comes back to my concern about just deploying a quick script to cache crossref. I think some more forethought may be of value here, or else we end up wedging things in without an idea up front if we're going to need parallel checks, merging of metadata, etc, etc.

**Comment by JosephMcArthur** [comment]
Feel free to hit pause on the crossref cache work if you think it's worth thinking about more. Can keep talking about this next week / over issues in other places.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
I think we can review and close this too, bringing into the current milestone to discuss at next meeting.

**Comment by markmacgillivray** [comment]
Closing this one as we've made the progress on the new system and there's an issue there to track the decision on how we use what we've built.
