### ISSUE TITLE
Deciding new frontend infrastructure

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1715]
As we build our the site for our new brand, we have a chance to lay down / test the first pillars of our new frontend infrastructure.

By frontend infrastructure, I mean everything from how the site is built, to how it's hosted, where code is, what languages are used etc. I also mean our website, not our embeds.

Here's what I think we're all aligned on:

* No bootstrap. Use Flexbox.
* No jQuery (plain Javascript)
* No Google Analytics
* We'll keep them all simple and static
* Jekyll for our site builder
* Gfonts to load Inter
* Overhauling all our CSS and on page styling

Here's what I think we're pretty aligned on, but haven't discussed as a group:

* Sophy can use her CSS system.

For this, I'd like to understand a little bit more what the implications of this are (I'm not so familiar with a post-bootstrap world)

* We have one repo (based on a template) per-site on Github, and manage them separately. While this is slightly inefficient it'll keep the codebases standard and simple. This will make documentation / set up really easy.
* We'll move login to be 'per-site' (aka you won't need to go to openaccessbutton.org/instantill/setup to do login)

The places I think we need to make a decision / have a discussion:

* Netlify vs CF workers

While the above is ostensibly a hosting decision they both some with fairly logical ways to then handle CI / CD... so making that call allows us to make the next calls. With either... I think we want avoid Codeship and likely use Github Actions #1616. 

| Netlify | CF Workers Site |
|---------|-----------------|
|Pro: S&I know how to use it        |Pro: Aligns with other infrastructure                 |
|Pro: Lots of nice CI / CD built in|Con: likely $$$ for each domain (@markmacgillivray... would it be $25 a month for each?) |
|Pro: Free|Pro: massive huge network|
|Con: Doesn't play nice with cloudflare. <br/>Pro: Still has a CDN behind it (just smaller)|Con: may need Mark's help setting up|
|same: once set up, life is easy|same: once set up, life is easy|
|pro: nice things like a/b testing and branch previews are built in for free|pro: server side analytics built in & free|
|pro: built in ally and performance checks are dope||
|add your| thoughts here|
|||

Sophy, one fun experiment might be using CF workers to try and build / host the SPARC infrastructure site. Since that's on Netlify and built in a very similar fashion to how we might do it here, that could be a good way to get a feel. Or, considering we know Netlify well we could try CF workers here, see how it goes, and retreat to netlify we don't like it. Anyway... just throwing stuff out there. Mostly, what I'd like to avoid is having worked so hard to make the API performant our static sites are slower simply as the network for them isn't so big. 

A read I've found helpful:https://brianli.com/migrating-from-netlify-to-cloudflare-workers-sites-for-2x-performance/

* I'd like us to support webp for images / mp4 for videos but don't understand the implications of doing it 🙃
* How will we handle forms on these sites (right now I don't love how we currently do forms, e.g bug forms)? Something that goes easily into sheet & gives email notifications would be better.
* For the embed code, should these be separate repos too? That feels sensible in some way.

Eventually, we'll have the follow sites running this same recipe:

* New brand 🤫
* Openaccessbutton.org
* InstantILL.org
* Shareyourpaper.org
* RSCVD.org

Of course, moving these all may take a while, which is cool.

The pay off to this new infrastructure should be:

* Faster loads (mainly due to lowered dependencies, webp for images)
* More private as no more g analytics
* Better SEO on new services
* Easy to spin up and build new sites in our infrastructure
* Lower server load (and generally more resiliency) 
* Building / maintaining should be easier, as styles will be more organized
* Users will have a nicer login flow

That was my attempt at pulling together the state of things. Some questions:

* Are there things I'm missing from the lists above?
* Shall we have a call?
* I think `Netlify vs CF workers` is the first thing we need to have a clear heading on at this stage. Do either of you have a strong opinion?

cc: @sssoz @markmacgillivray

**Comment by markmacgillivray** [comment]
I don't know anything about netlify to have an opinion on it, but I'd question what it is doing for you if you already plan to use something like jekyll. Is netlify just the deployment environment? If so the difference between that and CF workers is probably negligible, and it would be best to choose what is preferred by whoever has to use it most - I'd guess that will be Sophy. Spending a lot of time using something you're not comfortable with is not worth it long term, I don't think.

Yes we should stop using codeship - it's not hard to do with actions, we just have to prioritise that work, and we should.

Note, deploying static sites on netlify or CF workers will have virtually no effect on server load, so don't use that as a decision metric. The load to serve our current static sites is negligible anyway, so it really makes no difference. The load on our servers comes from the API code. 

Login is already possible across different sites, so that's not really a metric for this decision either - it can already be done, and can be done regardless of what frontend infrastructure we use. As long as the frontend is independent of the backend and queries using js to the API - which all the solutions we're considering would have to do anyway - then it makes little difference what frontend stack we use.

Deploying a site to CF workers looks simple, and I don't think would cost much - it's $25 per pro site, but it's not clear to me that we'd need that. There are also a free amount of workers allowed, but using KV (on the unlimited plan) has a $5 cost and I think that is necessary for CF sites. It's not clear yet if that has to be per domain or if a domain can point to the worker on a pre-existing $5 plan, in which case we're already covered. So at most it's possibly $5 per site, but possibly no extra cost per site.

However if deploying to CF workers is likely to require help from me, then netlify is probably the best option. I have no problem with helping out, but it seems like in this case if netlify already does what we need, is free, and can already be used by Sophy, then picking a solution that requires two people instead of the solution that requires one person seems like quite a big extra cost in terms of effort from us to use.

I think the speed gains from CF workers sites vs netlify are so small that on sites with our level of load, it's not important - I doubt a human will notice the difference, especially after first page load (which they only do once). But Joe likes things to be as fast as possible all the time, so in that case yes CF workers will be faster.

If Sophy already knows netlify, and it's free, there seems no downside to starting with that and moving to workers later if we feel like it.

No bootstrap and no jquery is totally possible, but remember the reason they are so popular is because they make a lot of very mundane work much simpler and less time consuming. If you already know lots about css and plain js, then yes it's not too hard to code up specifically what you need. If Sophy is happy doing that it's certainly fine with me too - but if you're new to js, it's a lot more hassle to use plain js than to use jquery. And again, the initial load time delay of getting jquery only occurs on the first load, and only for users who didn't already have it served to them by the same CDN (if we choose to serve it from a CDN). Also, depending on how we choose to bundle things, the jquery dependency very rarely has to upgrade, so even if you change our own js a lot, the same jquery file can be served to users across many releases of our site. So don't get carried away hoping that you're going to save tons of load time for millions of users just by dropping jquery and/or bootstrap. If the simplifications they provide feel worthwhile, I'd recommend using them. Of course it doesn't have to be bootstrap specifically - whatever CSS framework you're happy with fills most of the same functions. If Sophy already has one that she made / likes to use, it seems a good idea that we use the one she is most used to.

Whether you have one repo per site or not has pros and cons either way, I think again go with whatever is best for who has to use it the most here. About separate repos for the embeds - yes that's possible, it would depend on who is having to maintain them and how they are going to be deployed. The embeds need to be served with the site, so as long as you're able to make netlify (or whatever we use) also get the embed code when it deploys the site, then it doesn't matter what repo they are in. But if the deployment mechanism can't handle that then it's probably easier if they are in the same repo. When we used to do more with the browser plugins they also had shared dependencies with js used in the embeds, so it was better for them to be in the same repo back then, but that doesn't matter much any more as the embeds are now running on a new library.

**Comment by JosephMcArthur** [comment]
Thanks Mark! Super helpful :D

**Comment by sssoz** [comment]
> Here's what I think we're all aligned on:
> 
> * No bootstrap. Use Flexbox.
> * No jQuery (plain Javascript)
> * No Google Analytics
> * We'll keep them all simple and static
> * Jekyll for our site builder
> * Gfonts to load Inter
> * Overhauling all our CSS and on page styling
> 
> Here's what I think we're pretty aligned on, but haven't discussed as a group:
> 
> * Sophy can use her CSS system.

I wouldn’t call it a full-on CSS system; as in, it’s not a framework like Tailwind or Bootstrap or even any basic pre-made CSS minimal system. It’s just my preferred nomenclature for CSS (BEM, but I am flexible with that) and using modern / cross-browser-compatible CSS (e.g. favouring CSS flexbox over CSS grid for now, having fallbacks always ready). I do still use normalize.css, of course, to make sure that all stylesheets are applied somewhat evenly across browsers. 

Bootstrap, even if BS 4 one uses flexbox, is much too heavy for our needs and most people just end up overriding all the default styles (which look pretty outdated out-of-the-box); this might not necessarily affect performance but will affect maintainability, add unnecessary complexity to classes used in the markup, and possibly contribute to design debt. BS 3 used to allow custom installs, where users could select specific Boostrap components they wanted, but it no longer allows that. Either way, BS class-naming is not BEM and just makes styling very confusing. I favour not using any CSS framework, especially for something like our new website or our embeds, and to keep styling very simple. We can do a lot with very few lines of CSS & some inlined SVG nowadays. 

Any UI-related JS we might need (e.g. for creating modals, tabs, accordions, menus, scroll effects), we could do on our own & generally keep to a minimum (or get individual JS libraries for those).  

On the subject of UI-related JS: I do agree with @markmacgillivray that jQuery is extremely handy for "Javascript  shortcuts". If performance is not an issue (or, on the contrary, if it’s actually a good thing since most users might have already loaded it from navigating other sites), then I’m also happy to continue using it, as long as we keep our JS as clean as possible & all in one place. 

> For this, I'd like to understand a little bit more what the implications of this are (I'm not so familiar with a post-bootstrap world)
>
> * We have one repo (based on a template) per-site on Github, and manage them separately. While this is slightly inefficient it'll keep the codebases standard and simple. This will make documentation / set up really easy.

Agreed with this approach; we can also update the base template and push the changes to all repos using that base template. This is sort of the beginning of a design system as well, with reusable CSS components. For example, if we decide to base all apps (OAButton, InstantILL, SYP, Permissions etc) on the same template, we can set up the stylesheets using variables to input one base colour & logo that will be applied uniformly for each app.  

> * We'll move login to be 'per-site' (aka you won't need to go to openaccessbutton.org/instantill/setup to do login)

I don’t have any particular knowledge on how to set up authentification so I’ll defer to @markmacgillivray on this. 

> The places I think we need to make a decision / have a discussion:
> 
> * Netlify vs CF workers
> 
> While the above is ostensibly a hosting decision they both some with fairly logical ways to then handle CI / CD... so making that call allows us to make the next calls. With either... I think we want avoid Codeship and likely use Github Actions #1669 

Using Netlify isn’t a requirement for me, neither is Jekyll for that matter; I’m happy to learn something new, as long as it plays nicely with a static generator. I know Hugo has better plugins and handles i18n better but has a steeper learning curve and its templating engine (Go’s template library) is not as intuitive as Moustache/Handlebars/Liquid or Django’s templating engine. Not sure about Gatsy, but it also looks interesting.

I can make a list of requirements for a static site generator and perhaps we could start from there for that choice. 

> Sophy, one fun experiment might be using CF workers to try and build / host the SPARC infrastructure site. Since that's on Netlify and built in a very similar fashion to how we might do it here, that could be a good way to get a feel. Or, considering we know Netlify well we could try CF workers here, see how it goes, and retreat to netlify we don't like it. Anyway... just throwing stuff out there. Mostly, what I'd like to avoid is having worked so hard to make the API performant our static sites are slower simply as the network for them isn't so big.

That’s not a bad idea. I’ve already set up SPARC’s Negotiations site with Netlify + NetlifyCMS, but it’s still early on in the project so I could also try CF Workers. I looked at it, but didn’t have much time to delve deeper into it (not enough to deploy anything anyway haha). 
 
> A read I've found helpful:https://brianli.com/migrating-from-netlify-to-cloudflare-workers-sites-for-2x-performance/
> 
> * I'd like us to support webp for images / mp4 for videos but don't understand the implications of doing it 🙃

That would be cool, especially since we don’t have user-input images on any of the apps, but not sure how realistic for now. Not all major browsers [fully support WEBP yet](https://www.caniuse.com/webp). 

> * How will we handle forms on these sites (right now I don't love how we currently do forms, e.g bug forms)? Something that goes easily into sheet & gives email notifications would be better.

HTML forms that populate a Google Sheet are fairly easy to do with some scripts you can find on StackOverflow etc!  

> * For the embed code, should these be separate repos too? That feels sensible in some way.

Also not sure about this. 

> Eventually, we'll have the follow sites running this same recipe:
> 
> * New brand 🤫
> * Openaccessbutton.org
> * InstantILL.org
> * Shareyourpaper.org
> * RSCVD.org
> 
> Of course, moving these all may take a while, which is cool.
> 
> The pay off to this new infrastructure should be:
> 
> * Faster loads (mainly due to lowered dependencies, webp for images)
> * More private as no more g analytics
> * Better SEO on new services
> * Easy to spin up and build new sites in our infrastructure
> * Lower server load (and generally more resiliency)
> * Building / maintaining should be easier, as styles will be more organized
> * Users will have a nicer login flow
> 
> That was my attempt at pulling together the state of things. Some questions:
> 
> * Are there things I'm missing from the lists above?

(Mentioned earlier) requirements for a static site generator: what do we want it to do or be able to do? 

> * Shall we have a call?
> * I think `Netlify vs CF workers` is the first thing we need to have a clear heading on at this stage. Do either of you have a strong opinion?
> 
> cc: @sssoz @markmacgillivray

**Comment by markmacgillivray** [comment]
Just to confirm, I'm totally OK with us not using bootstrap or jquery, I was just making the points in their defence :) so that we consider all the options. I agree that it's easy enough to just write the css and js we need, and that's what I would do too.

We already have code in the API that can receive responses from forms and dump them into sheets, so we don't even need to go hunting to find ways to do that, we already have it. For example rscvd is already doing that. When we get to the point of having any forms you want to do that with, all we have to do is co-ordinate a little bit to use some UI-side JS, like there is on rscvd, to send the form content to a particular API endpoint, and to know which sheet that data should be sent to.

I also don't mind which site generator is used - jekyll, hugo, etc, all pretty similar, I agree it's a good idea to list up the requirements and just make sure the one we pick meets those requirements. There are places in the UI templates where you'll need to be able to set variables that the site generator will fill in, for things like the API URL, because the URL is different depending on if you're building for dev or live. So a site generator that can have different configs for different envs is a good idea, but I'm pretty sure most of them could handle that nowadays.

**Comment by sssoz** [comment]
> I don't know anything about netlify to have an opinion on it, but I'd question what it is doing for you if you already plan to use something like jekyll. Is netlify just the deployment environment? If so the difference between that and CF workers is probably negligible, and it would be best to choose what is preferred by whoever has to use it most - I'd guess that will be Sophy. Spending a lot of time using something you're not comfortable with is not worth it long term, I don't think.
>
> Yes we should stop using codeship - it's not hard to do with actions, we just have to prioritise that work, and we should.
> 
> Note, deploying static sites on netlify or CF workers will have virtually no effect on server load, so don't use that as a decision metric. The load to serve our current static sites is negligible anyway, so it really makes no difference. The load on our servers comes from the API code.

I think Jekyll (the static site generator) works fine with CF Workers. I haven’t tried it at all, but from what I’ve read, it deploys its properly. For comparison, I found that Netlify was better than Github Pages for deploying Jekyll sites because it worked well with plugins. Both support Jekyll though, and setup is very minimal: you just need to tell them both which branch you want to deploy and it does the rest for you (compiling stylesheets, javascript, HTML templates). 

> Login is already possible across different sites, so that's not really a metric for this decision either - it can already be done, and can be done regardless of what frontend infrastructure we use. As long as the frontend is independent of the backend and queries using js to the API - which all the solutions we're considering would have to do anyway - then it makes little difference what frontend stack we use.
> 
> Deploying a site to CF workers looks simple, and I don't think would cost much - it's $25 per pro site, but it's not clear to me that we'd need that. There are also a free amount of workers allowed, but using KV (on the unlimited plan) has a $5 cost and I think that is necessary for CF sites. It's not clear yet if that has to be per domain or if a domain can point to the worker on a pre-existing $5 plan, in which case we're already covered. So at most it's possibly $5 per site, but possibly no extra cost per site.
> 
> However if deploying to CF workers is likely to require help from me, then netlify is probably the best option. I have no problem with helping out, but it seems like in this case if netlify already does what we need, is free, and can already be used by Sophy, then picking a solution that requires two people instead of the solution that requires one person seems like quite a big extra cost in terms of effort from us to use.
> 
> I think the speed gains from CF workers sites vs netlify are so small that on sites with our level of load, it's not important - I doubt a human will notice the difference, especially after first page load (which they only do once). But Joe likes things to be as fast as possible all the time, so in that case yes CF workers will be faster.

🏎💨

> If Sophy already knows netlify, and it's free, there seems no downside to starting with that and moving to workers later if we feel like it.

I’d be okay with this approach too! Especially for the new website, which won’t rely on any user input & won’t need a proper database (it’s a promotional tool more than anything). 

> No bootstrap and no jquery is totally possible, but remember the reason they are so popular is because they make a lot of very mundane work much simpler and less time consuming. If you already know lots about css and plain js, then yes it's not too hard to code up specifically what you need. If Sophy is happy doing that it's certainly fine with me too - but if you're new to js, it's a lot more hassle to use plain js than to use jquery. And again, the initial load time delay of getting jquery only occurs on the first load, and only for users who didn't already have it served to them by the same CDN (if we choose to serve it from a CDN). Also, depending on how we choose to bundle things, the jquery dependency very rarely has to upgrade, so even if you change our own js a lot, the same jquery file can be served to users across many releases of our site. So don't get carried away hoping that you're going to save tons of load time for millions of users just by dropping jquery and/or bootstrap. If the simplifications they provide feel worthwhile, I'd recommend using them. Of course it doesn't have to be bootstrap specifically - whatever CSS framework you're happy with fills most of the same functions. If Sophy already has one that she made / likes to use, it seems a good idea that we use the one she is most used to.

(Commented on that in my previous note). 

Though: I think it would be good to learn vanilla JS, perhaps slowly replace jQuery with it! 

> Whether you have one repo per site or not has pros and cons either way, I think again go with whatever is best for who has to use it the most here. About separate repos for the embeds - yes that's possible, it would depend on who is having to maintain them and how they are going to be deployed. The embeds need to be served with the site, so as long as you're able to make netlify (or whatever we use) also get the embed code when it deploys the site, then it doesn't matter what repo they are in. But if the deployment mechanism can't handle that then it's probably easier if they are in the same repo. When we used to do more with the browser plugins they also had shared dependencies with js used in the embeds, so it was better for them to be in the same repo back then, but that doesn't matter much any more as the embeds are now running on a new library.

**Comment by JosephMcArthur** [comment]
Thanks so much for all the careful thoughts folks.

I personally agree with the vast majority of what's been said. A few points that have stood out:

* Mark, your point about having our infrastructure here needing as few a people to maintain as possible seems wise. That's a point in Netlify's corner I think.
* I appreciated the balance ya'll brought to my `no jquery` starting point. I likely misrepresented how we felt about that in drafting tbh.
* Much hunch from using Jekyll is that it'll more than meet our requirements for a generator. Having peaked at Hugo / Gatsby I'm not sure their USPs (hugo: quick build of big sites & Gatsby: built in PWA) feel all that important and both will need to be learned I think.
* The forms system we use for RSCVD is likely fine as a starting point. Probably best just to give it a bit more TLC before we use it for everything.
* Sophy, your CSS approach sounds great, thanks for explaining.
* I continue to be too obsessed with speed through a very narrow lens and appreciate people talking me down 😉
* That my opinion is much less important than the person who'll do most the work here: Sophy 👀

My hunch is that jekyll + netlify will be amazing (sophy, you showing me that was a life changing moment), and from there the jump to cf workers will be smallish if we decide to make it.

@sssoz shall we discuss how you want to proceed with this chat tomorrow in our call?

**Comment by sssoz** [comment]
@JosephMcArthur @markmacgillivray Yes, thank you both for these thoughts. I think we’re, generally, in agreement. 

Let’s talk about it tomorrow!

**Comment by JosephMcArthur** [comment]
Chatted with Sophy about this. Generally we felt like all had broad alignment, and certainly good enough to let her decide what makes sense to move ahead with.

Moving this into a future milestone for now.

**Comment by sssoz** [comment]
This article seems pretty relevant to this issue: [Building Micro Frontends
](https://www.telerik.com/blogs/building-micro-frontends). I think this aligns perfectly with what OAB is already doing and what we’re planning on doing with the rebrand project.

**Comment by JosephMcArthur** [comment]
This seems relevant: https://wicki.io/posts/2020-11-goodbye-google-fonts/ and worth considering.

**Comment by sssoz** [comment]
@JosephMcArthur I never really liked Google Fonts -- it’s an attempt at monopolising free & open source fonts on their  own platforms.

Another thing -- not exactly on performance & font-loading: there are plenty of talented type foundries and typeface designers that don’t distribute on Google Fonts. There are many poor-quality typefaces on there, so if you’re just looking to get a free typeface but don’t have time to thoroughly examine them, you might end up with something sub-optimal. Thankfully, many people also compile and curate nicer ones, and many foundries offer good-quality typefaces for much cheaper (I’m all for paying for that kind of work!). For example: 

- https://freefaces.gallery/ 
- https://open-foundry.com/
- https://www.bnicks.com/shop
