### ISSUE TITLE
wrong article form doesn't appear to be working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1718]
**Describe the bug**

When completing the wrong article form on InstantILL:
* if you don't complete a required field it should tell you to do that. It doesn't right now.
* if you give the required information, it should accept it. It isn't doing that atm.

**To Reproduce**

* enter `Pre‐Black Futures` as the title
* when you see the wrong form, attempt to submit
* it'll not do anything
* fill in the info: `2010`, `Antipode `
* it'll not do anything

**Expected behavior**

As above.

**Proposed Fix (if available)**

If this is because the title is too short, we should allow titles that short if they come through that form.

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [x] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [x] How can we avoid bugs like this in future?
- [x] How can we avoid regressions (e.g automated test)

A test for this is needed

- [x] let CJ know

**Comment by markmacgillivray** [comment]
This has been fixed, you can see it on dev instantill demo now. Yes it was because the title was too short, so every time you try to click the button and the title is still too short, it just takes you back to that page and it didn't even show the "complete required fields" msg because the title was still too short. We'd previously discussed this and decided not to accept short titles here because we're unlikely to successfully match them anyway, I think, and even with the extra metadata we still don't, but I've added a catch now so that if the title is too short and we still don't find it, the loop works as expected and you see the "complete required fields" msg and the button does finally re-run the search once the required fields are submitted, and even with a still-too-short title. Then you end up back on a result page that shows we couldn't find it, but where you can ask for a copy to be sent, or whatever else is configured to happen next.

**Comment by JosephMcArthur** [comment]
This looks good. Keeping open to add tests etc.

With our new crossref search ability, is it possible to send the title, publication year, and journal name together and have each of these taken into account in the result given back? Just thinking that we currently don't search due to the chance of false positives, but with those extra bits of information we'd likely be able to avoid that. Potentially a good improvement to make later (or now, if it happens to be easy and we've just not thought of it yet!)

**Comment by JosephMcArthur** [comment]
I've bumped this issue to next weeks sprint now, as the urgent part is addressed.

Still want to add tests, consider the below:

> With our new crossref search ability, is it possible to send the title, publication year, and journal name together and have each of these taken into account in the result given back? Just thinking that we currently don't search due to the chance of false positives, but with those extra bits of information we'd likely be able to avoid that. Potentially a good improvement to make later (or now, if it happens to be easy and we've just not thought of it yet!)

**Comment by JosephMcArthur** [comment]
Test added here: https://app.ghostinspector.com/tests/5fb158bb5f99e6612fea6216

**Comment by JosephMcArthur** [comment]
> I've bumped this issue to next weeks sprint now, as the urgent part is addressed.
> 
> Still want to add tests, consider the below:
> 
> > With our new crossref search ability, is it possible to send the title, publication year, and journal name together and have each of these taken into account in the result given back? Just thinking that we currently don't search due to the chance of false positives, but with those extra bits of information we'd likely be able to avoid that. Potentially a good improvement to make later (or now, if it happens to be easy and we've just not thought of it yet!)

Tests added. Moved this improvement to new issue.
