### ISSUE TITLE
deposited endpoint not showing non-file deposits (e.g redeposits)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1722]
**Describe the bug**

When our partner our Montana clicks [`All deposits`](https://dev.openaccessbutton.org/shareyourpaper/setup#bulk-upload) they only get their file deposits.

**To Reproduce**

Their id is `7jRfodNZoENFYrvZB`. 

Hitting https://openaccessbutton.org/deposited.csv?uid=7jRfodNZoENFYrvZB` should allow you to reproduce the issue. You'll see files deposits but won't get various OA redeposits like:

* OA Redeposit: 10.1002/ece3.5752
* OA Redeposit: 10.1093/ee/nvaa009
* OA Redeposit: 10.1073/pnas.1915006117
* OA Redeposit: 10.1177/1557988320913387
* OA Redeposit: 10.20900/jsr20200011

and others.

**Expected behavior**

They should get those non-file deposits like the above

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.

`good`

- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)

**Comment by JosephMcArthur** [comment]
Was just looking on our API for some bits, and found that for:

`https://openaccessbutton.org/deposited.csv?uid=7jRfodNZoENFYrvZB`

when I added my API key, e.g

`https://openaccessbutton.org/deposited.csv?uid=7jRfodNZoENFYrvZB&apikey=blahblah`

- [ ] I didn't get any response back. Is that expected?

On the API docs page we provide that route with the apikey it in (and not actually the UID).

Also, on my account, when I look for deposits on the frontpage SYP I don't get any, which I'd like to check... but maybe that's related to the above.

**Comment by markmacgillivray** [comment]
Should work now on dev, I tried with mine and it is fine. We had a deposited and a deposits endpoint but the UI code hadn't been updated with both. Also for when you go to the deposits/deposited endpoint you don't need an apikey, no. If you do provide one, and it is one for a real account on that system, then it should still work. Note though the example URLs you have above are not to the API, they are to the UI. Have a try again with the API URL (on dev) and let me know if you still have the problem.

**Comment by markmacgillivray** [comment]
This is now on live too. Close unless you want to follow up with them, then close.

**Comment by JosephMcArthur** [comment]
This is better, but not all the way fixed it seems.

A note from Leila:

> there are some duplicates. However, the info that is here is what we need for deposit. And, there are almost all of the articles we think should be in the spreadsheet represented. These articles are articles that we think we should have but are "missing":
> 
> https://dx.doi.org/10.1016/j.coldregions.2020.102994
> https://doi.org/10.1007/s11069-020-04104-7
> 10.1016/j.ejor.2020.03.077
> 10.1016/j.mimet.2019.105694
> 10.1126/science.196.4287.293

Can you take a peak at this Mark?

**Comment by JosephMcArthur** [comment]
Here, fwiw, is the file they got: https://drive.google.com/file/d/1-xbOBkOTcwTpOqMFXUmeuy3RSbdH5b9f/view?usp=sharing.

**Comment by markmacgillivray** [comment]
I had a look but can't really work out what it is you're expecting it to deliver. Deposits at the moment is a value added to catalogue records, stating that some deposit event occurred upon it. However we sometimes delete the catalogue altogether, and anything before end of April 2020 is not there any more. So for what period is it expected that this deposits sheet should go back to? For those DOIs that are listed above as being something they think they should have but are missing, what does that mean? In what way should they have them? Does it mean a deposit was performed since April that they expect to see in the sheet? Or does it mean they expect to "have" it in their library? The first two DOIs appear to redirect to another which is in the sheet, although it's not clear why they do that. The third one is in the catalogue, created on 7th October, but has no deposits recorded against it. The 4th was created on 8th July and has no deposits on it. The 5th is our demo DOI and has many review deposits recorded against it, but none for a specific user account.

It would probably be a good idea to review the requirements for these deposit logs and clarify them here before I rewrite deposit in the new CF workers codebase.

**Comment by JosephMcArthur** [comment]
> It would probably be a good idea to review the requirements for these deposit logs and clarify them here before I rewrite deposit in the new CF workers codebase.

When do you need this by, and would it be helpful to discuss?

> So for what period is it expected that this deposits sheet should go back to?

I'd have expected this is be basically a permanent record. I.e something that we'd basically never delete. I remember that at some point we consciously deleted this before we really made it "production ready" to ensure consistent, which is fine. Moving forwards, do you expect we'd need to delete this data again.

Appreciate the walkthrough on what's happened with each of these deposits.
- [ ] I'll dig into those a bit more with Leila.

For the duplicates issue, is there an existing way to build a query that would give us a list an export of DOIs deposited (with the first time they were seen in this embed as the record used). That would be helpful where, in the case of something like `10.1080/00222933.2020.1733120` it is originally `zenodo` deposited and then it looks like people retry it later and it gets `forward` deposited or things like that. That can happen as right now the UI lets you do multiple deposits for the same DOI (which is really what we should fix...). But, before we do that, it would be nice to be able to provide a cleaner export.

**Comment by markmacgillivray** [comment]
No rush on it, yeah we should discuss, but after the holiday is probably best time. When we wiped the catalogue in April is probably the time we decided to keep things for "production". We still hadn't rewritten the deposit endpoint then, and still haven't fully (I think) so it still does some stuff that was originally based on the request system - such as recording deposits in the catalogue record, which is what the request system had used. The original request stuff is still in there too, although I don't think anything is using it.

As we are making big changes now to how we catalogue stuff, we would probably be best to make the record of deposits a separate record, rather than saving them into the catalogue records. We still never looked at the problem of requests coming in for things that we have since actually received in a deposit either, and it wouldn't take much to work that in, but depends what we decide to do about the long term future of requests.

Your last para is the sort of thing we should clarify as requirements for this - what exactly we are providing for users in this deposit export, are they expecting certain kinds of deposit record to take precedence over others, how does that relate to the fact that the UI does allow multiple deposits of the same thing (because we haven't yet included the knowledge of "already deposited" into find/request), etc. So we can review this at the start of next year.

**Comment by JosephMcArthur** [comment]
> No rush on it, yeah we should discuss, but after the holiday is probably best time.

Kay, I've gotten thinking about this on my list. Who knows, maybe I'll make a diagram...

> As we are making big changes now to how we catalogue stuff, we would probably be best to make the record of deposits a separate record, rather than saving them into the catalogue records.

This makes sense to me.

**Comment by JosephMcArthur** [comment]
Whoops, hit send a bit soon. Long story short, we can close this soon (I just need to feedback to Leila) and we'll pick up the thread in #1515.
