### ISSUE TITLE
expose schema for APIs at an endpoint for /metadata (and others?)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1753]
As discussed

**Comment by markmacgillivray** [comment]
This is done on dev, if you go to metadata/keys it lists all the keys in use in the metadata. Once we push to live it will list all the  live keys. If you're happy with this we can close, or docs info can be added too. Details:

This is NOT a schema. We don't use a schema. This is just all the keys we have dynamically indexed to date.

All key names are provided. NOT all records will have all keys. They're all pretty much optional and depend what we get from sources on different searches.

More keys may appear in future, so can't rely on this being a definitive list.

Some keys may be different but really mean the same sort of value, for example in authors there are various keys that the sources we search would use for author last name. We don't normalise these, because invariably if we do then there will be a request a few months later wanting to know what the original value was, and also the formats of the sources we use can change too. So instead we just write our code to handle all the possibilities we've seen to date.

Any key may point to any sort of value, and it could be a singular value or a list. If the key points to an object (or list of objects), it will have sub-keys shown as dot notation. E.g. reference.doi indicates that "reference" is an object containing the key "doi". It is also possible that it is a list of objects, so check for that as well if trying to iterate them all. If you've seen that a particular key contains a particular sort of value, it is very likely that it will always contain that sort of value in future. If it does ever change, it would be a change in type of value for every value under that key - there won't be different types of values in the same key names (apart from the possibility of them being lists of a certain type of value, or singular values of that type).

We don't guarantee the reliability of these keys, but we do try to keep the same names in use over a long period of time, e.g. years. But any use in code of these keys should be written in such a way as to handle the key possibly being missing, or containing an unexpected value.
