### ISSUE TITLE
`10.1016/S0099-1333(02)00284-7` not recognised as a DOI

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1758]
**Describe the bug**

`10.1016/S0099-1333(02)00284-7` is not recognized as a DOI, but it is.

**To Reproduce**

See:
* https://dev.lvatn.com/service/oab/p2/10.1016/S0099-1333(02)00284-7
* https://shareyourpaper.org/10.1016/S0099-1333(02)00284-7

**Expected behavior**

It should work as normal.

**Checklist (For internal use)**

* Take a breath. Bugs are okay.
* Stay clear of hangouts

Process checklist:
* Do we want a `fast` first, then a `good` fix? A `good` fix likely involves discussion, and may be slower. A fast fix means whoever is available fixes the problem as best they can immediately without too much consideration for the `good` fix.
- [ ] Discussion of solution. Remember, our intuitive fixes may be different (e.g UI centric, backend centric)

Post-fix
- [ ] How can we avoid bugs like this in future?
- [ ] How can we avoid regressions (e.g automated test)
- [ ] Update `Share Your Paper error -- not-right DOI?`

**Comment by markmacgillivray** [comment]
Actually it turns out this is not strictly a DOI. DOIs are case insensitive, but in the case of this one, crossref returns the DOI as being lowercase (I suspect it always does that). Since we use the crossref DOI as the ID, we don't get an exact match when the "wrong" case (e.g. not the one crossref says is actually the DOI) is provided to the system. I've put in a catch to our crossref DOI lookup now so that we lowercase them before searching them in our index. So this is fixed now.

Also this fits with our recent attempts to see if our crossref changes are making things faster - they are. On dev, this one was failing to be found in our index because the DOI did not match, so the system was returning nothing for it. I altered this to fall back to a crossref lookup if we don't exactly match the DOI, which causes a slower response but potentially a successful one in cases where the DOI is real but we just don't have it yet. Because this DOI was being found each time, and saved, but then not retrieved because of the case mismatch, I was able to check the load times each time, and then again after I fixed for the case issue. Crossref is returning direct DOI lookups (not searches) to their API in about 4 seconds at the moment, so we were taking about that as well. Now that we have it and can find it in the index, the response is about 400ms. I also checked the live log and no crossref lookups have occurred since we updated live at the weekend, so that means we're not (or rarely) having crossref-related delays now.
