### ISSUE TITLE
RSCVD form not submitting and throwing jquery error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1764]
**Describe the bug**

As above.

When I submit, in the console I see:

`jquery.min.js:2 An invalid form control with name='' is not focusable.`

![image](https://user-images.githubusercontent.com/4953703/102984511-9ad90900-4505-11eb-91c1-7186cb6610d1.png)

**To Reproduce**
1. Go to `https://rscvd.org/submit?where=InstantILL&atitle=Concurrent%20validity%20of%20noninvasive%20coccygeal%20motion%20palpation&url=https%3A%2F%2Fjournals.lww.com%2Fjwhpt%2FAbstract%2F2020%2F10000%2FConcurrent_Validity_of_Noninvasive_Coccygeal.6.aspx&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing`
2. Complete the form
3. Click on 'submit'
4. Wait
5. It won't submit

**Expected behavior**

It should submit.

From a UX standpoint, when it fail, I'd hope to see an error (but don't expect one right now).

**Additional context**

- [ ] I need to answer `Form not submitting` when shut

**Proposed Fix (if available)**
How might we fix this?

**Checklist (For internal use)**

**Comment by JosephMcArthur** [comment]
A quick reminder... the dev repo is here: https://github.com/JosephMcArthur/rscvd-dev

**Comment by JosephMcArthur** [comment]
I'm having some luck here.

I have managed to remove the error on dev, it was happening because hidden fields on the page weren't being populated. Unhiding those fixed the issue.

However, the fields *should* have been populated. And I can't figure out why that isn't happening.

**Comment by JosephMcArthur** [comment]
I've released my partial fix as I'm getting so many emails!

**Comment by markmacgillivray** [comment]
The example link you have above doesn't include a journal title as far as I can see. However your form DOES include a journal title input, and that input is required. When you had it hidden, the submit button could not submit because a required field was empty. So it tried to display the required prompt, but couldn't because the required field was hidden. That was the error you were getting - it can't focus the required field because it is not visible. Now that you've un-hidden them you don't get the error. But I can't help with where you're saying those fields "should" have been populated. How? From the example URL you give, I don't see how that could be possible.

**Comment by JosephMcArthur** [comment]
Hmmm, I'm having trouble replicating what I'm seeing now. I was seeing requests where the details were in the URL, but they weren't being passed into the form. I was seeing this even with DOIs and things like that.

Also, I have a concern about how someone got a URL of `https://rscvd.org/submit?where=InstantILL&atitle=Concurrent%20validity%20of%20noninvasive%20coccygeal%20motion%20palpation&url=https%3A%2F%2Fjournals.lww.com%2Fjwhpt%2FAbstract%2F2020%2F10000%2FConcurrent_Validity_of_Noninvasive_Coccygeal.6.aspx&notes=Subscription%20check%20done,%20found%20nothing.%20OA%20availability%20check%20done,%20found%20nothing` as it shouldn't be possible to get through to the submit page without a journal title. 

But, I can't replicate any of those right now... so... let me try that again and don't worry about this for now.
