### ISSUE TITLE
Permissions returning author names as copyright names even when responding for a whole journal

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1799]
Getting dejavu here, I swear this was addressed at some point.

See at `https://api.openaccessbutton.org/permissions?issn=1932-6203` has `copyright_name: "Laerke Smedegaard et al"`. 

When `copyright_owner: "authors"` we probably shouldn't give a value for `copyright_name` when it's not for a DOI.

**Comment by markmacgillivray** [comment]
Currently the system imports from whatever is in the sheet. If the sheet doesn't have a copyright_owner value, it uses the issuer type value instead. For the record in your example, it does have copyright_owner from the sheet, and the value is "authors".

The algorithm we have for deciding what to put in the copyright_name field is:

* if copyright_owner is publisher then if there's an issuer parent_policy use that value otherwise use the issuer ID
* else if copyright_owner is journal or affiliation use journal name from the metadata if available, or nothing
* else if copyright_owner has the word "author" in it (because it can be authors, authors in name only, etc) and there are author names available in the metadata then use the first author plus "et al" otherwise nothing.

So, yes, we do handle the case where the copyright_owner is for a whole journal, but NOT if you've explicitly set the copyright_owner to "authors" in the sheet. In that case, it's going to (reasonably, given the name of it, I'd think), use the author names as the copyright_name.

I can change it if you want, but that's the explanation for why it is how it is.

**Comment by JosephMcArthur** [comment]
When dealing with a whole journal, can we just report "author", or "authors in name only" in that field? I.e don't merge it to produce the name of an author (as, that author can't own the copyright for the whole journal!).
