### ISSUE TITLE
Permissions journal endpoint missing licence for PLOS journal

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1800]
Getting dejavu here, I swear this was addressed at some point.

JCT expects a license for `https://api.openaccessbutton.org/permissions?issn=1932-6203` but we're not providing one.

Is this a bug in a system we expect to work, or do we not expect it to work?

**Comment by markmacgillivray** [comment]
Fixed on new dev, can update new live. The issue came up again due to aforementioned changes we need to make to having a reliable index of journals - changes on JCT project mean we need to review the case for ourselves now. I've got a new issue for that on the new code repo and I'll get those reviewed and prioritised asap.
