### ISSUE TITLE
Output & Analyse key metrics

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#192]
Mark, we may need to chat about this one but I'll do my best here. 

You've seen the key metrics [document](https://docs.google.com/presentation/d/15hR80_kle9nxGDrJqvGVe6JoibDpZL-Oe6DQmCSU0BE/edit#slide=id.p) . Right now, we can ignore JISC service data. Our figures shouldn't take anything into account that's a test or not shown on our UI (i.e is a duplicate or a filtered site).  

The key metrics relevant here are on:
- Slide 15
- Slide 9
  but in addition to this, it would be good if we could have the user management page show stats on what state our users are in as on page 6. 

Eventually, we should do cohort analysis on our data. With that in mind, it would be useful to think about an implementation of this: http://bslatkin.github.io/cohorts/. It's open source and seems incredibly useful. 

At the end of this issue we should be able to:
- [x] Output, or be ready to output our key metrics awaiting data from the plugin
- [x] Explore those metrics over time
- [x] Have some understanding of how key metrics have changed before now. 

and, as a warning, I may try and suggest we get more numbers into the mix here too at a later date.

**Comment by JosephMcArthur** [comment]
Have made some semi-major changes to the document. It:

* Simplifies the user flow and user types. Major change is removal of the idea of "advocate" as a separate user type. Now, instead of a user just being someone with the plug a user is just someone using any part of the service. 
* Makes modeling easier
* Makes words like user, sign up etc mean closer to how they're used by others. 
* Updates for new sign up structure

#### OLD

<img width="927" alt="screen shot 2016-09-04 at 22 28 54" src="https://cloud.githubusercontent.com/assets/4953703/18234015/2cee47e4-72ef-11e6-8b9c-ac225b0df3f5.png">

#### NEW

<img width="924" alt="screen shot 2016-09-04 at 22 29 00" src="https://cloud.githubusercontent.com/assets/4953703/18234014/2cebc3fc-72ef-11e6-91b7-36b3b311adca.png">

Next steps are 

- [ ] Fix glossary on backend
- [ ] Finish Model

**Comment by markmacgillivray** [comment]
The number of sign-ups we have (that's the same as total emails from the whole system)
The number of users we have (emails which we know downloaded the app)
The number of active users we have (people who've logged a block in the past month)
The number of inactive users we have (people who've logged a block it in the past 1-3 months)
the number of former users we have (people who've  logged a block it in 3+ months)
The number of blocks we have in total across all tools
The number of requests we have across all tools

**Comment by markmacgillivray** [comment]
Is it easy to get a sheet of sign ups + a timestamp of when they signed up? Would like to make a chart...

**Comment by markmacgillivray** [comment]
Users broken down by plugin version they most recently used

**Comment by JosephMcArthur** [comment]
#### New definitions:

##### Churn

* Not used tools or logged in for 6 months
or
* Not used current version of plugin for 2 months

- [ ] Code these into the model
- [ ] update defintions in presentation

**Comment by markmacgillivray** [comment]
I didn't get this complete over the weekend, will move into next milestone to get finished. There is not much left to do, but it is all the UI side, so nothing much to show yet.

**Comment by markmacgillivray** [comment]
I still did not finish this, will have to move it into the next sprint

**Comment by JosephMcArthur** [comment]
Anything I can do to help clarify things here?

**Comment by markmacgillivray** [comment]
No, it is just me doing other things first and not finishing this. Will try to prioritise when we look over the next milestone plan. We have the data collecting, it is just the UI of it that I need to finish work on.

**Comment by markmacgillivray** [comment]
Have made progress on this but still not complete so will continue into next milestone. I have written functions to extract the data from what we store in such a way as to provide the stats we need. These stats will drive visualisations, but those are still not in a state to show. However, the main stat figures have been added to a stats overview page now, with some headline data and table of plugin use info:

http://oab.test.cottagelabs.com/stats

From here it is not too far to go to finish the interactivity / visualisations (selecting by timeframe etc) and downloadability of this data. It just gets put off as is not critical for frontend work etc.

**Comment by JosephMcArthur** [comment]
Stats page looks wonderful. Really looking fowards to interactivity & visuals!

**Comment by JosephMcArthur** [comment]
It would be good to have a page that just lists all the "blocks" registered by OAB, regardless of if they become requests.

**Comment by markmacgillivray** [comment]
Moving this one to next milestone as it is an ongoing improvement rather than fixed to this milestone anyway

**Comment by JosephMcArthur** [comment]
Is it helpful if I'm more specific about what I think we need to close
this?

**Comment by markmacgillivray** [comment]
Probably not. I think we have enough detail already. It just gets pushed behind other work that becomes more urgent. Visualising stuff is not as priority as making stuff work.

**Comment by JosephMcArthur** [comment]
Okay, so 
>  It would be good to have a page that just lists all the "blocks" registered by OAB, regardless of if they become requests.

is closed by /export - yes? 

Regardless of visualising, can we get some more request system info on the stats page? E.g right now I'd like to know:
- [ ] # of requests made this week
- [ ] # of requests sent this week

**Comment by markmacgillivray** [comment]
I think we talked about the "this week" counts previously - it is not so simple.

We could easily list the number of request made this week, if by that you mean new requests created this week by users. It could currently be calculated by exporting everything and filtering down to this week only, but I can add it as a stat to the stat page too.

However, knowing we sent a request email in a given week is not something we currently track. I can track what requests CHANGED in some way this week, but not how they were changed. I can show a stat of how many requests are at the "progress" status, and were created before this week, and have changed this week, so it would be a close approximation.

To know what changes happened at what times on a request, or what emails were sent at what times, requires further development that we have not done yet.

**Comment by JosephMcArthur** [comment]
Ah yes, the above rings a bell. I think the best approximation you can do without needing further development would be appreciated. I think looking at the number in "progress" would capture the main piece of info that's helpful here (the number we've processed in some way is also helpful, but not as important). 

It's also worth noting, before long, that we should be regularly outputting:
* open rates
* unsubscribe rates
* reply rates
* click-throughs to links in the e-mails
* deposit (from email) rate

We should all the data to do this accumulating though.

**Comment by markmacgillivray** [comment]
There is now a date range slider on the /request page. With this and the other options on the page, it should be possible to answer the various analysis queries - e.g. find all requests of particular status created since date X, or all requests created by particular user profession, etc.

Please review and let me know if anything else is necessary.

**Comment by JosephMcArthur** [comment]
On /stats @markmacgillivray can we start to monitor:

* request email system open rate
* request email system dnrs
* request email system response rate (only click in the email)

**Comment by JosephMcArthur** [comment]
Discussed bringing back the bunch of stats stuff we had previous to the last launch as something we could do this week. @markmacgillivray

**Comment by markmacgillivray** [comment]
Email delivers, drops, and opens are recorded in mailgun logs for 3o days and are also sent to our own system and stored, so this data is available for stats. Also we have a list of the email addresses on our dnr list, but not info on failures to those addresses, because we just don't accept them as email addresses to send to. So I think for this issue we have the underlying infrastructure required, but how to surface that in a useful way still remains an open question, which is perhaps best discussed in (or at least in relation to) #587 

I will not bring back the stats stuff yet, discussion to continue in #587  so unassigning myself here.

**Comment by JosephMcArthur** [comment]
Let's reframe this issue. #587 & #477 are both centring around the request system. There are bits above here about that, but let's ignore them (as they're part of other those discussions) and centre on tracking "users" / "usage" here more generally. 

Okay, /stats looks very different to when I last looked (when it had the table that monitored plugin vs site us etc). 

Lets:
- [ ] make the page login only (I thought this had been done)
- [ ] bring back table measuring usage via different tools (including now, the API). 
- [ ] display average success rate of the find system (number of times we return a url for availability) & who many successful results we've given (for articles)
- [ ] display different user type figures
  * The number of sign-ups we have (that's the same as total emails from the whole system)
  * The number of users we have (emails which we know downloaded the app)
  * The number of active users we have (people who've logged a block in the past month)
  * The number of inactive users we have (people who've logged a block it in the past 2 months)
  * the number of former users we have (people who've logged a block it in 6+ months)

The later may actually be better shown on /admin, where we have other user data. Your call. 

Let's have the above be viewable as a graph, usually with datapoint vs time. As only graphs:
- [ ] request types / status vs time would be helpful

@markmacgillivray [here](https://github.com/OAButton/discussion/issues/587#issuecomment-300764587) you've asked for design here. I'm afraid I don't think we have the capacity for this. However, since this isn't going to public in the foreseeable future please just use designs that make sense to you. Again, feel free to do the copy for these pages where it speeds things up (cc @allanaaa  / @chealsye)

**Comment by chealsye** [comment]
@allanaaa's primary task is website copy. Please only assign her.

**Comment by markmacgillivray** [comment]
Stats updated on dev. Not exactly as above, because some of the stats don't quite make sense in the newer context of most things being possible without logging in now. Also I have not made it necessary to log in to view this page - it provides no administrative or other functionality, and contains no private info - if you still do want it to require login, please clarify if you mean login required AND restriction to admin. Seems unnecessary though, and the page content could be useful for other people. See what you think.

I have not added the table about which types of tools people are using - we can show this for about 3000 records, but we lost some data from May and June about this. I considered extrapolating, and still could, but we are now mostly getting hits on the API, so it is only about 1 in 1000 that would show as being from the tools (website/plugin/bookmarklet). Could still show if you would like, let me know - in comparison of how great the amount of API use is, the amount of lost figures will be insignificant when turned into percentages anyway.

I did not show request status vs time - read below about what I have shown, and there is a time chart for requests over time. What would you mean by status over time? The current graph goes by date created.

What we have, and why:

* total requests, and split by article/data, then success/progress/refused/moderate-help. I also stated how many are legacy, but can remove that if not of interest. As it is now possible to create a request anonymously and then possibly own it, it does not make so much sense to show further details about how many users have recently created one.

* then showing a graph of requests over time grouped by week.

* then showing total number of availability checks, how many found, and percentage (with explanation). Then how many made anonymously vs signed in, and how many actual users have used it whilst signed in.

* then showing a graph of availability checks over time grouped by week

* then total number of users, how many have made requests signed in, how many have added support, and then showing here how many in the last month and how many 1 to 3 months ago - still may be inaccurate as people could be using it anonymously too, but at least it is more likely to show activity than the requests. Anyone not showing as using it in last 3 months is not necessarily inactive because could be using anonymously, so did not state anything about that, but of course can be implied that the remainder are "inactive".

**Comment by markmacgillivray** [comment]
Note that although this is on dev, it IS using the figures from live, to give a clearer indication of things.

**Comment by JosephMcArthur** [comment]
Thank you Mark! This is looking much better. Some things below in response to places were more info looks like it's needed. 

> I have not added the table about which types of tools people are using - we can show this for about 3000 records, but we lost some data from May and June about this. I considered extrapolating, and still could, but we are now mostly getting hits on the API, so it is only about 1 in 1000 that would show as being from the tools (website/plugin/bookmarklet). Could still show if you would like, let me know - in comparison of how great the amount of API use is, the amount of lost figures will be insignificant when turned into percentages anyway.

- [ ] Yes, let show these as total figures (not %s) & their change in the past week.

> I did not show request status vs time - read below about what I have shown, and there is a time chart for requests over time. What would you mean by status over time? The current graph goes by date created.

It would be helpful to be able to show:
* Requests with stories
* Requests moderated
* Requests successful
per week.

**Comment by markmacgillivray** [comment]
What does requests moderated actually mean? There are requests at the "moderate" status, but after that there are requests received or refused, both of which are already shown. The only thing in between is requests in progress. Or do you want a count of everything at any status AFTER moderate? These could reasonably easily be added as overall counts, but not broken down per week, as requests can change back and fore between statuses and we do not record the dates those things happen. 

Similarly, requests successful - I can show how many requests are currently at a status of "received", but that is already shown. There is not really a per week figure, because some requests go in and out of "received" status, but I could show the count per week of items where SOMETHING was last received.

**Comment by markmacgillivray** [comment]
I have added the table of plugins/bookmarklets users are using all-time and in last week (but we have no figures for last week - they will show when we do). I have also added a line chart for successful requests over time by week, and have added the count of requests with stories.

I think that is everything except the requests moderated, which I think is just the inverse of what we are already showing.

**Comment by JosephMcArthur** [comment]
Great, we're getting close here. 

- [ ] Show website & api & bulk differentiated in table.

Also, when we have the old version of the page these numbers were higher, if memory serves, so what does "all-time' mean? 

- [ ] answer that

- [ ] show new requests (with stories) per week

**Comment by markmacgillivray** [comment]
I have added a plugin tag to bulk jobs that will say they were done as bulk. Website and API did not used to differentiate, however now the website will. API uses are not included in the table - they are not explicitly declared, and will just be the remainder.

The numbers were not higher, just different. The current live stats page shows "higher" numbers but what it is showing is a count of people using "website", however that actually includes the API too, and it is capping at 10000. We now have uncapped numbers, but are not including API uses as website uses.

So all-time means since we started recording, on 24th October 2016.

**Comment by JosephMcArthur** [comment]
> I have added a plugin tag to bulk jobs that will say they were done as bulk. Website and API did not used to differentiate, however now the website will. 

Great, can't see these in the table yet but I'm assume they will be soon. 

> API uses are not included in the table - they are not explicitly declared, and will just be the remainder.

It would be nice if they were :) 

> Also, when we have the old version of the page these numbers were higher, if memory serves, so what does "all-time' mean?

Here, sorry, I'm talking about website & plugin numbers.

**Comment by markmacgillivray** [comment]
Yes website, bulk etc will not appear until we push to live and wait a while.

Added API counts to table.

Added new requests with stories over time by week.

I'm talking about website and plugin numbers too. That is what I mean - current numbers on live are higher, but they are showing for the last 10000 queries, whereas the new stats on dev are querying the live stats but across all 3500000, then properly attributing what is website, plugin, etc.

**Comment by markmacgillivray** [comment]
@JosephMcArthur can this be closed now?

**Comment by JosephMcArthur** [comment]
yes, I'll keep looking at the page bug we're in smaller issue territory now! 

Thanks for getting this together!
