### ISSUE TITLE
Show all blog content on /blog

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#214]
Don't see why we should make people click... can still hyperlink the titles to give people a permanent URL to share. 
##### Strech goal
- [x] Speaking of sharing, wouldn't hurt to drop some share buttons into our blog page template

**Comment by JosephMcArthur** [comment]
Where does /blog live in OAB_Static?

**Comment by JosephMcArthur** [comment]
Haha, okay, does it just manually generate from here? https://github.com/OAButton/oab_static/blob/master/content/blog/index.html

As in, they way to close this is the just to copy all of the old content into the file, and keep doing that from now on?

**Comment by chealsye** [comment]
Just let me know how we can/want to make the blog work. Definitely want that sorted soon. Will we be including all the previous blog content from the wordpress (which is also in the OAB medium account too)?

**Comment by JosephMcArthur** [comment]
@chealsye to "post a blog live" do you simply copy the title into https://github.com/OAButton/oab_static/blob/master/content/blog/index.html?

If we can get archived stuff up, that would be good, but I don't consider it a priority. I'd consider just adding a note at the bottom of the page suggesting folks view our Archived content on Medium.

**Comment by chealsye** [comment]
@JosephMcArthur I don't know. I've never posted a blog through github. But I don't think it'd be a simple copy and paste, the paragraphs would need to be added and that's just one very huge line within github. I miss Wordpress every time we think about the blog.

**Comment by markmacgillivray** [comment]
The easiest way to have a blog would be to put the blog somewhere else - e.g. on medium or wordpress or wherever people prefer. Then we can just point blog.openaccessbutton.org to the blog, and have openaccessbutton.org/blog redirect there.

Over the years I have tried various iterations of this, having the blog built in, etc. But in the end it usually comes down to just using whatever the project team prefer. It is not worth running our own blog software just for this purpose - just use one of the many free platforms.

The current blog pages are listed on the main blog index manually, yes. This is not ideal. It is possible to auto-generate an index page with the titles and/or content, but writing the blog posts would still be a case of writing pages into the oab_static repo.

So there is a decision to make here - which is preferred:

* I automate the generation of the index page from blog post pages written into the oab_static repo

* we move the blog to an external provider (I quite like medium, but I won't be writing the blog posts!)

@JosephMcArthur @chealsye

**Comment by JosephMcArthur** [comment]
Can we still write posts in markdown? If so how? That's pretty easy tbh!

We thought about moving to medium before but it will mean Google thinks the
site isn't active - which seemed like to much of a cost.

**Comment by markmacgillivray** [comment]
Yeah markdown should still be possible, I will test. Would just be a case of writing markdown in the file instead of html, and giving it a .md suffix instead of .html. Or if doing a bit of both, make it a .html file with some html in it, and wherever you want to use markdown you would use an opening <markdown> tag then write your markdown then close with a </markdown> tag. The new site generation code should automatically build this into html, but I do need to check that.

**Comment by chealsye** [comment]
@JosephMcArthur 

Can we still write posts in markdown? If so how? That's pretty easy tbh! **We differ in opinion here. Where would it be written? Because when editing the blog directly it's just one massive line of text per post.**

We thought about moving to medium before but it will mean Google thinks the
site isn't active - which seemed like to much of a cost. **What do you mean by this?**

**Comment by JosephMcArthur** [comment]
Just figured out point one on chat.

Point two. Google uses the frequency of site updates as a part of ranking,
so it's useful to have content go on your own site.

J

**Comment by JosephMcArthur** [comment]
- [ ] Add a bottom on the right for linking out to our medium site

**Comment by markmacgillivray** [comment]
Markdown autogeneration currently not working - must just be due to the changeover to new generation code, not a big deal to fix. Will update as soon as fixed.

**Comment by JosephMcArthur** [comment]
Have discussed & worked through things made this process hard for @chealsye. We now have scripts that will turn gdocs in HTML (incase Markdown doesn't work) and a local system that she can use that's nicer than the web editor.

**Comment by markmacgillivray** [comment]
Hmm, I have never seen a document editor to html converter that did what
was expected. I don't think you could rely on one to make a web page that
looks like you expect. Markdown does not work at the moment but can be made
to work, if that is the solution we want to go for. I am not sure what the
web editor you mention means - do you mean editing on github itself? If so,
the idea of github is to pull the content locally then edit it with a text
editor. That would be much easier. However, this can be done in any way
with any local system, as long as it presents html or markdown that the
website can render as expected (which is what I would worry about from a
gdocs to html converter).

**Comment by markmacgillivray** [comment]
Mentioned on another issue, I now think medium.com would be a better approach for blog content. Or some other blog platform that we can direct a subdomain or path to. Alternatively, all the content of the individual blog posts can be manually inserted into one big index file, and that way all blog content will appear on the index page instead of on individual pages. Blog links to individual entries could be controlled by # identifiers to headers on the page. However someone would have to go through the content and make sure it all lines up nicely and looks good - there is too much variance for me to spend time doing this programmatically just now, as there are other technical issues that only I can do, whereas there are multiple people who could do blog content.

**Comment by JosephMcArthur** [comment]
> Where should this point to, to close the issue? In relation, I would now recommend using medium.com to write the blog instead of having it on the site. This will make blog content easier to maintain for non-technical people, then copy will only have to change on oab_static when it is about the site itself, which, after the main launch should become less common. I think the only concern of not having the blog on the itself is that of the google search ranking due to lack of site changes, but actually we should have plenty site changes because of new requests coming in. Looking at the amount of past blog posts we had, there were just about as many requests and certainly many more blocks (which now will be more requests). Keeping regularly changing content separate is perhaps an easier project management solution, for little technical loss. Also, there are additional ways via medium.com to generate more interest, so being in that community may be of benefit more so than google rankings from blog pages on the site.

Moving this comment over from #223 to keep all discussion of where to host the blog here.

**Comment by JosephMcArthur** [comment]
I think I'm happy to move the whole blog to medium (but not now, later)

**Comment by chealsye** [comment]
What changed your mind?

**Comment by JosephMcArthur** [comment]
hadn't factored in the requests into how our site will be viewed by search engines. I also thought that given we self-host everything, an external blog would give us more power in situations like this to do comms. It also reduces the amount of work we need to do generally, and I'm a fan of being strategically lazy. Frankly,

**Comment by chealsye** [comment]
I'm definitely on board with Medium instead - but was curious what changed your mind.

**Comment by JosephMcArthur** [comment]
Okay, well, I guess a few more thoughts. 

There are lots of factors, and to some degree I was & still am on the fence. But at this point in time the balance of pro's / con's is on Medium's side. Given this is a highly reversible move & there isn't a huge cost either way, I'm favouring trying something new.

**Comment by chealsye** [comment]
@JosephMcArthur What do you need from me for this? Confused by assignment - except for when actually making posts.

**Comment by JosephMcArthur** [comment]
So now it would be good to move everything over to medium, then Mark can point the domains there & we're done!

**Comment by JosephMcArthur** [comment]
@chealsye when you've moved posts over to Medium, let @markmacgillivray know and we'll point all the domains there.

**Comment by chealsye** [comment]
@JosephMcArthur All the posts have been on Medium since the spring. I've added the launch blog. Good to go!

**Comment by JosephMcArthur** [comment]
Great. Are the posts URL slugs the same as those on the site? If not all
links will break on redirect

**Comment by chealsye** [comment]
I don't think I can change the slug for a Medium post... I see no options. I've seen old forum posts saying it can't be done and speculation that it would one-day be a paid feature.

The majority of the Medium content is from the old Wordpress site.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you switch the domains and redirect old post to their new posts? @chealsye it would probably be helpful if you could make a quick table of old slug to new slugs for the posts on the current oab site.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @chealsye I cannot switch until we know the URL slugs are the same, or until I have a list of the redirects to send them to. Otherwise our blog pages would disappear. So I will reassign this for now back to you and @chealsye. As soon as you have these, I can do the redirect, so can assign back to me then and I can still fit it in sprint 6.

**Comment by chealsye** [comment]
@markmacgillivray Here ya go: https://docs.google.com/spreadsheets/d/1qfPZ4brtFPfeQsezDV2xhXgyHUUy_ouUDFWn9JZ437I/edit#gid=0

**Comment by markmacgillivray** [comment]
All blog post redirects have been put in place now on the dev site. Please check that all the blog URLs on /blog now go to where you want them to go. 

I have also set redirects openaccessbutton.org/blog and blog.openaccessbutton.org to go to medium.com, so we could use those in future on our medium blog, as well as or instead of the medium.com/@openaccessbutton part. But to do this, it looks like we need to register blog.openaccessbutton.org with medium via this form:

https://help.medium.com/hc/en-us/requests/new?ticket_form_id=165177

can whichever one of you has access to the oabutton medium account please create it as a publication if not already done so, then fill in that form?

The redirects will work anyway, but if you want the posts to show up as if they are at blog.openaccessbutton.org rather than medium.com, you will need to do that. If you don't mind them showing as URLs at medium.com (which is probably fine, I think), then just confirm on the dev site and if you are happy I will push it to live.

Create any new blog posts on medium.com, NOT on the dev or live openaccessbutton sites.

**Comment by chealsye** [comment]
@markmacgillivray, I can fill out the form. What registrar do we use to manage your DNS records?

By the way, @JosephMcArthur - Our Medium account is associated with our Twitter account. Just wanted to mention it, because we don't have it set up in our access docs, but you do have access to it as does anyone else on the team with Twitter.

**Comment by markmacgillivray** [comment]
@chealsye I use godaddy, but I don't actually control the domain. I think Joe and David did also use godaddy though, so if all you need to know is who the registrar is, that is it. Odd that they would ask though, it can be looked up by automated tools.

Note @JosephMcArthur this may require things being done to the domain dns setup, so if there are still issues getting those done, those issues will have to be resolved too. This is not critical at the moment though, and should not cause the blog to stop working at the medium.com domain in the interim.

I am assigning this one to you both now, to keep track of the process with medium. The live site is updated already so nothing more for me to do. If there are domain dns settings needing done, and if we get access to be able to make those changes, let me know if you need me back on this issue.

**Comment by JosephMcArthur** [comment]
Will get this changed when I have domain control

**Comment by JosephMcArthur** [comment]
Have filled in the medium form for blog.openaccessbutton.org. @markmacgillivray can you update dns to make this work?

**Comment by JosephMcArthur** [comment]
From Medium:

Thanks for contacting us about setting up your custom domain on Medium. Please read through this email to better understand what to expect as you go through this process. There are a few key things you should know and expect.

-The entire process can take up to 4-24 hours and there will be times during the process where your domain will return a certificate error. This is normal and expected.

-If you have an archive that you're migrating to Medium and you want 301 redirects from your old URLs to work, you need to migrate all the posts to Medium PRIOR to cutting your domain over to Medium. Read about how you can migrate your content here: https://help.medium.com/hc/en-us/sections/204026317-Migrations

-You CAN'T point your domain at your Medium profile. Your Medium profile URL looks like this medium.com/@username (there's an @ sign in the URL). We don't support that. You'll need to point it to a Medium publication which takes about a minute to set up. Here's how: https://help.medium.com/hc/en-us/articles/214559417-New-publication.

-We don't allow www as a subdomain, so if you requested www.domain.com, we're going to send you a CNAME for domain.com and you'll be able to add another CNAME that redirects www to domain. We'll provide more info on that in our response with your CNAME.

-You can read about SEO implications of moving to Medium here: https://help.medium.com/hc/en-us/articles/217991468-Duplicate-Content-and-SEO

Don't hesitate to reply to this email with any questions you might have.

We'll reply with your CNAME and A Records within 12 hours of receiving your request.

**Comment by JosephMcArthur** [comment]
Hmmm, actually we need to set up a publication for this. @chealsye can you do this: https://medium.com/new-publication

**Comment by chealsye** [comment]
@JosephMcArthur https://medium.com/openaccessbutton has always been publication. 

https://medium.com/@openaccessbutton is the profile. The wrong link just got grabbed.

**Comment by JosephMcArthur** [comment]
okay, I've submitted another request

**Comment by JosephMcArthur** [comment]
we're all good here!
