### ISSUE TITLE
Ready Plugin for submission

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#241]
This is a holding issue to codify #230 and to keep thoughts on what needs to be done during this sprint (thoughts that aren't #226 ).

**Comment by JosephMcArthur** [comment]
- [ ] @markmacgillivray to review submission guidelines
- [ ] @chealsye to have developed copy / screenshots for page

**Comment by chealsye** [comment]
Copy and screenshots are in #325.

**Comment by JosephMcArthur** [comment]
@chealsye can you check requirements for screenshot sizes?

**Comment by chealsye** [comment]
@JosephMcArthur I feel stupid, but I cannot find the image sizes for Firefox. I can easily find them for Chrome, but not Firefox...

**Comment by JosephMcArthur** [comment]
I'll try and use what we already have then and see how it goes.

**Comment by JosephMcArthur** [comment]
@markmacgillivray please prep a file for FF from the latest release. Then @meganwaps can test that. I think light touch testing is probably okay.

**Comment by markmacgillivray** [comment]
OK there is an .xpi file in the develop branch of the unified extension repo, and instructions on the develop branch README. Note, due to firefox annoyances and me not having a developer edition or time to install one before getting on to other things, I could not actually get as far as installing the add-on to firefox. See the notes for details. 

Note it probably also means we cannot do user testing with users on firefox because they will not be able to install the latest versions themselves. So in future if user-testing new plugin developments where we want users to actually install some latest dev version themselves to work through, we should just only do this sort of testing with chrome and then do the port over to firefox and just do the "sanity check" testing ourselves there, to ensure it works.

@meganwaps @JosephMcArthur hopefully now you can follow the README instructions on the develop branch of unified extension, and get an add-on installed on a developer edition of firefox. If there are further issues, update this issue with the details and we can look into it further.

I will assign to @meganwaps now to take the testing forward, just let me know if I have to pick it back up.

**Comment by meganwaps** [comment]
I'm testing now.

**Comment by meganwaps** [comment]
@markmacgillivray I apologize, answering this totally slipped my mind. Everything is fine, I just still have 1 of my testing articles which is being linked to an incorrect open article via the button. This has been a recurring problem with this one particular article, http://link.springer.com/article/10.1007/s40306-015-0117-0. However, other than that, I'm able to support requests, make my own, and find other articles. I'm closing this since it is doing its job. I'll create a separate issue for the incorrect article problem.

**Comment by JosephMcArthur** [comment]
Tried to upload, was told:

>    The add-on ID in your manifest.json or install.rdf (oab-ffx@openaccessbutton.org) does not match the ID of your add-on on AMO (jid1-I4HAe95cHq6CJQ@jetpack)

**Comment by markmacgillivray** [comment]
Odd. Steve thought it would not make a difference, but perhaps if it was already created with that ID then it needs to be the same. I have changed in dev, but need to create a production version anyway so that the FF plugin points to the live site, not the dev site. Also, as there is currently a bug to fix on the plugin, I will fix that then have the FF plugin updated too, then we can retry submission with that ID. But don't try yet!

**Comment by JosephMcArthur** [comment]
@markmacgillivray any progress here? Seems like we should be able to ship with only a small amount of work

**Comment by markmacgillivray** [comment]
There is now a 1.0.3 version on plugin master branch for firefox, it has the different key they asked for, and connects to the live API. It would be good if someone can test then try putting it on the firefox store.

**Comment by svmelton** [comment]
@markmacgillivray Can I test this from the test site, or do I need to pull the code repo?

**Comment by svmelton** [comment]
Ok, I downloaded the code from the repo and tried to test.

## Testing notes:
Tested on Firefox Developer 53.0a2 (2017-02-25) (64-bit)

### Logging In:
- When I tried to copy the token from my email, the system told me the token was invalid.
- No issues with clicking the link from the email
-Logging in seemed to create a "double log in" effect:
![screen shot 2017-02-25 at 10 51 41 pm](https://cloud.githubusercontent.com/assets/7232545/23337044/dfd9dbe0-fbaf-11e6-978f-4a108be0ce4b.png)


### Installing:
- No issues

### Hitting a paywall:
-Tested using http://www.nature.com/nature/journal/v536/n7615/full/nature19068.html#abstract. 
And 
http://www.emeraldinsight.com/doi/pdfplus/10.1108/LM-03-2013-0018

In both, the plugin would not work from the icon on the browser but would work if I clicked on the Bookmarks folder.

Page asked for location and appeared to find a version of http://www.nature.com/nature/journal/v536/n7615/full/nature19068.html#abstract. 
However, when I attempted to click on it, it took me to a log in page.

When I tried to place a request for http://www.emeraldinsight.com/doi/pdfplus/10.1108/LM-03-2013-0018, the plugin told me I was not logged in. After I logged back in, the plugin was stuck on the “we’re looking” screen.

**Comment by markmacgillivray** [comment]
I think this is irrelevant now as we will be redoing the plugins and so will have to retest the firefox one. New issues can be created as that progresses
