### ISSUE TITLE
Explore technical feasibility of lightweight mobile apps

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#287]
All discussion & background on this is in #286. 

Worth remembering that even if a mobile app is technically easy, it still requires design / copy / testing time & changes to already existing systems & ongoing maintenance. We must keep whatever we do here crazy simply & honed.

**Comment by JosephMcArthur** [comment]
@meganwaps before we explore new apps here, I'd like us to explore the use of bookmarklets on mobile. 

Can you have a play on your own phone, it should be possible to get the bookmarklet onto your browser. Once we've figured that out, lets have 5 user tests with it vs a slide show of how the mobile app could work as discussed in #286

**Comment by meganwaps** [comment]
@JosephMcArthur I can try on my phone right now before bed, discuss the rest in our stand up tomorrow?

**Comment by JosephMcArthur** [comment]
person who was going to help me on this bailed. Moving back.

**Comment by JosephMcArthur** [comment]
This might be helpful: http://www.androidnames.com/development/list-of-the-best-mobile-backend-as-a-service-mbaas-providers/

**Comment by markmacgillivray** [comment]
We already have a backend though, why would we need to run another one to support a mobile app? I still think the mobile app should be as light as possible, and still needs to have a clear use case - what do we expect someone to do with it? If bookmarklets / browser / android UI buttons can be used to launch a web page that we pass the URL of the thing the person wants to check to, then the whole mobile app need be nothing more than a button. I think we discussed this solution previously.

**Comment by JosephMcArthur** [comment]
Okay, just had a chat with a friend I live with at NWSPK about this (he builds mobile apps professionally) and he generally thought our direction with the app was a good idea for where we're at (lightweight, leaning on our current web infrastructure etc). 

He suggested we use React Native as a framework as it means we could deploy to iOS / Android from one codebase. It supports the key feature we need of sending the user to webpage from the share menu - https://github.com/alinz/react-native-share-extension. If needed, he says react would also help us build something closer to native too (i.e something that looked a lot close to using the plugin as a phone app) rather than just sending people simply to /request/new. 

React should also play nice with our meteor backend, which will make things simpler there. 

Here I'm also going to pull some discussion for #286 directly here:

# App concept

>Indeed. The ONLY thing it would add is allow you to use "share" links
(which exist on android & iOS) to simplify the workflow.

>### Without app
- Hit paywall :(
- change windows
- navigate to oab
  - maybe login
- navigate to new request page
- change windows back to paywall
- get url
- change windows to request page
- insert link
- use new request page

>### with app
- (prior) install app
- hit paywall
- share to oab app via the browser (similar to how you can share links to
  twitter / facebook)
- use oab app

# Comments

From Mark
> Hmm. If it is possible to make an app that introduces a "share to OAB" link
to the browser, then that "share to" could go straight to the web page.
That would keep the mobile app extremely simple, it would need barely any
maintenance.

From Me: 
> Makes sense, as long as the URL box was then filled on the users arrival.

From Mark:
> Yes, we can pass the url of the page they were on, which can populate the
URL box on the new request page, and that will trigger the scrape and
availability check, so we can give them the full functionality just by one
click of a "share to oab" button.

**Comment by markmacgillivray** [comment]
It's already possible with meteor to roll out code across platforms from one codebase. There's nothing wrong with react, but we would just be adding complexity for no extra gain, so we shouldn't use it.

Also, I'm still not sure I understand what it is you're still exploring here - why is sending someone to request/new not the ideal solution? I still don't see the benefit of having a native app at all for the use cases we have.

Even though we could deploy across platforms from meteor, I don't think we should. Our current site is actually just statically generated and separate from the meteor code. Meteor frontend and react frontend tend to be vastly over engineered for many situations, and I did actually start with a full meteor frontend for oabutton before reverting to simpler static site approach.

All we need is to add a "share to oab" button to the phone browser - that's what we want to know if possible or not. If it is, then that is all our app should do - that share button should just open a new web page that is on request/new with the URL populated, which triggers the lookup, and this is already possible.

So, keep it simple.

**Comment by JosephMcArthur** [comment]
Maybe I'm not being clear, the above description was thought to be the easiest way to do this:

> All we need is to add a "share to oab" button to the phone browser - that's what we want to know if possible or not. If it is, then that is all our app should do - that share button should just open a new web page that is on request/new with the URL populated, which triggers the lookup, and this is already possible.

To do that, we have to make ios / android apps, as I understand it, that can get placed in those menus. However, ALL those apps really do (expect maybe have an image when you open them saying how to use them) is push people to /request/new. 

If Meteor can do that, then let's use it, but it sounded like from my discussion that react would be a better option. I don't know anything at all about this aspect though, just relaying other thoughts. 

I want to be clear, I'm not advocating the "app" does any more than the share menu stuff. I wouldn't have any sign in to the app, any way to interact with your own requests etc. I'd suggest we handle all that via the site itself, as we do. 

If you know how to get our site in the "share menu" without needing a separate "app" then I'm all ears.

**Comment by markmacgillivray** [comment]
Ah ok, yes we agree the app should be the simple option of adding the button that links to the site then. 

I'm not sure react or meteor are the way forward though, as a combined codebase across platforms just to achieve that could be overkill. I'll look into how to add such a button for various phone browsers, and if it requires cross platform complexity then we can use meteor or react if meteor turns out to be unsuitable, but first I'll see if it's easy enough to just do in a simpler way.

**Comment by markmacgillivray** [comment]
Did anyone finish looking into whether bookmarks work for this? On android chrome the bookmarks are easy to get to and to click, it's about 2 clicks from page to bookmarklet. There may be reason to not just use bookmarklets.

**Comment by markmacgillivray** [comment]
On android chrome, clicking the menu and going to share then waiting for share options to load then clicking one then waiting for it to open the selection then triggering the share on the selection is far more steps and complexity than clicking menu then bookmarks then clicking a bookmark. But I've not actually tried the bookmarklet.

However even if the full bookmarklet doesn't work, a simpler one that just opens the request/new page, with the URL in it if possible, would still be simpler than a share button. 

I think whichever way we do this, the important thing will be having instructions on user account / download pages that show people how to use whatever option we go with.

Are we going to get any of those gif screen grab video things made any time soon? I think we need them even just for the plugin, and could do with them for bookmarklet too.

**Comment by JosephMcArthur** [comment]
I just tried on my phone. It's a small number of clicks, but they're not clear clicks (if that makes sense). We'd be in a position of trying to get people to remember how to do it (never seen another app work like this on mobile) through good instructions (maybe gifs) & that seems unlikely to work. Doesn't seem like it ever can be good if you have a lot of bookmarks too. Happy to consider more, though.

There is an interesting from blog hypothes.is on this. Might be interesting to see where they went in the end. https://hypothes.is/blog/farewell-to-bookmarklets/

P.s if people think we should get those gifs, I'm happy to get them made asap!

**Comment by JosephMcArthur** [comment]
To be clear, even if not ideal, if a bookmarklet is the 80/20 solution here, and means we can get some better functionality here faster (with e.g <1 sprint of work) it's appealing to me.

**Comment by markmacgillivray** [comment]
Yes, we'd have to show people how to do it. But I think the same is true of a share button. We'd need to tell people there's such a thing as a share menu on their phone browser, and that they can expect to find a share to oab button there after they install our app. Either way, we have to tell people how it will work and expect them to remember.

**Comment by markmacgillivray** [comment]
The hypothesis blog indicates that they went with a share button, but still had complexities on iOS. 

Saying that bookmarklets is dead is true in general, but if a share button is no more easy to use and a bookmarklet will do the job quicker and be easier to install and maintain, then a bookmarklet is still the answer.

The only reason so many app ecosystems exist is to benefit the people running the ecosystem, not the users. Switching away from a bookmarklet just because they are dead does not necessarily meet the user need any better than using a seemingly dead approach if it works better in our use case.

Is using the browser share menu really any more intuitive than using the browser bookmark bar? I think either way we'll have to explicitly tell the users what to do. So if we don't gain anything with the share button, then a bookmarklet is the answer due to being easier to install and maintain (assuming it's possible to do with a bookmarklet)

**Comment by JosephMcArthur** [comment]
Note to self: Pocket seems to heavily deploy bookmarklets. Once you've done #460 you should be able to see their sign up flow for all mobile browsers & move forwards here.

**Comment by JosephMcArthur** [comment]
We may want to edit how we display things on mobile because of this: http://www.omgchrome.com/chrome-now-lets-install-browser-extensions-android-phone/

**Comment by joshbalfour** [comment]
(sorry for the delay on this, I wanted to properly sit down and mull it over before posting)

from reading this thread the user story here seems to be:

> As a user on their smartphone
> when I find an article behind a paywall
> I want to easily be able to use OAB
> to circumvent the paywall.

(please correct me if I'm wrong!)

(10%) - A quick win here would be to take the existing bookmarklet and write up some instructions on how users can add it to their mobile browser and then use it. This is something I believe we should do first, as it would take minimal time but give us something to user test with, and gauge interest to justify investing more time into this.

(30%) - If we were to modify the existing bookmarklet, instead of sending the user to the OAB site we could embed content into the page the user is currently on, which would allow for better user feedback via a branded modal (so it's obvious it's from OAB), which could then display an error message (sorry, we don't have that article), or a success (click <big button> to open in OAB)

(80%) - However, on mobile devices, bookmarklets are not exactly an obvious journey, as the "bookmarks bar" we're used to on desktop browsers is replaced by the "share via" menu, and bookmarks are behind a separate, full screen view.
The most user-obvious solution for this would be to have the OAB be available on the "share via" menu on iOS/android. In order to do that you need to have an app available in the respective app stores.
However, in my experience, if Apple deems an app [too simple](https://developer.apple.com/app-store/review/guidelines/#minimum-functionality) they will not allow it onto the app store, so if we were to go down that road we would have to ensure that we provide a better experience than simply putting the user onto a web view.

With that in mind the tech approach I'd recommend is using a framework which would allow us to easily embed native UI components (menu bar, text view, buttons, etc.) across multiple platforms (android/iOS).
For this I'd recommend [react native](https://facebook.github.io/react-native/), as it would allow us to do exactly that, taking advantage of the [large array of native components already written for us](https://react.parts/native), whilst being able to write our code in JavaScript, which (I'm guessing) everyone here would be more comfortable with than maintaining separate Java and Swift repos.
I recommend react native over Cordova frameworks (ionic etc.) as it gives users a fully native experience, both in terms of look (native buttons, menu bars, etc.) and feel ([performance](https://www.quora.com/Which-Hybrid-Framewok-has-more-future-Ionic-React-or-Meteor), responsiveness).

Side effect: having multiple API clients (web & apps) will harden our backend APIs, as they will likely need to be used slightly differently

Obviously the app would be a _much_ larger undertaking, which I'd want to put through the full product workflow should we decide to move forward on this, but I'd like to be sure there is a need for this before going down that road.

**Comment by markmacgillivray** [comment]
I'm finding this hard to understand. Why does it seem we are continuing to investigate mobile apps at all? It's not that I disagree that mobile apps give a better experience or that react native would be a good way to do this - what I disagree with is that the point of this issue is to explore the lightest possible approach to what should be done for mobile users at all, if anything.

The use case of oabutton is a user searching for research. They are probably doing this on a computer, not a phone. If they are browsing on a phone and want to create a request etc etc, then what we want to do IS move them over to the website, NOT have the bookmarklet stick modals into the page they are viewing or open up a mobile app for them.

The reason for this is that we have already gone through two years of simplifying towards moving functionality to the site instead of having different user experiences across multiple different apps - now that we have a clear use case around making requests, which is not where oabutton initially started.

Even if we are going to make something as simple as a "share via" button, the point that matters her is - is that any better than a bookmarklet on a mobile browser? This is not a technical question - it is about how hard it is for a user to be told to do either. Having looked at the workflow for both, on android at least, it is easier to instruct a user to click a bookmarklet on their mobile browser than to go to "share via", and it more closely maps to their experience if they have already been using a bookmarklet on their desktop browser.

Lastly, if we are going to make apps available, whilst react native may be one option, we already use meteor which can also deploy onto mobile platforms - so bringing in another framework just for that would be an additional complexity. This is not too big a deal because there already is an API that could support clients written in any way we feel like, but there is no point bringing any further complexity in when we do not even have a clear idea if there is a user story to support people browsing on their phones and wanting to do anything more than click a bookmarklet and open up the website.

**Comment by JosephMcArthur** [comment]
Random note, this: http://kizu514.com/blog/manifest-json/

**Comment by JosephMcArthur** [comment]
Closing this, I think we've successfully explored & now would have to make a call on if to take forwards.
