### ISSUE TITLE
Check the map embed code works on new site

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#305]

**Comment by JosephMcArthur** [comment]
linked to #349 I expect

**Comment by markmacgillivray** [comment]
Checked, it does, it is driving the map on the front page.

**Comment by JosephMcArthur** [comment]
Sorry, this is the embeds for the map & request pages. Neither of those work when embedded on other pages.

**Comment by markmacgillivray** [comment]
Which emebds? The only map embed we have on the site now is the one on the front page - I don't know of any other maps we are currently using. For the request pages, we have the embed widgets although they do not include a map - they didn't work in dev but since I have moved everything to live I have tested and updated them, and as far as I can see they do work. On the dev branch, and as visible on the dev site, the embed code can be copied from a request page and pasted into any other web page - I tried it, and it works. Are we talking about the wrong things?

**Comment by JosephMcArthur** [comment]
I'm referring here to the map embed code for displaying on other sites.
This is what OSF funded us to do, and I want to display it on the resources
page. That code can be found commented out on the resources page currently.

On Fri, 28 Oct 2016 at 12:37 markmacgillivray <notifications@github.com>
wrote:

Which emebds? The only map embed we have on the site now is the one on the
front page - I don't know of any other maps we are currently using. For the
request pages, we have the embed widgets although they do not include a map
- they didn't work in dev but since I have moved everything to live I have
tested and updated them, and as far as I can see they do work. On the dev
branch, and as visible on the dev site, the embed code can be copied from a
request page and pasted into any other web page - I tried it, and it works.
Are we talking about the wrong things?

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/OAButton/backend/issues/305#issuecomment-256899060>,
or mute
the thread

**Comment by markmacgillivray** [comment]
Ah, I see - I didn't know it was also on the resources page. It does work - I just never knew to update it there. Will add now.

**Comment by markmacgillivray** [comment]
Hmm, hold on - I just had a look, and now I remember the map on the top of the resources page too, sorry, forgot about it. However, it is also working, and not commented out. I had a look through the page just now but don't see any other commented out sections that look like they need updating. Can you link to where in the file you want me to fix?

https://github.com/OAButton/oab_static/blob/develop/content/resources.html

**Comment by markmacgillivray** [comment]
@JosephMcArthur I still need a pointer from you on where this code is that you think needs fixed and uncommented - see previous comments from me on this issue, I could not figure out where you were referring to. Just let me know and this can be sorted.

**Comment by JosephMcArthur** [comment]
For now, this isn't a priority & so I'm moving out the milestone.

**Comment by JosephMcArthur** [comment]
these are actually working
