### ISSUE TITLE
Duplicate story boxes & other issues after making a request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#380]
### Expected Behavior
- once I've made a request via the plugin, if I try and make another while it's still open I'm either told:
  - I can't
  - it lets me do it
### Actual Behavior
- another textbox appears, but no ability to submit. 
- previous message doesn't disappear

I think, although I haven't confirmed, that making a request via the bookmarklet & then trying to click the other button will also bring out a bug (it doesn't open)
### Steps to Reproduce this bug

_Please include any info about the version of the tool you're using and your system. - remove this note before posting_
- Affects: Plugin / Bookmarklet
- Hardware versions: mac
- Software versions: chrome
- Steps to reproduce: 
  - open plugin / bookmarklet
  - make a request
  - DON'T CLOSE IT
  - try and make another request for whatever you didn't before

@meganwaps can you test this further & we'll fix in later builds. 
FYI: @markmacgillivray

**Comment by meganwaps** [comment]
@JosephMcArthur just checking, are you testing dev or live? or has this issue been affecting you on both?

**Comment by JosephMcArthur** [comment]
It'll be on both. But test dev.

**Comment by meganwaps** [comment]
@JosephMcArthur No problem. Testing now. Thanks for the step-by-step directions on how to duplicate, it makes things much easier on my end!

**Comment by meganwaps** [comment]
@JosephMcArthur I'm reproducing your steps on Chrome w/ the plugin dev v. 1.03. So far i've only used articles I know are available in our repositories. I have not been able to to recreate this duplicate test box. This is my process so far: 
1. Open plugin. 
2. Request what isn't available (usually Data).
3. Keeping the box open, I hit the 'Open Article' button. (the expected behavior of a new tab opening with the request *is* happening accordingly)
4. Takes me to the article. 

I'm going to try with articles that aren't in our repositories and we can't find access to. I'll let you know the minute I'm able to replicate this bug.

**Comment by meganwaps** [comment]
@JosephMcArthur @markmacgillivray Okay I believe I have successfully reproduced the problem. 
Using an article on JSTOR which is not in our repositories, I followed your instructions and ended up with this little beauty. 

![screen shot 2016-12-05 at 6 20 10 pm](https://cloud.githubusercontent.com/assets/5968703/20910657/aeb10a58-bb17-11e6-82b0-baacdd6bd4f0.png)

So that's pretty annoying, but as soon as you 'x' out of the plugin and click the icon again, it works.

**Comment by meganwaps** [comment]
Hey @JosephMcArthur @markmacgillivray I was wondering if there's any news on this? What more can I do so we can resolve and close this issue?

**Comment by markmacgillivray** [comment]
I believe this is up to me to fix now.

**Comment by JosephMcArthur** [comment]
plugin won't be fixed at this point, it'll be redone. closing.
