### ISSUE TITLE
Explore bringing back the map.

### ISSUE THREAD

**Issue by meganwaps** [OAButton/discussion#396]
This issue is so we can explore the possibility of being able to re-release our map which showed where requests were from for our next mini milestone. 

Every single user I tested who had previously used the button expressed a desire to see that map back on our website, and I'd like to try to respect those people who have been with us from the very beginning. 

@markmacgillivray, what would it take for us to make this happen? What would the difficulties be, and how can the rest of us help?

Again, this is just an exploratory issue.

**Comment by JosephMcArthur** [comment]
Immediate thoughts / background that come to mind here are below: 

* the information the map used to show has now been shown at a scale far larger by Sci-hub. However, sci-hub doesn't do stories. 
* The map people think of before showed paywalls hits. We have consciously de-prioritised this information on the website in favour of requests, which are more actionable by the community. We can still show these on the map, but it's a different thing altogether. 
* Gathering location data on most of our platform is currently a hurdle that most users won't understand or want for the task we now perform. My preference is to remove it where it causes the user an extra step (e.g, remove location gathering for the bookmarklet, but keep it in the plugin).
 * to do the above while also having a map be an important part our set up would mean needing to gather location info at other points - but most of the time guess it. 
 * We have previously discussed it not being interactive because this detracts from people looking at requests. 
* We had a huge data loss in 2014/5 due to some badly written code. This means we're missing a lot of location info. Doesn't mean there aren't ways to get it back though. 
* we do still have a map, but it's not front and centre as it once was. This can be changed, but it is currently not this way for many of the reasons above.  

All that said, I am partial to bringing it back. However, it would need to fit into our current goals more clearly than the previous implementation does. For example:
* as a tool for finding requests
* as advertising

I'm conscious that neither of those things are yet a priority. However, if we're lucky they will be sometime next year.

**Comment by markmacgillivray** [comment]
It would depend what it means to bring back the map - it is actually already there, at the bottom of the front page, and the top of the resources page, and is embeddable on any website elsewhere by anyone who would like to do so.

But this is just a visual of the location dots on the world map - it does not show any more information, but it could.

I think if users want it, then it should be done, but as Joe says, it would have to be clear what the use case is, given what it is that the plugin currently does - what is it that these users used to do with the map that they now can't do? Why do they want to do that now? Is there something else they want to do using the map that the functionality of the site does not currently enable?

I'd think actually adding the map in the next milestone is probably too soon, but answering the questions I just listed might be a good idea to do in the next milestone - then once we know what it is people are needing, we can actually add it in a later milestone.

**Comment by JosephMcArthur** [comment]
Closing to clean repo of old priorities.
