### ISSUE TITLE
Allow DOIs / PMC / PMID (and maybe titles) to be put into our url box on /request/new

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#418]
Like http://cx.ctg.li/ & oadoi.org

**Comment by markmacgillivray** [comment]
Done for DOI, PMID and PMC. Titles are probably a bit too vague, and there are limited places we could really search for them. Once we have a far larger collection of requests metadata ourselves, it may be worth just doing a match against our own data to see if a title is the same as one that someone else has already asked for, and that we already have a URL / ID to match against.

I will assign to @JosephMcArthur to be in charge of what happens copy/test wise now.

**Comment by JosephMcArthur** [comment]
I've made a small copy change in the search bar for this.

**Comment by JosephMcArthur** [comment]
Just had a quick play, looks good. 

Bug: On entering as https://www.ncbi.nlm.nih.gov/pubmed/28038472 I get the right response, on entering 28038472 I only get an invitation to make a request (not a notification the article is available). Duplicated with other articles too. Doesn't happen with their DOI's.  

- [ ] fixed

Bug: Spaces before DOI's / PMIC's causes them to not be recognised. this is easy to introduce when copy / pasting

- [ ] fixed

Also, we need to:

- [ ] simplify instructions seen on /request/new. Are they all needed? 1. Test all ID types / 2. understand their usage in the wild / 3. decide how to simplify with Chealsye. / 4. See how to monitor usage in the wild
- [ ] document this feature on testing guides (need ID's that give tested responses that we validate vs their URL's & manual tests
- [ ] do a miniblog about this (or include in another) - @chealsye 
- [ ] test spaces after the ID

#### notes for Joe

I looked at:
* https://www.ncbi.nlm.nih.gov/pubmed/28038452
* https://www.ncbi.nlm.nih.gov/pubmed/28038472
* DOI's are much faster than URLs in the system (nice bonus)

**Comment by JosephMcArthur** [comment]
Once we fix instructions on /request/new & 1 I think this is good enough to ship & we can hot fix other stuff.

**Comment by JosephMcArthur** [comment]
@chealsye / @markmacgillivray / @meganwaps how are PMC ID's seen in the wild? Are they usually already prefixed with PMC, if so, do we need the instruction? 

If they're not, is there a way we can remove this instruction (e.g doing some validation on things that look like PMC ID's)? 

Are they that common?

**Comment by markmacgillivray** [comment]
The proper way to use a PMC ID is to prefix it with PMC and they should always be found this way in the wild - so with any luck, people will know that. The problem though is that there is no way to differentiate between a PMID and PMC ID if the PMC ID does not have PMC at the start. So, if we are not explicit about it, and someone does put in a PMC ID without the PMC part, we will not be able to know the difference, and we will mistakenly look up a PMID instead.

There is no reliable way to programmatically validate from just the PMC ID number part alone, because it often will also be a valid PMID.

PMIDs and PMC IDs without the PMC prefix are both just sequential integer numbers, assigned to articles as they get published. Many people think that PMIDs are 8 digits long, but they are not - they can be any length; it just so happens that most people recently have only seen PMIDs with 8 digits in them, because there are between 20,000,000 and 30,000,000 articles with PMIDs - so for a good few years and a few more to come, all new articles WILL have PMIDs with 8 digits. But look into the past by a decade or so or more, and you will find ones with less digits.

So, we could drop the explicit mention of requiring PMC for PMC IDs, but we will then increase errors, and it is not possible to fix programmatically.

We looked into this a lot on other systems we run at CL.

**Comment by JosephMcArthur** [comment]
Okay, if they _should_ be seen like this in the wild I'd vote we remove the extra instruction & monitor errors. 

What we could do is after people search "PMC ID / PMC - like" numbers without the PMC prefix we can add an option on the page that is something like "Looking for a PMC ID?" that would correct their search or simply put a reminder in the text of the page while it's looking. I don't think we need that yet though.

**Comment by markmacgillivray** [comment]
Oddly I was able to use PMIDs and PMC IDs with or without leading or trailing spaces with no errors. Also putting PMIDs in instead of the full NCBI URLs worked fine for me too. This is only on the dev system so far - were you testing there or on live? Anyway, seems to be fine now...

**Comment by JosephMcArthur** [comment]
Did you try the IDS I used above?

I used Dev. Didn't realise it was on live.

**Comment by markmacgillivray** [comment]
Yeah it is not on live yet.

Yes I tried the IDs you put above, and some other ones too. They all worked.

**Comment by markmacgillivray** [comment]
And I tried with and without whitespace too, for the ones you provided and some others.

**Comment by JosephMcArthur** [comment]
Huh, I can't replicate now. That's a bit odd, but, perhaps there was another transient issue? 

In that case, we're good to push this live. @markmacgillivray, it would be good to do with #333 - any ETA on that?

**Comment by JosephMcArthur** [comment]
Since this is ready to push live & just needs some testing documentation (most of which can be grabbed from above) I'm moving this back into the backlog.

**Comment by svmelton** [comment]
@JosephMcArthur Just checking—am I tagged here to work on the documentation?

**Comment by JosephMcArthur** [comment]
Yup!

**Comment by JosephMcArthur** [comment]
this is now covered by having examples on the frontpage which deffo work
