### ISSUE TITLE
Backend work for ILL / Library Bookmarklet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#419]
Leaving to @markmacgillivray to make issues that are useful for this work.

**Comment by markmacgillivray** [comment]
Go through old discussions, talk with s.bannon at imperial and work out what extra we need on the backend if anything, particularly how to pass an auth token from the lib system to the ILL system

**Comment by markmacgillivray** [comment]
Note as with stated on #408 if we assume an installed bookmarklet can read an Imperial ID, we need to know where from.

Can Imperial install the bookmarklet on every browser?

Are we expecting their users are only going to use this bookmarklet on one specific site (e.g. the Imperial library site) - if so do Imperial have control of that site and can they just put a button in the page like the journal tool proposal? Possibly they cannot, because it may be an externally provided search page.

Can we find the Imperial ID in a cookie? If not, how is the browser identifying the user to Imperial systems? URL params on every page? Seems unlikely - just thinking through all possible issues here.

WIth the Imperial ID we can create a request on our system related to that ID. Can we get any user metadata from Imperial, either in a dump or dynamically, or if not, is it enough to simplify this request to "An Imperial user"?

What else is needed from the page the user is on, apart from the URL and the user ID, to trigger an ILL? What identifies the thing they are requesting? Presumably it has an ID too, where does it come from? Is it in the URL, or embedded in the page?

How can we trigger the ILL request as if we are Imperial? Either we need to be able to identify in the same way as they do (probably they do not want to / are not allowed to give us this power), or we ping their system to issue the ILL request. So they need to run hooks to catch our pings.

When the ILL is serviced, how do they inform their users? Do they contact the user directly? Do we contact the user again? Do we bother issuing the author request etc, or wait to see how the ILL request goes?

If Imperial are progressing the ILL and inform the user, how can they ping us to tell us it is successful? How can we ping them to tell them it is successful in other ways, and that they can abandon the ILL?

**Comment by markmacgillivray** [comment]
Copying my notes over from mockup issues #408 and #409 

#408 

Using a bookmarklet for this, and having a unique site for each library, sounds a bit different to what I was expecting here based on previous discussions.

Get it now / powered by OAB on the bookmarklet itself makes sense

apart from that, the bookmarklet should remain as close to exactly the same as the normal OAB bookmarklet, and only differ where there is a specific requirement - as far as I can see, that means hiding the open data option, and having a copyright statement checkbox

having a sign up page that is unique to the library is possible, as long as we know how users will be reaching it. The mockup for that page looks fine, but note it may be a sign UP rather than sign IN the first time round

but presumably the rest our OAB site remains the same, and we do not need a custom site for Imperial, for each library, right? Just a unique sign in page?

if we are to identify users by their Imperial IDs only, and not have them sign up to oab at all, we have the same problems as I have described for the journal tool - namely, lack of metadata on our system about the users, and problems for the libraries in being allowed to hand over such metadata about their users to a third party

How is a library going to install this as a bookmarklet and ensure the user can see it? Are they going to manually manage the bookmarks of their individual user accounts, and the display of those bookmarks in their user browsers? If so, on which browsers? Ideally this should not matter too much, but note for those doing UI testing that it may mean the bookmarklet going on to more browsers than have been checked for so far

NOTE that using a bookmarklet as an identified user requires DIFFERENT bookmarklet code to be installed for every user. I am not sure how a library are going to manage to automatically install this, for every user on every machine in their estate. This seems different to me to what was originally proposed, for how libraries would

So it seems either we must expect individual users to install the bookmarklet themselves, or we expect Imperial to do it for them and we pick up their Imperial ID from their login cookie - BUT in this case we will never need to, or be able to, send them to a login page. And we will have the problems mentioned above re. getting metadata about the individual users.

As with the journal tool and the comments I made there, it seems the mockup itself is OK (although in this case I think could also be kept simply as close to original bookmarklet as possible) but there is more complexity behind the scenes to consider.

In this case I think the recap has to be that we expect to identify users by their Imperial ID, that Imperial therefore have to be able and willing to give us metadata about all of their users (or at least provide us a way to look it up per user - and this may require them asking their users more things about them that they do not already know such as profession), or that we simplify how such requests are logged on our system - e.g. the request came from "an Imperial user" rather than "username who is a profession".

There are further complexities to consider behind the scenes, but as long as we know we can get their Imperial ID from their cookie / login session when they click the bookmarklet, then Imperial could install a generic plugin on all machines - and we accept the above simplified approach to what we know about the user accounts. After that, we then discuss with Imperial how we trigger the ILL request into their system and how they inform our system of progress. I will continue those points in the backend issue.

=====================================================

#409 

we should not have people signing up IN the plugin - if they need an account we should direct them to our signup page then redirect them back to the page they came from, as we already do within our own site.

So all we need is the embedded button to open the dropdown, which then asks users to sign in or to go to our site to sign up and redirect them back, then they write their story and submit. Alternatively, if users don't have to sign in, the request would need to be created for an account owned by the journal, but the user could still provide their email address to be kept up to date about it (as a supporter of the request created by the journal account).

if the user already has the plugin installed, the embedded button on the journal does not really have to do anything at all - we could add some code to the plugin to just trigger an opening of the plugin if the user clicks the embedded button but already has the plugin, and not open the embedded dropdown at all - this assumes that journals do not REQUIRE requests created via their site to be created under an account linked to the journal rather than the individual user.

If the journal website works fine on mobile already, this would work fine on mobile too, as long as the journal people embed it in such a way that it still shows up on the mobile version of their site pages.

Two state simplification is a good idea to me.

If we need a "your request will be public" and other caveats, they could just go in the placeholder text in the text box before the user types their story.

Probably the "powered by open access button" sentence should link to a page on our site that explains OAB in the specific context of the embedded journal tool, then goes on to link out to the rest of our site.

Is this embedded plugin only going to do data? I don't suppose we can get publishers who DO charge their users to embed it on their page to allow them to find publicly available versions where they already exist... but most publishers do include the links to people to sign in via their institutional connection etc, so it is not like they are totally unhelpful of people getting free (or at least otherwise-paid-for) versions. This is worth considering, perhaps at least asking - maybe some publishers would be OK with this? If we don't consider the possibility at all, then we have to change the embed later to support article requests - and we are already considering other kinds of requests too, so this is something to consider anyway, we may allow people to request things other than data at some point.

--------------------------------------------------------------------------------------------

So it seems we all agree on:

a simple one-page dropdown
with no tickbox but implicit agreement on submission
extra explanatory text in the textarea placeholder text such as "this will be public"
simplifying / removing signup/signin
I think the biggest point then is signing up /signing in. It simplifies the plugin the most, but is also the most complex to handle. It is not necessarily the technical complexity, but the user workflow, and how the organisations involved want to manage users.

I think all we need for the mockup is that if the user is identified (how they are identified is proposed below), we show the simple dropdown where they read the explanatory placeholder text, write in their own request story, then click the button which has implicit agreement of terms stated below it. But IF the user is not identified, then instead of showing the text box we show a msg saying "this service is provided by oab, you have to sign up / sign in to oab to use it" and instead of the submit button we show a "sign up / sign in" button.

Note, none of what follows matters much for the mockup itself - we just simplify how the tool looks. But we do need to be able to handle the following workflows in some way, behind the scenes. We could just not require sign up on the journal tool. This means we either group all requests from that journal under an account for the journal, OR we identify their users in some way depending on how they manage them. It is possible we could extract user ID from their cookies.

The issues for getting users signed up are:

for users that already have the plugin, we don't have a problem - they're just using the button, and the journal tool just turns into a useful link that opens the main plugin anyway

but it is probably not possible to have the bookmarklet interject in this way - there is no way for the journal tool to know the bookmarklet is present, and no way for the bookmarklet to do anything until after it is clicked

although we may be able to identify a unique user of the journal, we would not know anything about them (nice username, profession, etc). We could ask the journal for this info, but that probably changes their user agreement in ways that are non-trivial for them to solve - and that could differ for every different journal we try to integrate with

we could ask the users themselves to please provide account info to us to customise their requests. But they may not, so in places where we use info about users to display a request, we would be back to having some using user IDs and nothing else, which looks worse on our site

if we stick with just putting all those requests under an account for the journal itself, it is less personal and we cannot allow the individual users to sign in and manage those requests (fix their metadata, etc)

so I think we have to have the journal users sign up to our system too - even if we can identify them via the journal cookies or some other way. Where this is necessary, we should not have users signing up IN the journal tool - for sign up, we redirect the user to our site to sign up, then redirect them back to the page they were on.

we can ALSO offer automatic sign up for journal users, IF the journal is able to give us a list of users and their details. In this case we just make the accounts ourselves without the users having to do it. But as mentioned above, this is probably not within the rights of what the journals are allowed to do with their user data, and they may not necessarily hold what we need such as profession. But if a journal is willing to get it, we could do this. We could also allow journals to provide some sort of automated informing of user account changes. However, this all involves more work, and should only be done if there is a real use case - e.g. an actual journal wishing to give us data about their users in this way

Now, for signed up users, we still need to know who they are when they perform an action on a journal. Issues with this are:

if we can identify a user with a journal by reading a journal cookie, or some other in-page value (this is probably possible), all we need is to match a journal user with their OAB account - so when they create their account, I have the journal tool pass some ID from the cookie and we store it. The first time a signed in journal user clicks the journal tool button, we check if they have an account and if not we redirect them to sign up then back to the page

NOTE though this assumes the journal ONLY shows the journal tool to their signed in users. Is this actually the user story we are building? Are we expecting journals only to offer this to people who are signed in? Aren't they the people most likely to already have access? Would it not be more useful for people who are NOT signed in?

We can also probably put a cookie into the domain of the journal ourselves, when a user signs up / signs in via our own site. This is likely to be the easiest method, and avoids us having to worry about the journals own auth systems. It still requires that we have users signed up to our service even if they have a journal account though, and it still requires that they actually sign in to our service too, occasionally - except for those cases where specific journals are willing to give us that data about their users on their behalf. However I think this is probably the simplest and best solution.

So to recap, I propose that there is no sign in done on the journal tool itself, that there is no using of journal auth at all, that we do not expect journals to provide us user data (until one comes along who actually says they wish to do so), that on first use we have a journal user sign up to our system too, and that we then authenticate them to our system regardless of whether or not they are signed in with the journal

notes for MM:

tool embed must receive a response with a token to save in a cookie under the journal domain
user sign up must record which journal tool triggered it
user submission must record which journal tool submitted it
first click must check for url param - if present, POST back to oab to get user creds to set cookie
on first click if no url param check for cookie - if not present, redirect to oab sign up / sign in
if a user has an account but is using from a journal tool, save the info of the journal tool they used? really we expect these users just to be using the plugin, but they may be on a different browser / device. Save this info to their user account to show we know they did it, and to allow them a cookie on the journal tool too, and probably also save it on the request itself

**Comment by markmacgillivray** [comment]
Issues I will probably want for this, still considering:

* identify user via their being logged in locally already (look for cookie values)
* identify user of bookmarklet if necessary - e.g. have them sign in (preferably not)
* make user sign up to oabutton if necessary (preferably not)
* make user provide extra data to oabutton if necessary (preferably not)
* send a query to the library catalogue of the user and include in results
* send a query to other library catalogues if possible / allowed
* send ILL on behalf of library of user by authorising our oabutton server as the library (preferably not)
* relay an ILL on behalf of library user back to library system for that user (preferable)
* receive trackable info about ILL e.g. an ID number for it
* know when an ILL has been fulfilled... somehow

**Comment by markmacgillivray** [comment]
Moving up to current milestone, I think I have everything here, this should prob just stay open until we start the milestone to actually do this work, hopefully at start of new year.

**Comment by JosephMcArthur** [comment]
I'd actually suggest we make issues for these & a milestone (currently without due date). Then, when we move on it we'll just make that milestone the sprint. Just keeps things a bit cleaner by my taste as we've done the work here. 

Your call though.

**Comment by markmacgillivray** [comment]
removed blocked development tag because there is no actual dev to do on this issue - the ones it spawns may have dev to do though.

**Comment by JosephMcArthur** [comment]
Have made a milestone for this & issue. Will email why.
