### ISSUE TITLE
Guide an author on what they can deposit on the received page using sherpa romeo

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#425]
Needed:

- [x] technical implementation @markmacgillivray 
- [x] copy on what to deposit for white, blue, green, yellow & we don't know @chealsye 
- [x] Maybe: copy in email that suggests we'll tell them what to deposit @chealsye

**Comment by chealsye** [comment]
SHERPA/RoMEO does not have all journals. There are large gaps, sometimes almost whole disciplines. 

Since it says Mark is doing technical implementation, I assume we aren't just directing people to SHERPA/RoMEO, but instead pulling in information from it. I can draft up the copy for this... but what will we do if there isn't an entry?

**Comment by JosephMcArthur** [comment]
I think that's a decision you're best placed to make. I should say, if you
want to make changes to the structure of the page to allow this, I think
that's good. We may not want just a sentence for this, but maybe a whole
"info box" type affair (if that makes any sense). We should probably make
clear what they're allowed to deposit, what that looks like in simple terms
and where to find more info.

On Sun, 22 Jan 2017, 5:53 a.m. chealsye, <notifications@github.com> wrote:

SHERPA/RoMEO does not have all journals. There are large gaps, sometimes
almost whole disciplines.

Since it says Mark is doing technical implementation, I assume we aren't
just directing people to SHERPA/RoMEO, but instead pulling in information
from it. I can draft up the copy for this... but what will we do if there
isn't an entry?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OAButton/discussion/issues/425#issuecomment-274310959>,
or mute the thread

**Comment by chealsye** [comment]
@markmacgillivray, how are you envisioning using SHERPA/RoMEO info? Are the request page like Joe is implying in the above comment?

The problem though is if the journal is not in SHERPA/RoMEO, we won't be able to provide them with information in simple terms. Is it possible to have two versions of the page/email one with SHERPA/RoMEO and one with more generalised information? If a journal isn't in SHERPA/RoMEO what is required to find the archiving policies is to go to the journal website and *hope* they list archiving policies. A lot don't. The majority of medical research will be have journals listed in SHERPA/RoMEO, but we will have gaps for many disciplines. We need to go forward with this and it is incredibly helpful for authors, but I just want us to be aware of these gaps. I can suggest potential ways we can have a backup once I learn more about how this will be implemented.

**Comment by JosephMcArthur** [comment]
I think this was directed at Mark, but, I have some thoughts regardless :)

If the journal isn't in sherpa / romeo, then we should be able to know that
and change what is sent / shown. If the journal isn't in sherpa / romeo I'd
like this to be listed as something people can help with as part of the
request system or that we can figure out on authors behalf. Of course, we
need the fallback of telling them to look, but this is a mostly solvable
problem and we should solve it :)

**Comment by chealsye** [comment]
This issue is vague. I want to know *how* we're planning to do this before figuring out how to handle when it isn't in SHERPA/RoMEO. There's a difference between it being on a request page and in an email. 

@JosephMcArthur, have you looked up archiving policies of a journal before not using SHERPA/RoMEO? It is not always a simple task. We can try to ask people to help with it, but that's involving trust and they may interpret the policy incorrectly. We can do it ourselves, but it is a fair amount of time 2-10 minutes per journal (if it is even on the website!), so staff time is something to consider.

**Comment by JosephMcArthur** [comment]
There are many ways we can implement this, the issue is vague as we haven't decided the best way to do it yet. 

It seems that whatever we do we'll need some copy-guiding authors from whatever information we have. However, I have split off a separate discussion in #483 to discuss questions about what we do when we don't have that information. For the purpose of closing this issue and writing some copy we should essentially say "figure it out yourself, here is what you're looking for". 

For now, I think we should stick to thinking about copy on the received page. Copy inside of emails is likely too complex technically for now and doesn't follow our strategy their. We may just say that we'll give advice on what to deposit.

Does that help clarify what is / isn't in scope for this issue?

**Comment by chealsye** [comment]
I just want @markmacgillivray to tell me how he is envisioning implementing this. You and I do not need to be going back and fort. And then I can sort out copy.

**Comment by markmacgillivray** [comment]
How I implement this depends on what you want it to say ;)

It won't be sending a user away from our site to sherpa/romeo, unless you want that.

I'd envisage that if we know the journal an article is from (which is another gap - we don't always know) then I will have the system look up sherpa/romeo for the journal, and if found, I can stick whatever statements sherpa/romeo provides onto the page however you want them.

Note that what sherpa provides back is a big dataset of various kinds of statement that are sometimes there and sometimes not there. How this is presented to the user as decent copy is the hard part.

Here is an example JSON doc of all the info about a particular ISSN:

https://dev.api.cottagelabs.com/use/sherpa/romeo/search?issn=1444-1586

You'd have to decide what you would want done with that information, and whether it should be put in the email or on the request page - I would recommend the request page, but still it is a question as to where, and how formatted.


Here is a much simpler approach, which is just getting the sherpa colour back:

https://dev.api.cottagelabs.com/use/sherpa/romeo/colour/1444-1586

And from that we could display a particular piece of text on the request page, like: "this article is in a journal that sherpa says is green/yellow/red - that means you can do x y z with it" or if we can't find it in sherpa we just say nothing.

**Comment by chealsye** [comment]
Oh, yes, that's true that knowing the journal is another gap!

I agree that the simplest option is to display the RoMEO color. Do you think we should display the color or just interpret the color and show them an understandable result? Actually including the colors may potentially be confusing for those unfamiliar (and most likely will be) and ultimately are symbolic and extraneous when including the info.

Draft:

> Green - You can archive the submitted and accepted version!
> 
> Blue - You can archive the accepted version!
> 
> Yellow - You can archive the submitted version!
> 
> White - Unfortunately, archiving isn't commonly supported by this journal. 
> 
> No result - Hmm. SHERPA/RoMEO doesn't have this journal. Don't worry - check our Archiving 101 page for tips.

Now technically green/blue could also mean they can archive the publisher's PDF. But 99% of the time it is just the post-print/accepted version, not the publisher's PDF. If we do want to include the possibility of the publisher's PDF then we must send them to out to doublecheck. Although it may still be a good idea to include "Get more details" after each with a link to the SHERPA/RoMEO page so they have access to the full info.

**Comment by JosephMcArthur** [comment]
Thanks for the above @chealsye. I'd suggest we don't have the color in the text at all. I think this is what you're suggesting above, but just making sure that is clear. 

I didn't realise that it wasn't usually the publishers PDF even when it says it is, their color description doesn't make that clear at all. Can you expand on this just so I (personally) understand? If 99% of the time it isn't the publishers PDF, I agree listing what it usually is & adding a more details link is the way to go. Can we make it in any way clearer what accepted / submitted means, and is this common language for researchers to use?

**Comment by chealsye** [comment]
Oh, yes, @JosephMcArthur! I wasn't clear with that. I meant that if we have "green" from SHERPA/RoMEO then we display "You can archive the submitted and accepted version!" 

It is very, very rare for a publisher to be permitting the publisher's PDF (not including when the article is published Open Access and has a CC license, of course). I've read hundreds of copyright transfer agreements for my job and can only remember 4 times when someone could archive the publisher's PDF, and all were tiny publishers. Only one was in the full agreement stating it was the preferred archiving copy, which makes sense, because then the publisher gets advertising! I personally think SHERPA/RoMEO doesn't have the best colour categories... I'm not sure why they lump post-print or publisher's PDF together. Plus another issue of the colour is that sure they may be able to archive the post-print, but depending on where it is going they may or may not have an embargo and we can't tell them in 12 months unless we know what category they are under, the publication date, and where they are archiving (IRs have embargoes more than personal websites).

Well, accepted and submitted are the closest thing someone who doesn't know what pre-print or post-print means will understand it. Technically the full way I explain a post-print to a faculty member isn't just accepted version, but "the accepted version after peer review and before typesetting." I wanted to be as concise as possible if these are going on the request, but we can expand in full detail there or on an archiving 101 of sorts page.

**Comment by JosephMcArthur** [comment]
This is so useful @chealsye, thank you. So, am I to understand from this that even if we have Sherpa Romeo info & we do a good job of getting the author to understand what they need to deposit & they do that - it still might be wrong because we can't factor in embargo periods? 

In case this isn't coming across in the above, I'm actively groaning while writing this.

**Comment by chealsye** [comment]
@JosephMcArthur Yes, but not quite! Not all hope is lot because of embargoes! But we'd need to know the journal publisher. For the major publishers we can use default policies (although tbf the default policies may be new in the last year or three years and not apply to previously published research but whatever). So, for example, maybe we have a green journal from Taylor and Francis. The author can archive the submitted/pre-print version anytime, but ideally we want the post-print archived in a repository. They'd have an embargo of 12 months for a STEM journal or 18 months for a SSH journal (but guess what if it is a library publication there's no embargo period for the post-print to add an extra layer!). Okay, maybe it was mean to use T&F, they are the only major publisher with such a hodgepodge. We can do our best with what we get from SHERPA/RoMEO, but we can't give the author everything. We'll need to link out to the journal's entry so they can see details... unfortunately I can't see how we can know all details unless it is manual.

**Comment by markmacgillivray** [comment]
It is not clear yet from the above what I am to technically implement. Please review and confirm, then reassign once ready.

**Comment by JosephMcArthur** [comment]
- [ ] me to check this issue & put in clarifications for implementation next week

**Comment by chealsye** [comment]
@JosephMcArthur Could we also do a basic archiving page on how it works? Many authors aren't aware of how archiving works and many librarians have asked what we tell authors and how we advise them, so being able to provide that could be useful. I'd be happy to write it up by the weekend if you want to have a page.

**Comment by JosephMcArthur** [comment]
I know this is a dense question, but, what sort of information is on a page like this & can I see an example from somewhere else?

**Comment by JosephMcArthur** [comment]
Okay, some slightly edited copy / approach. I'd suggest, for now, placing after "Let’s help more people get access to your research." 

If Green: You can legally give us the accepted version of your article!
If Blue: You can legally give us the accepted version of your article!
If Yellow: You can legally give us the submitted version of your article!
If no result: SHERPA/RoMEO doesn't have this journal. Contact us for advice on what you can deposit. 
If not allowed to archive: We need a different approach here. @chealsye, how often can we expect this to be the case, is this about 30% of the time?

**Comment by markmacgillivray** [comment]
There's also the case where we don't know the journal of the article. Could just say nothing, but depends on what else you intend to say in other places.

**Comment by chealsye** [comment]
I suggest removing "local" from "local librarian." 

Not archiving permitted is probably more like 5% of the time, if that. Technically almost always for older publications, but more so just not thought about and expressly addressed in agreements, but in those cases authors are unlikely to have copies anyways. There's also legal justification for pre-prints always unless a contract specifically states against in.

**Comment by chealsye** [comment]
Submitted and accepted versions are the friendly way of saying pre-print and post-print.

**Comment by markmacgillivray** [comment]
The four statements above have been added below the relevant "let's make your research..." sentence. They can be easily edited in the page content if you desire. I removed the "local" as stated.

To test this, first there needs to be a test request on dev that we do actually get the journal title for. Try creating a few, and you can see if a journal title is present by looking for the "journal" field in the API response at:

https://dev.api.cottagelabs.com/sevice/oab/request/<REQUEST ID>

You can also test if a given journal title returns a response in sherpa romeo, and if it does you can find the sherpa color too, via:

https://dev.api.cottagelabs.com/use/sherpa/romeo/search?jtitle=<JOURNAL TITLE>

Once there is a suitable record in there, you should see the relevant green/blue/yellow/unknown statement appear on the receiver page after a couple of seconds (Sherpa is not that fast to respond).

**Comment by JosephMcArthur** [comment]
@markmacgillivray what goes after 

> https://dev.api.cottagelabs.com/sevice/oab/request/

I just tried it with a request ID & got just a blank page. e.g 

> https://dev.api.cottagelabs.com/sevice/oab/request/K76Dhg267PdHHRq2m

Also, I didn't see the phrase coming up for _any_ requests on the dev site.

**Comment by markmacgillivray** [comment]
Sorry I missed out the "r" in service:

https://dev.api.cottagelabs.com/service/oab/request/K76Dhg267PdHHRq2m

And yes, only two of the current requests on dev have a journal, and neither of those two get found in Sherpa. However, you can see that it shows the "unknown" message when it does not find anything in sherpa, for example in this response page:

http://dev.openaccessbutton.org/response/A8mW6tKoMYgevByjw

**Comment by JosephMcArthur** [comment]
Changed:
> If no result: SHERPA/RoMEO doesn't have this journal. Contact us or your local librarian for advice on what you can deposit.
to
> If you're unsure what you can legally send us get in touch with us or your librarian for advice on what you can deposit.

to avoid jargon.

**Comment by JosephMcArthur** [comment]
otherwise, this looks okay.
