### ISSUE TITLE
Simplify info collected at sign up

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#432]
I think having a username / full name / profession combo is ott now & we're not getting as many signed up users as I'd like. We have a chance to simply / upgrade to:

* First Name
* Last Name
* Profession (with a refined list)
* Email
* Affiliation (with consideration as to if it should be optional)
+ two usual tick boxes

and after they sign in:
if not on chrome & firefox in the same 
* Option to give us location & a line about how/why we use it

In this edited form the know effects would be:
* first name as what comes up on account page & requests (where we don't have a first name, it would be username)
* request system may need to be updated to include professions
* old professions would still display in the system as usual

Before we implement we should check:
- [x] if people are using the current sign ups system correctly (especially in affiliation)
- [x] how many people chose each profession (especially other)
- [x] how many people give us their email but don't give us their details

The ways this would be better:
* Less need to think about a username
* We can email users with their actual names
* Aligns better with other services (orchid / institutional sign on) so we may be able to skip for many users entirely

Assigning @markmacgillivray & @chealsye to both implement & help decide if this a good idea.

**Comment by markmacgillivray** [comment]
I also agree that we ask for too many names, and I've never liked it. I'd
prefer just using email addresses and nothing else, but then some people
get surprised when their (public...) Email address gets displayed publicly.
So I'd go for email and name - intentionally non-specific as to what sort
of name, or what part of name.

We could say that name will be used to publicly refer to them in requests
etc. Then a user can use their own first name or full name or made up
username if they want to, and it can be optional so if they don't care at
all we just use the email address everywhere.

This also relates somewhat to allowing people to make anonymous requests. I
disagree with the idea of anonymity, although I do like the convenience of
not having to sign up / login to things. So we could also allow anonymous
requests, but that also means not having an email address for the user, or
a way to list their requests. So the anonymous user would have to record
the URLs / IDs of the requests they create, and just manually go to those
request pages themselves if they want to track progress.

For location I prefer the idea of asking a user after sign up if they would
provide it, and for us to explain there why we want it. I don't actually
know the answer to this question myself! I know of course it allows us to
map requests to locations, and making a map to visualise the global impact
of lack of access used to be the sole purpose of the button. But it's moved
on since then, and such representations are less impactful or purposeful
than they once were.

For profession / affiliation, I think they're fine as is and should remain
optional. We may need specific affiliation info when it comes to library
plugins, but if so we can ask for it then.

You can already see how many professions and affiliations have been used by
looking at the admin page.

**Comment by JosephMcArthur** [comment]
Not responding to the above, just noting for myself that we could remove tickboxes for terms assumed to be okay on saving details.

**Comment by JosephMcArthur** [comment]
My suggested path forwards here is to collect:
* First Name
* Last Name

I'd suggest separating these as we can display someone's first name on the site without too many issues I think & combine with last for requests

* Profession
 * Remove: "advocate", "prefer not to say" (only been used 3 times)
 * Change: Doctor --> Heath Professional
* Email
* Affiliation + an option to say none

at sign up & remove tick boxes for terms / privacy instead having copy saying that if you use the service you're agreeing.

**Comment by markmacgillivray** [comment]
Unhide the download box even if people have not completed all the sign up boxes.

**Comment by chealsye** [comment]
What do you need from me here?

**Comment by JosephMcArthur** [comment]
- [ ] I'd suggest we think about a way to make clearer why we need this information (i.e just for requests). I think some brief copy would be fine. - @chealsye

**Comment by JosephMcArthur** [comment]
@chealsye part of this change has been pushed live without your approval on new t&c's copy, can you take a quick look?

**Comment by chealsye** [comment]
@JosephMcArthur Why did you have to push it live? Why didn't you communicate you wanted it done within a day if you weren't okay waiting for me to do it? 

I was literally writing a sentence to communicate this when I received this notification. I had a new account window open. When I refresh it there are no differences, nor when I logout and log back in, so I cannot take a look at what you just added. It does not appear for me.

**Comment by JosephMcArthur** [comment]
it wasn't what I asked you to do yesterday, it was a change to the t&c spoken about above & that has been there a while. I realised after we pushed that I didn't think you'd seen this, hence the comment. The following text is what I think you maybe haven't seen:

> I agree that by signing up I understand that information obtained by the Open Access Button will be publicly accessible, and that I have read the Open Access Button privacy policy and agree to the terms of service

**Comment by chealsye** [comment]
@JosephMcArthur Do you mean this change "Not responding to the above, just noting for myself that we could remove tickboxes for terms assumed to be okay on saving details."? 

Is that quoted information in the terms or on the create an account page? Neither page for me has any changes.

**Comment by JosephMcArthur** [comment]
it's on the create an account page. You may need to do a hard refresh to have it show up (shift + refresh) as always with copy changes.

**Comment by chealsye** [comment]
Oof. That is a big sentence. The old page looked a bit cleaner... but the sentence works. Perhaps the 'I understand' can be removed or removing 'I agree' and beginning with 'By signing up'

My suggestion for why we need details sentence was going to be

> We'll use these details to make article and data requests on your behalf. 

But my concern now is having the "I" sentences follow. Or this sentence could go above the details entry?

> We need some details to make article and data requests on your behalf. 

I'd really like it if we'd consider the look of the page. The blue isn't the best on the eyes and the text has very little height between lines.

**Comment by JosephMcArthur** [comment]
Okay, the page now has the copy changes you suggest & a suggest refinement of my own (combining the I read / I agree statement)

> By signing up I understand that information obtained by the Open Access Button will be publicly accessible, and that I agree to the Open Access Button privacy policy and terms of service

We could also say "by the button" & remove "accessible". I'm in favour of those changes.

**Comment by JosephMcArthur** [comment]
Scratch that, I've put the last two suggestions in to see how the statement now looks. It's a lot better. Feel free to reverse.

**Comment by JosephMcArthur** [comment]
We further simplied this for the release on Monday! Now includes copy changes suggested above.
