### ISSUE TITLE
Anonymity for users during requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#433]
I've had several people suggest that they'd like to see us implement anonymity as part of the request system & on the site generally. This is an issue to think about the implications of that & how to make it work. 

@OAButton/team

**Comment by chealsye** [comment]
I think this would be important. Technically they can to search for an article and the Button will continue to look - but we won't have a way to notify them when they are available. But anonymity would be very important in many scholarly communities where people are worried about providing the wrong kind of pressure to a senior colleague, especially important with datasets that can't find as instantly even if they are available or may soon be. 

Maybe we should be asking - do we really need people to have Button accounts at all? Stories are more impactful with names and titles/institutions can help us when contacting an author, but we don't *need* user info for operate successfully. We need contact info though in order to notify them, but we could permit anonymity as far as the request goes, but we need a contact info to notify them if it becomes available.

**Comment by svmelton** [comment]
I also think this is important.

I've been pondering @chealsye's point, and I think she's on to something. Creating a user account adds an extra step when we may not always need it.

**Comment by markmacgillivray** [comment]
Without user accounts we also can't have people supporting requests - it would be impossible to count how many people support something if we can't tell the difference between people. So a request would just be a one-time thing. We could try showing how many users clicked the button on that URL, but that does not necessarily mean they support the request. 

There's probably also a wider philosophical issue to consider. Whilst I like the convenience of not having to sign up if not necessary, the time I think it is necessary is precisely when people often wish for anonymity. Things change when people are willing to state they believe in a thing - if people wish to remain anonymous for personal reasons, they implicitly put their personal desires above the wider issue of cultural change for the greater good.

So I'd say we have to consider, is our greater aim to help individuals by providing convenience to their (perhaps anonymous) desire, or is it to contribute to efforts to change a culture?

**Comment by JosephMcArthur** [comment]
Hmmm, I think removing user accounts entirely would be too radical. However, I don't think it would be too radical to ask for info ONLY when someone makes a request. I think I've suggested this before, but we decided against it (as it puts a barrier in the way of someone making a request right when they want to). 

In general, I think having some info on people is still useful to provide, normally, authors with some basic info on who they're giving stuff too. This might not be born out by user testing (in which case we'll remove), but I've been told by many it's a good idea to have full names & affiliations in emails (hence adding that in). 

I'd suggest that we:

* allow a user to tag their request as anonymous after they've made it (via the page). This allows them to always do it right at the point they're most likely to realise it's public. This would mean we wouldn't use their name / institution on the site for that request or in emails to the author. Their story & profession could still be visible. 
* allow a user to ask to support a request anonymously when they support it. This would replace their name with "anonymous". Their story & profession could still be visible. 

At no other point do we currently use people's data in an identifiable way. I think if we broad back in depth mapping we'd just hide someone's data entirely if they ever requested anonymity. That's the route that protects folks who've ever felt vulnerable the most & gives us less headaches. If we brought back the map, we could have a "hide my data" button on the account page.

**Comment by JosephMcArthur** [comment]
@chealsye I'd be interested in a Twitter poll seeing how interested people are in something like this? Perhaps just asking generally if they've ever been afraid to ask for someone from someone senior in the field rather than about this feature or us in particular. Maybe posting it on the OpenCon discussion list?

**Comment by chealsye** [comment]
In order to make a culture change, we have to have users. If problems with the signup/login process or a desire for anonymity prevents us from acquiring users, we cannot achieve the changes we want.

How successful have supporting requests been? Are people actually choosing to support a request - or do they just happen to search for the same article? 

Yes, it would be great that people are willing to state they believe in a thing. Article and data requests are more likely to be fulfilled when they are coming from Dr. Smith from Harvard University or PhD student Jane Jones from Cambridge University. But there are people who flat out do not use the Button because they do not feel comfortable sharing their name. We have been told this privately. If a user simply uses a pseudonym then frankly their username doesn’t actually give us any more leverage than an anonymous request. Paper request successes may not be that different between johnneedsresearch username or first name only Sally without a uni  want your paper vs  there have been three requests for your paper (although yes, with anonymity we cannot prove it is three separate people). A researcher is more likely to consider sharing data when the request is coming from someone on their field — but first we have to get the requests. And what if how we are doing things prevents requests? When we ask someone that would prefer to be anonymous because they cannot face the potential fall out of requesting data from a senior researcher through the Button what happens is we don’t get a request at all. Personal desires will always come ahead of the Button. People will mostly even use it for personal desires, because they need access. My OA loving heart wants to believe in the cause more than people, but I cannot knock a young researcher being scared. It’s a real thing and it is important to realise how this may impact our success instead of just wanting to stick to ideals about culture change. Without an anonymous options, we have lost potential users.

Clearly our potential users appreciate simplicity of other services. We’ve simplified a lot, but the signup process is not a positive experience. Perhaps - among many reasons - people have leapt to call oaDOI ‘legal Sci-Hub’ because of its simplicity. 

Removing user accounts would be radical. But we make someone signup and register in order to complete a request, rather than just providing them with a form to complete a request. It is an extra hurdle. I think it is important to ask are we benefiting from it enough? Do we *need* Button accounts? Are we doing this because we have always had them? If we have positive answers to those questions, great! But I think it is worth actually thinking about. 

@JosephMcArthur I like your ideas for anonymous options for requests. I'll do Twitter polls and send out an email.

**Comment by markmacgillivray** [comment]
We're not doing accounts because we always had them, because we didn't
always have them.

If people are calling oadoi legal sci-hub, and if that is a good thing,
does that mean you think that is what the button should be? In my opinion
that's easy and we've been capable of doing it for years. The point of
requests is legally getting stuff that can't be found - NOT just showing
the links to things that can. No other service does this.

However, it may still be true that we don't need accounts for this. As I've
said, I agree of course that no accounts is simpler, and am not against
having no accounts. I don't think a half way option of choosing anonymity
in certain cases is good though, as it doesn't solve the complexity of
having a sign up process.

The solution in terms of ease of use and service efficiency is no accounts
- as long as you don't mind losing the data that comes with them.

But there is a second issue, which is the philosophical one - do we support
users doing things anonymously for reasons beyond that of just making the
service easier to use? Of course I understand that there are people who
won't use it because of various concerns, and if we don't get users then we
don't have requests to act on. My point though is that if we choose to have
anonymous users just because users desire anonymity due to concerns about
the culture they find themselves in, then we, and they, are choosing not to
challenge that culture.

I don't want to do open just for the sake of open. I want to do what works.
If the evidence is that it is easier for users to give in to the prevailing
culture just for the sake of anonymity, then we are supporting the position
that the prevailing culture IS the better one. If people are not willing to
risk anything, then it is because there is insufficient benefit in doing
so. If this is the case, we should give up the pretence that we are
advocating for open society, and instead focus on providing a more
convenient service to customers who have already accepted to remain in a
prevailing culture.

Perhaps this experiment of open access to research just doesn't work
because researchers still do not care enough about quality, and still care
more about their careers. This is an important distinction in the open
source software "movement" that is often overlooked - it started before the
people involved in it had their career interests, and so it has grown up
with them into their careers. Transporting this into research has always
seemed easy because research so often relies on data and software, but in
reality has always been hard because researchers are rarely as altruistic
as we wish them to be.

The two points to me still seem to turn on the philosophical issue - we
have to choose our aim, then communicate that to potential users ( and
they'll either choose to use our service, or not ).

So, are we trying to change cultures? If so, we need people willing to risk
it, and put their identity to that risk. Without it, the demand for change
is only theoretical.

Or are we trying to offer a convenient service? If so, "open" really has
nothing to do with deciding what we should do - at most it may be a
consequence of the fact that open also turns out to be the easiest way to
provide a convenient service (which, actually, is usually the case).

If we are doing the second, then anonymity is both a convenience and a user
desire, so we could just drop accounts. This does not mean we won't also
change cultures, but it would be coincidental rather than causal or
consequential (and as such should not be how we describe our intended
service).

**Comment by markmacgillivray** [comment]
Read the impactstory blog post that Joe linked to:

http://blog.impactstory.org/nps/

Note how much it discusses doing what the users "personally" want.

Also, see how much they consider themselves like a startup.

Are these good things to be doing, do you think we should be more like that?

This is the point that is interesting me right now - a lot of what was research projects / open access advocacy projects have actually just become startups who are getting their seed funding from philanthropic / research sources rather than VC sources. Things have shifted to being about providing services that users personally want. This is not necessarily a bad thing, but IS inherently different to any sort of attempt to change / improve a cultural process - often, a cultural process is not personally desirable but is necessary to meet certain shared desires.

Doing one or the other makes sense, but constantly hanging up on a dichotomy of the two does not. Sometimes it is said "why can't we have personal desires that are also shared cultural desires?" - well, of course we can, but those are trivial and not ones that we actually need to work at. If such desires happen to coincide, they resolve themselves. So we are explicitly talking about the situations where those things do not match up easily, when we are talking about doing something to help move people in a certain direction.

As noted in my previous comment, if academics care more about their career than about improving working practices, care more about not being seen to do something "against the grain" than doing what is necessary to improve, then continuing a false notion of them as being altruistically aligned with whatever improves high quality output is just misleading, and the movement to transplant "open" from software development to academia is essentially failed. This is borne out in a desire for anonymity in requests - such a desire indicates lack of conviction in standing for a change in practice, and if we support that personal desire then we too are indicating that same lack of conviction.

So, if we are just to focus on what users desire, and commit to the startup mentality like impactstory, then let's not pretend we are doing anything greater, because we will not succeed if we are deluding ourselves.

One of the less publicised rules of startups is that doing what the user desires is also NOT their end goal - they do what the user desires in order to monetise them in some way. So user accounts are usually necessary for the monetisation and resource management, but almost never for the sake of serving the user - almost all services you see online could work just as well without signing in, and personalisation is the myth used to pass that off to the user as "meeting their needs".

So where does oabutton fall in this landscape of serving users personal desires? Considering the landscape of what is available, and what people can do themselves, I see something like the following:

1. Anyone can search online for access to something, and find it via sci-hub, icanhazpdf etc, quickly and easily and at virtually no personal cost - BUT it is not technically allowed by their communities of practice.

2. Anyone can also search for alternative sources for the same things, such as institutional repos and so on, and there is a convenience possible there by having an app that finds it for them - oadoi and oabutton both do this, and if oadoi is seen as doing it first or better then we have an issue in how we communicate our capabilities to the world.

3. Anyone can request that an author gives them access to something, by emailing the author. There is also a convenience possible here, in having an app that makes these requests easier and publicises them, AND increases the power of the request by adding identifiable and provable community support - this is what I understand as being the purpose of oabutton, and it is something that nobody else does, and that users could not achieve on their own.


Note that only the third in the list above is unique, and it does meet a user desire, and it gives a reason for oabutton existing, in that it specifically achieves something that cannot be done by an individual, which is namely a group effort in supporting a request.

So, what would it mean to make that anonymous?

It seems to me that anonymity is a user desire more suitable to points 1 and 2 on the above list, which are just the cases of serving a personal desire for access to something, which is already achievable, has no impact on the wider community, and does not leverage the wider community towards solving the personal desires of users nor of changing the attitude of the community towards being more open with research.

This is the problem I have with the idea of anonymisation - it is contrary to the only unique purpose oabutton can serve. I see the oabutton as serving the third option described above, and it is the one that is explicitly NOT anonymous; it involves someone personally and identifiably asking someone else for access. Also, I think it is specifically that kind of action that drives cultural change - being willing to be seen to desire something that is outwith accepted norms, and take the risks associated with that in order to move towards a different practice - and in some way making those risks less scary and less risky by being able to do them as part of a crowd (which is not the same as being anonymous).

Now, it may well be that in actual fact none of our users share that desire, and perhaps even no academics in the wider academic world. Perhaps all they want is access to what they want access to, and they don't care about anything else but moving themselves forward in ways that circumvent whatever the current practice of their culture is. We CAN choose to support them in that. But if we do so, I think there are some existential paradoxes for our project to consider:

* why are we any more useful than sci-hub / other "grey" methods of access (we're not)

* why are we any better than oadoi at being the place people come to conveniently find alternative sources (we're not, and the only way to be better is in comms, not in tech)

* given that we are not an actual startup with a "farming" monetisation plan for our users and their data, why are we collecting user data at all if it is not for the purpose of doing something uniquely possible in the community setting, where users must be identified to show how and why (and how many) actual people want access to something?

* if we go anonymous, and cease to try to take our users on this "identified" journey, how will we differentiate ourselves from the sci-hub / oadoi / other alternatives for achieving that same simple personal convenience desire?

* if we are not differentiated from the alternatives, and we are not monetising the users, and we are not doing anything that cannot already be done in other ways by other people and by individuals on their own, what is our reason for being, and what will sustain us?


I think there is a choice to be made when faced with stated desires from users - one is to pander to everything they ask for, and the other is to think critically about what makes the best, most functional, useful, sustainable service overall.

If we can answer why an anonymous service meets the needs of users and is best / sustainable, then we should be getting rid of user accounts.

But if we cannot, and if user accounts are integral to what we are doing, then we should be considering why what we are doing is not being clearly communicated to the people trying to use our service.

**Comment by JosephMcArthur** [comment]
This is a super interesting discussion to read, certainly a lot to think about. 

I'm just going to drop a note or two here for myself while I was thinking about this last night. Doesn't reflect my opinion on the above which I haven't had time to really process. I'd suggest folks ignore till I have time to articulate! 

* Need info to protect authors from spam & moderate requests? Or, is a good story enough? Could authors ask for info if they want it? 
* Ask for sign up info in the request page itself? 
* We could make a whole request private if user requests anon. This reduces ways to harass, protects user & maintains symmetry in system.
* Need an email to keep in touch & harmonise usage & agree to terms
* Identify by default, anon when required. Or, the reverse. 
* How does this question bare out across the ecosystem? If request system is open approach to requests - what is the path suggested? 
* Not taking full sign up first might radically simplify workflows for institutions (e.g see first OAB mock-up / workflow for websites)
* Only get emails for accounts?
* Move getting apps to the homepage?
* What are the deeper design / ideology questions this is surfacing. How do they play out in other areas? 
* Sign up process is rated as easy in user tests, are we too worried? 
* Account info puts stories in context, what do they mean without that?

**Comment by JosephMcArthur** [comment]
Thanks everyone for the thoughtful comments about anonymity & other issues.

Before I start, for reference, here is the results of the twitter poll: https://twitter.com/OA_Button/status/812035372700024832 re this issue. 

I'm afraid unless it's really useful to someone, I'm not going to respond directly to all of the ideas & points raised above. My person opinions sit somewhere in the middle of what you'd both discussed and I think both perspectives are important. 

Two issues have been raised in this, and I think we need to handle them differently:

1) How we use accounts

@chealsye / @svmelton make good points here, in this new version of the button we don't need accounts for as much as we used to. I think we can start to be more lenient about how we get people to give us account data. In short, I'd suggest we start to delineate between things which need no info, an email, and a full account. Currently, the only thing that needs a full account is making a request. To access some new features ( e.g #333 ) we only need an email. This means I'd suggest we
* allow people to skip giving us details in our current sign up workflow & rely on our current systems to catch when people try to make a request without a full account. To do this we'd:
- [ ] add a skip button to our account create process (on the save details page)
- [ ] ensure our plug-in / request page copy reflects the above
* move the ability to get bookmarklets / plugins onto the front page (answering #447 perhaps). This could be responsive to whatever platform you're on. 
* simply what we collect for account to make it easier #432 

2) Anonymity for users, from authors, during requests

As above, for here I'd still suggest that we:
>* allow a user to tag their request as anonymous after they've made it (via the page). This allows them to always do it right at the point they're most likely to realise it's public. This would mean we wouldn't use their name / institution on the site for that request or in emails to the author. Their story & profession could still be visible.
* allow a user to ask to support a request anonymously when they support it. This would replace their name with "anonymous". Their story & profession could still be visible.

I'd suggest we prioritise changes in 1, and leave changes in 2 for later. 

I may split changes for 1 out into another issue.

**Comment by markmacgillivray** [comment]
Sorry to drag this on further with another essay, but...

1 >

A skip button on a signup process that only lets you skip providing a few optional fields seems a bit... over-engineered.

Note that if bookmarklets are available on the front page, they will have to be a different bookmarklet from the ones the user gets after login. This is not too hard to create, but it does mean that if a user then does sign up, their account page would have to somehow prompt them to install the proper bookmarklet.

There is no way to update a bookmarklet after it is "installed" by a user so we can't add their key to it like we can with plugins. Also there is no way to know if a user has a particular bookmarklet in their bookmarks bar, so we could not know whether or not they already had the bookmarklet prior to signing up - it would have to be purely textual explanation that encouraged them to check, then explained to them to get rid of the old bookmarklet and use their new one instead. This could be pretty clunky.

2 >

In the case of allowing a user to tag their request as anonymous after they've made it, there are still technical and non-technical issues to solve before the proposed solution could be implemented:

Technically, this could get tricky once there is automation in place - if a request has all necessary data and is capable of being sent to the author, and if we remove the need for an administrator to move the request to the status that kicks off the request process, then the request would get sent to the author before being marked as anonymous. A timeout on this would be a weak way of offering the anonymity. Also, if you're really wanting to be paranoid about anonymity, if the request exists at all in the system with any relation to the user that created it, it would be trivial to monitor the API for new requests being made and to track what users were creating certain requests. So if we are going to offer anonymity it has to be tagged as anonymous BEFORE the user submits the request, eg. as a new option on the plugin UI itself.

Non-technically, I still have issues with anonymity in the context of what we are claiming to offer to people. For example if enabling anonymous requests requires changing the plugin to have that as an option, it means making anonymity a far more highly visible option, which encourages people to question why they need to identify themselves at all for any request - as a user I'd wonder why I had been prompted to sign up for extra functionality, just to find I was then given the option to use that functionality anonymously. We would also risk implying that anonymity in requests is something worth having, which I think detracts specifically from the implied purpose of a request via our system - a public request from a community of people showing their support for open access to research, in order to stand up for change to accepted academic practice.

If you're not willing to put your name to something that changes the norm within your community (such as getting researchers to be more open with sharing their research), then why bother using our system to request access, if not to promote change within the research community? Without that intent, our service falls back much more towards a service for individual users, for simple personal gain / convenience, which can already be achieved in other more indirect ways such as sci-hub, icanhazpdf, etc, which I thought is what we are specifically different from.

Conversely, this could mean that the purpose of the requests system is not (or that I misunderstand) what we claim it to be.

Consider change.org, which I take as a good example of what a request is like - a petition to change something, to petition for access to a specific article, and also to change how people think about sharing their research. As far as I know, there is no way to create a change.org petition anonymously, and the idea of an anonymous petition that nobody is willing to identify with seems strange to me.

It IS possible on change.org to sign your support to an existing petition then unticking the box allowing them to use your name and story on the petition, and in fact it is even possible to support the petition without signing up at all. We could add that to our request UI, and could remove the login requirement too. However, I'd still argue that identifiable support is better than anonymous support in our case, given what we envisage the purpose of our requests system to be, and how it differs from other (anonymous) ways of getting access.

Note too of course that anyone who actually wants to remain anonymous in our system could already use a throw-away email address and a fake name anyway. Our entire concept of creating accounts before making requests and of individuals identifying themselves is predicated on the idea that they will honestly want to do so, in support of the claimed purpose of the requests system - and if they don't want to do that, they can already achieve anonymity anyway by just lying.

**Comment by JosephMcArthur** [comment]
Thanks again for this Mark. Responses:

1) Given the above I'd suggest we simply unhide the download section from the account page (even if you haven't "saved details". We also shouldn't display bookmarklets on the frontpage if you're not signed up, but we can consider other options in #447. 

Thoughts on that as a way forwards?

2) For now, I'd suggest we move talking about this off the "front burner" in favour of focusing on some larger problems with the system. The more we talk to more I think we're going to need a lot of resources to implement this in a way that's not immediately broken, and that a poor implementation could have bad consequences.

**Comment by markmacgillivray** [comment]
1. Yep, sounds like a neater solution - just lets people get on with what they want to do, and other parts of the system already prod them for extra data when we want it anyway.

2. Yeah - it's not that I'm against going one way or the other, but it feels more complex than it looks, and requires more thinking around what we are trying to do.

**Comment by JosephMcArthur** [comment]
Archiving some old discussions / issues.
