### ISSUE TITLE
Access of OAButton as web service

### ISSUE THREAD

**Issue by larsjuhljensen** [OAButton/discussion#434]
It would be great to have a way to access this as a web service, e.g. via a REST API. I do not find it on the website, but it was hinted to me on Twitter that this in fact exists (https://twitter.com/Mcarthur_Joe/status/812277276217851904)

This could be useful for people like myself who work on text mining and thus often need to download many articles.

**Comment by markmacgillivray** [comment]
Yes there is an API. It is a question for @JosephMcArthur whether we are publicising it or not - as you point out, the site does not mention it at the moment. @JosephMcArthur should we have some content on the site about the API?

@larsjuhljensen however I am not sure how our API would help you with text mining - we can't provide you with articles. We can provide you with links to where we think there is an open version of an article, but you would still have to get that article yourself. If what you want to do is pass a URL to our system and find out if we know of any available sources, then what you want to do is something like this:

curl -X GET 'https://api.openaccessbutton.org/availability?url=http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0167164'

View that URL in your browser and you will see what the response looks like. You would be interested in the data.availability section, which is a list of objects detailing what we have found. Each object will have a type (and at the moment they are most likely to be only articles) and a URL which we believe points to an openly available version of an article.

NOTE that the URL we give you could still be to a splash page rather than the article content itself, so you would need to check whether you are receiving the splash page or the full article.

If we can't find any available sources, then the data.availability section will be empty.

The data.requests section will show any requests that we already have open for the given URL, but this is probably not much help to you in getting materials for text mining. Perhaps longer term, if you wanted to, you could maintain a list of articles you want, and you could track the requests we have, and when their status changes to success you would then know you can do your text mining on that article.

For completeness, so you know, the data.accepts section lists what sort of requests we can currently accept. If a type is already available or already requested for a given URL, then we will not accept requests for that type at that URL again, so the data.accepts section would not show it. This is why on the above example you will see that the data.accepts section lists that it will accept type "data", but it will not accept type "article" because we can already find an article for this URL.

**Comment by markmacgillivray** [comment]
@larsjuhljensen it would also be possible for you to initiate requests via the API, for things you want to text mine that we cannot already find access to. You could also add your support to requests that are already open for URLs you are interested in. Let me know if you want more details on how to do this.

@JosephMcArthur you may want to consider if supporting this use case is something you want oabutton to be doing - if so, we need to have more info on the site about using the API. Particularly, the account pages no longer show any info about user account API keys, so at the moment nobody can use the API to do anything that requires authentication. Also, do you want any limitations on how much a user can use the API - note that if for example @larsjuhljensen wants to text mine 1000 articles and issues 1000 availability checks, this may not be too big a deal but if 900 of them come back unavailable and he then wants to programmatically create 900 requests for those articles, there will be a significant increase in how much work the oabutton staff managing the requests have to do.

**Comment by larsjuhljensen** [comment]
That looks really useful, thanks! I did not expect to get the document directly, just a pointer to where I can probably find it. I already have some code for automating navigation of splash pages to find the actual document, although it needs to be improved.

If I were in your shoes, I would probably not want to enable the API to also initiate requests. You could all too easily end up being flooded that way.

**Comment by JosephMcArthur** [comment]
Thanks for making this issue Lars, and for your interest in the system. 

@markmacgillivray I think we should take some time to document the API soon & add a docs / api page to the site that contains this info. If they need a key, then we can display it there. 

In the long term I'd like to see us be able to make requests via API and we should do some simple documentation (even just internally) of that now. 

Right now though I'm not sure how to prioritise this, it would be useful to know how long you think it might take to do this.

**Comment by JosephMcArthur** [comment]
@markmacgillivray to stop me blocking everything here, lets:
- [ ] document the find API
- [ ] leave a note about the request above on /api saying that if folks would like to use it, they should get in touch.

**Comment by markmacgillivray** [comment]
API docs are done on the dev site. @JosephMcArthur do you want to check this with Lars etc, or will we push it live?

**Comment by JosephMcArthur** [comment]
@larsjuhljensen do you want to take a look, would love your feedback on the docs. You can see them here oab.test.cottagelabs.com/api 

@chealsye can you write a mini blog for this please?

**Comment by larsjuhljensen** [comment]
Thanks everyone! As much as I'd love to contribute as a tester, I don't think you should wait for me. Realistically, there is sadly no way I would manage to look at it this week or next week.

**Comment by JosephMcArthur** [comment]
Okay thanks @larsjuhljensen, we won't wait on you to release it but if you get a chance to take a look we'd deeply appreciate it.

**Comment by JosephMcArthur** [comment]
am handling chat for api blog elsewhere, closing this for now
