### ISSUE TITLE
receive trackable info about ILL e.g. an ID number for it

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#449]
By @markmacgillivray from #419

**Comment by markmacgillivray** [comment]
We know we can't get trackable info back immediately because we are just POSTing to a script that will collect data and run the ILLs at a later date. However, we will be asking the user for their institutional ID / email address, and from that we can look up their ILLs and know when they are fulfilled, with a cron job.

For this we need either access to an API key that allows this lookup, or an additional endpoint at the library that we can call to trigger the lookup and return the results to us.

This can probably not be completed in this milestone as it depends on decisions at the library, which they probably want to take after seeing the first version.

However, we now know from this what we need to do to achieve it, and a cron stub is in place and just needs an endpoint or api key to start running it.

I will therefore move this issue to Library 2 milestone

**Comment by JosephMcArthur** [comment]
Done. Old, and not needed. Closing.
