### ISSUE TITLE
Say no to naughty strings

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#472]
I tried to test our input boxes for input we wouldn't expect, but these folks have a much wider array of strings.

Might be worth testing these at some point: https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by markmacgillivray** [comment]
Ooh, pretty handy. I have already added something to the accounts and requests endpoints that will silently refuse them if they put in any js code - I purposely did not bother with a UX aspect to this because anyone doing so is being naughty on purpose. But I suppose it may be useful to also catch things that people may not intentionally be being naughty with, and flag them a UI error.

**Comment by JosephMcArthur** [comment]
Makes sense. For me, I thought it would be worth:
- [ ] adding a note to our testing guides about testing odd strings (with
reference to this)
