### ISSUE TITLE
Requests not displaying in Firefox

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#479]
Requests are not displaying in Firefox, but are displaying fine in Chrome. I've double checked this problem on my work computer's Firefox and it is also not displaying. Both are macs. 

Chrome
![screen shot 2017-01-16 at 23 58 28](https://cloud.githubusercontent.com/assets/9299248/22008295/e5224ccc-dc47-11e6-9db4-46b5bffe1742.png)

Firefox
![screen shot 2017-01-16 at 23 58 20](https://cloud.githubusercontent.com/assets/9299248/22024867/6e42c684-dc99-11e6-86f1-c248e101e42d.png)

**Comment by markmacgillivray** [comment]
That is very strange - and turns out it appears to be a problem with firefox accepting our secure certificates. 

On my linux machine it does not work, but on my mac it does - my mac has a new version of firefox, whereas my linux machine does not.

A few types of secure certificate can no longer safely be used because they are not secure anymore, so we don't serve them. But I would have though this would only affect pretty old versions of firefox (like my linux machine).

@chealsye can you find out what version(s) of firefox this is failing for?

**Comment by chealsye** [comment]
Firefox versions 47.0.1 and 50.1.0. Apologies for not including that originally. The 50.1.0 is my personal computer and when I checked the version Firefox told me it was up to date.

**Comment by JosephMcArthur** [comment]
I can't replicate this on 50.1.0 (which happens to be my version)

**Comment by markmacgillivray** [comment]
Hi @chealsye sorry I forgot to get back to you on this, I have tested on the 50.1.0 version of firefox on mac and it works now. Can you check again? And let me know if you are on a version other than mac, just in case?

**Comment by chealsye** [comment]
@markmacgillivray I can now see the details in firefox, thanks!
