### ISSUE TITLE
What steps should we take when we find the OA version without contacting the author?

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#481]
This happened to me yesterday. 
I was searching the web for an author's email and accidentally found a link to the full text article that our user was looking for.

Here is the request https://openaccessbutton.org/request/G7wQeowq9ww7kyLgd and here is the paper https://www.researchgate.net/publication/304063680_Systemic_lupus_erythematosus

**Comment by markmacgillivray** [comment]
Ooh, this is interesting. As an admin, you should be able to go to the request page and see the "responder" buttton, that takes you to the page the author gets a link to. There, you have options to provide the content, including giving a URL to where it is. BUT at the moment it is assumed that the author does this. We don't currently send any automatic emails but once we turn them on, we would end up thanking the author for responding even though they never did.

We do already have a plan for what to do when we find something on our own weekly search, which we will be turning on next week - and in that case, we send out different emails that have already been written.

So, I think the solution could be quite simple - if you are an admin and you go to the responder page, you could provide the content that you find, and all I need to do is add something to identify that the content came from an admin rather than an author, and then we can use the same emails we already have for the weekly checks.

This also brings up the point we have previously discussed, which is that we could actually let ANYONE provide content if they think they have found it. Again, because we already have the infrastructure in place as described above, all we would need to do is some little updates to the UI and passing some params to identify that it was a user rather than the author that provided content.

**Comment by markmacgillivray** [comment]
Just to follow up about your actual current problem - you can go to the responder page and provide the URL. This should change the request to successful, but won't automatically send any emails to anyone. I believe at the moment it is you who is keeping an eye out for successful requests anyway though, so then you can follow up however you prefer, or check with Joe what he wants done on successful requests at the moment.

**Comment by JosephMcArthur** [comment]
This is a complex issue, I'd prefer that we weren't submitting research
gate articles without further discussion. It's not that I think we 100%
shouldn't, I just think we need to be explicit about it.

If you find versions via an authors own page, I think they can be
submitted, despite not being perfect.

Where there is a research gate copy available, I think we need to change
our comms to an author as part of the request.

Anyway, this isn't a full response, it'll take longer to write than I have!

**Comment by JosephMcArthur** [comment]
So, in summary. @markmacgillivray the changes you suggest that would allow this to be done smoothly should be put in.

**Comment by markmacgillivray** [comment]
This is already technically in place - the responder page has admin submit buttons.

**Comment by JosephMcArthur** [comment]
Okay, @natalianorori you can do this, but for things like researchgate / academia. If you find versions via an authors own page (on a personal site, or similar), I think they can be
submitted, despite not being perfect.

**Comment by natalianorori** [comment]
Noted!
