### ISSUE TITLE
How to get information on journal submission policies when Sherpa Romeo doesn't have it

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#483]
As discussed in #425 

Some ideas for tactics include:
- [ ] emailing journals to ask
- [ ] figuring it out ourselves
- [ ] asking (or paying) the community to help
- [ ] getting sherpa romeo to do it

and when we do this we should aim to contribute it back to sherpa romeo. 

Before investing in this issue, we should complete #425 & run an analysis on our backlog of requests to see how big an issue this is.

**Comment by JosephMcArthur** [comment]
Probably linked to #754

**Comment by JosephMcArthur** [comment]
@chealsye could we engaged with a group of librarians, like we're currently planning with the request moderators, to help with this?

**Comment by JosephMcArthur** [comment]
Like, I'm kinda of thinking we could take the current sherma romeo dataset & turn that into a google sheet. Then, add in a list of journals that we don't have info for (pulled from big TOC sources we pulled for the DOAJ sources) and ask people to fill stuff in as needed. We could highlight ones with requests currently associated. 

That sheet could be sent to shera-romeo periodically for them to do with as they please. Otherwise, it could be left as a sheet or turned into a microsite if people want.

**Comment by chealsye** [comment]
Potentially. But that is asking labor for free labor, so its success would depend on low commitment and/or the Button providing enough to the librarian (partly why I wanted a librarian notification system so librarians are getting something out of the relationship). However, I had my own such datasheet of education policies that weren't in SHERPA/RoMEO, so perhaps others do and would want to collaborate. I think there would be some interest and all the info would be accessible, so it is possible!

SHERPA/RoMEO isn't very lovely about accepting contributions. Every single time I've submitted a new journal or corrections they weren't accepted. If you want to send it periodically for them, I would suggest getting them on board ahead of time and find out exactly what they need otherwise everything might get rejected.

**Comment by JosephMcArthur** [comment]
Could you share the spreadsheet with me? I'd love to see what you thought was important to keep. I'd bet you're not alone in having this sort of data!

**Comment by chealsye** [comment]
The spreadsheet is from over 4 years ago. I don't still have access to our department's shared files. The spreadsheet would've just included the journal name, publisher, archiving policy, and archiving policy. It wouldn't have had all the details needed for SHERPA/RoMEO though, such as links and the ISSN.

**Comment by JosephMcArthur** [comment]
From a technical perspective, what we'd need here is for a spreadsheet to be able to feed info into our shera.romeo checker. It would probably need only two fields, journal name and sherpa remeo colour. 

After that, how we fill the sheet is another problem but at least it lets us experiment with that.

**Comment by JosephMcArthur** [comment]
@natalianorori would the above spreadsheet work for you? We'd need a dev & live version. Also, have you looked at that sheet from Penn too with this info? 

Once we have the sheet, then we can figure out the best way to get it filled with all the info needed but start to make some easy wins.

**Comment by JosephMcArthur** [comment]
Whatever we have here will need to track #992

**Comment by natalianorori** [comment]
Yes, the spreadsheet would work for me, I'd encourage us to have it. I have not looked at the sheet from Penn, do you have a link?

**Comment by JosephMcArthur** [comment]
This is the penn thing I think: https://pubpolicy.library.upenn.edu/. 

Also, we'd need to:

- [ ] add a way to flag & correct edge cases by journal and article (conceptually like the redirect system for availabilities)

**Comment by JosephMcArthur** [comment]
Okay, updating thoughts here. 

I think we want a spreadsheet that can *override*[1] SR data with other sources and provide that info to the request system. Eventually, it might become the primary source. There will need to be a dev & live version. The sheet should start by having whatever fields we currently pull from sherpa remeo in it (including new things in #922, maybe just everything they have), with room for identifiers for lookups (like ISSN or Journal names).

Here are two blank sheets that can be used:
* https://docs.google.com/spreadsheets/d/1I8KOV9vAEoZU9UzmsX3xAqfK7Rx7uqkr7RY_9p7Lg0o/edit#gid=0
* https://docs.google.com/spreadsheets/d/1GGo_kOWAdra8uy2qAz4wg7hLdXuxbw2JBJCt-cPaVJI/edit#gid=0

I'd like to keep us using SR as the main source since I suppose it's being updated from time to time.

[1] i.e if a journal turns up in both sources, trust the sheet.

**Comment by markmacgillivray** [comment]
There definitely are publishers that have different policies for different journals though. Also we are unlikely to know publisher but not journal. Similarly just because a paper from a journal exists in a repo does not mean that all papers from that journal have the same policy.

For the ML approach, we need to know that there is an actual way to identify the missing data first - there needs to be a pattern that can be learned, and it has to be one that is actually predictive. And it depends how accurate you want to be.

Is SR still being updated? It wasn't clear if they ever hired anyone to keep that going. If we also start managing a sheet, then I think we should also make an effort to get community involvement in maintaining it - SR never seemed to want to do this. If librarians are interested we could have a sheet and/or a simple UI onto it, and still also compare/check/ingest from SR if they are updating that too.

Unless SR are definitely going to start keeping it up to date and increasing coverage, I think we should move to having our own version as the leading version, and just ingest from SR as a secondary source for that.

**Comment by markmacgillivray** [comment]
Which looks like what Penn have already done anyway.

**Comment by natalianorori** [comment]
> There definitely are publishers that have different policies for different journals though. Also we are unlikely to know publisher but not journal. Similarly just because a paper from a journal exists in a repo does not mean that all papers from that journal have the same policy.

I agree with this, from what I've looked around, policies are generally similar but what changes is the embargo period. e.g elsevier has a bunch of different embargo periods for their journals, but the rest is pretty similar 

> I think we should also make an effort to get community involvement in maintaining it 

Librarians have confirmed than whenever they submit info to Sherpa Romeo, it never gets updated and they never get an answer. Our intention for this sheet is to share it with the community, and then having it being self mantained by it. :) 

>  I think we should move to having our own version as the leading version
+1000 to this. 

Mark, let me know what is needed from me.

**Comment by natalianorori** [comment]
Penn's database is very good, but searching through it is not as practical as searching through Sherpa/romeo ( yes, I am saying that). It's also missing a lot of information and there are a lot of clicks involved in order to get to the policies. their search bar is also harder to get to. I think that if we are going to make this approach, we should make it as simple as possible for humans to use. 

in my opinion, Looking through an excel sheet would still be easier to find information in than in penn and SR.

**Comment by JosephMcArthur** [comment]
Done a few bits here. 

- [ ] move penn data into a sheet
- [ ] ask friends for "their" local sheets
- [ ] write up database structure / ideal data structure: https://docs.google.com/document/d/1wZTa0Qs2azQSStwOKx5Vz8_ay28X2j739u_lWxoTNhk/edit#heading=h.bi4obqhy34ew

**Comment by markmacgillivray** [comment]
This is assigned to me but I don't think I can progress it at the moment. @JosephMcArthur is this better assigned to you at the moment? Just checking what things I can work on next.

**Comment by JosephMcArthur** [comment]
Yes, sorry, it's on me.

**Comment by JosephMcArthur** [comment]
Riiight, progress! I have the Penn data, and a metric tonne I found from publishers, in a sheet: https://docs.google.com/spreadsheets/d/1Oy12v5dRgwBFr3VfogOOepPXXswdCYjv6wn_6lMK57I/edit?usp=sharing that's representative of the sort of data we'll want to be feeding in here. 

At https://docs.google.com/spreadsheets/d/1Oy12v5dRgwBFr3VfogOOepPXXswdCYjv6wn_6lMK57I/edit#gid=1540153499 there is what amounts to a simplified, machine friendly, database of permissions for journals. It would be super helpful to get some feedback on this soon. 

If we're happy with the approach, or can stay flexible, we can start to move to this as our "first port" for permissions info.

**Comment by JosephMcArthur** [comment]
Closed by #1219
