### ISSUE TITLE
Feedback on proposal from Dissem.in on guiding authors on what to deposit

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#488]
https://www.eleves.ens.fr/pads/p/dissemin_institutions

**Comment by wetneb** [comment]
And this one: https://www.eleves.ens.fr/pads/p/dissemin_crawling

**Comment by markmacgillivray** [comment]
What sort of feedback are you expecting? And where do you want me to put it?

**Comment by wetneb** [comment]
@markmacgillivray as you want! inline or here, or via email…

**Comment by chealsye** [comment]
My biggest concern is using ROAR to tell authors that they can archive something because of their institutional Open Access policy. Are you identifying the rights on the type of policy? Some of the policies do have agreements that supersede any publisher contract, but most authors will not view it that way and won't be comfortable (if they know what the publisher policies are!). A Harvard style policy only holds legal weight if there is a written affirmation with consent of the author -- not all universities actually include this in their repositories though. So, I think the ROAR path has some obstacles to being valid advice.

**Comment by markmacgillivray** [comment]
@wetneb as @chealsye has mentioned, my main concerns would also be around what you hope to achieve with the data you are able to extract. We (at Cottage Labs) have already previously done what you are describing, in roughly the same way, both for ourselves internally and as a demo for University of Nottingham who were considering updating their sherpa/romeo and opendoar systems. Opendoar is like ROAR by the way, not sure if you mentioned it already, but it had the advantage of being curated by a human. However, Nottingham were not able to proceed with the update due to changes in their infrastructure and plans with a governmental body here in the UK (jisc) that has blocked them on being able to move forward, I think. This has also led to them not having a human curating their collection any more.

You can see the demos that we previously made if you want to look for useful code, and they also contain methods for extracting the data from opendoar, sherpa/romeo, and ROAR, I believe. (Also btw I have indexes with all their data in them too :)

Check the READMEs of these:

https://github.com/cottagelabs/opendoar
https://github.com/cottagelabs/oarr
https://github.com/cottagelabs/roar2doar

I would say that it would not be hard for you to get all the data you want, and build the model you describe, but the problem is that the data just does not contain logical means of programmatically deciding WHICH licence condition is the relevant one. They are often just lists of strings written by users or authors or publishers and all thrown in together. You can get the sherpa/romeo red/yellow/green "accessibility colour" but getting more specific than that is basically a lucky guess.
