### ISSUE TITLE
Allow author to validate they're the author of a paper through login

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#503]
Aim here to make "contact us if you're the author" more actionable & not need our involvement. Seems our new /request page will make it much easier for authors to see if they're in the system

So, instead of contact us if you're the author we'll ask them to login with their email (where we can then verify they have that address). If their address matches the address in the target field then they'll have access to submission box. 

There would be a way to game this, simply change the email targetted. However, this is a flaw with the current system anyway. 

- [ ] implement technical side @markmacgillivray  
- [ ] write copy for change @chealsye

**Comment by natalianorori** [comment]
I think this is a good idea, but what if the author has different email addreses and the one they enter doesn't match the one we have? Perhaps we should ask them to enter the email address we specifically used to contact them.

**Comment by chealsye** [comment]
What copy needs changing? Is it "Can you provide this content? If you have the right to share it, we'd love to hear from you. Please contact us to discuss providing a copy." or something else?

**Comment by JosephMcArthur** [comment]
That's it, just need suggested copy for if authors can use the login
system.

**Comment by markmacgillivray** [comment]
Hmm, thinking through this, it is not possible to do.

regarding @natalianorori point - If the author was viewing the page and also was the person with the email address we already had for the request, then they would also have already received the request email asking them to respond, so they'll have the responder link.

So we would only be considering cases where an author is looking at the page and is NOT the person with the email address we already have (if we have one at all).

Also @JosephMcArthur assertion that the new request system will make it easier for authors to see they are in the system is not true - either they are and we have already emailed them so they know, or they will not find themselves by their email address because we don't have it recorded against the request.

But authors could still be searching via the titles and find things we have requests for but where we do not have their email address. So this is the case where the idea of this issue could be applied.

BUT this cannot be done securely - if an author logged in and we sent them a link to confirm they are the author, we would then essentially give them the responder link. Unfortunately, there is no way to do this that would not also stop anyone else from signing in and saying the are the author and getting the link.

So we are back to the problem already discussed - either we make it so that anyone can respond with content and we say "only upload stuff you have permission to upload" (this idea was already vetoed though for not being secure enough) or we have to stick to what we currently have, which is that an author can contact us and talk to a human via email, and we then make a decision about if they are the author or not.

I will leave this open for you all to review, but will unassign myself as there is no technical solution here.

**Comment by JosephMcArthur** [comment]
Okay, this makes sense. Lets close for now, but, in think we may need to reopen in the distant future once / if we build more ways for authors to find requests e.g:
* by seeing a request in share
* by an intergration with orcid which showed requests on their profile
* by displaying request links through hypothesis comments on papers
etc
