### ISSUE TITLE
[UI convention] Tick exclusive choice with several choice tick

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#512]
@jibe-b commented on [Fri Feb 03 2017](https://github.com/OAButton/odb/issues/62)

Please forgive the approximative vocabulary I might use.

When entering a new request on https://openaccessbutton.org/request/new then entering a DOI
the next step is to tick either the request for
[ ] article
[ ] data
and the tick boxes _behave_ like unique-choice boxes, though _looking like_ multiple-choice boxes.

![tick-boxes](https://cloud.githubusercontent.com/assets/6146483/22591292/14fdbd30-ea14-11e6-878a-6d02ff4b4ef3.png) should look like ![single-choice-tick-box](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTrFyRwzJPBuTuSm1HTb9fUlpH7IoZDa737FVN9V8qwfp4_vPDXtA)

---

@JosephMcArthur commented on [Fri Feb 03 2017](https://github.com/OAButton/odb/issues/62#issuecomment-277256946)

Thanks @jibe-b, this is a good point! I'm going to move this to the repo we actively use for issues /OAButton/discussion

**Comment by markmacgillivray** [comment]
This is because originally it was possible to select both, but then it was decided to only allow one or the other, and to see how that goes. It could be changed to unique selectors now, but this will become obsolete once the new request UI changes to be more like the extension, which should be done soon.

**Comment by JosephMcArthur** [comment]
closed on dev
