### ISSUE TITLE
Button discovering non-OA articles in repositories

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#522]
Two recent requests were either from a repository or incorrect pointed a user there when the article was not available. I came across them when trying to find users to contact about their Button experience.

The first was a 2010 article that has a [record](https://biblio.ugent.be/publication/827711) in the University of Ghent's repository, but is only available full text to those at the uni. An IR would take this route to comply with an author's wishes or a publisher's requirements for when uni intranet is permitted but not public access. But it has been 6 years and it is an Elsevier published journal, so I'm doubtful this is a publisher requirement. The larger problem for us is that the Button think it is available. Not sure how we fix this, since some articles in this repository are fully OA and plenty of IRs do this for embargo periods. ([Button Request](https://openaccessbutton.org/request/QELQxZHx9W7L4FnAX))

The same thing happened when a user was trying to access a Lancet article and was referred to the UCL repository where it was just a metadata record.

> Was initially trying to get access to lancet article herehttp://www.thelancet.com/journals/lancet/article/PII0140-6736(91)93068-K/abstract OA button brought me to this UCL repository but the article isn't actually available here either. I would like to read the article to learn about health inequalities for a sociology essay ([Button Request](https://openaccessbutton.org/request/SuNHuN9LBycFSkR3Q))

Any ideas of how we address this problem?

**Comment by markmacgillivray** [comment]
This is a known problem, and is as you describe. The articles ARE open, by the definition, but are NOT accessible to someone without the relevant login. I have already been looking for ways round this, but it is impossible - because the articles meet the definition of open, the sources that we use to check for existence in repositories also count them as open, and do not indicate whether or not a login is required.

I do know a technical way round this, and I have suggested to @JosephMcArthur that it is probably our only option for solving this problem and actually getting people things they can access - but it is not straightforward, and is unlikely to be able to cover all repositories right from the start.

However if this is impacting on user experience already, we should prioritise this work in an upcoming sprint. It does also add a fair bit of ongoing technical overhead to maintain, but again, with no other option we should just deal with that.

**Comment by JosephMcArthur** [comment]
have added this url to the black list & added a redirect for this domain to full text
