### ISSUE TITLE
Differentiating help status on requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#528]
> We should also get a new status to differentiate our "help" requests that have not been managed yet from the ones that have been managed, but haven't find the author's email.
>for example, once we notify the user that we can't find the author's email and that is the reason their request is taking longer, changing their request status from "help" to something else would be useful to avoid confusions.

**Comment by JosephMcArthur** [comment]
currently we ask folks to help us get the title & also emails

**Comment by natalianorori** [comment]
I was thinking about changing the status from "help" to "hold" once we notify the user that we are missing the email. However, this would only apply to old requests since I am trying to handle the new requests on "help" status immediately. @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Hmmm. I'm struggling to understand the utility of this now..

**Comment by natalianorori** [comment]
This was useful with requests where we couldn't find author's emails, this
is not the case now. The system has evolved a lot since we created this,
emails are found way faster and I don't think this is as necessary as it
was before. (we almost always try to find the author's email and contact
them immediately).
