### ISSUE TITLE
Refine request management handbook for others using the request system 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#545]
@natalianorori this should lean on what we've already made but help library staff trying to moderate the system do that. Can be pretty simple! 

We'll also want to round up other info on the system for this (e.g the flow charts)

**Comment by natalianorori** [comment]
How should the handbook for libraries be different from ours? We currently have an onboarding document (OAB 101) which explains more about the button and our Request System Guide which focuses only on the request system. 
 if we are going to have a handbook for external groups, should we include on it more general info on general stuff instead of jumping directly to the system management?

**Comment by natalianorori** [comment]
I think this was achieved with the new onboarding docs for volunteers, let me know if you agree @JosephMcArthur

**Comment by JosephMcArthur** [comment]
yes! aces
