### ISSUE TITLE
On the find loading spinner have a cute phrase about how we're searching thousands of sources for access! 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#567]
Could link to our new /sources page?

**Comment by chealsye** [comment]
I'll have a think. But /sources page? When was this created and when is the timeline for it to go live?

**Comment by markmacgillivray** [comment]
I wrote it over the last four days. It would be good to put it live on Monday next week.

**Comment by chealsye** [comment]
Okay! So, I'm chatting with @meganwaps about this because I hit a wall with being funny and clever. She said, "I think it could be something we could change every so often to keep it fresh" and then lightbulb! what if we had multiple funny, short, cute phrases that rotated with every use? It would be fun, something different (mostly) with every request. Would that be possible, @markmacgillivray?

If it links to /sources, then I think /sources will need copyediting before linking.

**Comment by chealsye** [comment]
@JosephMcArthur Here's [a doc of phrasing ideas](https://docs.google.com/document/d/18yPQNgBuk33M8cgv8wRxbAOjZGw6bKDeoDmCtKRL6dk/edit). 99% credit to @meganwaps who is way funnier than I am!

**Comment by JosephMcArthur** [comment]
added a phrase here, but it's more descriptive than cute. Can add cute ones when we have a bit more time (added a descriptive one so we could link to sources)

**Comment by chealsye** [comment]
Did you look at the doc we created?

**Comment by JosephMcArthur** [comment]
Yup, and used one as the basis for mine, but didn't think one cute phrase alone was the right fit here for now. Will revisit soon I hope.

**Comment by chealsye** [comment]
Okay, fine then.
And you decided on the following?

_Searching thousands of repositories for access!.

Give us a moment._

There's an extra period in that first sentence.

**Comment by JosephMcArthur** [comment]
That's my current best bet, edits welcome! typo fixed

**Comment by chealsye** [comment]
We already provided our suggestions. It's fine that you didn't want a fun one.
