### ISSUE TITLE
Testing citation search

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#570]
@svmelton hopefully it should be relatively clear how to go about this (and builds on your work on other similar issues). 

Assuming title search testing is happening #111 

@markmacgillivray I don't think this is 100% required to ship in a week, if it's buggy we may be better placed to release it with care later.

**Comment by markmacgillivray** [comment]
I think we would be better placed to release things we CAN do, and deal with bugs when they're found. Otherwise we risk having yet more features that get released by other people a year after we had them, and overshadowing ours whether better or worse. We can't delay with care for too long - we keep falling into releases that contain less than we have done.

**Comment by svmelton** [comment]
@JosephMcArthur @markmacgillivray Are there examples of citation formatting? (I think there used to be on the test site.) I ask because there are a ton of different citation systems and they'll all be formatted differently. It would also be helpful to know which citation elements (author, title, name of publication, etc.) to test.

**Comment by JosephMcArthur** [comment]
This is on live now, we have a bug management system to catch errors & success cases as examples. Closing for now & we'll deal with the rest on a bug by bug basis.
