### ISSUE TITLE
On dev articles being linked to whole journals

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#575]
I'm guessing this is something to do with the DOAJ? 

From
 > http://science.sciencemag.org/content/293/5530/711
to
> http://www.springer.com/earth+sciences+and+geography/mineralogy+%26+sedimentology/journal/12182

**Comment by markmacgillivray** [comment]
Yep, this is a question of how wrong you want to be.

From DOAJ we can find that a journal is open access - that means if we told a user the article is not available and to start a request, we would be wrong, and we would be wasting time trying to request something that is already available.

Unfortunately, although we can know the journal is OA, we can not necessarily know a link to the article. In the case of this one, we do know the DOI and could show the DOI and it would link to the OA article on Springer - but in other cases it may not be possible to find a DOI, and even if we do it may not be possible to know that the DOI goes to the open version.

So for now on the dev site I have just treated it the same as if the article is open. Of course on the site I can easily show a msg saying this is just a link to the journal, but that will not work for the plugin, because we took away explanatory power for visual simplicity - we just show a blue "available" button.

However, I still think it is better to show "available" with a link to the journal than to say "unavailable" when we know that is wrong, and to potentially allow an unnecessary request.

I'll probably switch the journal URL for the DOI where one is found.

**Comment by markmacgillivray** [comment]
Please make appropriate strategic decision around how to handle this - if not desirable, I will disable DOAJ lookup. Will require decision on how to present different findings on site UI and plugins and bookmarklets.

**Comment by markmacgillivray** [comment]
DOAJ lookup is still done, but if only finding a journal URL it no longer gets shown as an article URL. The data is in there for us to do something with later, but for now, if a journal appears to be open but we cannot find a link to the article, then it is still assumed to be closed. Also, I found evidence of journals listed as open in DOAJ but for which the articles cannot be found openly anywhere (Elsevier ones, and this has been a problem on previous projects too, and identified by other OA people). So not much additional use right now.
