### ISSUE TITLE
New Look & UX

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#580]
This is a big'un. The objectives of this are to:
* make UX simpler (our friends at oadoi have shown how simple things like this can be, and we shouldn't be afraid to learn a thing or two!)
  * removing the need for a user to chose if they want articles / data before requesting (we'll guess for them). This removes several pages. 
  * removing need to sign up on a page separate to a request page
  * allowing requests to be made anonymously & be "claimed" by others (this doesn't 100% mean an anonymous request will be sent to an author). 
* make everything prettier
  * removing our boxy look
  * cleaner use of colour (fewer, lighter colours on a page)
  * less info on each page
  * no more buttons causing epilepsy
  * fewer icons in favour of text
* make our requests API friendlier by not having users through it get sent to a login page
* better define our value proposition at a glance

The stage this is at is essentially a first draft from the designer. We have more design time next week to refine. At this point, feedback on the style, broad structure & purpose of each element is helpful. Feedback on minor copy elements isn't. 

## 1 - homepage

![1v2 - front page](https://cloud.githubusercontent.com/assets/4953703/23903748/7723b952-08bd-11e7-9b9f-9d81982a339a.png)

Notes:
* The section under the down arrow isn't designed yet. Ideas helpful. Essentially, we need somewhere to put other super super critical info like examples / about.
* I'd like there to be a way to download the plugin visible
* Here the logo is shown as blue, which looks nice but I'm conflicted. 

## 2 - article found

![2 - article found](https://cloud.githubusercontent.com/assets/4953703/23903752/799fbb5e-08bd-11e7-87df-96e247406951.png)

Notes:

* Here I'd like us to put in some error handling text somewhere, but otherwise seems okay.
* May turn the plugin link into something more toned down.

## 3 - article not found

![3 - article not found](https://cloud.githubusercontent.com/assets/4953703/23903753/7b1c8642-08bd-11e7-80db-a2e9a93b8b3f.png)

* My feeling here is to try and break down this page a bit more. This feels like a _lot_ of boxes to fill at once. I think something like:
  * part 1: email / story input & a bit of text that says (essentially) "give us your email so we can let you know when the request is finished & the author know why this is important". This would then submit.
  * part 2: other fields like name etc. Some text that says "authors like to know who's asking, let them know (you only need to do this once)!"
* I like the first line here which is intended to show what's now happened & what would happen next. 

## 4 - email confirmation

![4 - confirm email](https://cloud.githubusercontent.com/assets/4953703/23903755/7c8a964a-08bd-11e7-9c90-b3afe45baedc.png)

* not sure about this page at all. Kind of depends on how we treat 3. 

## 5 - request submitted

![5 - request submitted](https://cloud.githubusercontent.com/assets/4953703/23916648/ccad67c0-08e4-11e7-887a-1bc821101a22.png)

* I can _feel_ my mind resisting this design, but, I'm going to hold an opinion for feedback.
* Note "reply" stuff is based around the idea of "chat" being super important to building a community. This isn't possible yet, but is still useful.

## 6 - /requests
![6 - request page](https://cloud.githubusercontent.com/assets/4953703/23915866/3da2a47a-08e2-11e7-8251-33768fc685e1.png)

* functionally this loses a lot we need from the current page, which isn't okay. 
* I think the 1/3 - 2/3 page split works well for search & we should keep it
* I don't like a lot about this but it does feel prettier than our current page, so there is certainly something going for it.

## How to give great feedback

Opinions from @OAButton/team helpful (as said over email). 

If you can, please structure feedback to help me digest (see code you can copy for use in the response. It'll make bullets & headers):
```

# 1 

* point 1
* point 2
* etc

# 2

* point 1
* point 2
* etc

# general

* point 1
* point 2
* etc
```

**Comment by markmacgillivray** [comment]
# 1

* having an input box (small one line) rather than a textarea box (bigger multiline) is bad if we want to enable title and citation searching - it just is not big enough. That's why I have been going toward using textareas in the recent developments I had done.

* we still lack clarity on how it will be explained what it is that a user can put in this box - without instructions, even our own team members have asked what it means to put a citation in here. The dev site I had already started on included a simple "more info" text link that opened up to show examples. I think this is necessary.

# 4

* I am not sure that having a user actually sign in and input their code on any page, as it appears on that UI example, is a good idea or even possible. The current system limits where it will accept login requests from in order to increase security. It is probably possible to bypass this and allow login from any page, but will take a bit of extra work from me, and a slight reduction in security.

* Even if I do the above, it then brings up the question of what you expect to show a user who comes back to any page of the site without having yet input their code - at the moment, where they do this on the login page, it shows the "input your code" box if we are still waiting for the code, but the user could view other pages of the site as normal. If we move this functionality to actually do login across the site (rather than just taking signup details in new request workflows but still pushing to the account page for the actual sign in) then what do you expect to happen to a user who visits any other page before they have entered their login code? Will they see nothing but the login prompt?

# 6 

* We still have a lot more functionality that could go on requests, but there has never been any clear decision on which of that functionality should be used. I have started multiple demos to attempt to get us moving, but we keep falling back. So, if we have no clear use case for what users should be doing on this page, and for example no clear understanding of why we even have 1/3 - 2/3 column splits with options down the left side, then go with the nicer design and leave out the functionality altogether.

* We can go live with the simpler requests as demonstrated, and then the team can make a decision about what user stories we are actually trying to support on this page, and do a redevelopment of it at a later stage, once the team has firmly articulated what the needs for it are.

**Comment by svmelton** [comment]
# 1 

* I like the blue logo tbh
* Have we done away with searching by title for the moment?
* I agree that the plugin needs to be visible. 
* I'm not sure about the Request tab on the front. I think "request" might be confusing for someone new to the site. (This would be a great area to do some user testing on!)

# 2

* I think we could make the Chrome store icon a little smaller, but I like the simplicity of it.

# 3

* I'd concur with the suggestion to break it up over two screens.

# 4

* It feels weird to me to put in a code in this area. Also—especially if we break the sign up phase into two pages—this creates a lot of steps to create a request.

# 5

* Huh. The "reply" functionality isn't intuitive at all for me, and I have to admit that I'm not sure I'm sold on the idea of chat? I think I'd have to know more.

# 6

* Agree with Joe that the search/request proportions look good.


# General

* Overall, the first part of the design—the article searching—works a lot more for me than the request part.
* I wish I had better-formulated feedback on the request pages—it just seems to me that they need to look really good if that's our centerpiece. Simplicity is good, but I think the requests need more context. I'd be curious to know more about what other functionality we've explored.

**Comment by markmacgillivray** [comment]
As Sarah mentioned chat, I'll just add that I hadn't noticed that. I'd agree with her that I'm not sold on chat. Without a clear use case as to why it's needed on our site, it's a gimmick. Even if we think it may lead to useful community building, if we're not clear on how or why, then all we'll end up doing is building a demand for something we'll have to maintain, with no additional benefit towards our aim.

**Comment by markmacgillivray** [comment]
@JosephMcArthur front page on dev now matches the new design. I need a better quality version of our logo in the blue please!

**Comment by markmacgillivray** [comment]
by the way I mean just the look of the front page when you land on it - no functionality yet, so if you try searching it will go weird. Working on that now.

**Comment by JosephMcArthur** [comment]
Only commenting on areas where it seems needed (i.e places where there are Q's / differences of opinion)

# 1 

> having an input box (small one line) rather than a textarea box (bigger multiline) is bad if we want to enable title and citation searching - it just is not big enough. That's why I have been going toward using textareas in the recent developments I had done.

I don't think a big box is an option. Perhaps we need to either:
 * have the box expand on input (if needed)
 * just search as soon as you put something in the box (I like this, it's how google does it!)

> we still lack clarity on how it will be explained what it is that a user can put in this box - without instructions, even our own team members have asked what it means to put a citation in here. The dev site I had already started on included a simple "more info" text link that opened up to show examples. I think this is necessary.

* I feel like some clever "learn more" link, as you currently have, is _probably_ the way to go.   

> I like the blue logo tbh
> Have we done away with searching by title for the moment?

Nope

> I agree that the plugin needs to be visible.

@markmacgillivray suggestions here are helpful.

> I'm not sure about the Request tab on the front. I think "request" might be confusing for someone new to the site. (This would be a great area to do some user testing on!)

@svmelton This is similar to what we have on the site now, any feelings as to why it would be an issue here? 

# 4 

> I am not sure that having a user actually sign in and input their code on any page, as it appears on that UI example, is a good idea or even possible. The current system limits where it will accept login requests from in order to increase security. It is probably possible to bypass this and allow login from any page, but will take a bit of extra work from me, and a slight reduction in security.
> 
> Even if I do the above, it then brings up the question of what you expect to show a user who comes back to any page of the site without having yet input their code - at the moment, where they do this on the login page, it shows the "input your code" box if we are still waiting for the code, but the user could view other pages of the site as normal. If we move this functionality to actually do login across the site (rather than just taking signup details in new request workflows but still pushing to the account page for the actual sign in) then what do you expect to happen to a user who visits any other page before they have entered their login code? Will they see nothing but the login prompt?

Sadly I have next to no clear suggestions for how to make this part of the process simpler. However, I'm thinking:
* Can we assume that emails entered will work enough of the time to move someone straight onto entering other info rather than waiting for them to enter a code?
* Can we have a user enter a lot of info without it refreshing or them being taken off page? For example, we could have an "action area" on the page which would have them enter an email / story, then user info, any author email info we need, then tell them to check their email. This would mean that when a user lands (if they're not logged in) we'd frame the page as a nearly finished request and ask them to enter the info required step by step. This would work nicely for coming from the API, as they'd land on a pretty page with the end in sight. 

# 5 

Let's ignore chat as an idea for now, we're not going to ship & this isn't how I'd suggest we implement anyway. 

#6 

Keep the added functionality & 1/3 - 2/3 set up. Lets just use the styling in this version to give an idea for how to make it more beautiful.

**Comment by markmacgillivray** [comment]
@JosephMcArthur I have already made it a small box that expands, see the dev site front page. I don't think it is as usable as a proper sized box, but best compromise.

We can't search immediately like google does, because we cannot do partial searches on the beginnings of inputs, and we cannot show potential results before processing the full string we are given - there is no such thing as a potential match to part of an url / doi / title etc.

# 4

I am going to make the new request page create the request with the provided user info, THEN create the user account. We'll see how that works.

**Comment by chealsye** [comment]
Overall I am SUPER excited about this new look and it is very close to what I’ve been wanting for a long time.

I’m not a fan of the font though. 


#1
* I’m on the fence about the blue. It is nice in many ways, but it is a big shift and was for ODB. I personally hate the color when it is used in large spaces and think it is hard on the eyes (fine for a logo, but not for large icons or background which has happened). 
* I’ve suggested this before, but adding a strip of color promoting the plugin could work and takes up little space while drawing attention to it.
* I’m not a huge fan of the book image (which Joe knows!) but ultimately it would provide a good bridge better our current site and this new design.
* I’m assuming this is placeholder copy that can adjusted.


#2
* I think we should have some image here.
* How will a user request data then?
* I agree that I think the Chrome store image should be smaller. 

#3
* Why do we need someone’s last name?
* What if they want to request the data?
* Will these be required or optional fields? 

#4 
* Why do they need to even get an email confirmation? 

#5 
* I think this is too plain and a step back from one area that looks good currently for us. 
* I don’t quite understand what is going on with it either…

* I’m also not sold on the light grey-blue background color to these pages.

#6
* I agree that we lose too much with this design. Our request page is one of the best looking bits of our site and very useful, so the main /requests doesn’t need a strip down like the frontpage does. We should discuss a middle ground between both looks and determine what is truly needed on this page.

**Comment by markmacgillivray** [comment]
Regarding @chealsye comment about not liking the font - I don't know which font the designer used, so the dev site is currently being done all in Roboto.

Latest progress - the dev site now has a requests page that attempts to merge the new style with the functionality we had. I have kept the different colour backgrounds to the requests, as that seems very useful, but if nobody else wants them I will remove.

Remember when checking the dev site for progress, refresh your browser pages with ctrl-refresh command for your given browser.

I will next work on the 2-3-4-5 workflow, which will provide some more insight into how a request could look.

**Comment by markmacgillivray** [comment]
2-3-4 workflow pretty much done, I need to add links to the plugin to the intermediary pages that show results / support / new request buttons.

I am now just working on automating the process of creating a request, and then showing the new request page, which includes using the new style for displaying a request. This should be finished today, then that will be all points implemented, ready for final content review and release to live asap.

**Comment by markmacgillivray** [comment]
2-3-4-5 workflow pretty much all done now, the new request style can be seen when viewing any current request. Creating an actual new request may still not quite or always work as expected, but is just about there. I have kept the colour themes of the different requests status, from the overall request search page, and incorporated them into the individual request page design. Admin functionality is being added back in, as is the ability for users to edit things, and take ownership of requests.

This means it is now possible to create a request without any login, and after the request is created, any additional missing info can be added by anyone. Any user can also claim ownership of the request - of course, a logged in user creating a request will have themselves assigned as the owner automatically anyway; whereas a non-logged-in user will be able to create a request and will be the first person to view it, where they are prompted to login / signup and take ownership of the request. Redirects via the account page should make this automatic, so that all the user has to do is login or fill in the signup form, then they get redirected back and have the ownership assigned - although all this is still to be tested.

I will continue on this tomorrow and should have it functionally complete, and in terms of visuals as close as seems possible to the design. I have tried to make content as close to what we had or what is in the design where still relevant, but of course any updates are welcome before going live.

We still have a couple of days for feedback if people want to get things changed, if we want to launch at the next sprint start/stop on Monday 20th. Otherwise it must roll on to the next sprint two weeks later, or delay other work further.

Given that this holds up oadoi integration though, and includes the updates @natalianorori needs for author responses, I'd propose this as still highest priority, so getting it on to live at start of next week would be great.

**Comment by markmacgillivray** [comment]
The workflow is now complete - it should be possible to test by dropping in URLs to articles and seeing that it either finds them or displays links to open requests or automatically creates a new request. When the user is logged in the request is allocated to them, when not it is created anyway and the user is prompted to login / signup and take ownership.

When a request lacks title or author email or story the users will be prompted to provide them, along with DOI as extra option. Once all these are provided, the users cannot edit anything. Admins can make further edits, like when we find that an author email is wrong or the author will not respond, or when we want to edit the story. The edit functionality is still being finalised, but will work as previously, except the author email is now also checked for validity and checked against our blacklist, and admins can add emails to the blacklist.

There is a decision to make around requests created anonymously. For now I have made it so that it sits at the "help" status and awaits someone taking ownership. However an admin could also go in and set the owner to "anonymous" and progress the request. Is this desirable, or do we always want a real user to take ownership before progressing?

I also have to do some work on the API to better match existing requests - now that we accept so many different things to search for, just matching on URL is not good enough, so I will default to URL only when no DOI is available, and if there is a PMID or PMC they will default to DOI if available or else the relevant ncbi / europepmc URL. Titles and citations will also default to DOI.

This remaining work for me to do is quite small and does not affect what the UI will do, so I can have these ready for Monday and everyone else can review the dev site as it currently stands.

@chealsye @meganwaps I believe you had an idea to include little statements under the loading spinner icon, is there a document with statements ready to be included? @JosephMcArthur are these statements something you want along with the new design? If so they can probably be added for next week as well.

**Comment by markmacgillivray** [comment]
We also need a decision on what to do about names - proposed in #581 to just collect first names when creating a request, so given that we can create anonymous requests and then have a user sign up, what name parts do we actually need?

This seems to have gone round in circles along with the question of anonymity in the first place.

My position is still that anonymity is a weaker form of community building - if our intent is to change the behaviour of a group of people, that is best done by demonstration of real named people related to that culture. Anonymous requests do not change a culture in this way, and privacy in this sense is a form of fear. On the other hand, people are fearful, and anonymous requests are functionally easier - but people are also lazy; so we have to make it clear what the value of identification is. I think we do that better now, as it is clear what taking ownership of a request means. But it is still not clear what we use their name for, or what part of it we need.

I think continuing to prod users towards signup, and taking their email address, affiliation, profession and "name" would be enough. For "name", I think we should ambiguously ask for just that - a "name". Not "first name / last name" or "username". That way, users can identify themselves however they wish, including putting in a fake one if they desire anonymity, yet still giving "identity" to their actions (quite a common thing that people do on the internet).
 
@JosephMcArthur - presumably final decision on this is up to you.

**Comment by JosephMcArthur** [comment]
Okay, I've taken a look today. Sadly I couldn't think everything through but my first wave of changes would be

# General

* Let's remove the large footer & replace with something really really tiny. Let's shoot for: 

"Our code is Open Source and on Github | Blog | Twitter | Feedback | About"

# Homepage

- [ ] Lets move "Paywalls avoided. Research data, shared." up to the logo area. There is no reason for people to read our name first. 
- [ ] Move "Comprehensive, instant, legal search and requests for inaccessible research in just a click" to where
- [ ] have "how it works" & examples & API as the learn more style clickable links under the search bar
- [ ] add plugin download icon / text from account page below the final line of text
* there needs to be some tweeking of element sizes here, but will suggest we leave that a while

# find page

* Generally this is fine, although it need some copy & design love. 
* Is there any way to avoid the two separate stages of spinners? It can spin for a realllly long time. 

# request page

When I was testing this it was buggy and I really struggled with it. I couldn't see a path to something that was good from there, so I went "back to the drawing board". 

![image](https://cloud.githubusercontent.com/assets/4953703/24076580/5158e978-0c2c-11e7-8b75-ac2b2f283172.png)

Here was my thinking:
* Big title & attribution statement frames the page. 
* Paywall statement makes clear what the problem is, what the page is for, and that people can help. This can change for data of course. 
* RHS box makes make information about the request known in a graceful way that kind of gets it out the way. I'd suggest this is always visible on the page though, rather than scrolling out the way. 
* LHS box is infinitely scrollable and can be used for whatever we need it to do. Here we may have "cards" that ask for information like the authors email, for people to share, to information we're missing about the paper or even to claim the request. In this area we could also include page updates, like when it passes moderation, a story is added & more. I didn't totally figure out how that should work though, however, I think that's okay as it'll need more dev work. 
* I've reframed "add your support" as something a bit more generic, simply getting notified about the request. I'd suggest that you'd only need an account (or even just an email) to do this. 

I'd love feedback from @OAButton/team on this design. This is just a broad idea, not a stipulation! My sense is though that the current design isn't adequate.

* When testing I couldn't get much of the page to work as expected, so hard to comment on some other more functional areas. I'm assuming "taking ownership" takes me to the account page? 
- [ ] make it clearer why a request needs "ownership". 

# account page

- [ ] #507 is a helpful reduction of this page for now
- [ ] tweek copy to speak more directly to why this is used for requests - me 

# other pages

- [ ] We need to unify the look of other pages (e.g sources, feedback, about). I'd suggest we just have a large, plain title & then text. I can do this.

**Comment by JosephMcArthur** [comment]
# Request page

I've gone back to a one column approach, but trying to keep some of what I've added. 

## When just made

![request page concepts 1](https://cloud.githubusercontent.com/assets/4953703/24084330/15b1513a-0ce0-11e7-988a-8f4d5790bf17.png)

## Anonymous request

![request page concepts](https://cloud.githubusercontent.com/assets/4953703/24084324/05c4176c-0ce0-11e7-8e29-5d205eba29e9.png)

## Fully made request

![request page concepts 2](https://cloud.githubusercontent.com/assets/4953703/24084335/1ffd853c-0ce0-11e7-8cc0-6512039b2a97.png)

**Comment by chealsye** [comment]
I'm not sure what it is, but I keep looking at your mockups, and they still lack the 'oompf' we were talking about yesterday. It is a lot of text. But they are a step in the right direction, focusing on calls to action for the user.

I'd like to hear others' thoughts regarding the background color. 

Regarding anonymous requests - anonymous requests are simply people not giving us a name and affiliation. We do need their email to notify them of course, but there's no reason we need to display their email publicly or to provide it to an author. So we need a different approach here - I know this is just a mockup and placeholder copy but want to address that since we have not yet reached an agreement regarding anonymous requests.

**Comment by JosephMcArthur** [comment]
> I'm not sure what it is, but I keep looking at your mockups, and they still lack the 'oompf' we were talking about yesterday. It is a lot of text. But they are a step in the right direction, focusing on calls to action for the user.

+1 step in the right direction but still lacking oompf. I don't envy Sam, I'm going to just have to ask him to figure out what oompf is, and how to add it. @OAButton/team ideas on this are worth their weight in gold. 

> I'd like to hear others' thoughts regarding the background color.

tagging @OAButton/team 

FYI, in my image the email shown is the authors, sorry that's not clear!

**Comment by markmacgillivray** [comment]
I like the background colour, i think it works well.

At the moment not even user email is required for anonymous requests. We can't require it because oadoi and oabot and other services that want to create requests may not have a user email to give us.

However an anonymous user gets prompted to take ownership. This directs them via login/signup where we collect their email address. We can also ask for first name, last name, affiliation and profession, but all should be optional.

**Comment by JosephMcArthur** [comment]
![request flow v2](https://cloud.githubusercontent.com/assets/4953703/24208663/1489f7a6-0f1c-11e7-8eee-e008ab703376.png)

# Notes from @BaronBlackmore 

After the user makes a request, they land on page 1, the discovery page, where they can put in their email to start a request. the bar on the right then will go up by 1. 
if the user continues to request to contact the author, the signup is included along with the plee and the page is made findable in the request search page.

pages 1.1-4

Light blue sits well, and would match the front page, but needs some tweaking to make it look like they're part of the same set. For a page that users will land on from both the OAB front page, button and external sources like the unpaywall, the user may need additional information about why they are on this page. Maybe a sentance or two about the OAB.

A theme I think would be strong is of an alternative route to the goal, where OAB may be signposting the way forward.

pages 4.1-5

I was thinking maybe we could have the whole page color change if the request is not fulfilled. have the background gradients and the links/buttons all red. The image should be of something closed, but with potential of opening. Case, vault, containers etc.

It's important that the first thing the user knows is the status of the request, 2nd is the title and 3rd how close it is to being fulfilled. Support call to actions are obvious and just subscribe to hear updates on this requests status.

The status headline needs to invoke disgust or anger in the user, they're the easiest reactions to invoke and will cause the most traction. Imagine the feeling like you're using facebook but have to log in every time you comment or like something, exhausting and irritating. However, the author needs to arrive on the page and not feel like the center of a witch hunt.

pages 4 and 5 show the difference if logged in or out.

-----------

Overall some styling still to do. It can be sharper and deeper, though I think putting in the top image and gradient background is a good combo. If the image is not too highly contrasting, the page has a nice information balance without being overwhelming.

# My thoughts

* explorer.opensyllabusproject.org is a cracking concept for /requests
* these designs are better than anything I've seen thus far. 
* I'd like to see us aways default to article requests in many cases
* Requests without any info should be hidden from /request. 

# Next steps

* @OAButton/team feedback
* On Thursday we'll take another punt at this and see how else we can approach it

**Comment by svmelton** [comment]
# Hot Takes

- I love the idea of a changing color/gradient if the request is or is not fulfilled.

- I'm intrigued by the "request levels."

- +1 on the opensyllabus idea from Joe.

**Comment by markmacgillivray** [comment]
The designs with full different background colour and a banner image across the top are good. If these can be agreed asap, they can be worked into the new site.

Regarding the opensyllabus /requests page - I'd prefer to have some decision from the team on what actual functionality either the team or the user stories support. Then, if those fit a particular design that we like, we should go with that.

Hiding requests that lack info from the /requests page means that there is no way for a user to find the requests they have created and see them again - especially if they were created anonymously, how would you expect anyone to ever find them again?

**Comment by JosephMcArthur** [comment]
# @BaronBlackmore designs

These are more polished designs for what he's suggest as our UX from the front page. 

![request flow v3](https://cloud.githubusercontent.com/assets/4953703/24297293/2c97e5d6-109a-11e7-935a-ec23a1ecec73.png)

Some notes that're helpful to interpret:

* Copy is still not final
* The "level" language won't be used. It should be more about steps before the request is complete, or how many supporters it needs. All this will be framed around author engagement.
* footer isn't intended to be that wide, and it should be out of view when you first arrive at the page. This might not play nice with current ideas.
* This assumes we can have forms on pages, which would be nice but not required for a release. 
* He & I suggested that the first step, before ever reaching a "request" page could be
  * breakdown sign up, it's a bit much to land on a site you might not know & then have a lot assumed about what you want. 
  * make the first ask reaally really easy, but still something we can provide value from (weekly checks)
  * helps prevent some issues with spam & having people freak at being landed on this somewhat "big" thing.
* generally, I really like the pages. There is some really clever stuff there and it feels more excited / clearer / engaging. The only thing I can see being tricky are this "unfound" page vs our find page vs a request page. I think it's best to think of the unfound page similarly to the request page (we may actually want to use the same design).
* Note, when logged in & signed up you'd skip straight to "part-2" & be asked for a story. The rest is essentially "onboarding". 

How anonymity should work (i think):  

* Last name & institution should be optional on sign up. Everything else should be required. 
* requests with no user information attached shouldn't be shown on /request for now. It would be too hard to tell between mistakes & actual intent + there is noone to send it too. 
* Stories should still be required
* "support" (aka, now, being "notified" or something like that) can now be shown with just an email. 

Some ideas we probably can't implement yet:
* automatically sending a request (without review) if 1 or more people support it.
* I'd suggest we always default to assuming a user wants the article (except when there is a data request or something available). This smooths the UX in the majority of cases & we can correct for a user in the same number of clicks as if we show the option as we do now (see designs for "wait, I want the data"). That is, of course, unless an external service tells us otherwise! 

# Notes from @BaronBlackmore 

![request flow v3 details](https://cloud.githubusercontent.com/assets/4953703/24297289/2aed0ffe-109a-11e7-9115-71e32c1a0c07.png)

----------------
the unfound page
----------------

download button needs to be part of the footer
	- it's becoming an increasingly less important part of the user journey

"This is the OAB Request system and we aim to put you directly in contact with the authors"
	- this statement tells users that they may be using a service different from the previous page
I can choose to accept putting in my email to become notified when the paper is released
	- an easy step, fulfills the requirements of the motivations of the users to come here 
single column, to remain as approachable as possible
	- this page will be a landing page for many users

-------------------
Psuedo Request page
-------------------

show the bar for the first time here
	- you already want to be notified, now we incentivise you to help speed up the process

"I actually wanted the data"
	- allows users to switch to a data request

------------
request page
------------

"This is an OAB request page"

Details of the paper and ability to edit them or amend 

dedicate the larger part of the page to authors attention, the smaller part to supporters

all request statuses need to be author orientated
	- it'll be clear what the authors role is to do upon arriving from a non-email link
	- it is the focus of what the users are waiting for

authors action to go alongside the progress bar as well as at the bottom of the main section

Describe what the levels do (e.g.)
	1 - request to be sent within the nect 24 hours
	2 - request to be sent within the next hour
	3 - phone the author

Describe sharing on social media as promoting the page

**Comment by JosephMcArthur** [comment]
@markmacgillivray regarding explorer.opensyllabusproject.org. Generally, I think the page is about:
* showing requests that are active
* describing the system
* helping people find requests they can help
* Soon: having people join / make community & projects around the system

I think the example given does a good job of that, in a pretty way that would now fit well with our style.

**Comment by markmacgillivray** [comment]
Seems fine except one point - you're still saying requests with no user info won't show on the /requests page, but my previous point still stands: if they are not shown on the /requests page, there is no way for anyone to find them again, including whoever just created them. That means if that user goes away from that page before putting in their details, they will never again be able to. So anonymous requests would essentially become non-existent to the outside world.

**Comment by JosephMcArthur** [comment]
Okay, I need to take a step back here and walk this through (if only for my future self). Currently, there isn't enough information to really make a good decision here and so I want to track why a decision was made one way or another. 

Here is how I'm thinking about anon atm: 
* this is primarily a technical choice, to simplify UX
* anon isn't in the interest of authors. 
* anon leaves us open to risking spam & abuse, and make it hard for us to tell what is a mistake vs a real user action
* First name & profession, and story is a reasonable expectation for information needed to contact an author. Generally, we need something to say who is actually asking (e.g for institutions it might be their name). 
* How do we measure request success when many "requests" might not be sent to authors

Finally, the question comes up of how full is the anon. Does only anon from the author count, or anon from us too? I'd suggest that a user can't quite be anon from us. 

In the proposed workflow you shouldn't be able to make a request without at least an email. "requests" with just an email shouldn't be shown as technically at that point the user hasn't really initiated, this is why it's referred to as a "pseudo-request". A user who creates a pseud-request should still be able to share that page with someone if they like, or, have another user put on the page "directly" by requesting it themselves (it would just be created with 2 supporters). 

However, displaying what is essentially a stub page on /requests feels a little off to me. I think we should display if a user is viewing "their requests", and then we can handle as we currently do (by saying we need someone to take ownership). We can also display to "communities" if the request falls into their remit (they can then start the request). 

For folks working from the API, if they're making bulk requests I'd suggest they need to pass a story / some identifiers for that. For individuals going via the UI, they still get to land on a "request page", not a dull sign-up page, which as I understand it fits what folks have asked from us. 

LMK if there are questions.

**Comment by markmacgillivray** [comment]
My update:

* The dev UI has been updated with the red style for the requests. It stands out that we do not have a style for the "successful" requests now though, so please provide one asap.

* It is not clear how the path flows for the different types of user and their potential different states. The first "unfound" design is nice, but it does not make sense for a signed in user - we already have their email address. If I skip that bit for someone signed in and take them straight to pseudo request 1 or 2, neither of them make sense either, because we already know this user is going to be the first requesting user and we do not need their login details.

* Which also brings up the point again, of why do we need sign up fields in this workflow at all, when we can send users to the sign up page for that info. A non-signed up user hitting the first "unfound" design is going to have to at least type in their email address and hit submit before they get anywhere else anyway, so why not have that submission route them through sign up and then back to the request page? Alternatively, why not show them pseudo article 2 straight away, but without the sign up boxes, because the first thing we want from them is a story. Then with that they can submit, and complete the sign up process. So, still makes "unfound" and pseudo 1 superfluous.

* The final slide "request page, logged out" makes sense and has been implemented. Also, where the user is logged in, it just does not show the support box if they already support or created, or if they are logged in but don't already support, it shows them a support button but not the email box.

* The "support" functionality is now just described as "notify me" and no story is asked for.

* If status is "help" and we are missing title, author email, story, or DOI, relevant boxes will show and the user will be prompted to give us more info. This happens regardless of whether the request is new and the user is the creator, or whether it is someone viewing the page later. Again, this does not fit with the presented workflow, so just shows as necessary.

* If the story is missing, then it makes no sense to get a "notify" first, so the user is asked to provide the story. This means the first story provider may not be the owner, if we allow people to create the requests without stories and they subsequently do not provide one.

* If the request has no owner and the user is signed in, they will be asked to "be the first", which will also make them the owner. If the user is not signed in, they will be asked to "be the first" but will be routed through login / sign up page. This also does not quite fit the workflow, in that we cannot ask users with accounts to be the first and provide sign up details - we have to give them the opportunity to sign in. So again, given this, and given that we can route users to the account page, it makes more sense to offer either kind of user the option to "be the first" and then to sign them in, and then to redirect them back to the page.

Any of the above can be changed, but please note where there would then be gaps in the functional workflow. If it is not desired as is, please have the team map out and agree the complete workflow for exact replication.

The requests search page has been altered back towards the old style, as requested. However this is not then like the style of that opensyllabus requests page. If that is to be released with everything else too, please agree a mockup with the team and provide for implementation.

Given the above points and feedback from other team members today, it does not seem likely we can deploy this tomorrow. I have one more day this week to work on this, and if we are not ready this week then we cannot have a link from oadoi to our new request page in time for their official launch next week. However if we follow up with them at a later date, I am sure they would add it for us at some point, but keep it in mind for any comms plans.

**Comment by JosephMcArthur** [comment]
Tried to respond below, can talk more on the phone. 

> The dev UI has been updated with the red style for the requests. It stands out that we do not have a style for the "successful" requests now though, so please provide one asap.

That should switch to a blue background & the bar on the right should just have a "go to article". I'd suggest we just hide the image at the top.  

> It is not clear how the path flows for the different types of user and their potential different states. The first "unfound" design is nice, but it does not make sense for a signed in user - we already have their email address. If I skip that bit for someone signed in and take them straight to pseudo request 1 or 2, neither of them make sense either, because we already know this user is going to be the first requesting user and we do not need their login details.

In the case of a logged in user we should be taking them to "P2", with just a box to put in their story. 

> Which also brings up the point again, of why do we need sign up fields in this workflow at all, when we can send users to the sign up page for that info. A non-signed up user hitting the first "unfound" design is going to have to at least type in their email address and hit submit before they get anywhere else anyway, so why not have that submission route them through sign up and then back to the request page? Alternatively, why not show them pseudo article 2 straight away, but without the sign up boxes, because the first thing we want from them is a story. Then with that they can submit, and complete the sign up process. So, still makes "unfound" and pseudo 1 superfluous.

Idea here was to try and keep people on the same page as it's a little less jarring. If for now we just have an email box, which routes them through the account page (similarly to how we used to have sign up on the homepage) as is then please do that & skip pseudo 1 / unfound. I'll make copy to suite.  

> If the story is missing, then it makes no sense to get a "notify" first, so the user is asked to provide the story. This means the first story provider may not be the owner, if we allow people to create the requests without stories and they subsequently do not provide one.

Having other people put in stories that'll be attributed to the first user seems weird - not sure we should allow it. 

> If the request has no owner and the user is signed in, they will be asked to "be the first", which will also make them the owner. If the user is not signed in, they will be asked to "be the first" but will be routed through login / sign up page. This also does not quite fit the workflow, in that we cannot ask users with accounts to be the first and provide sign up details - we have to give them the opportunity to sign in. So again, given this, and given that we can route users to the account page, it makes more sense to offer either kind of user the option to "be the first" and then to sign them in, and then to redirect them back to the page.

Alright, let's do that then for now. 

> The requests search page has been altered back towards the old style, as requested. However this is not then like the style of that opensyllabus requests page. If that is to be released with everything else too, please agree a mockup with the team and provide for implementation.

Lets just keep this as close to what we currently have as possible. Right now I can't even see the page (some bug) so I can't really comment. 

In thinking about where to head later, some notes to myself for later:

H1: Let's free the world's research
P: We're asking authors to open up their research to the world, once and for all. Find, support, and share requests that matter to you.

Button 1: View your requests
Button 2: Help requests

We can then keep their ticker.

**Comment by JosephMcArthur** [comment]
New UX is on the site, and is moving into bug testing. Shutting this.
