### ISSUE TITLE
Fix PMC issue and filter repos where login is required

### ISSUE THREAD

**Issue by markmacgillivray** [OAButton/discussion#592]

**Comment by markmacgillivray** [comment]
None of the examples in the oadoi blog post are currently incorrect in BASE. They may have been at the time, but are fixed now. So it seems that such errors are intermittent, or possibly fixed by oadoi contacting them, and either way we now check oadoi instead of BASE by DOI, then only check BASE by title where no DOI can be found. I've added an extra catch to our title lookup that checks to see the link is not one that ends with PMC but misses the number.

Regarding the filter repos where login is required, we have other issues tracking that

**Comment by JosephMcArthur** [comment]
What are our options for catching login repo's before they get reported to us? Right now, we have a responsive solution (we find a login wall & we fix it). I've highlighted a base page which we can use to be proactive (manually) in another issue. That's helpful, but still pretty work intensive.  

In terms of trying to avoid login walls & link to full text more automatically, proactively, can we implement a version of the oadoi script, or other methods, to catch these errors more? Perhaps, for example, if we can't do this on the fly (because it would add too much load time on search for a user) before we've seen a repo we could run the script for the repo after the first time a user lands there (similarly to how we cache results now)? This stops us needing to spend ages building our own local copy initially, but helps us get better over time still. 

So, the logic here would be:
* user searches
* user lands on a repo page we've sent them to, probably a splash page (maybe a login page). 
* we save the url we sent them to
... later
* (if we don't already have a redirect) we go to the URL & take a copy of the page locally
* we run a script over it to see if we can grab a .docx / .pdf file (perhaps by checking commonly used metatags we've built up manually)
 * if yes, we add a redirect telling us to do this on the fly. We could also tell it to not send a user to a domain that doesn't look like a .pdf / .docx (or, generally, things that look like login pages)
 * if no, flag for manual review

**Comment by markmacgillivray** [comment]
I think this is a pretty flaky approach. How will you know if you have found a link to a pdf or a docx? They don't necessarily end with those suffixes, or any suffix at all. And even if you find the link, you don't know it is accessible unless you try to access it. And even if you do access it, how do you know you're getting the full article and not just a paywall stub? Some services may properly return the item as a pdf or docx and specify that they are returning that kind of content, but many will not.

That's the problem - what LOOKS like a login page?

We could use the oadoi script to pre-flag a bunch of domains just like we are doing now, and build on that approach to flag places we think require login - but even then, how flaky is their script, and how accurate is it? Does it blacklist entire domains, or specific pages on those domains where things may or may not be available with or without login? Of course we can investigate their script to find out more detail, but that in itself would have to be the first time consuming step.

**Comment by markmacgillivray** [comment]
We will need a specific review of the spreadsheets we are using to track the various kinds of sites we want to block, and how we want to block them - the use cases we envisaged have already come up short in terms of how people have actually used them. And then we will need to decide how to proceed with those ways of flagging inaccessible content, and also how to review them - e.g. if they are embargoed and become unembargoed, as well as having a look at the oadoi script and deciding how its results fit with our desires.

There is really a fair bit of work involved here, and we should expect it to take an entire two week sprint at least, and the real difficulty is scheduling that in along with everything else we want to do. As we are focusing on what Natalia needs for the next four weeks, that means this is unlikely to see any progress until May at the earliest, so I'm dropping it out of the current milestone, as it is beyond the original scope.

**Comment by JosephMcArthur** [comment]
Understood, thanks Mark. Sorry to keep hounding on this issue, I just want to make sure that we're exploring our options here. 

Let's build up our manual approach for a while (I'm doing bits & pieces whenever I get some down time) and I think that'll really help us understand the problem here. 

Otherwise, lets close this and move discussion to #642.
