### ISSUE TITLE
Find page UI changes

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#603]
<img width="1204" alt="screenshot 2017-03-30 08 57 19" src="https://cloud.githubusercontent.com/assets/4953703/24497043/03118bee-1532-11e7-9a90-bf21223886c5.png">

###  done

* I've moved stuff to be left aligned, and for links to be smaller
* I've changed some copy to be clearer

###  to do

- [x] make sure all stuff is left aligned, not sure I caught it all
- [x] include links to report bad linkages on the page
- [x] include a bit to download the plugins (somehow, similar to account page I guess) & perhaps advertise the API
* should the background be blue... not sure.
- [x] don't allow scroll on this page
* should article link be in button (saves us showing fugly links), I think so, not sure though. 
* should the page have a great big head on being like "here's what we found"? Something to frame the page. Not sure, probably not. 
* would small icons (for article / data) help frame the page? 
* should probably have a way to share success on this page. Would be great to thank the author for sharing the article here, that would be hella cool. 
- [x] show long url to allow direct linking to this page

**Comment by markmacgillivray** [comment]
I don't think we should use buttons instead of the full link. People will sometimes want to know the URL, so it should be shown on the page.

Page does not scroll if large enough window.

Long URL shows when executing.

I don't think we should link to download the plugins now that we have that on the front page. The user has already succeeded. And we don't have time to keep going back and fore on where to put those links.

Not sure what you mean by left aligning, everything looks fine to me.

Re. links to support bad linkages, we are supposed to have various feedback forms now, but I don't know if you / the team have progressed them to the point of being ready.
