### ISSUE TITLE
Being told: http://science.sciencemag.org/content/293/5530/698 is OA, but isn't

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#604]
Just links back to the original version.

**Comment by markmacgillivray** [comment]
According to BASE, it is OA but the link it returns for it is the DOI link, which just goes back to the article. There is a link via sfx search through Hong Kong university, but accessing that requires login. If you don't want potentially inaccessible links to show up via BASE search, the easiest thing to do would be to only use oadoi instead of BASE (currently we search oadoi then BASE)

**Comment by JosephMcArthur** [comment]
This makes sense to me, since they're doing cleaning ontop of it (but I assume keeping it up to date too) there doesn't seem to be a downside to that. Just less errors & complexity for us?

**Comment by markmacgillivray** [comment]
it will only work on the doi search though - we also run a BASE title search which we should still do, because oadoi don't do that at all

**Comment by JosephMcArthur** [comment]
That makes sense. 

So, I just went to add this to our blacklist but realised if I do that we'll be telling users this isn't the type of article we work on. Obviously, fine for one of ten million billion articles, but as we use this more it's something to keep in mind.

**Comment by markmacgillivray** [comment]
Yes, which I think is about messaging and how we tell users what we do consider to be an open article. e.g. it does not include things on facebook, also does not include things that are open but not accessible, may not include things on embargo etc - all things that have come up in recent weeks that there seems to be no clear concept of what we count and don't count as open (hence why I used to say that our default stance was that if our sources say it is open, it is open - because that is what we functionally did, even if we never stated it).

**Comment by JosephMcArthur** [comment]
So, I've seen that latest comment and will come back to it another time. It's clear to me, so I'm failing to communicate! 

This seems quite different, though, this list was just meant to be URL's we didn't work on (i.d we're not going to try and search repo's for a self archived version of facebook and to weed out spam). By putting this article on the list, we'll be telling users that "this isn't an article" in the same way we say "facebook isn't an article". That doesn't seem right to me.

**Comment by markmacgillivray** [comment]
Well, we can go back to having the URLs of things that are not open but not "blacklist" in the other sheet, but need to decide how you want that handled. The concepts we have so far are "sheet of things that are blacklisted" and "sheet of things that we want to check for fulltext url".

**Comment by JosephMcArthur** [comment]
Let's go back to having two lists. One is for repo URL's we don't want to send people to, the other is for redirects we want to use to try and avoid login walls / point to full text. So, the concepts you suggest above.

**Comment by JosephMcArthur** [comment]
duplicate discussion of https://github.com/OAButton/discussion/issues/560. Closing
