### ISSUE TITLE
https://doi.org/10.1155/2017/3795120 No OAB bookmarklet never appears

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#629]

**Comment by JosephMcArthur** [comment]
this still happens with the new bookmarklet, atleast on firefox

**Comment by JosephMcArthur** [comment]
`
XML Parsing Error: mismatched tag. Expected: </img>.
Location: 
Line Number 1, Column 386:  (unknown):1:386
SyntaxError: An invalid or illegal string was specified  includer.js:25
	<anonymous> https://dev.openaccessbutton.org/static/bookmarklet/includer.js:25:1`

that's what I get from the console

**Comment by markmacgillivray** [comment]
I've tried a few ways to fix this, but it still does not work - it could be an issue with the format of the page itself rather than our booklet, given that the bookmarklet works. The console complaint is that our injected code is not valid xml, although we are not using xml. Possible the site only wants xhtml strict, but that is pretty old, and even then I am not sure why it would not still accept html later injected by the bookmarklet. Could spend more time on this, but may not be worth it for a one-off page.

Will assign to @JosephMcArthur to decide - if you want further investigation, or know it happens on many pages, reassign to me. Otherwise, close, or push to backlog.

**Comment by JosephMcArthur** [comment]
We don't get many issues like this reported. I'm happy to treat as a one-off for now and de-prioritise having looked at it. 

Is there a way we could log pages where we get this error quickly to help build up a picture of the issue?

**Comment by markmacgillivray** [comment]
No, because it makes our code fail completely.

**Comment by JosephMcArthur** [comment]
Got you. Then I'm going to close.
