### ISSUE TITLE
file upload error 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#644]
When trying to submit the link as both an author or an admin, the site gives an error. See the image below @markmacgillivray @JosephMcArthur 
![screen shot 2017-04-07 at 9 10 03 am](https://cloud.githubusercontent.com/assets/20844934/24806465/f9bda90e-1b82-11e7-922c-345a1cb3bb03.png)

**Comment by markmacgillivray** [comment]
related/same #612

**Comment by markmacgillivray** [comment]
It looks like a cluster issue (only the main machine can read locally uploaded files) so I have changed the upload routing to only be handled by the main machine. This had to be put in at the time when we were having trouble getting files onto OSF quick enough, but now we get round that by running a separate cron job later to check for uploads. This means though that even if the upload is just an article rather than data, the later job still needs access to the temporary local file, so the receiver request has to be sent in to just the main machine. This has been done now, and will push to live.

@natalianorori I will leave this issue open and assign to you so you can try doing it on the live article mentioned above. You should see it succeed as expected, and can then go to zenodo to manage the files that should show up there.

This should mean that uploads now works, although the response page is still a separate page from the request page, but this won't stop you proceeding with the work. I'll continue merging the response page with the request page and let you know when that is ready to review on dev, and that is covered in issue #612

**Comment by natalianorori** [comment]
I was able to upload that file today through the button's website. I published the article through zenodo here https://zenodo.org/record/546117#.WPBNMFPytME . Once published, the article's URL is not the same displayed in the website.  You get a 404 when you follow this link: https://zenodo.org/record/546117/files/2017%20-%20ajcn_MARLATT%20-%20RAVUSSIN_Persistence%20of%20weight%20loss%20and%20acquired%20behaviors%202%20y%20after%20stopping%20a%202-y%20calorie%20restriction%20intervention%20+%20supplemental-2.pdf

@markmacgillivray I feel like I might be the one missing something here. What steps do I have to follow so that the URL displayed in our responder's page is the same as the one from zenodo? So far, All I do is login to zenodo when we receive a paper and publish it, as you taught me before. 

here's a link to the request:  https://openaccessbutton.org/request/3Cc3h6GHmcbx2ibuK.

**Comment by markmacgillivray** [comment]
Hi Natalia, no you're right, the Zenodo links are not working when published. They don't appear to work as I expected from the docs, so I have just pushed a change to the API and updated the site to display the link correctly. Check that request again now and you should see it display as you expect.

**Comment by natalianorori** [comment]
Thanks for the fix Mark, I checked the link and it does match the one stored in zenodo

**Comment by JosephMcArthur** [comment]
@natalianorori is this closable?

**Comment by natalianorori** [comment]
Yea, lets close it
