### ISSUE TITLE
Fix blacklisting of email addresses

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#645]
as discussed on clal

**Comment by markmacgillivray** [comment]
When an email address is blacklisted by an admin on a request page, it is now also removed from any other request that has it as the email address, and the status of those requests will be changed to "help" (but this does not run on requests that have already progressed, because they must be functioning already with the address they have. Future created requests are also checked against the dnr list so future requests won't have blacklisted emails assigned to them. This will go live when we next update the API.

@JosephMcArthur please confirm this is what you expected from the call and if so this can just be closed. If not, let me know what else is needed and reassign to me.

**Comment by JosephMcArthur** [comment]
Yup, this sounds like 100% what is needed. @natalianorori , shout if it isn't what you had in mind. Closing for now.

**Comment by JosephMcArthur** [comment]
Actually! @markmacgillivray can we boot up a spreadsheet for this too?

**Comment by markmacgillivray** [comment]
I'd rather not have to keep two sources in sync

**Comment by JosephMcArthur** [comment]
Alright, not to worry
