### ISSUE TITLE
Use https://hunter.io/ API to speed up finding author emails

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#649]
@natalianorori says this is one of the best ways for finding emails. If we'd like author names for the emails, and institutions are easy to pick up from papers, it seems reasonable to suggest we can put them into Hunter automatically & have a guess at the emails. This might be worth doing from user input since we can validate if the email is actually real before sending. 

Some discussion is worthwhile around if this is worth doing + mterk. However, my personal bias he is towards giving us options & several approaches to this problem since it's so large! 

- [x] Next step is for @natalianorori to let us know if she's still finding hunter very useful & could see this making sense. Also very helpful for @natalianorori to help us understand indepth how she uses it. 

I could even see admins using this + author first / last names & looking for for to date institutions we could message. This might also be a more sustainable way for us to guess co-author emails where the lead author fails.

**Comment by markmacgillivray** [comment]
I'm not sure I see how the hunter API could help programmatically. It may indeed be useful for Natalia using it manually, but I don't think that programmatically it would add much more than what we already have.

It appears to be a tool for extracting email addresses from a web page, and checking that those email addresses are verifiable - but, this we can already do.

It does not appear to have any magic in it that would enable it to know which email address on a page is the author email address, or which name on a page is the name of an author for whom an email address should be discovered, or how to relate a given mentioned author to a given mentioned company.

I think the steps that are currently done manually by Natalia would still be done manually, even if we were programmatically linked up to the API here.

So it seems to me that if we are pushing requests to mturk, then pointing our mturkers at the hunter web site may be a useful part of the instructions they are given for finding an address manually.

**Comment by natalianorori** [comment]
Hunter.io isn't as useful as it was in the past for me, and I haven't had the need to use it in weeks. this is because a) The system is doing a great job in finding the author's emails and b) I am using google scholar as my main tool in tracking down these emails. 

What I usually do is that when the email is unavailable, I track the author or the paper in google scholar, if they have a verified address in there I get it directly from google scholar, but If they don't I look for other papers they have published in other journals and see if those journals are showing their email addresses (this works 90% of the time) and if it doesn't, I just run a more specific google search. 

Hunter is only useful to guess the format the institution where the author works creates emails, but I haven't needed it in weeks.

**Comment by JosephMcArthur** [comment]
Okay, since this isn't seemingly useful lets not do it!

**Comment by JosephMcArthur** [comment]
Okay, different thought. I'd be interested to see how often the email address we get is different from what Hunter would guess if we just give it the author name & institution. If it's similar enough of the time this gives pretty large opportunities for simplification.

**Comment by natalianorori** [comment]
we could test that once we are done with our tasks for this week, let's
say, with the requests we get next week if you want.

**Comment by JosephMcArthur** [comment]
lets just see what hunter.io would bring back on requests we've already sent + what we get back from m-terk

**Comment by natalianorori** [comment]
ok, testing this tonight

**Comment by JosephMcArthur** [comment]
Any news? Would love to close this before starting the next sprint if possible!

**Comment by natalianorori** [comment]
here's a sheet i made from requests we got back from mterk: https://docs.google.com/spreadsheets/d/1S1rpuCMU88IWyUdlp9M2vW0sQJCsKfoZb4a5PX0BDtI/edit#gid=0

Out of 16 requests, hunter failed 6. This is a significant number, all of the email addresses were already verified by me. I would suggest not using this anymore, because in order to use it you still have to perform a google search for the institution's url, so it would be better if we search for the author's name and institution directly on google instead. This is more accurate and saves us time.

**Comment by JosephMcArthur** [comment]
Alrighty, closing again :)
