### ISSUE TITLE
Hiding user emails when we don't have their usernames

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#652]
When someone doesn't have a username, the system automatically gives you their email address instead of their username, and this information is filled in the templates when we contact authors. This means that authors get access to our users email addresses, and could have the option to contact them directly to send them the paper, which might be good for the users but not so good for us. This has happened before but the user was kind enough to forward us the preprint the author sent her. I am manually trying to remove email addresses and figuring out our users names from there. I wanted to see if everyone thinks its a good idea to hide user's email addresses from authors, and if we all agree on that, it would be good to have the system substitute accounts with no users to general terms (ex: instead of showing the email address, saying our "user" instead). 

@JosephMcArthur @markmacgillivray @chealsye

**Comment by JosephMcArthur** [comment]
This problem should now be much better as we've cleaned some of the user data to better show first names when we have them. However, this seems like a reasonable fix.

**Comment by chealsye** [comment]
Replacing with just user seems fine.

We could even experiment with having a standard name like Jane or John, but I think it would be good to find out how authors response to requests without specific names and just knowing they come from a user.

**Comment by natalianorori** [comment]
they still know the user's profession in our first contact email, ex: " one of our users, a librarian" so they get the sense they are getting a request from a real person. It would be interesting to do a test experiment with this in the future. I am aware @svmelton is currently doing user testings to see if author's really care about usernames and identities.

**Comment by JosephMcArthur** [comment]
Okay, let's trying having it:
- [ ] revert to "a user", when only an email address is available

**Comment by markmacgillivray** [comment]
Update the dev api to use the firstname if available, and add the secondname if available, and if neither are available to just say "User". Note as the templates currently stand, it does not appear that this would read correctly because it would say something like "one of our users, User, ". So let me know when you want this change moved to live and I will push the update.

**Comment by JosephMcArthur** [comment]
Seems like there are few sensible ways to structure the same template to be good for when we both have info & don't have it is to move some words into the tags. Some options...

# 1 

> One of our users, {{fullname}}, who is a {{profession}} is interested in an article

is nice when filled, but bad when not. Unless, {{fullname}} also added in the "," when it had info we were happy to put in. For profession, the equivalent would be adding in "who is a" when we have info. 

Of course, for #491 makes this even harder:

> profession of type "other" will now be automatically substituted with "user" when substituting values into email templates.

#2 

Another route here is to just have a bunch of templates that are subtly different and use the correct one. However, if we want to automate the backend will have to know which to chose. 

# 3 

We just flag these for manual review & sending when viewed by admins.

**Comment by JosephMcArthur** [comment]
Thanks, Mark, let's try and go simpler here. 

To step back, I think we might be dealing with a non-issue. A scroll down /requests on live suggests there are almost no requests were we don't have the info required to fill this info. Certainly no new ones. Unless I'm missing something @natalianorori (for example, ones without stories). We may have had a transient issue when we changed the sign-up process but that's fixed now. 

However, this is still worth doing to refine our current inputs & provide some peace of mind to @natalianorori & users that we can always hit send without odd things being put in emails. 

Now... I'm going to try and figure out a simple fix. 

Currently we suggested,

* {{Fullname}}, if we have only an email = "a user"
* {{Profession}}, if "other" = "user" or not available = "user"

and below is the current context of these tags (yes, I fucked up above):

Always used in emails:

> A {{profession}} is interested in reading your article, {{title}}, but is unable to access it. {{fullname}} told us that "{{story}}".

> By sharing your article you'll help {{fullname}}, but it could also increase the impact of your research.

Used only when we have a story:

> {{fullname}} told us that "{{story}}"

I'd suggest, for emails:

* {{Fullname}}, if we have only an email = "a user"
* {{Profession}}, if "other" = "person" or not available = "person"

This requires no copy changes in the email, and Mark you just need to sub in those values where you've got others currently. 

In future, if new templates require new values, we'll just change these. However, I hope these are going to be robust uses, as they're generic but accurate terms for each tag. My niggling doubt is that we don't really introduce what a "user" is to an author, so I thought about things like "reader" or "researcher" (since they were researching) or "a person" but in the end went with user.  

The reason this wasn't possible here is because now we have two possible unknowns (a we removed the option of emails), when previously we had one, so the use of "user" is odd. This change fixes that. 

To close, I'd suggest we
- [ ] change the values as suggested (unless there are vetos and it makes sense) - @markmacgillivray 
- [ ] document the values in the example so we can see them more clearly (and don't need to hunt through issues like I did) - me

p.s the sarcastic side of me wants to make profession be "person who funded your research" :)

**Comment by natalianorori** [comment]
I agree with your suggestions Joe. I'd also like to point out that we
probably had this issue when we changed the sign up process, but I haven't
encountered this recently. However, It would still be good to have these
changes in case we have to manage requests in which the information is
missing (ex. old requests)

ps. sarcastic me would enjoy seeing how author's respond to "person who
funded your research" :)

**Comment by JosephMcArthur** [comment]
Update: removing assignment, I'm not going to document until we implement

**Comment by markmacgillivray** [comment]
Implemented on dev, {{fullname}} never uses email and reverts to "a user" and {{profession}} reverts to "person" if not known or Other.

**Comment by JosephMcArthur** [comment]
documented. closing.
