### ISSUE TITLE
on ff (and maybe other non-chrome browsers) link "get the extension" to /account

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#653]
Getting a lot of bug reports about this, as this currently isn't happening. Please push to master asap. 

cc @chealsye

**Comment by markmacgillivray** [comment]
I'd guess that's because at some point whatever I put in to route to different things depending on browser was removed and not added back to the new wording.

Also today someone I know tried to sign up to oabutton, and their user journey was concerning. Having heard about unpaywall, I recommended they look at oabutton as well. They went to our site, and seemingly tried to get the extension then on the account page were told the account and plugin could not be matched - of course we know this can happen in some circumstances, but what interested me about it is why the user did this at all.

Because our front page says "get the extension", that takes focus away from our USP - the fact that the user can search for things and then create a request if it is not available. Instead, the user misses that and is pulled away to getting an extension and seeing an account page where basically nothing happens.

Given that the plugin is not our core function, and given that it seems to be detracting from our USP, I still think that it would be better to prompt about our extensions as just a handy add-on AFTER the user tries searching for something and then sees the actual USP functionality we are trying to offer.

Also, to reduce plugin issues altogether, the "get the extension" link would be better to go to a /install page where we just list the available extensions/plugins/bookmarklets and can mention unpaywall there too (especially once they link through to us on failure to find). And our extension and bookmarklet should be simplified down to just a trigger that goes to our site front page and runs the search, then creates or redirects to a request or available item as necessary, at which point all the user account stuff manages the workflow anyway. This makes the plugins very simple to maintain and removes the need for the account page syncing with the extensions, and thus simplifies and reduces error.

A /install page will require some content be written for it.

I propose the above, please let me know if I can proceed @JosephMcArthur @chealsye and if someone can provide /install page copy.

**Comment by JosephMcArthur** [comment]
Can you confirm when the immediate bug can be fixed?

Let's keep this issue focused on that and open up a new one for broader
plugin chat. Interesting ideas, but would take longer to implement than its
acceptable to leave this bug lying around.

**Comment by markmacgillivray** [comment]
Fixed.
