### ISSUE TITLE
Add "Send to author" button for requests in moderate on /request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#669]
Most of the information Natalia needs to moderate requests is displayed on /request. This means in many cases just hitting send there would be possible. 

To make this a one button action a "Send to author button" would need to:
* Change status from moderate --> in progress
* Send /emails/requesters_request_inprogress.html to requestors 
* Send email to author
  * If article, with story send: emails/author_request_article_v2.html
  * If article, without story send: emails/author_request_article_v2_nostory.html
  * if data, send: emails/author_request_data_v2.html
* Rate story as pass (#668)

**Comment by markmacgillivray** [comment]
Can do on the actual request page for now, and add to the /request page later

**Comment by markmacgillivray** [comment]
Done on the request pages now via an action dropdown in the admin area. Can later add a button to each item on /request, but not done that yet - probably need to reassign this in a later sprint to get it done.

**Comment by JosephMcArthur** [comment]
@natalianorori can you test please?

**Comment by natalianorori** [comment]
Tested and added a comment on #673

**Comment by JosephMcArthur** [comment]
@natalianorori make sure to test things like with / without story. Also test data requests sends the data email.

**Comment by natalianorori** [comment]
So I tested that the button saves the author's name once we write it. However, I tried testing it today with requests on dev with/without stories and in different status, and I did not receive anything (I am the author for all requests on dev). Templates were sending out just fine a few days ago, I don't know if something changed. Mark, it would be great if you can check this out for me and let me know where the problem is so that I can go back to testing this button

**Comment by natalianorori** [comment]
I was just testing the site with Allana, when you press the "send to author"button on the dev site, the site sends out two templates, one with a story and one without a story to the author. This happens even though the request had a story.

**Comment by allanaaa** [comment]
Screenshots for reference, note the emails are identical except the story line: 

![screenshot-mail google com-2017-05-12-11-32-53](https://cloud.githubusercontent.com/assets/28012148/26005375/d8c2ac1e-3706-11e7-82fb-fee3c3adea1f.png)
![screenshot-mail google com-2017-05-12-11-32-23](https://cloud.githubusercontent.com/assets/28012148/26005376/d8c58880-3706-11e7-9026-d8a65a46fd80.png)

**Comment by markmacgillivray** [comment]
Hi, I have tested this multiple times on dev now, and when I create a request and use the "send to author" button, I get the expected behaviour and the expected emails, in each case where I try a request with a story or without a story. Can you please re-test and confirm if you still get a problem? I can't find anything wrong at the moment.

**Comment by natalianorori** [comment]
I am getting the expect behaviour both on live and the dev site. I've also tested this multiple times and I think we can close this!! Thanks for implementing this btw, my life is so much easier now

**Comment by JosephMcArthur** [comment]
\o/
