### ISSUE TITLE
Integrate OpenAire 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#68]
Openaire is a repo aggregation service run by the EU. https://www.openaire.eu/ for general info and details on the API appear here - http://api.openaire.eu/

**Comment by mtb-za** [comment]
If we want something that the API can not currently do, then we are welcome to ask them. The API is not finalised as yet.

It sounds like we can do what we want (which is get a link to a page which will hopefully have an open copy).

**Comment by mtb-za** [comment]
@markmacgillivray If you can have a look at their api and see if we want to ask them for anything extra, that would be good.

**Comment by markmacgillivray** [comment]
The openaire /use endpoint now exists. However, it is not connected up to what oabutton uses yet, because we still need to know what new coverage if any we get from doing so. So this is all that can be done technically for this one now, and I will assign to @meganwaps so she and @JosephMcArthur can decide which sources we will actually use.

Note that I don't think openaire contains anything that is not aggregated from elsewhere, and we search for things by DOI by default, so it is only going to be useful if it aggregates sources that are not already in other places we search (particularly BASE). Also, this will relate to what we decide to do about using SHARE (which by the way SHARE appears to use the same data structure as openaire).

Finally, although openaire also provides a way to search datasets, there is no way to search for datasets that are about or related to a particular article, so we cannot go from an article web page to a dataset. This appears to be true in general across these data services - I don't know why there is not some default relation in each such service (or for all of them) where they declare "this data is about the article with this doi". At best sometimes the dataset publisher writes the article title in the dataset description, along with other information, but nothing reliable enough to search on yet, I don't think - we would likely get a lot of false positives.

So, make a decision after the review of which sources to use is complete from the previous milestone, and then I can plug this in to the oabutton availability checks with just about 15 minutes more work.

**Comment by markmacgillivray** [comment]
oops never mind about their underlying data being the same, I was looking at an old result page

**Comment by JosephMcArthur** [comment]
Please push ahead as discussed in our meeting on intergrating this.

**Comment by markmacgillivray** [comment]
Does anyone know how openaire actually states that something is open? I was about to add this to our results when I realised it does not seem to work...

Have a look at this result from openaire:

https://dev.api.cottagelabs.com/use/openaire/doi/10.1142/9789814546898_0036

It says it is open, but the only URLs it gives are this:

http://www.worldscientific.com/doi/pdf/10.1142/9789814546898_0036

Which is the same as where the DOI resolves to, and which asks for payment.

The openaire result also says it finds it from opendoar, but opendoar is a list of open access repositories, not articles themselves, so it is not clear where openaire thinks it is finding this.

It is possible to restrict openaire searches to only return things which are open access, but the problem here is according to the openaire metadata this thing IS open access - but there is no way to access it.

@JosephMcArthur further research of openaire will be needed here, and possibly having a discussion with them - it is not a technical issue though, the API is working right, it is just that either their data is wrong or I am misinterpreting how to get from what appears to be an open article in their system to the actual open article.

Not adding this to the system just now, and may have to push back to later sprints.

**Comment by JosephMcArthur** [comment]
This looks like a book chapter, not an article. Could this be a reason why this is the case?

**Comment by markmacgillivray** [comment]
I considered that, but the problem still persists in that it does identify it as open, so we would end up passing it back to a user as if they could access it. Whilst we could solve by checking every type that openaire claim to hold metadata on, and only accepting those that we deem appropriate, the underlying concern remains, which is that they identify this as open although it appears not to be. If this is the case for this metadata type, it could be the case for other types too.

**Comment by markmacgillivray** [comment]
This one still needs discussion. Leaving open.

**Comment by JosephMcArthur** [comment]
I'll reach out to them. Moving into this milestone. We have new info here, and did the work agreed for this milestone.

**Comment by JosephMcArthur** [comment]
Have reached out to find the right people to speak to.

**Comment by JosephMcArthur** [comment]
>In response to your Twitter question, our tech team advises that the issue with the article you mention has to do with the metadata collected from that repository (RePEC). The original metadata states that it is an Open Access publication and gives us two URLs to the publisher version (one for the full-text, one for the abstract). As the problem is in the original metadata records, there is little we can do.

They don't suggest any fixes that would help in the short-term. They only mentioned updating their guidelines, I'm betting that'll take a long time to do & an even longer time to filter down to repo's. 

So, in short we can't count on Openaire to deliver the correct answer. Can we do a similar fix to what folks do with Base, check the links we're sent to see if we can get a PDF (and if so, just give that to the user?)

**Comment by markmacgillivray** [comment]
Much of the time, even for an open article, the link would first go to an html page rather than direct to a pdf. We could search that html page for a link to a pdf and then see if we can access that, but sometimes this would give false results because there could be other pdf links on the page, for example to referenced materials. Also, there may be no pdf at all because the html page itself may be the open article, or it may link to another html page that is the open article. It is possible to check the length of the page and from that make a rough guess as to whether it is long enough to be the full article or not, but that is a pretty fuzzy way to go about it. 

In the case of the above example, it returns a short page which does contain links to a pdf but which we would not be able to access. So we could discount it on that basis. But by doing so we may also discount more actually open articles than the amount of closed articles we filter out.

Or we just accept some of openaire is wrong and use it anyway

**Comment by JosephMcArthur** [comment]
Any way we can look for a licence statement with the CL system?

**Comment by markmacgillivray** [comment]
The example page has no licence information on it. It has a copyright-statement xml area which is empty, and a human readable copyright statement which just says it is copyright to world scientific publishing co. But copyright is not licence anyway. So we could search the page of every URL we retrieve from openaire, but we would have to still decide what to do with ones that have no licence statement, and also what licences we would count as open anyway. We would potentially have the same problem of then throwing away ones that are open but that just do not say so on the page we have the URL for. Some journals for example are fully open access and don't bother stating this on every page of the site, because they think it implies across their whole site - but there is no way to know that programmatically.

**Comment by JosephMcArthur** [comment]
Can we get anything from cross ref? Or, would the URL we'd be given be the
same as the one given to the system (I.e. the URL openaire gives us is the
same as the URL a user gives us if openaire gives us a paywall).

Sorry to keep pushing this, I just wonder if we can think laterally on
this.

**Comment by markmacgillivray** [comment]
I'm going to assign this to @JosephMcArthur for now, to think about when we may return to this issue, or give an answer on whether or not to risk openaire results at the moment. Also moving on to the next milestone

**Comment by JosephMcArthur** [comment]
So, this comes down to risk essentially. I've asked them to put a number on how often they're going to get this wrong. From there, we'll make a call on if it's worth it. My bias is towards turning it on. 

When I say checking Crossref & the URL's, what I'm saying is that if the DOI goes to the same URL as openaire is linking is to it's NOT something we want to send the users too because most dois go to publisher versions - but openaire should be pointing us to a repo copy.

**Comment by markmacgillivray** [comment]
It is now possible to find the licence info and source URLs of things in openaire, and we can now cover with the bug form, so this is complete in dev and ready to go live

**Comment by JosephMcArthur** [comment]
Before we absolutely close this we need to test & document it. Assigning @svmelton for that. Sarah, this works similarly to #418, but can discuss in our 1:1

**Comment by svmelton** [comment]
# Testing Notes
Tested on Chrome Version 54.0.2840.98 (64-bit)

## Testing Articles
Tested:

https://www.openaire.eu/en/search/publication?articleId=od_______229::1c38c4bce0484f8997b3cebc7a2f9722
-Found article in OceanDocs, one of the repos in OpenAire

http://www.oceandocs.org/handle/1834/1299
-Found article in OceanDocs, one of the repos in OpenAire

https://www.openaire.eu/en/search/publication?articleId=dedup_wf_001::e3bf0808361a21d924efbe415a87d5bb
-Article was identified as unavailable, although it is available in OpenAire and here: https://www.hindawi.com/journals/ddns/2012/908451/

**Comment by markmacgillivray** [comment]
Title search with apostrophe may be causing an issue with the last - check

**Comment by svmelton** [comment]
@svmelton will test a few more articles

**Comment by JosephMcArthur** [comment]
Much love for the third person here.

**Comment by JosephMcArthur** [comment]
We don't use the reactions enough!

**Comment by svmelton** [comment]
# Testing Notes
Tested on Firefox 51.0.1 (64-bit)

## Testing Closed Access Articles with DOIs
Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::852e93e30217ede163d950f1edca5592 (DOI doi:10.1145/1778765.1778849)
-Behaved as expecting, giving me option to create a request

Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::d01e64382bb4ae44a9d974da03aa31c7 (DOI doi:10.3233/AO-2012-0114)
-Behaved as expecting, giving me option to create a request

Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::170e5894d687d875d75e5fa3c8e218ac (DOI doi:10.1038/NPHOTON.2011.56)
-Behaved as expecting, giving me option to create a request


## Testing Closed Access Articles with URL
*I found closed articles by using the "filter by closed access" option in OpenAire

Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::852e93e30217ede163d950f1edca5592
-Received "Sorry, something went wrong" message

Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::d01e64382bb4ae44a9d974da03aa31c7
-Received "Sorry, something went wrong" message

Tested https://www.openaire.eu/en/search/publication?articleId=webcrawl____::170e5894d687d875d75e5fa3c8e218ac
-Indicated that an open article was available and provided link http://www.researchonline.mq.edu.au/vital/access/services/Download/mq:34309/DS01. However, when I clicked on it, the page required a login.

## Other Notes

- When attempting to use the search functionality on the test page, I'm taken to the /find page after I click the button. I then have to reenter the request.

**Comment by JosephMcArthur** [comment]
done & up!
