### ISSUE TITLE
Automation of refused requests

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#683]
Thought I had more time than I did to write this, but leaving a note to myself to expand.

* Should send apology to use & change status immediately from an author's action automatically
* Email Natalia

**Comment by JosephMcArthur** [comment]
Returning to this! So, this one is relatively straightforwards. 

If an author chooses refuse:
*  change status from in progress --> refused
* Send emails/requesters_request_refused.html to all requestors

bumping to a later sprint for implementation

**Comment by JosephMcArthur** [comment]
This should be ready to implement

**Comment by markmacgillivray** [comment]
@JosephMcArthur can you remind me how an author currently indicates their refusal? Are they doing it from a link in the request email we send to them? If so can you confirm which email template is the current one, so I can check that link and ensure it triggers the expected behaviour?

This prob won't be finished this sprint, can roll into next one - won't take long once I know what triggers it.

**Comment by JosephMcArthur** [comment]
> @JosephMcArthur can you remind me how an author currently indicates their refusal?

answered in #498

**Comment by markmacgillivray** [comment]
Await #739

**Comment by markmacgillivray** [comment]
Complete
