### ISSUE TITLE
Data request is a "test" on an uninteresting URI

### ISSUE THREAD

**Issue by jibe-b** [OAButton/discussion#693]
Link: https://openaccessbutton.org/request/t6AvCLSdQ6F5mGWXF

**Comment by JosephMcArthur** [comment]
@natalianorori is there any reason why this wasn't marked as a test during moderation?

**Comment by JosephMcArthur** [comment]
Thanks for flagging @jibe-b!

**Comment by natalianorori** [comment]
This was an old request, March 2016 and was marked on Help (It was marked as invalid by mturkers and wasn't moderated by me because as you know, we were giving priority to old requests with stories and on moderate status). Since the link to the URL is nature's comments section, there is no info for author and no story, I deleted the request. Thanks for pointing this out!
