### ISSUE TITLE
Unusual error on giving us a title

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#697]
The text was:

> Land use for animal production in global change studies: Defining and characterizing a framework

They got "something is wrong"

Is this a special character thing?

**Comment by markmacgillivray** [comment]
I don't see any such error. When I put it in the request page search, it searches. When I put it in the front page find, it runs. It has now created a request for that item because we did not yet have one. The request page search now returns that request (for an admin user) when the title is put in the search box. The user possibly just coincided their search with network inaccessibility or something like that, and got a temporary error back.
