### ISSUE TITLE
Using Google Scholar / Google in a way that doesn't break TOS

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#700]
We know that using GS in any way that provides nice UX breaks their TOS, and so we haven't done this. 

However, we also know that many articles are discoverable there and ILL folks often check it. Many others chose to ignore the TOS, but I think with the requests system we can do it nicely in a way that doesn't. 

We could, for example, as soon as a request comes in:
* make it easy for us / others to go a scholar search
* ask turkers to do a scholar search

then fulfil the request as usual within minutes. We can catch the biggest offenders of illegal copies through our current filters. We could also ping any copies we find out to the internet archive to be preserved. 

The impact here would be:
* Fewer checks for ILL staff when using OAB
* Decreased turn-around times for requests
* Recognition of this as a tool most people use anyway 
* Making copies findable via scholar better preserved & discoverable

The major downside here is:
* increased complexity
* potential for grabbing illegal copies
* cost

Throwing out to @OAButton/team for opinions & things I've missed.

**Comment by nemobis** [comment]
By "illegal copies", do you mean the direct PDF links which Google Scholar provides automatically without supervision? Like, copies of the PDF which the author placed on their university web space, possibly without having a SPARC addendum or equivalent?

**Comment by chealsye** [comment]
@nemobis Illegal copies would refer to any version of the article that an author shares publicly that they are legally not permitted to based on their publishing agreement. This can include PDF links from Google Scholar, Academia.edu, personal websites, repositories, etc. Often an illegal copy appearing in Google Scholar will be the publisher's PDF rather than the post-print (accepted version) that an author archives on their university website or institutional repository.

A SPARC addendum is usually not required to legally share research, but certainly can help improve author's rights in agreements! All major publishers permit some form of archiving. The majority of authors can legally share the submitted or accepted version. However, no major publisher permits  sharing the publisher's PDF (unless it was published Open Access with the extra fee). Our primary check for legality here would be if it was the publisher's PDF and then archiving permissions data from SHERPA/RoMEO.

**Comment by nemobis** [comment]
Ok, thought so.

Of course, if you managed to fully automate the process and embedded as many such checks as technically reasonable in your code, then you would not be responsible of any copyright violation by merely linking such copies available online. (You really cannot know whether the author had some special agreement with the publisher, for instance.)

On the other hand, if your aim is to educate the uploaders about their rights (or lack thereof) and possible improvements to their archival practices, rather than to provide a short-term service to the users looking for full-text, then it makes sense to be maximally restrictive.
