### ISSUE TITLE
Login system still causing people trouble

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#703]
Despite the relative simplicity of the login system, today I saw problems (again) with people on our team & close to me:
* getting sent two emails
* being logged out immediately upon login

These are long-standing issues that we've had issues for time & again, seemingly tried to optimise & test for etc etc. Yet, here we are, they still exist in a frequency that is somewhat alarming.

@markmacgillivray I'd like to arrange some time to sit down for an hour in this sprint and talk through our options here from the ground up. 

Can we arrange some time, doodle.com/joemcarthur?

**Comment by JosephMcArthur** [comment]
Am seeing flickering login / logout on lantern.cottagelabs.com too.

**Comment by markmacgillivray** [comment]
Flickering login on lantern is likely due to you being logged in on the dev site somewhere. It works fine for me. If you are logged in on a dev site, it sets different login cookies that confuse the live login, hence why when checking live login you always need to ensure you are logged out of dev first.

Apart from that, re. the other issues, probably no time to talk this week but can discuss on Monday in / after our usual call.

**Comment by JosephMcArthur** [comment]
Today while trying to login on dev on my mobile (android, chrome) the site became damn near unusable while it flickered between the email input page & login code input page :'(

**Comment by JosephMcArthur** [comment]
@markmacgillivray have sent you an invite to speak after the sprint call

**Comment by JosephMcArthur** [comment]
- [ ] monitor logs & reach out to people who have trouble @josephmcarthur

**Comment by JosephMcArthur** [comment]
Note... life here is a lot better for me personally now we have the cookie clearer.

**Comment by JosephMcArthur** [comment]
Some things from users here who had trouble. There were other fixable issues (confusion about one-use only & wanting to check login info which are now separate issue):

# 1 

> 
> Yes, I was having trouble, mostly probably my lack of technical savvy and my use of Opera as my primary (and more secure) browser. When I remembered that I should not use it for this I moved to Chrome but encountered other issues.
>  
> I guess I couldn’t tell whether I was logged in or not, or why I was prompted to do it a couple of times. That might have been the Chrome vs. Opera issue, since the emails I got with the link would be opened by default in Opera. I would then move to Chrome.
>  
> So, I didn’t see a “you are now logged in, proceed”. I also didn’t see a place to alternatively put the code offered in the email. I’m afraid my low tech savvy might be at play and my poor memory of everything I did and steps I did or didn’t take.

# 2 

> Yes, I had a little trouble yesterday. I don’t know if it’s a problem on my end or not. When I clicked on the link in the email to confirm my email address, it sent me to a page where I could enter the code. However, this page literally blinked – like, everything on the page blinked in and out very rapidly and didn’t stop until I exited the page. Don’t know how else to describe it, so I’ve attached a video.
>  
> I was unable to add the code. I have Privacy Badger and Ad Blocker Plus enabled in Chrome, but I disabled them for this site in case that was the problem.
>  
> I have no idea what’s going on, but it appears to have been resolved? I’m able to “log in” to the Button this morning. The only problem I’m having now is that when I click on “get the Chrome extension” nothing happens.

# 3 

> Thanks for following up. As far as I could tell, I only actually logged in once, but I did receive five e-mails afterwards (each with a different link/activation code.) I'm not sure if it was browser or system related, or which browser configuration I was using at the time (it was most likely Chrome, but I use a few different machines with different extensions enabled throughout the day.)

# 4 
  
> Initially, the problem was me having Firefox as my default browser. When I tried to open OAB in Edge, I was asked to enter my email, where I then received the link. Since the link by default would direct to Firefox, I tried to copy-paste it to Edge, which did not work. Also, I do not use Edge so much, so after switching it as my default browser I still am not sure how the extension should work. When I try to use it, I only get a link prompting me to get a Chrome extension or log out. I have also tried it with Chrome now – it works fine but I can’t install the extension on Chrome either. Perhaps the problem is related to some setting on my computer.

# 5 

> I'm not sure if it was the site or due to my computer having just undergone an system upgrade.  Nothing seemed to happen on the first click, hence the second. 

# 6 

> Hmm... I didn't notice that any unusual problems -- just that the site said no need for a Password and asked me to log in again.  I was using Chrome. 

# thoughts

- [ ] Can (if someone clicks on an expired link) we give a helpful error message? Currently nothing happens and they're dropped on the page to put in their email. 
* Currently, on the dev site, if I sign in the page 
* Currently, we suggest people go to the "login page" to enter the code. However, the page they're meant to do this isn't actually called the "login page" anywhere, and while there is only one box it doesn't say put the code here. I can see people may get confused here. 
![image](https://user-images.githubusercontent.com/4953703/28248046-add9eff6-6a34-11e7-8e48-5c1fdeb4f384.png)
* problems installing are mentioned, that I think are fixed by #791
* There is a lot of page refeshing now that happens when I move through our install process (e.g when I login through the link the page lets me on, then refreshes. When I get the plugin the page refreshes, then again). Bit odd, and that's when it works. Could this contribute to the infinate refresh cycles that people get stuck in sometimes?

**Comment by JosephMcArthur** [comment]
@allanaaa I've made some changes to the login email and /account here. Can you take a look at code & let me know if all looks okay copy wise? 

+ @svmelton if you could dig through the above comment and see if there is anything I'm missing in terms of how we'd address I'd be interested.

**Comment by JosephMcArthur** [comment]
- [ ] Once the above are discussed, mainly,

>  Can (if someone clicks on an expired link) we give a helpful error message? Currently, nothing happens and they're dropped on the page to put in their email. Note: if we do this we can remove mention of the time limit in emails, which gives room for other stuff.

and implemented, do another couple of weeks of monitoring - me

**Comment by allanaaa** [comment]
The code indicates you want the placeholder text in the input box to read "Enter your login code"
I'm seeing 
![prob](https://user-images.githubusercontent.com/28012148/28279015-1ffd44f8-6aed-11e7-9460-f595d22d4f1c.PNG)
... which is weird because I can't find the "Delivering to" text on the dev or master /account pages anywhere .... 

Otherwise, looks good - just clarified that the login code is in the email: 
> "We sent you a login code via email. Enter it below."

The "Enter it below" will become redundant and can be deleted if you get that placeholder text to appear in the input box.

**Comment by allanaaa** [comment]
Login email: fixed typo of "preferred." Entered a linebreak between email text + signature, as per @chealsye's request.

**Comment by markmacgillivray** [comment]
the "Delivering to" statements are not part of oabutton per se, they are part of the login system that oabutton uses. They update the placeholder text to indicate the status of the email, which was previously requested as a way to indicate to oabutton users where in the process of logging in they were. So it overwrites the default "enter your login code" placeholder text.

**Comment by markmacgillivray** [comment]
"preferred" is not necessarily a typo, it is the English spelling. Whether it is a typo or not would depend on whether or not we use American or English spelling on oabutton content, for consistency.

**Comment by allanaaa** [comment]
I had no idea about "prefered"! I had understood Canada and UK to be of a
piece on this one. My (biased, of course) Google search results are
indicating most people see "prefered' as a misspelling. (Also
https://en.wiktionary.org/wiki/prefered)

**Comment by allanaaa** [comment]
It doesn't sound like we can wipe the placeholder that our login system pushes, so, I think the copy is fine as-is.

**Comment by markmacgillivray** [comment]
I don't mind which spelling we use, just thought it might be useful to know!

For the placeholder text, we don't have to allow the login system to push the email status into the box at all if you don't want it, but it does do that because that was requested as a solution to users not knowing that an email had been sent to them, so removing it again would seem counter to previous user tests.

**Comment by JosephMcArthur** [comment]
Thanks for the edits @allanaaa they look good to me. We use US spelling, so good catch.

So, for the expired notification, I'm gonna suggest a dismissable info/alert box (as we want them to be able to put in their email as usual). So, the copy for that should be something like:

> This link or code expired! They do that after their first use, 30 minutes, or if you get sent another. Request a new one below. 

@allanaaa I think the above sucks. Alternatives?

**Comment by chealsye** [comment]
@allanaaa, it wasn't a typo. @markmacgillivray, thanks for jumping in and mentioning the English spelling! @JosephMcArthur, our style is to use British spelling, not US. This has been our official communications policy since inception and reiterated by you multiple times with the exception of the institutional service description, which you decided in March should be US spelling instead due to the primary audience.

**Comment by allanaaa** [comment]
> This link or code expired! They do that after their first use, 30 minutes, or if you get sent another. Request a new one below.

Alternatives:

> Sorry, you must request another login code. Login codes expire after 30 minutes, after new ones are requested, or after they get used.

> Sorry, this login has expired. This may have happened because you already used it, waited more than 30 minutes, or have requested a more recent one. You'll need to put in another request below.

**Comment by markmacgillivray** [comment]
It is not possible to differentiate between expired and invalid logins, so I have put a message into it which is now viewable on dev, as below:

Sorry, your login has expired. This may have happened because you have not signed in for a while, or because you tried to sign in with a token or a link that you have used before, or because it expired (they must be used within 30 minutes), or because you have since requested another one. Please enter your email address again and wait for a new login email - remember to check your spam folder too.

You can edit this directly if you wish, on line 72 of the account page template.

**Comment by JosephMcArthur** [comment]
Thanks @markmacgillivray . 

I used:
> This link or code expired! They do that after their first use, 30 minutes, or if you get sent another. Refresh the page and reenter your email to try again.

Sound okay @allanaaa? 

If so, please close!

**Comment by JosephMcArthur** [comment]
Note: I've asked @svmelton to start emailing users as I did at the start of the issue with these new changes in. Will ask her to continue until I say otherwise.
