### ISSUE TITLE
Problems linking to /request with filtering or search results

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#727]
The URL for any /request?[query] is long and unwieldy. When I try to share the URL to a subset of our requests via Twitter and Tweetdeck, the link can't resolve past the { character (normally it would auto-shorten): 

![link](https://cloud.githubusercontent.com/assets/28012148/26168283/8b22cffc-3b07-11e7-896c-848e912528f4.PNG)

I've tried shortening the query with a bit.ly but receive an error message there as well. When it does provide a bit.ly link, following that link indicates that the results are filtered but still brings up the full number of requests (now in the 10,000 range):

![display](https://cloud.githubusercontent.com/assets/28012148/26168362/ce3903c4-3b07-11e7-8a35-c978320c5f2c.PNG)

You can try any subset - this one is the [[status=help] subset](https://openaccessbutton.org/request?source={%22query%22:{%22filtered%22:{%22query%22:{%22bool%22:{%22must%22:[{%22match_all%22:{}}]}},%22filter%22:{%22bool%22:{%22must%22:[{%22exists%22:{%22field%22:%22story%22}},{%22query%22:{%22query_string%22:{%22query%22:%22story:*%22}}},{%22term%22:{%22status%22:%22help%22}}]}}}},%22from%22:0,%22size%22:500,%22fields%22:[%22status%22,%22type%22,%22user.profession%22,%22user.affiliation%22,%22_id%22,%22url%22,%22created_date%22,%22createdAt%22,%22title%22,%22email%22,%22user.username%22,%22user.firstname%22,%22user.email%22,%22location.geo.lat%22,%22location.geo.lon%22,%22story%22,%22count%22],%22sort%22:[{%22createdAt%22:%22desc%22}],%22facets%22:{%22status%22:{%22terms%22:{%22field%22:%22status.exact%22}},%22user%22:{%22terms%22:{%22field%22:%22user.profession.exact%22,%22size%22:100}},%22type%22:{%22terms%22:{%22field%22:%22type.exact%22}},%22keyword%22:{%22terms%22:{%22field%22:%22keywords.exact%22,%22size%22:1000}},%22journal%22:{%22terms%22:{%22field%22:%22journal.exact%22,%22size%22:1000}}}}) - in https://bitly.com/ to reproduce its error message, then test the bit.ly link to reproduce the actual error.

I'll take a workaround (other link resolvers that work?).

**Comment by markmacgillivray** [comment]
This was already covered in a previous issue, and @chealsye already wrote some posts using the short link format. It can be done like so:

https://openaccessbutton.org/request?q=status:moderate

If some other service such as twitter or bitly can't handle the full length URLs, there is not much we can do about that.

As for the counter showing the full amount, this is because when we decided not to show requests without stories by default, the counter had to be set to the full amount even WITH stories, otherwise Joe was worried the count would look too low. Because of this, when you first load the request page, the count is always the maximum amount no matter what query you pass to it. I could try to have it not do that if it appears the user is trying to load the page with a query in place right from the start, but this is not the result of a bug - it is the outcome of a previous decision. So should it be prioritised over other work as a bug, or scheduled into a later sprint as a feature change?

**Comment by allanaaa** [comment]
Thanks! Once again, I searched but could not find the relevant thread.
