### ISSUE TITLE
Creating a process for receiving embargoed articles

### ISSUE THREAD

**Issue by chealsye** [OAButton/discussion#738]
There will be times that authors respond to requests saying that they will archive the article after the embargo period expires.

There will be two scenarios for receiving embargoes:
1) The author replies simply staying they will share the article after the embargo period.
2) The author replies stating that they have deposited the article in a repository and it will become available after the embargo period.

Embargo periods are typically 12 months. However, 24, 18, and 6 month embargo periods also exist.

There are two questions we need to address:
1) How do we handle this process within the request system?
2) How do we communicate to users when their request is affected by an embargo?

For question 1 - need thoughts from @natalianorori and @JosephMcArthur.
-How do we accept and communicate embargo links that will not be accessible yet but will be by x date? 
-How does this affect other processes? 
-Do searches that result in a known embargoed link come with a notification about it being embargoed? 
-Do we encourage authors to archive the pre-print for now if they are waiting for the post-print embargo time period to expire?

For question 2 - Here is a [draft of notification emails](https://docs.google.com/document/d/1ljA7vygPlQ7dRoz8w83wxBFuHhK0bGZd4E1gu9OvUPE/edit#) we could potentially use.

Suggestion for the short term: We use the drafted emails as a template for manually informing users when this situation occurs. Currently this isn't a common occurrence (although I personally experienced both embargo scenarios this week with requests), but it may increase with users requesting recently published research and if we do massive requests via spreadsheets.

**Comment by natalianorori** [comment]
**-How do we accept and communicate embargo links that will not be accessible yet but will be by x date**?
I think that they can be accepted through the responders page, however, we should be able to put a box or something in the responders page that notifies users that the links belongs to an embargoed article. Maybe Mark can set up a checkbox for us to keep track of it. 

**-How does this affect other processes?**

My guess is that it doesn't affect other processes much. after getting the embargoed link we can thank users for giving us the URL and stating that we understand that they are under a publisher agreement, but still appreciate that they'll make their research open in the future, and notify users about it with the templates Chealsye drafted. However, we should keep embargoed requests on a different spreadsheet and notify users again when they're made open access. This would be a longer process. 

I'd like opinions on which status to place embargoed requests, since we might have an answer but they are not really "received" 

**-Do we encourage authors to archive the pre-print for now if they are waiting for the post-print embargo time period to expire?**

We can give them the option to archive the pre-print, although not all of them might feel comfortable with that. We can list it as an option in the embargoed email we send authors. 

--

I agree with you with the short term solution, specially on managing this manually. More templates that are not widely used might make it harder to manage things on the system.

**Comment by chealsye** [comment]
Thanks, @natalianorori! Before this week had you encountered an embargo from an author?

Let's figure out how to support this on the responders' page. If this doesn't affect other processes, then I would assume this is a fairly easy thing to implement, but with an established, separate process to handle embargoes as you noted is needed.

I absolutely agree re pre-prints. Most faculty I've worked with never wanted to archive the pre-print. This will very heavily by discipline, but a sentence mention may be good in the email.

**Comment by JosephMcArthur** [comment]
Does Sherpa / Romeo give us Embargo data @natalianorori ?

**Comment by natalianorori** [comment]
We can get embargo data from Sherpa/romeo if we search for the journal on their database. It's typically under "restrictions" e.g http://www.sherpa.ac.uk/romeo/issn/1547-5816/

 we, however, are not automatically extracting that data for existing requests, just the color.

**Comment by JosephMcArthur** [comment]
Okay, got an issue for this to pull in Embargo lengths and get into a field #992. That's step one here in a move towards automation.

We'll only want to encourage this:
> The author replies stating that they have deposited the article in a repository and it will become available after the embargo period.

Then, what we'd want to do is:
* Compare embargo length to publication date, if published outside embargo proceed as normal. If not...
* notify Natalia as usual to check if it's the right copy (aka, run whatever process we have at the time to check this). Do all normal status changes associated. If it passes
* DON'T, put in Zenodo as we normally would. Keep on our server.
* Notify user that the request has been successful but they have to what. Change the request page to success but give no link except a "notify me" box (same as support). Notify author of what we're doing too.
* On date embargo passes (+1 day) put article in Zenodo, email author with link, email all supporting users with link

Let me know if that sound okay @natalianorori

**Comment by natalianorori** [comment]
sounds okay. Will the system notify me when embargo date passes, or should I track this in a sheet and link it to a calendar for notifications?

**Comment by JosephMcArthur** [comment]
You won't need to track the embargo after content approval, we'll have it do everything else auto-magically. 

- [ ] The next step on this is for me to work the above into our content moderation workflow.

Currently, I've noted it as a shortcoming and pointed people here, so it need not block feedback.

**Comment by JosephMcArthur** [comment]
Note from  https://github.com/OAButton/discussion/issues/1015#issuecomment-443718534, here we need to specify setting access_right and embargo_date.

**Comment by JosephMcArthur** [comment]
Update here, in #992 and my spreadsheet we'll be able to get Embargo information. We'll then put everything in Zenodo as usual, but have the system set "setting access_right and embargo_date". 

We'll then need to notify users, and display on requests differently.

**Comment by JosephMcArthur** [comment]
Closing in #1222. That takes this the final mile and so it's confusing to have this open.
