### ISSUE TITLE
Linking the website to the blog

### ISSUE THREAD

**Issue by allanaaa** [OAButton/discussion#741]
I just realized our website doesn't actually link to our Medium blog anywhere on the About page or in any menus. 

Suggestions as to where to insert this link? 

On the About page:

> Get in touch
> We'd love to hear from you! We can be found on **our blog**, Twitter, Facebook and GitHub - or say hello via email at hello@openaccessbutton.org.

Alternatively, in the bottom menu:

About · **Blog** · For libraries · API · Bugs · Twitter · Account

**Comment by natalianorori** [comment]
I vote for putting it in the bottom menu

**Comment by JosephMcArthur** [comment]
All for adding this on the above page. Please update there. 

Generally, I removed the blog from the footer previously because the blog should be about bringing people _in_ - rather than a place we should be sending people. So, given the footer space is really limited I removed it.

I was actually conflicted about Twitter, but I thought that at the least there was a good place to follow / engage there more easily than via medium.
