### ISSUE TITLE
New ScienceDirect articles pages going to same re-direct page?

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#748]
example new page: http://www.sciencedirect.com/science/article/pii/S0010938X13005064, http://www.sciencedirect.com/science/article/pii/S0010938X13004150, http://www.sciencedirect.com/science/article/pii/S001346861201612X
Where we send: http://jbc.bj.uj.edu.pl/Content/202782/DIGONLINE002583.html

Interestingly, Unpaywall doesn't recognise the above article as an article. Apparently, this started 2-3 weeks ago. 

We do recognise articles like this: http://www.sciencedirect.com/science/article/pii/S0020768317300744. 

Note, the different page styles. 

I expect they've change it & now our scrapers don't work (through design or badluck).

**Comment by markmacgillivray** [comment]
All the links to the Polish repo are provided by BASE. It thinks they are open access. I suspect that BASE included this Polish repo, then something happened at the Polish repo to get them shut down or otherwise to stop them serving the copies they had, and so now all those pages on the Polish repo still return, but all they return is a link to science direct. They don't actually include a link to the specific article in science direct, just a link to the front page of science direct. This was perhaps done because they had no other choice, or maybe they just decided to stop hosting their repo and did the simplest redirect that they could, so people hitting their pages now just get sent to science direct.

There is nothing we can do about this, apart from adding that Polish repo as a repo that we cannot trust, and refusing it as a valid source of open content.

**Comment by JosephMcArthur** [comment]
I've put it here: https://docs.google.com/spreadsheets/d/1f3dyU0xmCh2fgEMgNY1yHSXqyB0j6WZ_WDeS2AS669M/edit#gid=0. Sorry to be dumb, but is that the correct blacklist?

**Comment by JosephMcArthur** [comment]
@markmacgillivray I think given there is more than one link from totally random pages doing this (I just picked a random science direct link) it seems more likely to be something to do with those pages than the polish repo - no? 

/scrape suggests we grab the title of "sciencedirect" from the pages, which when searched on the polish repo leads to the sciencedirect redirect page we're seeing.

**Comment by svmelton** [comment]
I think that this issue, flagged on ZenDesk, may be related:

"Hi OA Button,

I just wanted to let you know about a few issues I've been having with the button. I've noticed that links to open papers will not open by a normal click, I have to open in a new tab. This has been true on my personal laptop and also all the UCLA Library's lending laptops. For an example I'll use http://www.sciencedirect.com/science/article/pii/S1047965116300420, though I've noticed this clicking issue on more than just ScienceDirect articles. Screenshot 1 shows the point at which I cannot left click to open the result. The next issue seems unique to ScienceDirect. When I open it in a new tab I get the screen shown in Screenshot 2. The URL is: http://jbc.bj.uj.edu.pl/Content/202782/DIGONLINE002583.html. Both links from this page go to www.sciencedirect.com."

![screenshot 1](https://user-images.githubusercontent.com/7232545/29571547-775d26ea-8727-11e7-8600-18390d81a116.png)

![screenshot 2](https://user-images.githubusercontent.com/7232545/29571549-7c52a60c-8727-11e7-825c-4d548e1aa30a.png)

**Comment by markmacgillivray** [comment]
Phantom get of sciencedirect pages no longer returns ANY useful content...

**Comment by markmacgillivray** [comment]
We now know that sciencedirect renders an empty page where the only available title is ScienceDirect - and this happens to title match against the same item in BASE every time, hence why we go to that same Polish repo. So that repo is fine, BASE is fine, just the new science direct pages give no title or anything else useful when rendered by our system.

We already use phantom to render the pages, and already forward cookies and user agent and so on, so this would seem to be a change that specifically makes it harder to access programmatically (looks like they switched to using react too).

Science direct has now switched more (possibly all) pages to their new format. This means for now, possibly all science direct answers will be wrong. Fixing this requires investigating how we can render the page in a way that will work again.

**Comment by JosephMcArthur** [comment]
on the off chance, it's useful, here is a perhaps useful API: https://www.page.rest

**Comment by JosephMcArthur** [comment]
the refactor doesn't appear to have fixed this. All the links on this thread just kick off requests.

**Comment by markmacgillivray** [comment]
The new code definitely can read metadata out from the first example page, which the old code could not do. However, it does not yet seem to be getting used properly by oab pages. This is just an update to remind me where I am up to investigating this.

**Comment by markmacgillivray** [comment]
It turns that although the new code does now work, we now have an additional problem which is that science direct does not return the article splash pages when they are requested from our server. If I run this locally or even just curl GET them, I get back the html that I can extract the metadata from. If I do the same thing on our server I get back an error page, with this reference number for the "problem":

18.c6ce1951.1515078193.2d771252

I imagine the problem is that our server IP is being blocked.

**Comment by markmacgillivray** [comment]
This may not be a problem for the plugins, because they should be able to pass the page metadata from when the user is viewing the page. So we should at least now have the ability to get titles and DOIs from science direct again. But anything that runs bulk or on the server directly, like dropping a sciencedirect url into the homepage, will not work.

This may not be worth pursuing any further.

**Comment by markmacgillivray** [comment]
Tested the discussed alternative for searching from front page of our site - doesn't work. @JosephMcArthur will leave this with you to think more about, and can consider options during our next meetup.

**Comment by JosephMcArthur** [comment]
Could we figure out a way to display a message suggesting they use the plugin?

**Comment by JosephMcArthur** [comment]
Note: I've tested the plugin on the links above and confirmed they do all work great.

**Comment by markmacgillivray** [comment]
This is done now.
