### ISSUE TITLE
Author's emailing users directly (after Googling them)

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#758]
This is a problem as it deflates our success rate and means we can't share with EVERYONE. 

There seem to be several approaches to fixing this... 
* (maybe) making clear to authors why they shouldn't do this
- [ ] asking users to notify us when an author does this
- [ ]  understanding why authors do this

Here we can discuss how we want to handle this issue.

**Comment by chealsye** [comment]
@JosephMcArthur I'm not sure we want to muddle communications with users for this. It will be a low amount of authors who take this initiative and likely only when it is for a researcher or librarian at a specified uni they could potentially track down. Authors are likely doing it because they either think we are spam or know they cannot legally share (at least the copy they want to share). It could be worth asking authors why they do this, and I know you didn't specify that as a route to understanding why authors do it, but I would recommend being a bit careful with that because we sometimes are seen 

Will include why it is important to share it directly with us in the new author email draft.

**Comment by natalianorori** [comment]
>  Authors are likely doing it because they either think we are spam or know they cannot legally share (at least the copy they want to share)
I agree with that, but I also would like to note that the amount of authors contacting users directly might not be as low as we think. I don't have exact numbers, but there have been some users reaching us out letting us know that they got hte paper directly from the author and that they don't wish to bother them again

I think that in the future, it might be worth asking users for feedback (either through a follow up mail or social media poll) and adding a question to see if they've gotten articles from author's directly after submitting a request through the button.

**Comment by chealsye** [comment]
My reason for thinking the numbers are low is because it is too difficult for someone to figure out who a person is. It is easy to identify a librarian if you know their uni and name, but it is next to impossible to identify a student which is our greatest amount of requests.

Do you know if that user *also* emailed the author themselves after making a Button request? I know advocates who do both, because they know the reality of wanting that paper now.

**Comment by JosephMcArthur** [comment]
Archiving older issues, including this one!
