### ISSUE TITLE
Link to paper through OAButton?

### ISSUE THREAD

**Issue by mtb-za** [OAButton/discussion#77]
With the recent kerfuffle about Elsevier giving some "top Wikipedia editors" access to things, @menzenski suggested the following, in (this blogpost)[http://www.menzenski.com/Some-Thoughts-On-WikiGate/]:

> Imagine a URL (say, `http://www.openaccessbutton.org/?linkthrough=` or something similar) which could be prepended to any link to a paywalled journal article. That paywall page would be displayed in a window of the resulting page, with the area outside that window providing a link to the Open Access Button and the message “Can’t access this research? Click here to register to help us measure the accessibility of research like this”.

This seems like something that would not be too difficult to do, but is probably harder than I imagine.

Thoughts? It would be reliant on people using the links like that, but it might be possible?

**Comment by markmacgillivray** [comment]
Yes this can be done, it's essentially how the bookmarklet operates, and
can be done by a URL link. But, the URLs have to be distributed to people
somehow. Where is the intended target for such URLs to be written? It seems
to me that it doesn't solve a problem beyond that which the bookmarklet
already tackles.

**Comment by CAYdenberg** [comment]
@menzenski suggests putting these links in Wikipedia articles, either by the writers instead of the closed-access link, or by a bot that scans for closed-access links. Of course, it could generally be used anywhere someone wants to link to a closed-access source (which still properly cites and credits the source).

One limitation of the OA Button is that people have to "install" it to use it (yes, I realize it's just a bookmarklet, but still it's an on-boarding barrier) ... this would help disseminate knowledge of the tool using systems that already exist on the backend.

**Comment by wetneb** [comment]
@markmacgillivray @JosephMcArthur just found out about this GitHub issue. We would be keen to distribute such URLs on http://dissem.in/, as explained in an email to the team.

**Comment by markmacgillivray** [comment]
I still like this idea and will see if we can work it into the current
development. However there is still an issue of getting people to use the
links - what I meant there was not so much about "how" they use them, but
about how they will know such links even exist to be used. Some sort of
outreach seems necessary. So although using these links may not have the
technical on-boarding barrier of installing a button, they instead have a
social on-boarding barrier of having to be known about by someone who
presumably has not installed or used the button.

**Comment by wetneb** [comment]
Yes, of course! But I expect people on dissemin to be already interested in open access and willing to do something for it, so it would be quite easy to explain in a short phrase why they should also use the OAB. So I would not worry too much about the social on-boarding barrier: the current technical barrier (not being able to use this feature in the first place) is much greater.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can we still do this, but just haven't advertised? If not, what do we need to do to be able to enable it? 

Note to self, ideas for our version of this include:
* getmethisdoi
* ineedthisdoi
and our other domains (including oabutton)

**Comment by markmacgillivray** [comment]
Yes, it is already possible. It only works on the cx.ctg.li domain name so far, because we never came to a decision about how to present it under oabutton. All we need to enable it is to tell me what domain name you want it at, or what route of the main openaccessbutton.org domain to put it at. It works like the new request page, so it can work with URL, DOI, PMID, or PMCID. (the cx.ctg.li domain may not actually do so, because it was only a demo, and the latest code for PMID and PMCID is not actually on the live API, but it is ready, so there is nothing new needing to be done to make this work.)

**Comment by JosephMcArthur** [comment]
Can you give an example for us to see?

**Comment by JosephMcArthur** [comment]
http://cx.ctg.li/ has examples. 

We can have it point straight to the paper, like those examples or if not possible to redirect sends you to a request page.

**Comment by JosephMcArthur** [comment]
can we get this set up for openaccessbutton.org/[doi/url/pmid etc] to start

**Comment by JosephMcArthur** [comment]
We now have ineedthisdoi.org too, which this can be set up on

**Comment by markmacgillivray** [comment]
This has been done, there is a description at ineedthisdoi.org of how it works (basically same as cx.ctg.li). 
Please review then when we make the next update to live we can start using these too - of course the ineedthisdoi.org homepage can be customised somehow too.

**Comment by JosephMcArthur** [comment]
Great! Let's close this out for now!

**Comment by wetneb** [comment]
Hi! Thanks a lot for working on this, but…
It's still not we need to point our users to the OAB.
For instance, here is a case where the article cannot be found by the OAB: http://ineedthisdoi.org/10.1016/0165-1161(82)90161-3
This should point to the request page for this DOI, not a generic page where the same DOI has to be input again, I think.

**Comment by markmacgillivray** [comment]
HI @wetneb I can make it so that the DOI is automatically passed into that page and it runs the search, but the user would still have to sign in and provide a story to create the request - it can't go direct to a request page for that DOI, because at the moment we require user accounts to create requests. Unless @JosephMcArthur confirms he wants this to be able to create requests without an account - in which case I need to know a few more things about what to display instead of user account details on the request, e.g. "an anonymous user", or whatever.

**Comment by wetneb** [comment]
okay! I was expecting it to land on something like this: https://openaccessbutton.org/request/j5L47ukCaDWeLf2ML but apparently it's only available for requests that have already been made.

**Comment by markmacgillivray** [comment]
@wetneb yes that's right, they only exist for requests that have already been made. I could auto-generate one, but it depends on the wider question of allowing anonymous requests - which is up to @JosephMcArthur

**Comment by markmacgillivray** [comment]
@JosephMcArthur we should shift signup prodding to after request creation - allow users to come along, search, or go through the ineedthisdoi / @wetneb system, have a request automatically created if there is not one already existing, and THEN we ask them to give us an email address and a story, and sign them up for an account. And in cases where a request already exists, we ask them for email address and story to add their support. That way the ineedthisdoi and other URLs can go direct to either the item if we find it, or a request page already created, instead of landing on the find page.

**Comment by JosephMcArthur** [comment]
@wetneb we've now pushed changes from your feedback above live. You should be able to do what you'd like from: https://dev.openaccessbutton.org/request?doi=DOIHERE (for test, just remove the "dev." for the live site). 

Would love your feedback on the implementation, and if we could make anything better for you here! 

Closing this for now, just to keep us on top of what needs doing, but don't hesitate to reopen / comment / make a new issue to discuss further! Thanks for your thoughts here, always appreciated.

**Comment by markmacgillivray** [comment]
@JosephMcArthur @wetneb note that using the /request address will bypass our own availability checks. If you want to first check that we can't find the thing either, then just use the root address. e.g. for testing https://dev.openaccessbutton.org?doi=DOIHERE

Also, please use a param to identify the requests are coming from you, such as &from=oabot

**Comment by wetneb** [comment]
Great, thanks! I'll add that to our sidebar.

**Comment by JosephMcArthur** [comment]
Any ETA on that? Would love to blog about it.

**Comment by wetneb** [comment]
@JosephMcArthur I'll check with the others at our dev meeting this week, but it's trivial to add so I could do it by Monday if they all agree.
