### ISSUE TITLE
new plugin ignores article blacklists

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#893]
e.g when clicked on facebook / openaccessbutton. 

When clicked, we could open http://openaccessbutton.org/instructions unless you have a better idea.

**Comment by markmacgillivray** [comment]
Actually the plugin would not go as far as creating a request for a blacklisted URL - it is just that on dev, with a debug plugin, all the requests are tests so are not checked against the blacklist. However, because there is no plugin UI now, I thought the idea to send them to the instructions page was good, so I have set it to do that if the API returns a 400 code (which is what it does when blacklisted). The /instructions page now has an alert section which you can see by appending #blacklist to the URL like so:

https://dev.openaccessbutton.org/instructions#blacklist

and the plugin does this, so the user will see the blacklist warning.

I have also added the blacklist to the bottom of the page, and added a link to the feedback page in the alert section, so users could contact us if they think we should allow what they are trying to do, or if they actually encountered some other sort of problem.

Will assign back to @JosephMcArthur to check, just close if OK.

**Comment by JosephMcArthur** [comment]
@allanaaa I've written some fresh copy for this page. Can you review?

**Comment by JosephMcArthur** [comment]
note to self I want to add a gif to this page

**Comment by allanaaa** [comment]
Looks good - fixed a typo, did a bit of consistency stuff. What kind of gif do you want?

**Comment by JosephMcArthur** [comment]
@allanaaa I was thinking gifs like on slides 6 / 7 / 8 here https://docs.google.com/presentation/d/1uFHNJAqkAatLdTt-vBxoLXHpS4W6-Fo9BCupax97NVM/edit#slide=id.p (the oab usage & install gifs)
