### ISSUE TITLE
1st end-to-end test of dev request system

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#901]
* objective of the test is to set baseline figures for the performance of this system vs the live system. this should test #634 
* They hashtag for this is `dryrun`
* run 250 requests from the backlog

**Comment by natalianorori** [comment]
This is the[ google drive folder](https://drive.google.com/drive/folders/0B-F7etjqq9CxQmo5cnNKUjg1VjA) for the test, where notes and spreadsheets used to perform it can be found.

**Comment by natalianorori** [comment]
**UPDATE: September 28th, 2017**
**Dev system stats**
We sent out the test on September 18th , 10 days ago, as of today: 
Click rate: 9%  (7)
Open rate: 32% (74)
Response rate: 10 out of 74 opened. (7.4)
		   10 out of 250 sent (4%)

_Observations:_ 
We received content from 10 authors, of those 10 authors 5 sent us paywalled links or the publishers PDF that we can't display on the site. They have been contacted but haven't replied yet. This confirms our necessity to start telling authors what they can deposit and exactly what we are asking (pre-print, post-print). 

I am not sure if we can trust these numbers. Specially the click rate. Since I have records of authors depositing their work directly, and YAMM still shows the email as "opened" YAMM is clearly not tracking the mail correctly, cause in order to deposit they would've had to click the email. 

**Live system stats**
Analyzed last 250 emails sent from September 18th, 2017. We are not able to see the click and open rate with the live system 

Response rate: 2.4%  (6) 

_Observations._
The email we sent out looked exactly the same. The advantage of the dev method (YAMM) is that it lets you track how many emails were opened, this could help us with follows ups. We have to consider we have been having issues with the responder's page, and that could have affected our response rate. 

Two essential things to include on our next emails: telling authors what they can send us. Telling authors to send us their work by replying to the email, not uploading things to the responders page until we are 100% sure it's working correctly. 

(These comments are already on 901's drive folder. The analyzed data there as well. )

**Comment by JosephMcArthur** [comment]
This is WONDERFUL Natalia, exactly what we needed to see here. 

> We received content from 10 authors, of those 10 authors 5 sent us paywalled links or the publishers PDF that we can't display on the site. 

* Was the paywalled link the same as the one to user submitted to us? I know we had this issue early on, but thought that we'd addressed it! 
* Did we have sherpa remeo info for these records? I know these are old and we've identified an issue on old records with them still not having info where they should. 

> I am not sure if we can trust these numbers. specially the click rate. Since I have records of authors depositing their work directly, and YAMM still shows the email as "opened" YAMM is clearly not tracking the mail correctly, cause in order to deposit they would've had to click the email.

Does YAMM have anything to say about this? I've never had an issue before with this (that I could tell)

> Analyzed last 250 emails sent from September 18th, 2017. We are not able to see the click and open rate with the live system

* Do have a spreadsheet / list of the ones you looked at, or can you make one easily? I might be able to cross reference with email data, but I'm not confident. 

> Response rate: 2.4% (6)

* Did you analyse the correctness of what we got here? 

> The email we sent out looked exactly the same.

* can you make a test request on the live site with me as the author, and send me a request. Then, can you do the same with the dev spreadsheet system? I just want to verify something for 100% sure.

**Comment by natalianorori** [comment]
Swore I had answered these, sorry it took me this long: 
This is WONDERFUL Natalia, exactly what we needed to see here.

> Was the paywalled link the same as the one to user submitted to us? I know we had this issue early on, but thought that we'd addressed it!

Yes, it was the same link submitted to us. 

> Did we have sherpa remeo info for these records? I know these are old and we've identified an issue on old records with them still not having info where they should.

No, we didn't have Sherpa Romeo info for these records, we currently have little info on all requests, this is why we discussed we need to push #898 asap. 

> Does YAMM have anything to say about this? I've never had an issue before with this (that I could tell)
They said it was a temporary error with the system. 

> Do have a spreadsheet / list of the ones you looked at, or can you make one easily? I might be able to cross reference with email data, but I'm not confident.
Yes, spreadsheet is here: https://docs.google.com/spreadsheets/d/1m_pII7O1j0jyPlJSDYJAgkwiMldLKhIMwOTDQCU6a04/edit#gid=389610455


> Did you analyse the correctness of what we got here?


I have to get back to you on this one. this is only counting our received requests on the site , which are all correct, however, I did not count email responses from zendesk in which authors were not sure what to submit.

can you make a test request on the live site with me as the author, and send me a request. Then, can you do the same with the dev spreadsheet system? I just want to verify something for 100% sure.

Sent you two emails to this request: https://openaccessbutton.org/request/hXuuopYdtF25Lp22E

**Comment by JosephMcArthur** [comment]
>can you make a test request on the live site with me as the author, and send me a request. Then, can you do the same with the dev spreadsheet system? I just want to verify something for 100% sure.
Sent you two emails to this request: https://openaccessbutton.org/request/hXuuopYdtF25Lp22E

I seem to have only got one :/
