### ISSUE TITLE
If new plugin is clicked twice on the same article, the second time it'll start a request

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#913]
A caching issue, I presume?

**Comment by markmacgillivray** [comment]
Clicked in quick succession? Do you mean it creates ANOTHER request? Or that it creates a request even when it should not, for something that should not have a request created?

If the problem you saw is that it creates another request, then yes, probably due to the time it takes to create a request, and if the button is clicked again in quick succession the backend will not have had time to create it and two may get made.

I have added a "running" checker, which stops the button executing again until the first availability check is completed. This stops the above problem from happening, so if this is the problem you could close this issue.

If the problem is that it creates a request it should not create - I don't know what would cause that. Would have to investigate further, and let me know if you have an example I could look at and reassign back to me.

**Comment by JosephMcArthur** [comment]
Steps to reproduce:
* Click on an article where we can find oa, let it open the new tab
* go back to the article, click the plugin again
* a request will be started. 

How that?

**Comment by markmacgillivray** [comment]
So does this still happen? I pushed changes to the phoenix branch of the plugin that I think should have already stopped this - they stop the button from sending another request.

**Comment by JosephMcArthur** [comment]
Hmmm. It was. Perhaps somewhere I didn't push a release??? Let me check.

**Comment by markmacgillivray** [comment]
The actual releases won't be up to date, I just pushed this to github a few minutes ago. I mean if you use a dev install of the plugin on your browser and pull the latest from git and reload it, you should have this solved.

**Comment by JosephMcArthur** [comment]
just tested with plugin downloaded from pheonix using dev install. All is well.
