### ISSUE TITLE
OAB finds bogus reference

### ISSUE THREAD

**Issue by bsavage** [OAButton/discussion#931]
### Expected Behavior
_From the main OAB page, entered url of http://this.com/test_

https://openaccessbutton.org/?url=http%3A%2F%2Fthis.com%2Ftest

### Actual Behavior
_OAB should not have found anything but returned the following article reference:_
http://research.sabanciuniv.edu/34037/

### Steps to Reproduce this bug
Enter this in browser:
https://openaccessbutton.org/?url=http%3A%2F%2Fthis.com%2Ftest

### Note
Perhaps having something to do with the title of the found resource shown above being:
"404 not found"

**Comment by markmacgillivray** [comment]
When we get a 404 we do still process it because it is possible for a user to search for an article at a URL which is only available via login and for that URL to return 404 if the user is not logged in.

Unfortunately, yes, because there is an article in existence with 404 not found as the title, we now redirect to that article.

It is not common for an inaccessible article to return 404 because most systems return at least a splash page, but it is possible.

Our code can be changed to consider a URL that returns 404 as just being something we should not process, or we could continue treating 404 as a potentially inaccessible article but add a specific catch to not use the "404 not found" title string as a valid search parameter, meaning we would never successfully find a title search for the "404 not found" article when we should. This would not be a big deal if the "404 not found" article was accessible, but it is only actually accessible by request after login, from the looks of it. So we would have to accept that this is one article our system just would not work on.

Assigning to @JosephMcArthur to decide his preference, then I can add it either way to the code.

**Comment by JosephMcArthur** [comment]
Happy with everything proposed, with a preference for whatever is simpler. Close as you wish @markmacgillivray.

**Comment by markmacgillivray** [comment]
Added a specific block to not do title searches if starting with 404
