### ISSUE TITLE
sign in prompts not being removed when there are several

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#970]
The sign in prompts on pages like deliveroa isn't always going away when signed in. E.g on deliveroa it'll go on illiad, but not ill. 

What I think is going on (copy & pasted from email to user)

> the issue here is that we have a bit of code that removes that line when you're signed in, but it is only working on the first instance of that line on the page (opps!). So, if you're looking at Libguide (and I'm right), it should be gone. 

```
noddy.afterLogin = function() {
    $('#promptsignup').hide();
    var uid = noddy.user.account._id;
    $('.stickidin').html($('.stickidin').html().replace('openaccessbutton_widget()','openaccessbutton_widget({uid:"' + uid + '"})'));
  }
```

The above probably either needs to check for all prompts, or we need different IDs and duplicate code

Note, this will need to be updated on deliveroa, embedoa, integrations etc. The code is used in many places.

**Comment by markmacgillivray** [comment]
If you're trying to refer to more than one item on a page you can't use hash tags - those are IDs, and should be unique. Instead you should use classes, which are found using dot notation. On dev I have changed these pages to look for .promptsignup instead of #promptsignup and changed the elements to have the class instead of the ID. This should therefore be working on dev now.

**Comment by JosephMcArthur** [comment]
Fab! Fixed on /deliveroa & /integrations too.
