### ISSUE TITLE
put a word limit in the story box 

### ISSUE THREAD

**Issue by natalianorori** [OAButton/discussion#975]
So that we don't have stories as long as this one https://openaccessbutton.org/request/Z3TRCmYzx9Yz4JtRu

**Comment by JosephMcArthur** [comment]
This just looks like nonsense :| May be best to just delete as part of moderation unless we regularly get stories which are legit but too long.

**Comment by natalianorori** [comment]
true. closing this :)

**Comment by markmacgillivray** [comment]
It looks like someone copy-pasted the content of the page the request is about, and the user that submitted this seems to have the same name as the lead author of the paper. Also, it is not actually a paper, it is the data supporting what appears to be a paper. Most likely the person did not understand how to use our system correctly. I think we already have a word limit on the story box, we certainly used to, so if we don't now then it must be because we specifically decided to remove it at some point. Probably someone can copy-paste into the box though, as that would immediately take them past the word count limiter.
