### ISSUE TITLE
oasheet email issue

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#982]
issue sent over email, here for tracking

**Comment by markmacgillivray** [comment]
So far, as far as I can tell, the emails are working fine but some large jobs just don't complete reliably. This can be the case when just one of the identifiers provided turns out to be impossible to process in an expected way. Normally this just results in having no answer for that ID, but can sometimes lead to a large job seemingly not completing, thus not sending a completion email.

I am adding checks to catch for this, but I think we could also improve the UI on this. The lantern UI allowed people to go back to the job page to see how it was doing, and this way they are able to see progress even if not at 100%. I think we should bring in just a very simple page on oasheet, which the user can be given a link to in their "job started" email, where they can get simply a progress counter and download button. We can add some commentary on that page too saying that they can download any time, and come back later to get more results if the job is not yet at 100. So then they won't get stuck waiting for one problem ID out of 1000s, and if that problem ID ends up not processing successfully, it is not such a big deal, and they could inform us of it if we put a feedback button on the page.

@JosephMcArthur I can make this page on the next sprint unless you want to have it designer-ed.

**Comment by JosephMcArthur** [comment]
I'd rather not add complexity to the UI now, and just have the email sent. Is there a fallback we can have, e.g "if job not complete after X amount of time send email". If the entry in the sheet could just say "UI not processible" or something like that it would be great.

**Comment by markmacgillivray** [comment]
It is more complicated to do "if not complete after X" than it is to alter the UI.

**Comment by JosephMcArthur** [comment]
Alrighty, go for the UI changes then! We do have designs already available if that's helpful.

**Comment by markmacgillivray** [comment]
OK where are they?

**Comment by JosephMcArthur** [comment]
Example here: https://github.com/OAButton/discussion/blob/master/UI:UX%20Mockups/OA%20sheet%20design/V2/OA-Sheet-Design-v2-page-2-1.png

The design requires much more functionality than you're suggesting, so don't actually worry about that. Just thought some idea to go off here might be nice.

**Comment by JosephMcArthur** [comment]
Small thought, I wonder if doing this on /account makes sense? All yours to decide, I don't mind at this point.

**Comment by JosephMcArthur** [comment]
to be clear, this is currently blocking a big round of publicity as I don't want to push people towards this when a non-trivial number may hit this error.

**Comment by markmacgillivray** [comment]
The design stuff was quite different from what we need right now. I have altered the oasheet page itself to include a % counter and a download button. That way people can come back to that page any time. You can see an example here:

https://dev.openaccessbutton.org/oasheet#NdBTfYZ3gJTivRmGj

If the job is not yet at 100% the % complete sentence also says "You can download the results so far, and revisit this page any time to check further progress and download more."

I've added a line to the bulk_start email to give the user a link to the job progress page and I've refreshed the email templates on dev.

**Comment by JosephMcArthur** [comment]
Perfect. If you're confident this all works I'm happy for it to ship. Thank you.
