### ISSUE TITLE
Stats as Sheet Export

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#985]
@markmacgillivray to what extent does it make sense to turn /stats into an export (or sync) of summarized figures we can play with (make graphs of, work out figures for) in gsheets. I'd like to expand our ability to get info on performance (especially over time) and wonder if it makes more sense to remove the need for you to code UIs to do that (where sheet templates will likely be just fine) and focus on getting summarised info out. I may still ask you to work in sheets, but at least others can work on that too. 

I'd also adore a script which sends us KPIs each week, something to force us to check figures. That could be done in sheets of course.

**Comment by markmacgillivray** [comment]
How different would this be to the /export page? I could add the queries that build the stats page onto the export page as options, then you could select what stuff you want to include in the export. Actually the export and stats page used to be the same page.

**Comment by JosephMcArthur** [comment]
Yup, they'd be the same. But it would allow you/us to focus on getting the numbers out / created and we can build graphs and views more easily / flexibility there.

**Comment by JosephMcArthur** [comment]
Back to the original question, would this be a helpful way to make it easier to get more data out in the long term Mark?

**Comment by natalianorori** [comment]
stats I've needed to figure out in the past:

- filtering requests by creation date
- filtering requests by journal 
- filtering requests by publisher 
- Percentage of requests with DOIs
- Percentage of requests with sherpa colors
- percentage of requests for each sherpa color  
- filtering requests by sherpa color 
- Percentage of requests with publication year prior to certain date
- filtering requests by publication year
- filtering users by profession 
- filtering users by afiliaton 
- distribution of requests over fields of research 
- our success rate
- percentage of requests closed by each of the reasons we close them e.g percentage of requests closed because of publication year, because of broken links and because of not being a scholarly article 
- filtering received requests by the author's institution and field
-  number of requests received weekly and number of requests moderated per week 

getting any of those numbers automatically will help. for stats, I only need us to count requests with stories.

**Comment by markmacgillivray** [comment]
There are aspects of this that are more like a faceted browse interface, which we have had before, and still do have in the admin UI. We also have had the maps and other interactive ways of exploring the requests. Also, if the best solution is just to have a sheet export that goes into google sheets or some other tool (datopian or similar), then that precludes spending much time building a new stats/export page, which I had already been spending time on. 

So for now I think we have to move this issue out of this sprint, and first make decisions on where you want this data to go, and how it will then be used. I can either spend useful time making updates to our own UI / API to support what we need from stats / export / faceted browse, or I can ensure we can export data to whatever preferred system is chosen.
